[2단계 - 최단 경로 및 요금 조회 api] 주드 미션 제출합니다.
woowacourse/jwp-subway-path pull request #102
Opened 2023-05-14 13:35 UTC by kevstevie

안녕하세요 빙봉!
처음 뵙겠습니다.
이전에 제출했던 1단계에서 코드를 다듬고 기타 예외처리 추가했습니다.
테스트 결과 (아마도) 모든 기능이 잘 작동할 것 같습니다.

가장 큰 질문은 패키지 구조에 대한 질문입니다.
현재 대부분의 패키지가 root에서 시작되어 상당히 번잡한 모양인데 더 효율적으로 나눌 방법이 있을까요?

현재 역을 추가하고 추가된 역을 노선에 추가하는 형태인데 현실과 결합해서 생각했을 때 둘의 생명주기는 같아야한다고 생각하지만 편의상 나누었습니다.
빙봉은 어떻게 생각하시나요?

첫리뷰 잘부탁드립니다..🙇‍♂️

2023-05-15 16:14 UTC, aegis1920 requested changes
안녕하세요 주드! 빙봉입니다 🙂 

2단계 잘 작성해주셨네요! 질문에 대한 답변 및 코멘트 남겼으니 확인해주세요~

궁금한 점은 언제든 편하게 DM 주세요!

2023-05-15 16:14 UTC, aegis1920 commented on src/main/java/subway/application/feepolicy/DefaultFeePolicy.java
> +public class DefaultFeePolicy implements FeePolicy {
계산하는 역할이라 DefaultFeeCalculator 라는 클래스명이 더 어울려보이는데 어떻게 생각하시나요?

2023-05-15 16:14 UTC, aegis1920 commented on README.md
도메인이나 API에 대한 내용보다는 주어진 요구사항에 대해 기능 구현 목록을 적는 건 어떨까요?

2023-05-15 16:14 UTC, aegis1920 commented on src/main/java/subway/application/feepolicy/DefaultFeePolicy.java
> +        int fee = 1250;
기본 fee도 상수로 빼면 좋겠네요

2023-05-15 16:14 UTC, aegis1920 commented on src/test/java/subway/integration/LineIntegrationTest.java
> +import static org.apache.http.HttpStatus.SC_BAD_REQUEST;
apache.http 패키지의 HttpStatus를 사용하신 이유가 있을까요?

2023-05-15 16:14 UTC, aegis1920 commented on README.md
> 현재 대부분의 패키지가 root에서 시작되어 상당히 번잡한 모양인데 더 효율적으로 나눌 방법이 있을까요?

요구 사항 자체가 지하철 도메인에 대한 이야기라 subway 패키지로부터 시작해도 괜찮다고 느껴지는데요. (이런 부분은 직접 다른 어플리케이션을 개발해도 똑같을 거라고 생각이 들긴 합니다!) subway가 아니라 처음부터 다르게 패키지 구조를 가져가고 싶으셨던 걸까요?

> 현재 역을 추가하고 추가된 역을 노선에 추가하는 형태인데 현실과 결합해서 생각했을 때 둘의 생명주기는 같아야한다고 생각하지만 편의상 나누었습니다. 빙봉은 어떻게 생각하시나요?

둘의 생명주기가 다를 수도 있을 것 같습니다! 역을 미리 추가해두는 일도 있을 것 같아서요. 역을 생성해서 바로 노선에 추가할 수 있지만 이것보단 역에 대한 정보를 미리 추가해둔 후, 검증을 한 뒤에 노선에 역을 추가하는 형태가 더 안전하네 느껴지네요 🙂

2023-05-15 16:14 UTC, aegis1920 commented on src/test/resources/test.sql
> +DROP TABLE paths IF EXISTS;
테이블을 DROP하는 것보단 TRUNCATE하는 게 좋지 않을까요?

2023-05-15 16:14 UTC, aegis1920 commented on src/test/resources/logback-access.xml
> +</configuration>
마지막 줄 개행(EOF의 개행)에 신경써주시면 좋을 것 같습니다!
참고로 유닉스 시스템의 표준이 한 줄에 대한 정의가 개행으로 끝납니다. ([링크](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206))

2023-05-15 16:14 UTC, aegis1920 commented on src/test/resources/application.properties
> +spring.sql.init.mode=never
never로 설정하신 이유가 있을까요?

2023-05-15 16:14 UTC, aegis1920 commented on src/test/resources/test.sql
> +INSERT INTO line (name, color)
test 데이터를 schema.sql과 data.sql로 나누지 않은 이유가 있을가요?

2023-05-15 16:14 UTC, aegis1920 commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost:13306/subway
h2로 하되 경로를 로컬로 주면 요구사항을 만족하지 않을까요? 굳이 mysql db로 할 필요는 없을 것 같아요. (혹은 mysql을 사용할거라면 docker-compose.yml 파일도 공유해주시면 좋겠네요!)

2023-05-15 16:14 UTC, aegis1920 commented on src/main/resources/application.properties
> +spring.sql.init.mode=always
init 설정을 always로 주신 이유가 있을까요?

2023-05-15 16:14 UTC, aegis1920 commented on src/main/java/subway/persistence/dao/LineDao.java
SQL 쿼리에서 Join하지 않고 Application 로직에서 직접 조인하시는 이유가 있을까요?

2023-05-15 16:14 UTC, aegis1920 commented on src/test/resources/test.sql
> +CREATE TABLE IF NOT EXISTS paths
여기만 소문자군요?

2023-05-15 16:14 UTC, aegis1920 commented on src/main/java/subway/ui/StationController.java
환승역을 삭제하고 find line을 하면 환승역 데이터의 name에 null이 들어가는데 의도한 바가 맞을까요?

2023-05-15 16:14 UTC, aegis1920 commented on src/test/java/subway/ui/FeeControllerTest.java
> +class FeeControllerTest extends IntegrationTest {
- Controller 테스트인 이유가 있을까요?

2023-05-15 16:14 UTC, aegis1920 commented on src/test/java/subway/integration/PathIntegrationTest.java
> +public class PathIntegrationTest extends IntegrationTest {
기점, 중간, 종점 관계에서 역을 추가, 삭제했을 때의 테스트가 존재해야할 것 같아요. (환승역 포함)

2023-05-16 05:12 UTC, kevstevie commented on src/test/java/subway/integration/LineIntegrationTest.java
> +import static org.apache.http.HttpStatus.SC_BAD_REQUEST;
SC_OK 등의 상수를 제공하는게 편리해서 사용했습니다

2023-05-16 05:12 UTC, kevstevie commented on README.md
>요구 사항 자체가 지하철 도메인에 대한 이야기라 subway 패키지로부터 시작해도 괜찮다고 느껴지는데요. (이런 부분은 직접 다른 어플리케이션을 개발해도 똑같을 거라고 생각이 들긴 합니다!) subway가 아니라 처음부터 다르게 패키지 구조를 가져가고 싶으셨던 걸까요?

개발 경험이 적다보니 그냥 이게 맞나.. 싶어서 질문드렸습니다 하하

2023-05-16 05:15 UTC, kevstevie commented on src/test/resources/application.properties
> +spring.sql.init.mode=never
init.mode를 켜두는 것과 테스트에서 @sql 를 사용하는 것의 차이를 잘 모르겠습니다,,
비슷한 작동원리를 가질 것 같은데 init.mode를 켰을 땐 테스트가 깨지고 @sql로 sql파일을 불러올 땐 깨지지 않아서 never로 설정했습니다

2023-05-16 05:16 UTC, kevstevie commented on src/test/resources/test.sql
> +INSERT INTO line (name, color)
위 내용과 연장선상인데 하나의 @sql 을 통해 테스트할 때 하나의 sql 파일로 진행하고자 나누지 않았습니다

2023-05-16 05:16 UTC, kevstevie commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost:13306/subway
그런 부분을 생각못했네요 현재는 h2 로컬로 수정했습니다

2023-05-16 05:33 UTC, kevstevie commented on src/main/java/subway/application/feepolicy/DefaultFeePolicy.java
> +public class DefaultFeePolicy implements FeePolicy {
더 좋아보이네요!

2023-05-17 00:24 UTC, kevstevie commented on src/main/java/subway/ui/StationController.java
로직에 오류가 있었습니다. 현재는 수정했습니다

2023-05-17 00:24 UTC, kevstevie commented on src/test/java/subway/integration/PathIntegrationTest.java
> +public class PathIntegrationTest extends IntegrationTest {
추가했습니다!

2023-05-17 00:25 UTC, kevstevie commented on src/test/java/subway/ui/FeeControllerTest.java
> +class FeeControllerTest extends IntegrationTest {
자동생성 기능을 썼더니 이렇게 되었군요 이름 수정했습니다.

2023-05-17 03:54 UTC, kevstevie commented on src/main/resources/application.properties
> +spring.sql.init.mode=always
프로덕션은 디비를 로컬에 한번만 생성하면 되기 때문에 현재는 embedded로 수정했는데 만약 처음 실행할 땐 어떻게 해야할지 방법을 잘 모르겠네요,,

2023-05-17 03:55 UTC, kevstevie commented on src/test/resources/test.sql
> +DROP TABLE paths IF EXISTS;
truncate를 할 경우 id가 달라지거나 하면서 테스트 격리가 이루어지지 않아 drop 하고 다시 만드는 형태로 구성했습니다

2023-05-17 05:27 UTC, kevstevie commented
안녕하세요 빙봉!
지하철역을 삭제하면 경로에서 삭제되지 않던 버그 수정하고 다양한 케이스들에 대한 도메인 단위 테스트와 통합테스트 작성했습니다.

테스트 편의성을 위해 `@sql` 애노테이션을 통해 테스트 격리를 하고 기존에 주어진 값으로만 테스트를 진행하는데 이런 방식도 괜찮은가요? 다른 격리방법이 있다면 어떤게 있을지 궁금합니다.

sql join을 통해 join 구문만을 위한 엔티티를 작성하고 객체로 변경하는 방법을 거치는 것보다 select쿼리를 필요한 만큼 보내고 도메인 객체로 변환하는 것이 트레이드오프에서 이득이라고 생각했습니다. 단순 조인문이라면 쿼리를 복잡하게 작성하는 것보다 쿼리를 여러번 날리는 선택을 하는 것이 유지보수에 좋다고 생각하기도 했습니다. 쿼리를 적게 날리는 성능상 이점과 기존의 자바코드를 재활용할 수 있다는 편리성 중 어느쪽을 선택하는 것이 좋을까요?

2023-05-18 10:42 UTC, aegis1920 commented on src/test/java/subway/integration/LineIntegrationTest.java
> +import static org.apache.http.HttpStatus.SC_BAD_REQUEST;
org.springframework.http.HttpStatus를 사용해보는 건 어떨까요? org.apache.http.HttpStatus은 io.restassured에 종속되어있어서 테스트에서 io.restassured를 쓰지 않게 된다면 해당 코드도 변경이 필요할 것 같습니다!

2023-05-18 10:45 UTC, aegis1920 commented on README.md
root에서 시작하는 건 모든 어플리케이션이 다 그럴 거라고 생각해요. root에서부터 분리될 필요가 있다면 모듈 단위로 분리해봐야되는 건 아닐지 고민해보는 것도 좋을 것 같습니다!

2023-05-18 10:50 UTC, aegis1920 commented on src/test/resources/test.sql
> +DROP TABLE paths IF EXISTS;
실무에서 테이블을 삭제하는 일은 정말 드문데요! table을 drop하는 것과 table을 truncate하는 것에는 의미로도 성능으로도 차이가 있습니다! 그 차이에 대해서 직접 찾아보시는 걸 추천드려요!

더불어 테스트 격리는 테이블을 drop하든, truncate를 하든 성공해야합니다. 즉, id가 달라지더라도 성공해야합니다. 그래야 테스트 격리로서 의미가 있어집니다. 제대로 된 테스트 격리를 위해 truncate로 수정해보는 건 어떨까요?

2023-05-18 12:08 UTC, aegis1920 commented on src/test/resources/application.properties
> +spring.sql.init.mode=never
이미 아실 수도 있겠지만 스프링부트 지식과 상황 정리부터 해보겠습니다. never로 설정하지 않으면 터지는 removeStationTest2를 기준으로 살펴볼게요.

현재 성공하는 이유부터 보겠습니다.

- 기본적으로 resource의 data.sql과 schema.sql이란 이름을 가진 파일은 스프링 부트가 시작되면 자동으로 실행됩니다. ([링크](https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.data-initialization.using-basic-sql-scripts))
- 해당 파일은 지금도 프로덕션(main) 코드에 존재합니다.
- 그래서 테스트가 실행되면 프로덕션에 있는 main.resource에 있는 data.sql과 schema.sql 파일이 실행됩니다. 
- 그러나 테스트 패키지에는 spring.sql.init.mode=never가 존재해서 main.resource에 있는 파일들이 실행되지 않았고, IntegrationTest의 `@Sql`이 실행되었습니다.
- IntegrationTest의 `@Sql`을 통해 스키마가 생성되고 데이터가 생성되어 테스트가 통과했습니다.

그러면 init.mode=always로 두고 removeStationTest2를 실행시켜보면 왜 터질까요?
에러 메시지에는 아래와 같이 나와있습니다. 

```
org.springframework.jdbc.datasource.init.ScriptStatementFailedException: Failed to execute SQL script statement #4 of class path resource [test.sql]: INSERT INTO line (name, color) VALUES ('1호선', '파랑'), ('2호선', '초록'), ('empty', 'none'); nested exception is org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_2 ON PUBLIC.LINE(NAME NULLS FIRST) VALUES ( /* 1 */ U&'1\\d638\\c120' )"; SQL statement:
INSERT INTO line (name, color) VALUES ('1호선', '파랑'), ('2호선', '초록'), ('empty', 'none') [23505-214]
```

primary key 인데도 불구하고 같은 데이터를 넣고 있어서 해당 에러가 발생했습니다. init.mode=always로 두면 프로덕션에 있는 data.sql과 schema.sql이 실행되고 테스트에서 test.sql, drop.sql이 실행돼 같은 키의 데이터를 넣으려고 해서 터지게 됩니다.

이해가 조금 되셨을까요? 

해결하기 위해서 간단하게 아래와 같은 방법이 떠오르네요 🙂 

- test 패키지 프로퍼티에서 spring.sql.init.mode=never 삭제
- drop.sql, test.sql 삭제
- IntegreationTest에서 `@Sql` 모두 삭제 

위와 같이 삭제한 후 실행하면 프로덕션에 있는 schema.sql과 data.sql만 실행시키면서 테스트가 통과됩니다. (test.sql에서 insert하는 데이터를 보면 `여긴 못감` 데이터만 프로덕션과 달라서 다른 테스트에서는 실패할 여지가 있겠네요)

이와 관련되어 예전에 크루 리뷰를 남겼던 적이 있었는데 도움이 되실까 싶어 링크 남겨둡니다!([링크1](https://github.com/woowacourse/jwp-shopping-cart/pull/189#discussion_r1181579031), [링크2](https://github.com/woowacourse/jwp-shopping-cart/pull/189#discussion_r1181595490))
혹시 이해가 안 가신 부분이 있다면 언제든 말씀해주세요!

2023-05-18 12:11 UTC, aegis1920 commented on src/test/resources/test.sql
> +INSERT INTO line (name, color)
아시다시피 각 파일에는 의미가 있습니다. 테이블을 생성하는 것 데이터를 넣는 것을 구분하면 좋을 것 같아요.
구분하고 나서 아래와 같이 작성할 수도 있습니다.
```
@Sql({"/data.sql" , "/schema.sql"})
```

2023-05-18 12:14 UTC, aegis1920 commented on src/main/resources/application.properties
> +spring.sql.init.mode=always
처음 실행할 때도 똑같이 embedded로 하면 되는 거 아닐까요?

2023-05-18 14:20 UTC, aegis1920 requested changes
안녕하세요 주드! 빙봉입니다 🙂 

질문주신 것에 대한 답변 및 코멘트 추가했습니다. 확인 부탁드려요!

궁금한 점은 언제나 편하게 DM 주세요!

2023-05-18 14:20 UTC, aegis1920 commented on README.md
> +## 기능 요구 사항
이번 미션의 목표가 복잡한 도메인 이해와 설계인 만큼 요구사항이 좀 더 구체적이면 좋을 것 같아요! (e.g. 상행, 하행, 비용 정책 등..)

2023-05-18 14:20 UTC, aegis1920 commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost:13306/subway
tcp로 하지 않고 file로 만들어서 현재 프로젝트 내에 로컬 경로로 저장해줘도 될 것 같습니다!
```
spring.datasource.url=jdbc:h2:file:./db/subway
```

2023-05-18 14:20 UTC, aegis1920 commented on build.gradle
> +    runtimeOnly 'mysql:mysql-connector-java:8.0.28'
h2를 사용한다면 mysql 의존성은 없어도 되겠네요!

2023-05-18 14:20 UTC, aegis1920 commented on src/test/java/subway/application/service/ServiceTest.java
> +@Sql(value = "/drop.sql", executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD)
> 테스트 편의성을 위해 `@sql` 애노테이션을 통해 테스트 격리를 하고 기존에 주어진 값으로만 테스트를 진행하는데 이런 방식도 괜찮은가요? 다른 격리방법이 있다면 어떤게 있을지 궁금합니다.

네 상관없습니다! 

테스트를 격리하는데는 여러 가지 방법이 있는데요. (`@Sql`을 이용하는 방법, `@Dirtiescontext`, 직접 SQL문을 작성해서 삭제하는 방법, Service 혹은 Dao를 호출하는 방법 등등...)
각자 트레이드 오프가있으니 상황에 따라 적절하게 사용하시면 됩니다. 개인적으로 저는 TestSupport라는 클래스를 테스트 패키지에 만들고 직접 SQL문을 작성해서 삭제하는 방법을 사용합니다. ( 가장 의존성이 적고 직관적이라고 생각해서요!)

2023-05-18 14:20 UTC, aegis1920 commented on src/main/java/subway/persistence/dao/StationDao.java
> sql join을 통해 join 구문만을 위한 엔티티를 작성하고 객체로 변경하는 방법을 거치는 것보다 select쿼리를 필요한 만큼 보내고 도메인 객체로 변환하는 것이 트레이드오프에서 이득이라고 생각했습니다. 단순 조인문이라면 쿼리를 복잡하게 작성하는 것보다 쿼리를 여러번 날리는 선택을 하는 것이 유지보수에 좋다고 생각하기도 했습니다. 쿼리를 적게 날리는 성능상 이점과 기존의 자바코드를 재활용할 수 있다는 편리성 중 어느쪽을 선택하는 것이 좋을까요?

잘 분석해주셨네요! 말씀대로 두 가지 방법 모두 각자 트레이드 오프가 있습니다. 그리고 현재 상황에서는 저도 select쿼리만 하는 게 더 나아보이긴 해요!

기억해주셔야할 부분은 지하철 도메인이 복잡하나 테이블이 몇 개 없어서 단순히 select한 후 조합해도 괜찮습니다. 도메인이 지금보다 훨씬 복잡해지고 테이블도 많다면 하나하나 select를 한 후, 조합하기는 힘들기 때문에 sql join을 해줘야하는 상황이 자연스럽게 오게 될 거예요. 데이터가 많아지면 성능적으로도 join이 더 장점이 있고요! select해서 Application에서 조합하는 경우는 직관성이 필요하거나 매개변수가 필요하거나 SQL 쿼리로는 불가능한 복잡한 상황이 있거나 그럴 때 정도가 있겠네요! 🙂

2023-05-18 14:20 UTC, aegis1920 commented on src/main/java/subway/domain/dijkstra/Dijkstra.java
> +import subway.domain.Station;
Line이나 Station이라는 도메인이 모두 들어가있어서 다익스트라 그 자체만을 의미하긴 어렵지 않을까요?

2023-05-18 14:20 UTC, aegis1920 commented on src/main/java/subway/domain/dijkstra/Dijkstra.java
> +public class Dijkstra {
추상 클래스의 개념일까요?

2023-05-18 14:20 UTC, aegis1920 commented on src/main/java/subway/domain/ShortestWayCalculator.java
> +    }
필요한 코드인가요?

2023-05-18 14:20 UTC, aegis1920 commented on src/main/java/subway/domain/ShortestWayCalculator.java
> +            return new ShortestWayCalculator(((int) result.getWeight()), result.getVertexList());
new ShortestWayCalculator()를 하고 다시 새로운 ShortestWayCalculator을 생성하는 것(계산기에서 다시 계산기를 생성하는 구조)보다 다른 좋은 구조가 있지 않을까요?

2023-05-18 14:20 UTC, aegis1920 commented on src/main/java/subway/domain/addpathstrategy/AddPathStrategy.java
> +public interface AddPathStrategy {
👍

2023-05-18 14:20 UTC, aegis1920 commented on src/main/java/subway/ui/ExceptionController.java
> +public class ExceptionController extends ResponseEntityExceptionHandler {
Controller 역할은 아니지 않을까요? GlobalXXX~ 정도가 되면 좋을 것 같습니다!

2023-05-18 14:20 UTC, aegis1920 commented on src/main/java/subway/ui/PathController.java
>  @RequestMapping("/lines/{line-id}/stations")
이거 궁금했었는데요! lineId가 아닌 `line-id`로 주신 이유가 있을까요?

2023-05-18 14:20 UTC, aegis1920 commented on src/test/java/subway/application/service/feecalculator/DefaultFeeCalculatorTest.java
> +        final DefaultFeeCalculator policy = new DefaultFeeCalculator();
policy 그대로네요!

2023-05-20 08:51 UTC, kevstevie commented on src/main/java/subway/domain/dijkstra/Dijkstra.java
> +import subway.domain.Station;
도메인에 대한 정보를 완전히 제거하고 support 패키지로 분리헀습니다.

2023-05-20 09:17 UTC, kevstevie commented on src/main/java/subway/domain/ShortestWayCalculator.java
> +            return new ShortestWayCalculator(((int) result.getWeight()), result.getVertexList());
유틸 클래스로 변경하고 가장 짧은 경로에 대한 정보를 갖는 객체를 반환하게 수정했습니다.

2023-05-20 09:18 UTC, kevstevie commented on src/test/java/subway/application/service/ServiceTest.java
> +@Sql(value = "/drop.sql", executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD)
답변 감사합니다!

2023-05-20 09:19 UTC, kevstevie commented on src/test/resources/test.sql
> +INSERT INTO line (name, color)
분리했씁니다!

2023-05-20 09:20 UTC, kevstevie commented on src/test/resources/test.sql
> +DROP TABLE paths IF EXISTS;
TRUNCATE 후에 auto_increment를 초기화하는 방법은 어떤가요?

2023-05-22 06:22 UTC, kevstevie commented on src/main/java/subway/ui/PathController.java
>  @RequestMapping("/lines/{line-id}/stations")
음 사실 별 이유는 없는데 url에 카멜케이스를 쓰는게 어색해서? 입니다
별다른 컨벤션이 있을까요?

2023-05-22 07:02 UTC, kevstevie commented
안녕하세요 빙봉! 리뷰 반영하고 다시 요청드립니다.
인수테스트에 대한 글을 좀 찾아보게 되었는데 그걸 중심으로 리팩터링했습니다.
한가지 문제가 있다면 문서화는 항상 익숙해지지 않는 것 같습니다,,더 자세한 명세를 쓰는게 어렵게 느껴지네요

2023-05-23 16:06 UTC, aegis1920 commented on src/test/resources/test.sql
> +DROP TABLE paths IF EXISTS;
위에 이야기한대로 테스트 격리에 의미를 둬주시면 좋을 것 같습니다. `TRUNCATE 후에 auto_increment를 초기화` 방법도 괜찮다고 생각합니다!

2023-05-23 16:11 UTC, aegis1920 commented on src/main/java/subway/ui/PathController.java
>  @RequestMapping("/lines/{line-id}/stations")
따로 컨벤션이 없는 것으로 알고 있습니다! 궁금해서 물어봤습니다ㅎㅎ 답변 감사합니다 🙇

2023-05-23 16:54 UTC, aegis1920 requested changes
안녕하세요 주드! 빙봉입니다 🙂 

전반적으로 잘 구현해주셨네요! 👍 
질문에 대한 답변 및 추가 코멘트 남겼습니다! 다만 테스트에서 깨지는 부분이 있어 확인 한 번 부탁드려요!

궁금한 점은 언제든 편하게 DM 주세요~

2023-05-23 16:54 UTC, aegis1920 commented on src/test/java/subway/integration/LineAcceptanceTest.java
> +    void 기존에_있는_이름으로_노선을_추가한다() throws JsonProcessingException {
혹시 테스트가 깨지진 않는지 확인 부탁드려도 될까요?
<img width="647" alt="image" src="https://github.com/woowacourse/jwp-subway-path/assets/22311557/66a30cda-3c2b-4ddc-b9ac-f586b93fa8d7">

2023-05-23 16:54 UTC, aegis1920 commented on src/test/java/subway/integration/AcceptanceTest.java
> +public class AcceptanceTest {
abstarct 여도 되겠네요 🙂

2023-05-23 16:54 UTC, aegis1920 commented on src/test/java/subway/integration/AcceptanceTest.java
> +    @LocalServerPort
Deprecated된 어노테이션입니다! `org.springframework.boot.test.web.server.LocalServerPort`을 활용해보세요!

2023-05-23 16:54 UTC, aegis1920 commented on src/main/java/subway/ui/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {
에러가 발생하면 서버에서는 어떤 로그도 남기지 않는데요. ERROR 로그를 남기면 에러 분석에 도움이 되지 않을까요?

2023-05-23 16:54 UTC, aegis1920 commented on src/main/java/subway/application/service/FeeService.java
> +    @Transactional(readOnly = true)
- FeeService 위에 `@Transactional`이 붙어있는데 여기 다시 `@Transactional(readOnly = true)`이 붙어있네요. 하나만 적어도 될 것 같습니다!
- 현재 상황에서 `@Transactional(readOnly = true)` 관련해서 다른 크루와 이야기를 나눈 게 있었는데요. 주드도 알면 좋을 것 같아서 공유드립니다! (주드에게도 똑같은 피드백으로 접근하면 좋으나 시간이 부족할 것 같아 링크로 전달드리는 점 양해부탁드려요 🙇  ([링크](https://github.com/woowacourse/jwp-subway-path/pull/125#discussion_r1197941181)))

2023-05-23 16:54 UTC, aegis1920 commented on src/main/java/subway/domain/Line.java
> +    private boolean isEndOfTheLine(final List<Station> stations, final int index) {
함수 분리 👍

2023-05-23 16:54 UTC, aegis1920 commented on src/main/java/subway/domain/util/ShortestWayCalculator.java
> +public class ShortestWayCalculator {
Way와 Path 중 하나만 사용하는 게 좋지 않을까요? 테스트에는 computeShortestPath라고 적혀있기도 하네요!

2023-05-23 16:54 UTC, aegis1920 commented on src/main/java/subway/domain/util/ShortestWayCalculator.java
> +    private static final Dijkstra<Station> dijkstra = new Dijkstra<>();
변수명이 대문자가 아닐까요?

2023-05-23 16:54 UTC, aegis1920 commented on src/main/java/subway/ui/GlobalExceptionHandler.java
패키지가 ui 쪽이 맞을까요?

2023-05-24 06:57 UTC, kevstevie commented on src/test/java/subway/integration/LineAcceptanceTest.java
> +    void 기존에_있는_이름으로_노선을_추가한다() throws JsonProcessingException {
왜 깨질까요..?

2023-05-25 06:51 UTC, kevstevie commented on src/main/java/subway/ui/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {
slf4j를 통해 로그 남기도록 했습니다👍

2023-05-25 06:52 UTC, kevstevie commented on src/main/java/subway/ui/GlobalExceptionHandler.java
exception 패키지에 들어가도록 수정했습니다

2023-05-31 05:27 UTC, kevstevie commented on src/main/java/subway/application/service/FeeService.java
> +    @Transactional(readOnly = true)
transaction은 상당한 공부가 필요해보이는군요,, 감사합니다

2023-06-01 06:43 UTC, kevstevie commented
안녕하세요 빙봉
별 다른 변경이 없었는데 협업, 글쓰기 등등..때문에 이제야 리뷰요청 보냅니다.
한가지 의문이 생겼는데 response나 request를 만들 때 보통 기본 생성자를 사용하는 편인가요? 아니면 이것도 팀 컨벤션마다 다를까요??
리뷰 감사합니다!

2023-06-01 15:52 UTC, aegis1920 approved these changes
안녕하세요 주드! 빙봉입니다 🙂 

피드백이 많았는데 끝까지 반영해주셔서 감사합니다! 많은 이야기를 나눌 수 있어서 재밌었어요! ㅎㅎ

request dto 혹은 response dto 질문에 답변하자면.. 팀 컨벤션에 맞춘다기보단 기본 생성자를 만들 이유가 없다면 만들지 않는 편이라고 이야기할 수 있을 것 같아요. jackson이 버전업을 하면서 만들지 않아도 되는 것처럼요. 필요없다면 굳이 작성하지 않습니다!

고생 많으셨고 지하철 미션은 여기서 머지할게요! 협업 미션 파이팅입니다!!

2023-06-01 15:52 UTC, merged