[2단계 - 경로 조회 기능] 두둠(최영훈) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #108
Opened 2023-05-16 04:57 UTC by younghoondoodoom

안녕하세요 시카! 백엔드 크루 두둠입니다. 이번에도 잘 부탁 드리겠습니다!
1단계에서 구현 했을 때 시간이 모자라서 대충 구현한 감이 있어서 거의 새로 구현했습니다ㅠㅠ 시카가 1단계에서 피드백 해주신 내용을 이번 코드에 반영하고 tdd로 거의 새롭게 구현 했으니 참고 부탁드립니다!
이번 단계에서는 1단계에서 못했던 테스트와 쿼리 최적화에 집중하여 진행 했습니다. 그리고 최대한 객체지향적인 코드를 짜려고 노력했습니다!

## Questions
1. 쿼리 최적화 관련한 문제
만약 update를 하는 경우에 현재는 관련된 모든 데이터를 delete하고 다시 insert하고 있습니다. 어떤 데이터가  변경 되었는지 감지하는 기능을 사용할 수 없다보니 어쩔 수 없다고 느꼈는데, 다른 아이디어가 있으신지 궁금합니다!
2. 계층 간 격리성을 위한 dto
계층간의 완전한 격리성을 위해서는 통신을 할 때 dto를 사용하는 경우가 있는 것 같습니다. 예를 들어, controller에서 service로 넘어갈 때 현재는  request를 거의 그대로 넘겨주고 있는데 이럴 때 request가 바뀔 경우 service까지 문제가 발생할 수 있을 것 같습니다. dto를 통해서 계층 간 소통을 하여 완전한 격리성을 보장 할 수 있지만 약간 오버엔지니어링이라고 생각이 들 수 있을 것 같습니다. 시카는 어떤 케이스를 선호하시나요? 만약 dto를 통해 통신하지 않으신다면 controller와 service 중 어느 쪽에 request, response 같은 dto를 두시나요??
3. domain bean 등록
spring bean으로 등록하게 되면 spring에 의존하게 되므로 가능한 bean으로 등록하지 않고 사용하는 것을 선호합니다. 특히 domain 객체의 경우 최대한 bean으로 등록하지 않고 개발자가 생명주기를 직접 관리하고 있습니다.
하지만 교체 가능성이 높은 객체의 경우 bean으로 등록하여 di를 받는 것이 갈아끼우기 쉬울 것 같습니다. (ex - domain.CostPolicy) 
이러한 경우에 service가 domain 객체를 주입 받는게 어색한지 여쭤보고 싶습니다!

많이 성장할 수 있는 리뷰 부탁드립니다!

2023-05-17 12:04 UTC, dks301 requested changes
안녕하세요 두둠, 리뷰어 시카입니다. 😄

어려운 미션이었는데, 빠르게 피드백까지 잘 반영해주셨네요! 👍
추가로 코멘트드렸으니 확인 부탁드려요!!

추가로 궁금한 점이 생기면 언제든지 DM 주세요 ㅎㅎ

---

> 쿼리 최적화 관련한 문제
> 만약 update를 하는 경우에 현재는 관련된 모든 데이터를 delete하고 다시 insert하고 있습니다. 어떤 데이터가 변경 되었는지 감지하는 기능을 사용할 수 없다보니 어쩔 수 없다고 느꼈는데, 다른 아이디어가 있으신지 궁금합니다!

음... 이 부분은 코드에서도 봤는데요...! 추가적인 설명을 해주시면 좋을 것 같아요. 
1. 쿼리 기준으로 update 쿼리를 날리면 되는데 모든 데이터를 왜 delete하고 insert해야하는지 궁금합니다.
2. jpa의 변경감지와 어떤 관계가 있는지도 설명 부탁드려요 ㅎㅎㅎ

> 계층 간 격리성을 위한 dto
> 계층간의 완전한 격리성을 위해서는 통신을 할 때 dto를 사용하는 경우가 있는 것 같습니다. 예를 들어, controller에서 service로 넘어갈 때 현재는 request를 거의 그대로 넘겨주고 있는데 이럴 때 request가 바뀔 경우 service까지 문제가 발생할 수 있을 것 같습니다. dto를 통해서 계층 간 소통을 하여 완전한 격리성을 보장 할 수 있지만 약간 오버엔지니어링이라고 생각이 들 수 있을 것 같습니다. 시카는 어떤 케이스를 선호하시나요? 만약 dto를 통해 통신하지 않으신다면 controller와 service 중 어느 쪽에 request, response 같은 dto를 두시나요??

서버 입장에서 `도메인, entity vs Dto, controller` 중 어떤게 더 중요하고 변경될 가능성이 클까요?? 
당연히 도메인과 entity이 더 변경가능성이 낮고 중요하기 때문에 격리해 보호할 수 있도록 노력하는 것인데요.
frontend와 합의하에 Request가 변경될 때마다 Service 부터 도메인과 entity 코드까지를 수정해야한다면
1. 일단 수정사항이 많아지니 개발하기 힘들고, 리뷰하기도 힘들고
2. 개발자의 실수나 기타 문제가 발생할 확률(도메인이나 entity는 여러곳에서 사용하기 때문에)이 높아집니다.

개인적으로도 계층별로 DTO를 사용하는 것을 선호하는데요 ㅎㅎㅎ  위 내용에 따라 조금 더 외부 계층인 controller는 당연히 사용하고요.
service에까지 dto를 사용해야 하는가는 계층이 보호된다는 전제하에 유지보수나 확장성에 따라 결정할 것 같습니다 :)

> domain bean 등록
> spring bean으로 등록하게 되면 spring에 의존하게 되므로 가능한 bean으로 등록하지 않고 사용하는 것을 선호합니다. 특히 domain 객체의 경우 최대한 bean으로 등록하지 않고 개발자가 생명주기를 직접 관리하고 있습니다.
> 하지만 교체 가능성이 높은 객체의 경우 bean으로 등록하여 di를 받는 것이 갈아끼우기 쉬울 것 같습니다. (ex - domain.CostPolicy)
> 이러한 경우에 service가 domain 객체를 주입 받는게 어색한지 여쭤보고 싶습니다!

정답은 없지만 아무래도 교체 가능성으로만 빈으로 등록하는 것은 어색한 느낌이 있는것 같아요...! 오히려 그런 경우는 자바의 추상화나 디자인 패턴을 통해서 해결하는 것이 더 적절하지 않을까요??
스프링에서 bean은 핵심적이고 추상적인 개념이기 때문에 확실히 어떻게 해야한다는 정리하기 어려운데요
https://www.baeldung.com/spring-bean 설명을 읽어보고 다시 한 번 이야기해보면 좋을 것 같아요 😄

2023-05-17 12:04 UTC, dks301 commented on src/main/java/subway/application/LineService.java
> +    private final LineRepository lineRepository;
Repository로 추상화 👍

2023-05-17 12:04 UTC, dks301 commented on src/main/java/subway/application/LineStationService.java
> +    private final StationRepository stationRepository;
```suggestion
    private final LineService lineService;
    private final StationService stationService;
```
이렇게 Service를 DI하는 것과 Respository를 DI는 것을 비교해보고 장단점을 고민해보면 어떨까요??

2023-05-17 12:04 UTC, dks301 commented on src/main/java/subway/application/LineStationService.java
> +    private Station getStationByName(final String name) {
get이란 네이밍은 레벨1과 마찬가지로 getter를 연상시켜서 지양하는게 좋은데요..!
다른 이름을 고민해보면 어떨까요??

2023-05-17 12:04 UTC, dks301 commented on src/main/java/subway/domain/Navigation.java
> +    }
Navigation이라는  class를 만들어서 외부 라이브러리 전용 클래스를 만드셨는데요...!
Bean으로 설정하지 않고 이렇게 하신 이유가 있을까요??

2023-05-17 12:04 UTC, dks301 commented on src/main/java/subway/domain/Navigation.java
> +    }
가독성을 높일 수 있도록 적절하게 개행을 추가해주면 어떨까요??
코드상 개행이나 줄바꿈이 일반적인 문장의 띄어쓰기나 문단 나눔과 같아 읽기 더 좋아질 것 같아요!

2023-05-17 12:04 UTC, dks301 commented on src/test/java/subway/integration/PathIntegrationTest.java
> +        final LineResponse lineResponse1 = createLineResponse1.as(LineResponse.class);
1. 주석으로 추가 설명을 해주긴 하셨지만 DisplayName으로도 테스트코드를 이해 할 수 있도록 바꿔보면 어떨까요??
2. 잘 사용된 주석문은 코드가 왜 그 작업을 수행하는지 표현해줄 수 있어 유용한데요...! 지금은 주석이 어떤 일을 하는지가 설명되어 있는 것 같아요😅 또한 주석으로는 가독성 높은 코드를 대체할 수 없는데요...! 메서드로 추상화를 하는 방식이나 or 다른 더 좋은 방식으로 테스트 코드도 리팩토링해보면 어떨까요??

2023-05-17 12:04 UTC, dks301 commented on src/main/java/subway/domain/Line.java
> +    }
final 키워드를 많이 사용하고 있네요...!👍
변수나 메서드 명으로 많이 명시해주셨지만, 비즈니스 로직이 복잡해지면서 동시에 객체의 상태가 많이 변화되어 코드 레벨도 복잡해지고 있는 것 같아요 😢
도메인 객체들을 최대한 [불변 객체](https://tecoble.techcourse.co.kr/post/2020-05-18-immutable-object/)로 만들어서 안전성과 다른 장점들을 가져가보면 어떨까요??

2023-05-18 02:40 UTC, younghoondoodoom commented on src/main/java/subway/domain/Navigation.java
> +    }
Navigation의 생명주기를 직접 관리하고 싶었습니다. Navigation을 초기화할 때 Lines 객체를 넣는 것이 클래스 사용자 입장에서 사용하기 쉬울 것 같다고 생각했습니다. 만약 따로 Lines를 추가해주는 메소드를 생성할 수도 있겠지만, 그런 경우에 다른 메소드를 호출하기 전에 Lines를 추가해주는 메소드를 먼저 호출해줘야하므로 메소드 간에 순서가 생기게 됩니다. 그렇게 되면 사용자가 사용하기 쉽지 않은 클래스가 된다고 생각을 했습니다. 물론 그런 경우가 어쩔 수 없는 상황이 있지만 최대한 방지해야한다고 생각합니다!
도메인 클래스가 특정 라이브러리를 의존하는 것이 어색한가요? 제 생각은 해당 객체가 길을 찾는다는 역할을 추상화 했다고 생각을 했습니다!

2023-05-18 06:12 UTC, younghoondoodoom commented on src/main/java/subway/application/LineStationService.java
> +    private final StationRepository stationRepository;
service를 service가 di 각 도메인의 service마다 해당 도메인의 repository를 의존하게 되니 repository의 공통적인 기능에 접근할 때, 동일한 처리를 해줄 수 있어서 조금 더 추상화가 되고 코드 중복을 줄일 수 있겠네요! 트랜잭션도 필요한 경우 정말 최소 단위로 쪼갤 수도 있을 것 같습니다. 하지만 그렇게되면 service가 어쩔 수 없이 domain을 반환하게 되고 controller에서 service에 접근이 가능하니 controller에서 service를 통해 domain을 알게되는 경우가 생길 것 같습니다. 제 생각에는 장점보다 단점이 큰 것 같은데 시카의 생각은 어떤가요??

2023-05-18 07:06 UTC, younghoondoodoom commented
> 음... 이 부분은 코드에서도 봤는데요...! 추가적인 설명을 해주시면 좋을 것 같아요.
쿼리 기준으로 update 쿼리를 날리면 되는데 모든 데이터를 왜 delete하고 insert해야하는지 궁금합니다.
jpa의 변경감지와 어떤 관계가 있는지도 설명 부탁드려요 ㅎㅎㅎ

현재 Line에서 Collection으로 Sections를 가지고있고, Sections는 Station을 가지고있습니다. 만약 이 Line의 Collection을 수정하게 되면 기존 데이터와 변경된 데이터를 비교할 수가 없습니다. 그래서 해당 Line과 관련된 데이터들을 삭제하고 다시 insert하는 식으로 진행하고 있습니다. (LineRepositoryImpl.update) 
jpa의 변경감지를 사용하게되면 영속성 컨텍스트를 이용해서 변경된 데이터를 감지하고 알아서 update쿼리를 날릴 수 있습니다. 현재는 jdbc만을 이용하니 이 기능을 사용할 수 없으니 이러한 문제가 생기는 것 같습니다.
만약 수정하려는 Line이 엄청나게 많은 Section을 가지고있으면 모두 삭제하고, 모두 삽입하는 과정이 굉장히 비효율적일 것 같습니다. 이 쿼리를 최적화할 수 있는 아이디어가 있으신가해서 여쭤봤습니다!

2023-05-18 08:09 UTC, younghoondoodoom commented
3단계는 2단계 merge 되고나서 추가적으로 구현하고 리뷰요청 보내겠습니다!

2023-05-19 08:11 UTC, dks301 approved these changes
안녕하세요 두둠, 리뷰어 시카입니다. 😄

코멘트를 잘 반영해주셨네요! 👍
2단계 요구사항도 대부분 만족하신 것 같아서 이만 머지하겠습니다 :)
몇 가지 코멘트 남겨드렸으니 3단계에서 같이 이야기해보면 좋을 것 같아요!

추가로 궁금한 점이 생기면 언제든지 DM 주세요 ㅎㅎ

---

> 현재 Line에서 Collection으로 Sections를 가지고있고, Sections는 Station을 가지고있습니다. 만약 이 Line의 Collection을 수정하게 되면 기존 데이터와 변경된 데이터를 비교할 수가 없습니다. 그래서 해당 Line과 관련된 데이터들을 삭제하고 다시 insert하는 식으로 진행하고 있습니다. (LineRepositoryImpl.update)
> jpa의 변경감지를 사용하게되면 영속성 컨텍스트를 이용해서 변경된 데이터를 감지하고 알아서 update쿼리를 날릴 수 있습니다. 현재는 jdbc만을 이용하니 이 기능을 사용할 수 없으니 이러한 문제가 생기는 것 같습니다.
> 만약 수정하려는 Line이 엄청나게 많은 Section을 가지고있으면 모두 삭제하고, 모두 삽입하는 과정이 굉장히 비효율적일 것 같습니다. 이 쿼리를 최적화할 수 있는 아이디어가 있으신가해서 여쭤봤습니다!

쿼리를 최적화하는 방법은 다양하게 있는데요...!
여기에서는 sql 자체를 최적화를 한다던지 or 캐시를 활용한다던지 or batch insert/update를 활용한다던지 or .... 등등 여러가지 방법을 사용할 수 있을 것 같아요 😄

다만, jpa를 많이 사용해보신 것 같아 말씀드리자면..
지금은 학습하는 과정이니 jpa를 사용할 수 없어서 사용할 수 없다보다는
1. jpa 내부의 영속성 컨텍스트는 이 문제를 어떻게 해결했는지 고민해보고
2. 최대한 고민해 정답이라고 생각할 수 있는 해결방법을 찾아 구현해보고
3. 실제 jpa는 위 문제를 어떻게 해결했는지 찾아보면 훨씬 더 성장할 수 있는 믿거름이 될 것 같습니다 ㅎㅎ

2023-05-19 08:11 UTC, dks301 commented on src/main/java/subway/application/LineStationService.java
> +    private final StationRepository stationRepository;
장점에 대해서 정리를 잘해주셨네요...! 👏👏

단점에 대해서는, 단순히 "controller에서 domain을 알게된다"라는 것이 정확히 장점에 비해 어떤점 더 큰 단점인지 설명해주실 수 있을까요??
단순히 알게된다라는 것 자체가 문제라면 계층과 격리를 위한 DTO를 사용하면 되는 것 아닐까요?

2023-05-19 08:11 UTC, dks301 commented on src/main/java/subway/domain/Navigation.java
> +    }
아니요 어색하지 않습니다 ㅎㅎㅎ 어떤 고민을 통해 이렇게 하셨는지 궁금해서 질문드렸는데요. 오히려 개인적으로도 RichDomain 형태를 선호합니다.

다만, 현재는 private method가 많고 최종적으로 최단 경로를 찾는 해피 케이스에 대한 테스트 하나만 존재하는데요...!
외부 라이브러리를 사용하는 만큼 이를 적절하게 테스트하는 방법과 객체지향적으로 더 잘 표현할 수 없는지에 대해서 고민해보면 어떨까요??

2023-05-19 08:11 UTC, dks301 commented on src/main/java/subway/domain/Line.java
> +    }
도메인 객체에 적용해보셨네요 ㅎㅎㅎ
개인적으로 실무에서 reactive 환경(모두 함수형으로 불변객체 사용)하고 있어 추천드렸는데요...!
리팩토링하시면서 어떤 장단점이 있었는지 공유해주실 수 있을까요? 😄

2023-05-19 08:12 UTC, merged