[2단계 - 경로 조회 기능] 연어(황재현) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #110
Opened 2023-05-16 06:29 UTC by nuyh99

범블비 안녕하세요!!
2단계이지만 첫 미션 제출이네요...!!
피드백 없이 진행해서 다른 분들에 비해서 많이 부족할 수도 있을 것 같습니다.
가감 없는 채찍질 잘 부탁드려요 😃

2023-05-16 12:44 UTC, ddaaac requested changes
안녕하세요 연어 👋 

전체적으로 구현이 깔끔하게 되어있네요. 

간단한 코멘트들 남겼으니 확인해주세요!

2023-05-16 12:44 UTC, ddaaac commented on src/test/java/subway/application/ShortestServiceTest.java
> +            Long stationId4 = stationService.saveStation(new StationRequest("해운대역")).getId();
이 테스트를 구현하기 위해 최단거리를 구하기 위해서 Station, Line을 저장하고 스프링의 빈들을 모두 불러오는 과정이 필요할까요?

2023-05-16 12:44 UTC, ddaaac commented on src/main/java/subway/application/ShortestService.java
> +            throw new IllegalStateException("경로가 존재하지 않습니다.");
예외 처리까지 꼼꼼히 해주셨네요 👍 
- 라이브러리 내부에서 발생하는 IllegalArgumentExcetpion은 따로 처리해주지 않은 이유가 있을까요?
- 여기서 IllegalStateException을 사용해주신 이유가 있을까요?

2023-05-16 12:44 UTC, ddaaac commented on src/main/java/subway/domain/PathEdgeProxy.java
> +public final class PathEdgeProxy extends DefaultWeightedEdge {
상속이 빛을 발하는 몇 안 되는 순간이죠. 
만약 라이브러리 버전을 업그레이드해서 DijkstraShortestPath에서 Path를 구하는 로직이 변경되면 어떤 일이 일어날지 고민해보시면 좋을 것 같네요.

2023-05-16 12:44 UTC, ddaaac commented on src/main/java/subway/domain/Paths.java
> +        result.add(previous.merge(next));
Path의 로직들이 해피케이스 위주로 짜여있는 것 같아요. 예를 들어 merge되는 두 Path에 공통 Station이 없다면 어떻게 될까요?

2023-05-16 12:44 UTC, ddaaac commented on src/main/java/subway/domain/Paths.java
> +        return fareStrategy.calculate(getTotalDistance());
이 계산까지가 Paths의 책임으로 적당할까요?

2023-05-16 12:44 UTC, ddaaac commented on src/main/java/subway/domain/Paths.java
>                  .filter(station -> station.equals(up) || station.equals(down))
Path#contains를 사용해도 될 것 같네요

2023-05-16 12:44 UTC, ddaaac commented on src/main/java/subway/domain/Paths.java
> +                .ifPresentOrElse(originalPath -> {
else에 걸리는 케이스가 있나요?

2023-05-16 12:44 UTC, ddaaac commented on src/main/java/subway/domain/Paths.java
> +        final Path next = affectedPaths.get(1);
두 개의 Path가 사용되는 곳이 꽤 있어보이는데요, 이런 경우 이를 감싸는 객체를 하나 만드는 것도 방법이 될 수 있겠네요.

2023-05-16 12:44 UTC, ddaaac commented on src/main/java/subway/application/StationService.java
> +        return StationResponse.of(station);
전체적으로 정책이 추가되면서 기존 코드는 거의 수정하지 않고 잘 구현해주셨네요.
어떻게 이게 가능했는지 가볍게 생각해보셔도 좋을 것 같습니다 :)

2023-05-17 01:53 UTC, nuyh99 commented on src/test/java/subway/application/ShortestServiceTest.java
> +            Long stationId4 = stationService.saveStation(new StationRequest("해운대역")).getId();
테스트하기 힘든 상황이 아니면 통합테스트로 진행하는 것이 신뢰도 측면에서 더 좋다고 생각해요..!

하지만 말씀하신 대로 `최단 경로를 구할 수 있는 지`를 테스트하기 위해서 DB와의 트랜잭션은 불필요한 과정입니다.
테스트 더블을 사용해서 반영했습니다!!

2023-05-17 02:23 UTC, nuyh99 commented on src/main/java/subway/application/ShortestService.java
> +            throw new IllegalStateException("경로가 존재하지 않습니다.");
- 해당 예외를 깜빡했습니다ㅠㅠ
DB에 Station은 저장돼있지만 해당 역이 아무 노선의 Path에도 없을 때, Vertex에 안 들어가서 발생합니다.
`Exception`을 처리하도록 변경했습니다!!

- 경로 찾기가 불가능한 도메인 상태라고 판단했습니다.
클라이언트는 제대로 DB에 존재하는 Station들로 요청을 보냈지만 경로를 찾을 수 없는 상태로 `IllegalStateException`을 썼습니다.
하지만 결국 예외 핸들러에서는 400으로 보냈었는데, 사실 성공적인 요청이라고 생각합니다. 따라서 200으로 처리하지만 body에는 "경로가 없습니다" 등을 보내도록 수정했습니다.

2023-05-17 02:31 UTC, nuyh99 commented on src/main/java/subway/domain/PathEdgeProxy.java
> +public final class PathEdgeProxy extends DefaultWeightedEdge {
우선 기존에 사용하던 `DefaultWeightedEdge`를 그대로 쓰거나 Deprecated 붙여두는 두가지 경우가 있을 것 같습니다.

1. Deprecated를 명시해둔 상태 -> IDE에서 주황색 줄을 그어주고 개발자가 preferred 방식으로 리팩토링할 가능성이 높다.
2. DefaultWeightedEdge 내부 구현이 달라진 상태
    1.  **현재 오버라이드한 메서드들의 시그니처는 그대로지만 내부가 달라진 상태** -> 오동작을 일으킬 것이다. 
             하지만 내부 동작을 바꾸려고 하면 라이브러리 개발자들은 새로운 메서드를 추가하거나 어댑터 클래스를 추가할 것이다.
    2. **새로운 메서드가 추가된 상태** -> 상속을 받았기 때문에 문제없이 잘 동작할 수 있다.

2023-05-17 02:40 UTC, nuyh99 commented on src/main/java/subway/domain/Paths.java
> +        result.add(previous.merge(next));
현재의 로직에서는 해당 상황이 발생할 일이 없지만, 다른 개발자가 merge() 메서드를 사용할 때는 문제가 발생할 것 같습니다.
따라서 아래와 같이 처리해뒀습니다.
<img width="584" alt="image" src="https://github.com/woowacourse/jwp-subway-path/assets/93072571/80a8b68b-e642-40ed-88b6-e752bb36bbb8">

다른 개발자가 오용하지 못하도록 하는 것이 제일 좋은 것 같습니다.
하지만 그렇다면 다른 모든 메서드도 이런 식으로 구현해야 할 지 궁금해요!
Checked 예외를 사용해서 한다면, 더 확실하게 처리하도록 할 수 있을 것 같지만 사용하는 입장에서는 매우 불편할 것 같습니다.
그리고 예외를 사용해서 처리하는 것이 좋은 지도 의문이에요...!!

2023-05-17 04:15 UTC, nuyh99 commented on src/main/java/subway/domain/Paths.java
> +                .ifPresentOrElse(originalPath -> {
> UpStation = 해운대, DownStation = 서면

위의 상황에서
> Upstation = 서면, DownStation = 전포

구간을 추가하려고 하면, UpStation이 같거나 DownStation이 같은 경우가 없기 때문에 말씀하신 else 케이스가 됩니다!
기존 경로의 상행 종점이나 하행 종점에 경로를 추가하려고 할 경우입니다.

2023-05-17 04:35 UTC, nuyh99 commented on src/main/java/subway/domain/Paths.java
> +        return fareStrategy.calculate(getTotalDistance());
아무 생각 없이 `ShortestResponse.of()`에서 파라미터로 `Paths` 한 개만 받기 위해서 역할을 추가해버렸습니다.
DTO의 편의를 위해서 도메인에 역할을 추가한 것이라 완전히 잘못된 행동이라고 생각해요!
서비스 레이어에서 넘겨주도록 반영했습니다.

2023-05-17 10:32 UTC, nuyh99 commented on src/main/java/subway/domain/Paths.java
> +        final Path next = affectedPaths.get(1);
두 개의 Path를 하나의 객체로 만든다는 것이 어떻게 사용될 지 전혀 감이 안옵니다ㅠㅠ
지금은 두 Path에 대한 로직들을 수행하는 PathUtils를 만들고 역할을 위임했습니다.

범블비의 말씀에 대해서 조금만 힌트를 주실 수 있을까요...??

2023-05-17 10:42 UTC, nuyh99 commented on src/main/java/subway/application/StationService.java
> +        return StationResponse.of(station);
객체지향과 레이어드 아키텍처의 장점인 것 같습니다.
필요한 부분에 대해서 추가적으로 구현해서 조립만 하면 됐습니다...!

2023-05-17 10:46 UTC, nuyh99 commented
범블비 피드백 감사합니다!
최대한 반영해봤습니다😄

---

Path 도메인에서 충분히 두 Path 간의 로직을 가지고 있었고, Paths에서 경로 컬렉션에 대한 로직을 가지고 있었습니다.
다만 두 Path 를 감싸는 다른 객체로 분리하라는 것이 어떤 의미이신 지 의문입니다...!
이번에도 미리 감사드려요!!

2023-05-17 14:44 UTC, ddaaac requested changes
안녕하세요 연어 👋 

리뷰 반영 잘 해주셨습니다.

간단하게 코멘트 남겼으니 확인해주세요~

2023-05-17 14:44 UTC, ddaaac commented on src/main/java/subway/domain/Paths.java
> +        final Path next = affectedPaths.get(1);
```java
class BothPath  {
    private Path first;
    private Path second;
    public List<Path> toList() {
}
```
이런 식의 간단한 객체를 구성할 수 있다는 얘기였습니다. (이름은 대충 지었으니 무시해주세요 ㅎㅎ)
코드 여기저기서 2개의 Path를 필요로 하는 곳들이 눈에 띄더라구요.

2023-05-17 14:44 UTC, ddaaac commented on src/main/java/subway/domain/Paths.java
> +        result.add(previous.merge(next));
> 하지만 그렇다면 다른 모든 메서드도 이런 식으로 구현해야 할 지 궁금해요!

네. 객체는 그 자체로 온전해야합니다. 지금 만든 객체는 어디서 사용될지 모릅니다. 
나중에 누군가(본인이 되기도 합니다. 정말 자주 일어나요) merge할 수 없는 Path를 넘기면 어떤 일이 일어날까요?
꼭 Checked 예외까지 던지지는 않더라도 궁금할 때 코드를 통해 빠르게 파악하거나, 테스트 작성하면서 런타임에라도 파악할 수는 있어야겠죠.

2023-05-17 14:44 UTC, ddaaac commented on src/main/java/subway/domain/PathEdgeProxy.java
> +public final class PathEdgeProxy extends DefaultWeightedEdge {
> 하지만 내부 동작을 바꾸려고 했다면, 라이브러리 개발자들은 새로운 메서드를 추가하거나 어댑터 클래스를 추가하는 등으로 바꼈을 가능성이 높다. 

모르는 일이긴 하죠 😄 
그래서 상속이 꽤 위험한 방식이구요.

2023-05-17 14:44 UTC, ddaaac commented on src/main/java/subway/domain/Paths.java
> +                .ifPresentOrElse(originalPath -> {
아 제가 overlap 정의에 대해 착각했네요.

2023-05-17 14:44 UTC, ddaaac commented on src/test/java/subway/application/ShortestServiceTest.java
> +            Long stationId4 = stationService.saveStation(new StationRequest("해운대역")).getId();
코멘트를 남겼던 의도는 특정 기술과 결합한 형태가 아닌 도메인으로 분리해보는 건 어떨까?였습니다.
서비스 레이어는 단순히 도메인에 넘길 값들을 가져오는 용도로 가볍게 작성해보시는 것도 좋을 것 같네요.

2023-05-17 14:44 UTC, ddaaac commented on src/main/java/subway/domain/Paths.java
>      public Paths(final List<Path> paths) {
new Paths(new Path(1, 2), new Path(3,4))와 같은 input이 들어온다면 어떻게 될까요?

2023-05-17 14:44 UTC, ddaaac commented on src/main/java/subway/application/ShortestService.java
> +            throw new IllegalStateException("경로가 존재하지 않습니다.");
- 예외 상황이 아닌데 예외로 처리해도 괜찮을까요? [예외는 예외 상황에만 사용](https://madplay.github.io/post/effectivejava-chapter10-exceptions#%EC%95%84%EC%9D%B4%ED%85%9C-69-%EC%98%88%EC%99%B8%EB%8A%94-%EC%A7%84%EC%A7%9C-%EC%98%88%EC%99%B8-%EC%83%81%ED%99%A9%EC%97%90%EB%A7%8C-%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC)해야합니다.
- 예외로 처리할 거라면 IllegalArg 예외가 더 적당해보여요. `service.findShortest(source, dest)`에서 내부 상태 때문이 아닌 요청값이 잘못되었으니 경로가 없는 것 아닐까요?

2023-05-18 02:16 UTC, nuyh99 commented on src/test/java/subway/application/ShortestServiceTest.java
> +            Long stationId4 = stationService.saveStation(new StationRequest("해운대역")).getId();
감사합니다👍
최단 거리 관련 기능이 바뀔 가능성이 높다면 최대한 상위 레이어에 위치하는 것이 좋을 것 같고, 근본적인 도메인이라면 도메인 레이어에 위치하는 것이 좋을 것 같습니다.
외부 라이브러리를 사용하는 부분이라서 도메인으로 만들기 좀 꺼렸던 것 같습니다.
현재는 도메인으로 분리했습니다 !

2023-05-18 02:18 UTC, nuyh99 commented on src/main/java/subway/application/ShortestService.java
> +            throw new IllegalStateException("경로가 존재하지 않습니다.");
링크 감사합니다!!
생각해보니 예외가 아닌 것 같네요...!
Empty한 Paths를 주는 것이 맞는 것 같습니다.

2023-05-18 02:32 UTC, nuyh99 commented on src/main/java/subway/domain/Paths.java
> +        result.add(previous.merge(next));
감사합니다!!
반영하겠습니다.

2023-05-18 06:24 UTC, nuyh99 commented on src/main/java/subway/domain/Paths.java
>      public Paths(final List<Path> paths) {
전체가 이어져있는지 검증 로직을 추가하면 됩니다.
하지만 현재 전체 노선의 경로들을 Paths에 매핑하는 경우도 있기 때문에, 이 상황에서는 1호선과 2호선이 서로 연결이 안돼있을 수 있습니다.

따라서 현재 생각했을 때 가장 좋은 방법으로 반영해봤습니다.
Paths에는 전체가 연결돼있는 지 검증 로직을 추가하고,
최단 경로 로직에서 모든 노선의 Path들을 Paths로 매핑하고 있는데, 이것을 List<Paths> 타입을 사용하도록 로직을 변경했습니다!

2023-05-19 01:29 UTC, nuyh99 commented
피드백 감사합니다 범블비!!
다른 개발자가 최대한 오용하지 못하도록 만드는 것은 어렵네요...!
코드가 좀 더 길어지게 되지만, 가정 없이 재사용이 가능하다는 장점이 훨씬 큰 것 같습니다.

이번에도 최대한 반영해봤습니다. 잘 부탁드려요👍

2023-05-19 14:15 UTC, ddaaac approved these changes
안녕하세요 연어 👋 

리뷰 반영 잘 해주셨습니다.

다음 단계 진행을 원하시면 진행해주세요!
고생하셨습니다~

2023-05-19 14:15 UTC, ddaaac commented on src/main/java/subway/domain/Shortest.java
> +        } catch (final Exception e) {
예외를 잡을 떄는 최대한 타이트하게 잡아주시면 좋습니다.
개발자 본인이 인지하고 있는 예외에 대해서는 빈 Path를 리턴하는 게 맞겠지만, 그렇지 않은 예외가 라이브러리 깊숙한 곳에서 터질 수도 있거든요. 이런 경우는 예외 상황이고, 예외를 빠르게 잡아서 버그 상황을 고칠 수 있어야겠죠.

2023-05-19 14:15 UTC, ddaaac commented on src/test/java/subway/domain/ShortestTest.java
> +            //given
그림까지 잘 표현해주셨네요.

TC가 조금 더 다양하면 좋을 것 같아요.

2023-05-19 14:15 UTC, merged

2023-05-19 15:44 UTC, nuyh99 commented on src/main/java/subway/domain/Shortest.java
> +        } catch (final Exception e) {
편의를 위해서 `Exception`으로 처리해버렸네요ㅠㅠ
동의합니다. 반영했습니다!