[2단계 - 경로 조회 기능] 져니(이지원) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #111
Opened 2023-05-16 11:01 UTC by Cl8D

안녕하세요, 또링! 져니입니다!
지난 1단계 때 피드백을 빠르게 주신 덕분에 2단계도 금방 구현할 수 있었습니다~!
`2단계 - 경로 조회 기능` (DB 설정, 경로 조회 API, 요금 조회 기능)에 해당하는 부분은 Commit [191dac9](https://github.com/Cl8D/jwp-subway-path/commit/191dac9abfca7c8e437349f84cd57a67c1b1785a)까지 구현해두었습니다.
추가적으로 `3단계 - 요금 정책 추가`에 해당하는 부분이 마지막 커밋까지입니다 😊
- 요금 정책의 경우 Age를 입력받아서 처리해야 되나 싶었는데, 쿼리 파라미터의 개수가 너무 많아지는 것 같아서 그냥 적용된 요금을 반환하는 식으로 진행하였습니다!

그리고, LineService와 RouteService 사이에서 공통적으로 사용되는 메서드는 SectionProvider 쪽으로 뺐는데 어울리는 네이밍인지... 이런 구조로 가져가도 될지 고민이네요 🥲 + 아직 Sections라는 도메인에 대한 마땅한 이름도 생각하지 못했습니다 ㅠㅠ

API 문서화는 1차적으로 피드백 받은 뒤에 함께 적용해서 PR 올리겠습니다! 
피드백은 얼마든지 환영입니다!
이번 리뷰도 잘 부탁드려요! 감사합니다 🙇‍♀️

2023-05-17 04:51 UTC, Cl8D commented
안녕하세요, 또링! 생각해보니까 추가 요금에 대한 도메인을 생성하지 않은 것을 발견해서 이건 제가 따로 추가해두겠습니다 🥲 (커밋은 리뷰 후에 반영할 예정이에요!)
추가적으로 최단 경로 생성 시 단방향으로는 잘 조회가 되는데, 반대방향에 대한 경우를 고려하지 않았던 것 같아요... ㅠ_ㅠ 
이 부분도 리뷰 받은 후에 함께 반영해서 푸시하겠습니다!

2023-05-18 09:35 UTC, jnsorn requested changes
안녕하세요. 져니! 이번 단계도 빠르게 잘 구현해주셨네요. 👍
2단계에서 3단계까지 같이 반영해서 요청주셨는데, 우선 2단계 내용에 대해서만 리뷰 드렸어요!
3단계에 대한 내용은 2단계를 마무리한 이후에 다시 얘기 나눠봐요 😃

2023-05-18 09:35 UTC, jnsorn commented on src/main/resources/application-test.yml
> +spring:
> 데이터베이스 설정을 프로덕션과 테스트를 다르게 합니다.
프로덕션의 데이터베이스는 로컬에 저장될 수 있도록 설정
테스트용 데이터베이스는 인메모리로 동작할 수 있도록 설정

요구사항을 잘 구현해주셨네요 👍환경별로 값을 다르게 주입하기 위해서는 
하나의 yml 파일에 profile을 사용하여 환경별로 값을 구분하는 방법과
지금처럼 환경별로 yml 파일을 만드는 방법이 있는데요, 현재의 방법을 선택하신 이유가 궁금해요.

2023-05-18 09:35 UTC, jnsorn commented on src/main/java/subway/dao/LineRepositoryImpl.java
>  }
convert 역할을 하는 객체를 만들어보면 어떨까요?

2023-05-18 09:35 UTC, jnsorn commented on src/main/java/subway/dao/LineDao.java
> +    public List<LineWithSection> getAllLineSectionsBySourceAndStationId(final Long sourceStationId,
메서드명이 살짝 부자연스럽네요 👀 
```getAllLineSectionsSourceAndTargetStationId``` 를 표현하고자 하신 거 같은데 맞을까요~?

2023-05-18 09:35 UTC, jnsorn commented on src/main/java/subway/application/FareCalculator.java
> +    }
OCP를 위반하고 있어요. 어떻게 개선해볼수 있을까요? (Hint. 해당 구간에 판단하는지 여부와 요금을 계산하는 메서드가 공통적이네요)

2023-05-18 09:35 UTC, jnsorn commented on src/main/java/subway/application/RouteService.java
> +import org.jgrapht.graph.WeightedMultigraph;
최단경로를 찾기 위해 외부 라이브러리를 사용하셨군요. 💯
다만 현재 RouteService에서 외부 라이브러리 구현체를 직접 의존하고 있어요.
만약 지원 중단 혹은 더 좋은 라이브러리의 등장 등으로 라이브러리를 교체해야 하는 경우, 영향받는 범위는 어떻게 될까요?
또 영향 범위를 어떻게 최소화 할 수 있을지 고민해봅시다!

2023-05-18 09:35 UTC, jnsorn commented on src/test/java/subway/integration/RouteIntegrationTest.java
> +    }
통합테스트도 잘 작성해주셨네요 💯

2023-05-18 09:35 UTC, jnsorn commented on src/main/java/subway/application/RouteService.java
> +public class RouteService {
> 추가적으로 RouteService를 리팩터링하고 있습니다! 너무 서비스에서 많은 일들을 하는 것 같아서 도메인쪽으로 위임할 수 있는 로직들은 위임해보려고 해요...!

져니가 말씀해주신대로 RouteService에서 너무 많은 일을 하고 있네요. 😉

2023-05-18 15:48 UTC, Cl8D commented on src/main/resources/application-test.yml
> +spring:
하나의 yml 파일에 환경별로 값을 구분하는 것은 구분자를 사용하는 방법일까요 ?_?
아니면 필드명을 다르게 해서 별도의 프로퍼티 클래스를 생성하여 거기서 정보를 로드하고, 필요한 설정 정보를 빈으로 주입하는 방식일까요...?! (@Profile 어노테이션 사용)

저는 개인적으로 환경별로 yml을 설정하는 것이 특정 환경에서 어떤 정보들을 사용하는지 한 눈에 알아볼 수 있어서 선호하는 편이에요! (사실 이 방법이 더 익숙해서 자연스럽게 사용한 것도 없지않아 있는 것 같아요...!)
보통은 application.yml에 공통적으로 사용하는 정보를 두고 환경별로 달라지는 부분에 대해서만 정의하는 편입니다 😊 

또링은 어떤 방법을 더 선호하시나요?!

2023-05-18 16:27 UTC, Cl8D commented on src/main/java/subway/dao/LineRepositoryImpl.java
>  }
mapper class를 생성해서 저런 식으로 변환하는 로직(?)들은 모두 그쪽에서 처리하도록 만들어보겠습니다! (repository / service 모두!)

2023-05-18 16:37 UTC, Cl8D commented on src/main/java/subway/dao/LineDao.java
> +    public List<LineWithSection> getAllLineSectionsBySourceAndStationId(final Long sourceStationId,
출발역에서 도착역으로 갈 수 있는 노선들이 가진 모든 구간 정보를 구하는 메서드인데 이름이 조금 애매하죠 😅 (쿼리가 워낙 복잡해서 더 그런 것 같기도 해요)
출발역, 도착역이 조건으로 주어지기 때문에 By를 넣기는 했는데 어떤 것이든 좀 부자연스러운 것 같아요 ㅠ_ㅠ
우선 또링이 말씀해주신 `getAllLineSectionsSourceAndTargetStationId`으로 변환해보겠습니다!

2023-05-18 16:38 UTC, Cl8D commented on src/main/java/subway/dao/LineDao.java
> +    public List<LineWithSection> getAllLineSectionsBySourceAndStationId(final Long sourceStationId,
아...!! 메서드명이 너무 길어지면서 착각했던 것 같아요 😅 바로 수정해두겠습니다!!!

2023-05-20 09:43 UTC, Cl8D commented
안녕하세요, 또링! 져니입니다! ㅎㅎ
DM에서 받았던 답변대로 구현을 해보았습니다 🙇‍♀️
Rest-docs를 통해 문서화를 하려고 했었는데 지난 미션 때 시도해봤어서, 이번에는 http client를 이용해서 직접 문서화를 진행해보았어요 ㅎㅎ
mapper class를 따로 두면서 각 서비스들이 조금 더 비즈니스 로직에 집중할 수 있도록 만들었는데, 괜찮은 선택이었는지 고민이네요...!
그래도 각 정책별로 클래스를 나누다 보니까 확실히 단위 테스트가 더 짜임새 있게 잘 짜진 것 같아요! 조언 주셔서 감사드립니다!!
피드백은 어떤 것이든 너무 환영이에요!
이번에도 잘 부탁드려요~! 😊❤️

2023-05-22 01:35 UTC, jnsorn approved these changes
안녕하세요 져니! 리뷰 잘 반영해주셨네요 😃
3단계 코드도 같이 확인했는데 잘 구현해주신것 같아요.
이번 미션의 요구사항은 모두 충족한 것 같아 여기서 머지하도록 할게요.
코멘트 남겨두었으니 확인해주시고, 이후 궁금한 점은 DM주세요!

2023-05-22 01:35 UTC, jnsorn commented on http-client.env.json
> +}
중복되는 부분들도 별도로 빼서 잘 구현해주셨네요 👍

2023-05-22 01:35 UTC, jnsorn commented on src/main/resources/application-test.yml
> +spring:
구분자로 환경을 구분하는 것을 의미했습니다 😎 져니는 환경별로 설정하는 것을 선호하시는군요! 
프로젝트의 규모가 작거나 외부 설정값이 적은 경우에는 져니가 말씀해주신 방법이 좋은 것 같아요. 

저는 현업에서 구분자를 이용하여 한 파일 내에서 여러 환경에 대해 설정값을 명시해주는데요, 이렇게 하는 이유는 설정 파일을 용도에 맞게 구분하여 사용하고 있기 때문이에요. database, redis, 외부 endpoint와 같은 설정값들의 파일들을 생성하고 해당 파일내에 환경별로 값을 명시해주면 값이 변경 되었을 경우 관련된 파일만 변경할 수 있습니다. 

다음 미션 진행하시면서 여러 방법 시도해보시고 져니에게 가장 좋다고 생각하는 방법을 찾아가시면 좋을 것 같습니다.

2023-05-22 01:35 UTC, jnsorn commented on src/main/java/subway/dao/mapper/LineMapper.java
> +public final class LineMapper {
> mapper class를 따로 두면서 각 서비스들이 조금 더 비즈니스 로직에 집중할 수 있도록 만들었는데, 괜찮은 선택이었는지 고민이네요...!


어떤 이유로 고민이 되셨는지 궁금하네요 ㅎㅎ

2023-05-22 01:35 UTC, jnsorn commented on src/main/java/subway/domain/fare/discount/ChildFarePolicy.java
> +public class ChildFarePolicy implements DiscountFarePolicy {
3단계도 잘 구현해주셨네요!

2023-05-22 01:35 UTC, jnsorn commented on src/main/java/subway/domain/fare/discount/ChildFarePolicy.java
> +        final double discountPercentage = (100 - CHILD_DISCOUNT_RATE) * 0.01;
매직넘버가 보여요 🔎

2023-05-22 01:36 UTC, merged

2023-05-22 09:37 UTC, Cl8D commented on src/main/java/subway/dao/mapper/LineMapper.java
> +public final class LineMapper {
뭔가 다른 협업자가 mapper class를 잘 찾을 수 있을까... 라는 생각도 들었고, 여러 개의 mapper class가 서비스 클래스와 연관관계를 맺다보니 남용될 수도 있지 않을까 싶었습니다 ㅎㅎ mapper는 그렇게 중요한 클래스가 아니니까 요정도는 사용해도 괜찮을 것 같다는 게 제 생각이지만요!

2023-05-22 09:37 UTC, Cl8D commented on src/main/java/subway/domain/fare/discount/ChildFarePolicy.java
> +public class ChildFarePolicy implements DiscountFarePolicy {
또링 덕분이에요 👍