[2단계 - 경로 조회 기능] 하디(전동혁) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #112
Opened 2023-05-16 12:02 UTC by jundonghyuk

안녕하세요 카일 리뷰이 하디입니다.
1단계 때 말씀해주신 내용을 보완하고, 2단계 기능을 구현하여 제출합니다!

### 1단계에서 코멘트 주신 부분
마지막에 말씀해주신 부분을 첨부하겠습니다.
```
다만 구현이 조금 DB 친화적인 것 같습니다.

Sections가 내부적으로 History/Snapshot 을 가지고 있고 자신의 상태변경을 기록하고 있다 정도로만 도메인에서는 기능을 제공하고, 이를 적절히 찾고 조회하여 처리하도록 구현해보면 어떨까요?

전체적으로 도메인 기능을 약간 더 추상화해보면 좋을 것 같습니다.
```
저도 미션을 진행하면서 도메인을 짤 때 데이터베이스 테이블 구조를 계속 생각하게 되더라구요.
카일도 그렇게 생각하시는 것을 보면서 저의 생각이 구현에도 영향을 미쳤다는 것을 깨달았습니다.
Sections를 조금 수정해보았는데 카일이 의도하신 방향대로 했는지 의구심이 들어 여쭤봅니다.

저의 처음 구현은 Sections는 `add / remove` 메서드마다 변경사항을 반환값으로 주었는데요, 이제는 
변경사항을 필드로 가지고 있고, 그곳에 저장을 합니다.
또한 `reflectSectionChange`라는 메서드를 `Sections`에 정의하여 내부의 `List<Section> sections`에 변경사항을 업데이트 할 수 있습니다.
하지만 현재, 바뀐 정보만 필요하기 때문에 따로 `reflectSectionChange` 메서드를 호출하진 않았습니다.

이것이 의도하신 바가아니라면 다시 남겨주시면 반영하도록 노력해보겠습니다.

### 2단계에서 고민한 부분
#### 1. 데이터베이스 친화적인 도메인 설계를 피하는법..?
저번 1단계 리뷰에서도 카일이 저에게 주신 코멘트중 하나였습니다! 사실 저도 도메인 객체 모델을 설계하면서 테이블의 구조를 생각했던것 같습니다.
사실 도메인 객체 모델들을 설계하는 방법은 설계자에 따라서 천차만별일 것이라고 생각하는데요.
다양한 방법이 존재하는 만큼, 데이터베이스 테이블 설계방식을 참고하는게 안좋은 일인지 궁금합니다.
아예 고려를 안하고 짜는게 맞는 방식인지 의문이 들어 여쭤봅니다.
</br>
#### 2. DTO의 재사용에 대해서
만약 예를 들어,
```
public class LineResponse {
    private Long id;
    private String name;
    private String color;

    public LineResponse(Long id, String name, String color) {
        this.id = id;
        this.name = name;
        this.color = color;
    }

    public static LineResponse of(Line line) {
        return new LineResponse(line.getId(), line.getName(), line.getColor());
    }

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getColor() {
        return color;
    }
}
```

이러한 클래스가 존재한다고 할 때, 어떤 요청에 대한 응답이 위의 클래스의 부분집할일 때, 예를 들어, 위의LineResponse의 `color`필드는 쓰지 않고, `id, name`필드만 필요할 때 위의 클래스를 `color`필드는 쓰지 않기에 빈 문자열로 초기화하고 재사용해도 되는지 궁금해서 여쭤봅니다.

매번 응답 포맷에 대한 `DTO`를 설계하면 독립적인 `DTO`라 서로 영향은 안받겠지만, 관리해야하는 수가 늘어 트레이드오프가 존재한다고 생각하는데 어떻게 생각하시는지 궁금합니다.

긴 글 읽어주셔서 감사합니다.
오늘도 좋은하루되세요:)

2023-05-18 04:01 UTC, KIMSIYOUNG requested changes
안녕하세요 하디!
깔끔하게 잘 구현해주신 것 같아요.
몇가지 코멘트 남겼는데 확인 부탁드립니다.

2023-05-18 04:01 UTC, KIMSIYOUNG commented on src/main/java/subway/dto/response/PathAndFeeResponse.java
> +public class PathAndFeeResponse {
DTO 응답에 대해서 여기서 이야기해보면 좋을 것 같아요.
재사용과 별도로 만드는 것의 장단점에 대해서는 이미 잘 인지하고 계신 것 같아요. 
그리고 하디는 관리해야하는 DTO의 수가 많아지는 것이 조금 더 큰 단점으로 다가오시는 것 같습니다.
의견 차이이기에 저의 의견도 참고만 해주세요.
저는 완전히 동일한 응답을 제공하더라도 각 `API`별로 별도의 응답을 만드는 편입니다. 저는 이 방식을 선호하는 방법은 아래와 같습니다.
1. 기본적으로 동일한 사이클로 `API`응답이 변화하는 경우는 많지 않은 것 같습니다. 추후에 완벽하게 동일하게 동작한다는걸 확인하고 이를 합쳐도 늦지 않을 것 같습니다.
2. 해당 응답을 여러개의 응답에서 사용하고 있다는 것을 인지해야하는데, 이를 놓치기 쉽습니다.
3. 응답에 하나를 추가 또는 삭제하는데 사용하고 있는 여러 API를 보아야합니다. 이 자체가 이미 SRP를 위배하는 것 같고 SRP를 위배해서 별로다 라기 보단, 작은 작업을 하더라도 많은 것을 고려해야한다 라는 점이 저는 치명적이라고 생각했습니다.

2023-05-18 04:01 UTC, KIMSIYOUNG commented on src/main/java/subway/application/PathService.java
> +public class PathService {
서비스가 나오는 기준은 어떻게 되나요? `PathService`가 별도로 생긴 이유가 무엇일까요?

2023-05-18 04:01 UTC, KIMSIYOUNG commented on src/main/java/subway/application/PathService.java
> +    private int calculateFee(List<Section> sections) {
요정도 로직은 메소드를 분리하지 않는게 더 가독에 도움이 되는 것 같습니다

2023-05-18 04:01 UTC, KIMSIYOUNG commented on src/main/java/subway/ui/PathController.java
> +@RequestMapping("/paths")
서비스와 마찬가지로 `Path`라는 단독 `Controller` 를 만들어주신 이유는 무엇일까요?

2023-05-18 04:01 UTC, KIMSIYOUNG commented on src/main/java/subway/dto/PathAndFee.java
> +public class PathAndFee {
서비스와 컨트롤러의 DTO를 다르게 사용하시는 이유가 무엇일까요?

2023-05-18 04:01 UTC, KIMSIYOUNG commented on src/main/java/subway/domain/SectionEdge.java
> +public class SectionEdge extends DefaultWeightedEdge {
상속을 사용해서 잘 구현해주셨네요🙂파악하면서 어려움은 없으셨나요?
저는 예전에 구현할 때 상속으로 하면 되겠다라고 생각했을 때 거의 유레카 였거든요ㅋㅋㅋ..

2023-05-18 04:01 UTC, KIMSIYOUNG commented on src/main/java/subway/domain/Path.java
> +import org.jgrapht.GraphPath;
도메인에서 인프라에 의존하는 것은 어떤 위험성을 가질 수 있을까요?

2023-05-18 04:01 UTC, KIMSIYOUNG commented on src/main/java/subway/application/PathService.java
> +    public PathAndFee findShortestPathAndFee(Long sourceStationId, Long targetStationId) {
로직이 깔끔하게 잘 보이네요🙂

요금계산과 경로 두가지를 하나의 서비스에서 제공하도록 설계해주신 이유는 무엇일까요?

2023-05-18 04:01 UTC, KIMSIYOUNG commented on src/main/java/subway/domain/SectionChange.java
>  public class SectionChange {
깔끔하게 잘 구현해주신 것 같습니다.
현재는 단발성으로 이루어지지만 SectionChange를 리스트로 히스토리를 갖거나 하는 방법도 있을 것 같네요🙂
현재 필요하진 않은 것 같고 잘 구현해주신 것 같아요.

어느정도 DB 친화적인 느낌도 있지만, 섹션의 변화에 대해서 추적하는 요구사항을 만족한다라고 봐도 무방할 것 같아요.

2023-05-18 04:21 UTC, jundonghyuk commented on src/main/java/subway/application/PathService.java
> +    public PathAndFee findShortestPathAndFee(Long sourceStationId, Long targetStationId) {
처음엔 경로를 구하는 것과 요금 계산을 따로 분리하려고 하였는데요,
생각을 해보니 경로 없이는 요금계산이 불가능하다는 결론이 나와 같은 서비스에 두었습니다.

요금계산을 안하고 경로만 구하여 반환하는 메서드도 만들까 싶었지만 (어떤 요청에서는 응답값으로 경로만 원하고 요금을 받고 싶지 않을 수도 있기에), 그러한 요구사항이 아직까지는 없어 메서드로 따로 두지는 않았습니다.
만약 메서드로 따로 둔다면 `findShortestPath`라고 메서드명을 지을 것 같습니다!

요약하자면, 경로 없이는 요금계산이 불가능하여 같이 두었고 요금계산없이 경로를 구하는 건 가능하기에 경로만 구하고 반환하는 메서드를 따로 만들어도 된다고 생각합니다.

2023-05-18 04:26 UTC, jundonghyuk commented on src/main/java/subway/application/PathService.java
> +    public PathAndFee findShortestPathAndFee(Long sourceStationId, Long targetStationId) {
아니면, `PathController`에서 `PathService`에게 `sourceStationId`, `targetStationId`를 넘겨주어 최단경로를 받는다.
`PathController`에서 방금 받은 최단경로를 `FeeService`에게 넘겨주어 요금 계산을 시킨 뒤 요금을 반환받는다.
결과적으로 `PathController`에서는 `PathService`로부터 경로를, `FeeService`로부터는 요금을 전달받아 응답값을 구성하여 리턴한다.

이런식으로도 만들어 볼 수 있을 것 같은데요.
저는 사실 굳이(?)라는 생각을 하긴 했습니다.

애초에 요금을 계산하는 것은 경로를 필요로하기 때문에  같은 서비스에 두는것이 응집도가 높을 것이라고 생각하여 이렇게 설계하였습니다.

혹시 카일은 어떻게 생각하시는지 의견을 듣고싶네요!

2023-05-18 04:35 UTC, jundonghyuk commented on src/main/java/subway/domain/Path.java
> +import org.jgrapht.GraphPath;
이것도 고민을 해본 내용이었습니다!!

외부 라이브러리에 저희 도메인이 의존한다는게 영 반갑지 않았는데요!

이런 외부인프라에 의존하면 그것이 변했을시 저희의 도메인도 변해야된다는게 단점이라고 생각합니다. 
그러면 이런 인프라에 의존을 아예 하면 안되나?라고 생각을 해봤을 때, 결론에 미치는 요인들이 있다고 생각하는데요.

1. 이 외부라이브러리가 현재에도 유지, 보수가 계속 잘되고 있나?
2. 이 외부라이브러리가 변경가능성이 있나? 
- (예를 들어, `WeightedMultigraph`의 상속구조 라던지, parameter 개수, 메서드 등 여러가지 요인들)
3. 많은 사람들이 사용하고있나?
- 사실 여러 사용자로부터 꾸준히 사용되어 인정받는 것도 중요하다고 생각하는데요.. 저의 생각입니다...

이 조건들을 봤을 때, `jgrapht`의 `WeightedMultigraph`에 의존하는 것에 큰 위험상황이 존재할까?라는 생각을 해봤습니다.

하지만 다른 graph를 쓸 수도 있으니 생성자로 상위 타입을 받는 방식을 한 번 적용해보겠습니다!

2023-05-18 04:36 UTC, jundonghyuk commented on src/main/java/subway/application/PathService.java
> +    private int calculateFee(List<Section> sections) {
1. 경로를 구한다.
2. 요금을 구한다.

의 부분을 분리하고 싶은 마음이 컸나봅니다. 그런데 한 줄 짜리 메서드라 같이 껴놔도 될 것 같네요...ㅎㅎㅎ

2023-05-18 08:34 UTC, jundonghyuk commented on src/main/java/subway/dto/response/PathAndFeeResponse.java
> +public class PathAndFeeResponse {
그러네요 해당 디티오가 여러 응답에서 쓰일 수 있다라는 사실을 인지하기 쉽지 않겠군요
이러한 점이 코스트가 더 높을 수 있겠네요!

2023-05-19 01:51 UTC, jundonghyuk commented on src/main/java/subway/dto/PathAndFee.java
> +public class PathAndFee {
서비스가 반환하는 반환 타입이 항상 클라이언트에게 주는 응답형식과 다를 수 있다고 생각했습니다.
언급해주신 `PathAndFee`는 응답 형식과 같지만, 응답 포맷이 달라지더라도 서비스는 일관되게 자신이 제공하는 정보를 주어야한다고 
생각해 한 번 적용을 해보았습니다.
너무 과한 처사일까요 ?

2023-05-19 01:52 UTC, jundonghyuk commented on src/main/java/subway/domain/SectionEdge.java
> +public class SectionEdge extends DefaultWeightedEdge {
저도 항상 요금부과가 거리만으로 진행되진 않을 것이라고 생각해 `Edge`에 포함되는 정보를 거리로만 주기가 싫었습니다.
그래서 `Section`에 대한 정보를 다 주고싶었는데 상속을 활용하니 해결이 되더라고요!

생각해내고 신나긴했습니다...ㅋㅋ

2023-05-19 02:34 UTC, jundonghyuk commented on src/main/java/subway/domain/Path.java
> +import org.jgrapht.GraphPath;
카일 생각을 좀 해봤습니다.

`Graph` 라는 것이 자바에는 구현이 되어있지 않더군요.
외부라이브러리 종속적이지 않게 받아보려고 시도를 해봤는데 맞는 방향인지 의구심이 들긴합니다.

인터페이스로 받는 것으로 바꾸어 보았는데, 어떻게 생각하시는지 궁금합니다!

2023-05-19 02:39 UTC, jundonghyuk commented on src/main/java/subway/application/PathService.java
> +public class PathService {
이 부분이 참 고민인데요.. 
`경로와 요금을 구할 수 있다` 라는 요구사항을 분석하였을 때
필요한 의존성을 생각해 볼 수 있습니다.
`StationDao -> 경로를 찾으려면 역들이 필요함.`
`feePolicy -> 요금을 구하는 정책이 바뀔 수 있다` 

이런식으로 생각해 보았을 때, 기존의 존재하던 서비스에서 이러한 기능을 제공못할 때 분리합니다.
그리고 또 주관적으로 새로운 도메인이다. 라고 생각이 들었을 때 분리하는 것 같습니다.
카일의 의견도 듣고 싶습니다..!

2023-05-19 02:44 UTC, jundonghyuk commented on src/main/java/subway/dto/response/PathAndFeeResponse.java
> +public class PathAndFeeResponse {
카일 ! 고민하다가 질문이 있어서 여쭤봅니다.
만약, 어떤 API의 응답값으로는 `Stations`만, 어떤 API 응답값으로는 `요금 + Stations` 등등... 

물론 모든 응답값에는 위에서 말했던것과 다르게 `Stations` 내 모든 필드를 사용합니다. 다른 정보와 붙여서 응답할 수 있는 것이죠.

이러한 상황에서도 분리하신다고 하셨는데, 네이밍이 참어렵습니다.
같은 정보를 가지고 있는데, 카일만의 네이밍을 다르게 가져가는 팁같은게 있을까요 ?

2023-05-19 02:47 UTC, jundonghyuk commented on src/main/java/subway/ui/PathController.java
> +@RequestMapping("/paths")
저는 `URI`에 맞춰서 컨트롤러를 분리하는 것 같습니다.
`URI`만 봐도 어떠한 행동을 할지 예측할 수 있어야된다고 생각하는데요.
이러한 측면에서 `경로와 요금을 구한다.`라는 행동은
기존에 존재하던 `URI` 즉, `/stations/~~ or /lines/~~`로는 제대로 표현하지 못하는 것 같아 새로 만들었습니다.

`URI`에 따라 분리하다보니 컨트롤러가 많이 생성되는 문제(?)도 생기는 것 같습니다.
컨트롤러를 나누는 기준은 주관적인 측면도 영향을 많이 받는 것같고.. 서비스의 규모(?)에 따라서도 달라질 수도 있을 것 같고 정답은 없다고 생각하는데요.

카일의은 어떻게 생각하시나요? 또 카일의 컨트롤러 분리 기준을 듣고 싶습니다.

2023-05-19 02:52 UTC, jundonghyuk commented
안녕하세요 카일 질문에 대한 답변과 답변을 생각해보면서 고민했던 내용들을 코멘트 밑에 달아 두었습니다..!

오늘도 잘 부탁드립니다:) 좋은 하루 되세요 !

2023-05-20 14:54 UTC, KIMSIYOUNG commented on src/main/java/subway/dto/response/PathAndFeeResponse.java
> +public class PathAndFeeResponse {
저는 네이밍은 모두 동일하게 가져가고 있습니다. 대신 내부클래스로 선언하여 어떤 응답에 종속되었다는걸 보여주는 편이에요.

2023-05-20 14:59 UTC, KIMSIYOUNG commented on src/main/java/subway/application/PathService.java
> +public class PathService {
말씀하신대로 새로운 기능을 제공하기에 분리하는 것도 좋은 방법이라고 생각합니다. 저도 비슷한 이유로 분리했을 것 같아요.
현재 서비스는 여러가지 도메인과 인프라를 조합하여 하나의 `기능`을 완성시켜주는 곳인 것 같아요. 그렇기에 새로운 `기능` 요구사항이 있다면 말씀해주신대로 분리해주는 것이 괜찮을 것 같아요.

2023-05-20 15:02 UTC, KIMSIYOUNG commented on src/main/java/subway/ui/PathController.java
> +@RequestMapping("/paths")
맞습니다. 모호한 부분은 라인과 스테이션은 `자원에 대한 접근`을 기준으로 URL을 분리하는데 `Path`는 행위로도 간주할 수 있기에 어색할 수도 있는 것 같습니다.
다만 `Path`라는 것도 행위로 간주하지 않고 `자원`으로도 간주될 수 있기에 한편으로는 자연스러운 것 같아요. 

저 또한 상황에 따라 다르게 설계하는 것 같습니다. 뷰와 엮여있는 곳이라면 뷰에 적합한 형태로 네이밍을 하고 (/v1/mypage, /v1/home) 서버끼리 소통한다면 자원을 기준으로 주로 사용하는 것 같아요.

2023-05-20 15:02 UTC, KIMSIYOUNG commented on src/main/java/subway/dto/PathAndFee.java
> +public class PathAndFee {
이론적으로는 레이어간의 소통을 위해 DTO를 사용하기에 말씀해주신 것처럼 분리하는게 더 좋은 것 같습니다. 다만 현재 어플리케이션에서는 불필요하다고 느껴지긴 하네요ㅎㅎ

2023-05-20 15:06 UTC, KIMSIYOUNG commented on src/main/java/subway/domain/Path.java
> +import org.jgrapht.GraphPath;
좋은 고민을 해주신 것 같습니다. 다만 고민의 관점이 조금 엇나간 것 같습니다.

도메인에서 인프라를 참조할 때 직접 참조하지않고 인터페이스를 통해 의존을 역전시키는 이유는 인터페이스의 구현체가 어떠한지에 대해 고려하지 않기 위함입니다. 
즉 인터페이스의 구현체가 변경되어도 도메인은 변경되지 않기 위함입니다. (도메인과 인프라상의 코드결합도를 분리시키는 것)

하디가 고민해주신 이 라이브러리를 사용하는게 괜찮은가에 대한 고민점은 그 구현체로 무엇을 사용할지/사용해도 괜찮은지에 대한 고민인 것 같아요.

2023-05-20 15:08 UTC, KIMSIYOUNG commented on src/main/java/subway/application/PathService.java
> +    public PathAndFee findShortestPathAndFee(Long sourceStationId, Long targetStationId) {
말씀하신 것과 동일하게 생각하고 있습니다. 굳이 분리할 필요는 없는 것 같아요. 결국 `경로`라는 것을 통해서 알 수 있는 추가적인 정보가 `요금`인 것이고 `경로`를 알았을 때 추가로 알게되는 정보도 결국 `경로조회`에 속하는 것 같아요.

대부분 질문드린 것은 반대의 케이스도 고민은 해보시면 좋을 것 같아 드린 질문들입니다.

2023-05-20 15:09 UTC, KIMSIYOUNG commented on src/main/java/subway/application/PathService.java
> +    public PathAndFee findShortestPathAndFee(Long sourceStationId, Long targetStationId) {
다만 `Fee`라는 것을 네이밍으로 드러내진 않아도 될 것 같네요. `경로`라는 개념에 포함되는 하위 데이터라고 보여져요. (회원조회를 getMemberAndNameAndEmail이라고 표현하지 않는 것 처럼요)

2023-05-20 15:15 UTC, KIMSIYOUNG approved these changes
안녕하세요 하디
리뷰 반영 잘 해주셨네요.
몇가지 추가 코멘트와 답글 남겼는데 확인 부탁드립니다.
미션은 이미 잘 구현해주셔서 머지해도 될 것 같아요.
추가로 이야기하고 싶은 내용이 있으시다면 디엠 부탁드립니다! 
고생하셨습니다.

2023-05-20 15:15 UTC, KIMSIYOUNG commented on src/main/java/subway/application/PathService.java
> +                .map(SectionEdge::getSection)
잘 구현해주셨는데요. 도메인에서 반환하는 값이 결국은 특정 라이브러리를 상속한 객체라면 도메인은 인프라에 의존하고 있다라고 볼 수 있을 것 같아요.

2023-05-20 15:15 UTC, KIMSIYOUNG commented on src/main/java/subway/domain/path/JgraphtPath.java
> +public class JgraphtPath implements Path {
해당 클래스가 도메인 패키지에 있는게 적절한지도 고민해보면 좋을 것 같아요.

2023-05-20 15:15 UTC, KIMSIYOUNG commented on src/test/java/subway/application/PathServiceTest.java
> +    void getShortestPathAndFee() {
테스트 케이스가 조금 더 다양하면 좋을 것 같네요🙂

2023-05-20 15:15 UTC, merged