[2단계 - 경로 조회 기능] 여우(조승현) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #114
Opened 2023-05-16 15:17 UTC by BackFoxx

제가 만든 기존의 코드에 2단계에서 추가된 요구사항을 하나하나 덧붙이는 방식으로 구현하면서
1단계에서 만든 제 프로젝트가 무언가 많이 잘못되어 있음을 깨달아야 했어요.
줏대없고 복잡한 제 프로젝트의 구조를 보며
마치 제 삶의 단면을 보는 듯한 기분이 들었습니다.

하지만 코드는 무언가 잘못되었음을 느꼈을 때 
그 이유를 파악하고, 
고칠 수 있고, 
고치고 나면 반드시 정상 궤도로 돌아온다는 점에서 
사람과는 다른 것 같습니다.

어쩌면 그래서 제가 우테코를 좋아하고 프로그래밍을 좋아하나 봅니다.

---

제가 작성한 코드에서 느꼈던 문제점을 곰곰히 생각해본 후 정리해 보았습니다.
함께 이야기하면서 고쳐나갈 수 있으면 좋겠습니다 !

### LineService와 SectionService의 책임을 구분하는 기준이 모호하다
제 프로젝트에 있는 도메인 객체 중 '노선'을 표현하는 Line과, '역과 역 사이', 즉 '구간'을 표현하는 Section이 있습니다.

1단계에서는 노선에 대한 비즈니스 로직, 구간에 대한 비즈니스 로직을 구분하고자 하는 의도로
LineService, SectionService 이렇게 두 서비스 클래스를 운영하고 있었습니다.
그런데 2단계에서, '떨어져 있는 두 역의 최단 경로를 조회하는 기능' 을 서비스 레이어에 구현하려고 하니
"이 기능은 노선의 책임인가, 구간의 책임인가?" 라는 고민이 생겼습니다. 

이 기능을 구현하기 위해서는 LineDao와 SectionDao 객체를 둘 다 사용하고
'노선' 객체와 '구간' 객체를 둘 다 사용하기 때문에
'LineService나 SectionService 둘 중 어디에 구현해야 하지' 를 결정하지 못하게 된거에요.

제 생각에는 '구간' 이라는 개념은 '노선' 의 하위 개념이기 때문에,
즉 Line 도메인의 하위 도메인으로써 Section 도메인을 포함하고 있는 개념적 구조에서
서비스 코드는 마치 서로 다른 도메인인 것처럼 
LineService와 SectionService를 불필요하게 나누어 두었기 때문에 이 문제가 생긴 것이 아닌가 싶었습니다.

토론스터디에서 이 고민을 공유하고 함께 이야기했는데, 대략 두 가지 해결방법이 제시됐습니다.
1. LineService와 SectionService는 나누어 둔다. 대신 LineService에서 SectionService를 상태로 가지고 사용한다.
2. Line과 Section이 서로 포함관계라면 SectionService가 따로 있을 필요가 없다. LineService에서 Section과 관련된 비즈니스 로직까지 전부 관리한다.
이 두 방법 중 어떤 것이 정답인지는 결정하지 못했습니다.
일단은 PR 제출을 위해 1번 방법으로 구현하긴 했지만 제 선택에 확신이 없는 상황입니다.
제이온께서는 위 고민에 대해 어떤 입장이신지, 1번과 2번 중 어떤 선택이 낫다고 생각하지는 지 궁금합니다.

---

### 서비스에서 컨트롤러로 DTO를 응답하는 것이 컨트롤러에 대한 역류참조인가?
컨트롤러에서 서비스 레이어를 의존할 수는 있지만 그 반대가 되어서는 안된다고 합니다.

그리고 서비스에서 비즈니스 작업을 수행한 후 도메인 객체를 응답하는 구조로 코드를 작성하면
컨트롤러에서 도메인 객체를 조작할 위험이 있으므로 도메인 객체 대신 DTO를 응답하는 것이 안전하다고 합니다.
그리고 서비스에서 응답하는 DTO는 보통 컨트롤러가 원하는 정보를 담고 있습니다.

이 두 문장을 보았을 때 한 가지 고민이 생겼습니다.

1. 컨트롤러에서 A 서비스 메서드를 호출해서 '최단 거리', '최단 경로' 를 응답받고 싶어한다. 그래서 A 서비스 메서드의 응답값인 ResponseDTO에는 '최단 거리', '최단 경로' 정보가 들어있다.
2. 어느날 요구사항이 바뀌어, 컨트롤러에서 A 서비스를 호출한 후 '지하철 요금'까지 같이 받고싶어 한다.
3. 그래서 A 서비스 의 ResponseDTO의 구조를 바꾸어 '지하철 요금' 정보도 담을 수 있게 한다. A 서비스 메서드의 구현부도 바꾸어 '지하철 요금'을 DTO에 담는 코드를 추가한다.

위 상황에서 컨트롤러가 요구하는 정보의 내용이 변경되면 서비스 레이어의 코드도 따라 바뀌는 현상이 발생합니다.
'이것은 서비스가 컨트롤러를 직접 import해 사용하는 것은 아니지만
개념적으로 컨트롤러의 내용에 의존적인 형태가 아닌가.
차라리 도메인 객체를 그대로 응답하게 구현했다면
컨트롤러에서 필요로 하는 정보를 도메인 객체에서 직접 뽑아 사용할 수 있을텐데' 라는 고민이 생겼고,

서비스 레이어에서 도메인 객체를 응답할 것인가, DTO를 응답할 것인가를 제대로 정하지 못해
결국 둘 다 쓰고 있는 줏대없는 코드가 완성되었습니다.

다른 크루들은 다들 일찍이 이런 고민을 하고 자신만의 기준을 세운 것으로 보이는데
저는 이제야 이런 고민을 하고 있네요 🥲 제이온과 함께 이야기하며 저만의 기준을 세우고 싶어요.

---

### 여러 작업을 하는 API 하나 vs 단일 작업을 하는 API 여러 개
컨트롤러에서 '최단 경로', '최단 거리', '요금' 정보를 필요로 하고, 이 정보를 얻기 위해 LineService의 API를 호출하려 합니다.
이 때 LineService에서 위 정보를 가져오는 두 가지 전략이 있습니다.

1. findShortestInformation() 메서드를 호출하면, 이 메서드 안에서 '경로 찾기', '거리 찾기', '요금 계산하기'를 다 수행합니다. 그 후 이 세 정보가 들어있는 ShortestInformation을 응답합니다. 
2. findShortestPath()를 호출해 '최단 경로' 를 조회하고, findShortestDistance()를 호출해 '최단 거리'를 조회하고, findFare()를 호출해 '요금'을 조회합니다. 

한 메서드는 하나의 책임을 가진다는 단일 책임 원칙을 지키려면 2번을 선택하는 것이 당연해 보입니다.
그럼에도 저는 1번을 선택할 수밖에 없었습니다. 세 작업 모두 '그래프'를 필요로 했기 때문입니다.
1. 최단 경로 조회 방법 : 모든 구간 정보를 DB에서 꺼낸 후 ->  그래프를 만들고 -> 경로를 조회합니다.
2. 최단 거리 조회 방법 : 모든 구간 정보를 DB에서 꺼낸 후 ->  그래프를 만들고 -> 거리를 조회합니다. 
3. 요금 조회 방법 : 모든 구간 정보를 DB에서 꺼낸 후 ->  그래프를 만들고 -> 거리를 조회하고 -> 거리에 따른 요금을 계산합니다.

세 작업 모두 '모든 구간 정보를 DB에서 꺼낸 후 ->  그래프를 만들고' 라는 공통 작업이 필요한데,
작업별로 API를 3개로 나누어두면 위 작업을 중복 구현하게 됩니다.
그리고 컨트롤러에서 위 API를 차례대로 호출하여 경로, 거리, 요금을 조회하는 경우
같은 작업을 3번 반복하는 형태가 되고, 성능 저하가 생길 수 있겠다는 고민이 생겼습니다.

토론 스터디에서 위 내용을 또 하소연했더니
'그럼에도 API를 나누는 게 낫다. 세 API를 한 번에 사용한다는 보장을 항상 할 수 없기 때문이다.
최단 경로를 조회하고, 구간을 추가하고 다시 요금을 조회하는 경우도 있을 수 있지 않느냐. 
그 땐 그래프 내용이 바뀌지 않느냐' 라는 피드백을 받았습니다. 일리있는 이야기라고 생각했습니다.

특별히 다른 정보를 얻지 않는다면 스터디 동료의 말대로 API를 나누는 형태로 리팩토링을 할 것 같습니다.
리팩토링 전에, 제이온의 의견은 어떤 지 듣고 싶었습니다. :)

---

한 미션을 하면서 이렇게 많은 고민을 해본 게 처음이고
PR 날릴 때 질문을 해본 게 처음이라 내용이 많이 두서없습니다 🥲
질문 내용이나 코드 내용 중 이해되지 않는 점이 있다면 알려주세요. 이번 주도 감사합니다 :)

2023-05-18 05:30 UTC, pjy1368 requested changes
안녕하세요 여우!
1단계 미션에서 피드백이 많았는데, 해당 내용과 2단계 요구 사항을 잘 반영해주셨습니다 👍
서비스에서 도메인으로 넘겨주면 좋을 로직들이 보여서 이 부분을 중심으로 다시 수정해보시면 좋을 것 같습니다.
PR 본문에 올려주신 질문은 여기서 답변드릴게요~

Q. LineService와 SectionService의 책임을 구분하는 기준이 모호하다
상황에 따라 다를 것 같아요. Line이 Section을 관리하더라도 하나의 서비스의 코드가 많이 길어지면 SectionService로 분리하고 그 Service는 DTO 반환이 아닌 LineService의 하위 성격으로 가져가도 괜찮습니다.

Q. 서비스에서 컨트롤러로 DTO를 응답하는 것이 컨트롤러에 대한 역류참조인가?
이 부분도 정답은 없습니다.
서비스에서 컨트롤러로 DTO를 응답하면 말씀주신대로 컨트롤러의 DTO 스펙이 변경되면 서비스도 어느정도 영향을 받을 수 있습니다. 하지만 서비스에서 도메인을 그대로 컨트롤러에 노출하면 컨트롤러에서 도메인을 조작할 수 있다는 위험성이 있습니다.
만약 서비스가 컨트롤러에 영향받는 것이 싫다면, 서비스 쪽에서는 범용적으로 쓰일 만한 DTO(도메인이 들고 있는 필드를 상당수 가지고 있음)를 정의하고 컨트롤러에서 다시 그 범용 DTO를 API 특성에 맞게 Response로 다시 매핑하는 방법이 있습니다. 하지만 이 방법은 복잡도가 올라가고 매핑 코드가 추가로 생긴다는 단점이 있습니다.
한 번 고민해 보시고 취향에 맞는 방법을 선택해 보세요!

Q. 여러 작업을 하는 API 하나 vs 단일 작업을 하는 API 여러 개
API는 사용자의 요구 사항을 만족하면 됩니다. 기본적으로는 단일 작업 API 여러 개를 두는 편이지만, 여러 작업을 사용자가 매우 빈번히 사용한다면 성능 상의 이유로 여러 작업을 하는 API 하나를 둘 수도 있습니다.
하나의 작업에 API 하나를 할당하는 이유는, 현재는 단순해 보이는 하나의 API가 시간이 지날수록 복잡해질 수 있기 때문이죠~

2023-05-18 05:30 UTC, pjy1368 commented on README.md
> +| 노선 삭제하기           | DELETE | /lines/{id}         |                      | 주어진 ID에 해당하는 노선 정보를 삭제합니다.                                                                              |
시간이 남으면 API 문서 제작을 위해 Swagger 설정을 해 보면 좋겠네요 ㅎㅎ

2023-05-18 05:30 UTC, pjy1368 commented on src/main/java/subway/ui/exceptionhandler/CommonControllerAdvice.java
>      }
커스텀 예외를 잘 작성해주셨네요~
예외 전략은 정해져있는 것은 없지만, 우리는 Rest Api를 사용하고 있으니 RuntimeException을 상속받는 HttpException 클래스를 정의하고, HttpException을 상속받는 BadRequestException(401번), NotFoundException(404번) 등의 클래스를 정의하고, 그 아래에 다시 실질적으로 도메인에서 발생하는 각종 예외(StationNotConnectedException)을 정의해보면 어떨까요?
그리고 데이터베이스 쪽에서 발생한 예외를 만약 따로 처리하고 싶다고하면 RuntimeException을 상속받는 DatabaseException을 정의하고, 그 아래에 자유롭게 작성하는 방법도 있습니다~

2023-05-18 05:30 UTC, pjy1368 commented on src/main/java/subway/application/exception/ExceptionMessages.java
> +}
만약 프로그램이 매우 복잡해져서 이 안에 온갖 예외 메시지가 합쳐진다면 어떻게 될까요?

2023-05-18 05:30 UTC, pjy1368 commented on src/main/java/subway/application/SectionService.java
> +                : new Section(line, nextStation, previousStation, distance);
가능한 삼항 연산자는 if문으로 바꿔주세요~

2023-05-18 05:30 UTC, pjy1368 commented on src/main/java/subway/application/strategy/sectioninsertion/SectionInsertionStrategy.java
> +}
전략 패턴을 잘 구현해 주셨네요 👍

2023-05-18 05:30 UTC, pjy1368 commented on src/main/java/subway/application/strategy/sectioninsertion/UpDirectionSectionInsertionStrategy.java
> +@Order(1)
빈의 우선 순위를 정하신 이유가 따로 있을까요?

2023-05-18 05:30 UTC, pjy1368 commented on src/main/java/subway/application/SectionService.java
>          }
변수명을 좀 더 의미있는 이름으로 바꿔주세요~

2023-05-18 05:30 UTC, pjy1368 commented on src/main/java/subway/application/SectionService.java
> +            }
```java
if (nextStation.isPresent()) {
    stations.add(nextStation.get().getPreviousStation());
    station = nextStation.get().getNextStation();
    continue;
}
station = null;
```
이렇게 바꿔보면 어떨까요?

2023-05-18 05:30 UTC, pjy1368 commented on src/main/java/subway/application/SectionService.java
> +            Station currentStation = station;
전반적으로 기존 코드보다 이해하기 훨씬 쉬워졌네요!

2023-05-18 05:30 UTC, pjy1368 commented on src/main/java/subway/application/LineService.java
> +    public static final int SURCHARGE = 100;
도메인에 enum이나 전략 패턴 형태로 위임하면 어떨까요?

2023-05-18 05:30 UTC, pjy1368 commented on src/main/java/subway/application/LineService.java
> +    }
<img width="959" alt="image" src="https://github.com/woowacourse/jwp-subway-path/assets/56083021/c3b5923a-a32f-4298-bfc5-e18ea51ee612">
현재 제 컴퓨터에서는 ShortestPathResponse 클래스가 없다고 컴파일 에러가 발생하는데 푸쉬를 따로 안하셨나요?

2023-05-18 05:30 UTC, pjy1368 commented on src/main/java/subway/application/LineService.java
> +    }
graph 도메인으로 위임할 수 있는 로직 아닐까요??

2023-05-18 05:30 UTC, pjy1368 commented on src/main/java/subway/application/LineService.java
> +    }
별도의 계산기같은 객체에서 이 책임을 가져가면 좋겠습니다!

2023-05-18 05:30 UTC, pjy1368 requested changes
안녕하세요 여우!
1단계 미션에서 피드백이 많았는데, 해당 내용과 2단계 요구 사항을 잘 반영해주셨습니다 👍
서비스에서 도메인으로 넘겨주면 좋을 로직들이 보여서 이 부분을 중심으로 다시 수정해보시면 좋을 것 같습니다.
PR 본문에 올려주신 질문은 여기서 답변드릴게요~

Q. LineService와 SectionService의 책임을 구분하는 기준이 모호하다
상황에 따라 다를 것 같아요. Line이 Section을 관리하더라도 하나의 서비스의 코드가 많이 길어지면 SectionService로 분리하고 그 Service는 DTO 반환이 아닌 LineService의 하위 성격으로 가져가도 괜찮습니다.

Q. 서비스에서 컨트롤러로 DTO를 응답하는 것이 컨트롤러에 대한 역류참조인가?
이 부분도 정답은 없습니다.
서비스에서 컨트롤러로 DTO를 응답하면 말씀주신대로 컨트롤러의 DTO 스펙이 변경되면 서비스도 어느정도 영향을 받을 수 있습니다. 하지만 서비스에서 도메인을 그대로 컨트롤러에 노출하면 컨트롤러에서 도메인을 조작할 수 있다는 위험성이 있습니다.
만약 서비스가 컨트롤러에 영향받는 것이 싫다면, 서비스 쪽에서는 범용적으로 쓰일 만한 DTO(도메인이 들고 있는 필드를 상당수 가지고 있음)를 정의하고 컨트롤러에서 다시 그 범용 DTO를 API 특성에 맞게 Response로 다시 매핑하는 방법이 있습니다. 하지만 이 방법은 복잡도가 올라가고 매핑 코드가 추가로 생긴다는 단점이 있습니다.
한 번 고민해 보시고 취향에 맞는 방법을 선택해 보세요!

Q. 여러 작업을 하는 API 하나 vs 단일 작업을 하는 API 여러 개
API는 사용자의 요구 사항을 만족하면 됩니다. 기본적으로는 단일 작업 API 여러 개를 두는 편이지만, 여러 작업을 사용자가 매우 빈번히 사용한다면 성능 상의 이유로 여러 작업을 하는 API 하나를 둘 수도 있습니다.
하나의 작업에 API 하나를 할당하는 이유는, 현재는 단순해 보이는 하나의 API가 시간이 지날수록 복잡해질 수 있기 때문이죠~

2023-05-24 23:32 UTC, BackFoxx commented on src/main/java/subway/ui/exceptionhandler/CommonControllerAdvice.java
>      }
피드백 반영하였습니다! 도메인 객체의 의존성 분리와 관련해 궁금한 게 있었는데, 도메인 객체에서 발생하는 예외를 정의할 때, BadRequestException같은 http 프로토콜 개념에 의존하는 예외를 사용하는 것도 부적절한 예외 사용인가요? 서버와 통신하는 방법이 http에서 다른 프로토콜로 변경될 것을 고려해서 예외 설계를 해야 할지 고민했습니다!

2023-05-24 23:34 UTC, BackFoxx commented on src/main/java/subway/application/exception/ExceptionMessages.java
> +}
관리하기 불편할 것이라 생각합니다! 동일한 종류의 예외는 동일한 예외 메시지를 갖는 것이 좋겠다고 생각했습니다. 그래서 커스텀 예외 안에 예외 메시지를 상수로 정의하고 무조건 그 예외 메시지를 사용하도록 개선했더니 관리가 훨씬 수월했어요 :) 커스텀 예외의 중요성을 깨달았네요!

2023-05-24 23:34 UTC, BackFoxx commented on src/main/java/subway/application/SectionService.java
> +                : new Section(line, nextStation, previousStation, distance);
이걸 못 고쳤네요 ｡ﾟ(ﾟ´ω`ﾟ)ﾟ｡

2023-05-24 23:35 UTC, BackFoxx commented on src/main/java/subway/application/strategy/sectioninsertion/UpDirectionSectionInsertionStrategy.java
> +@Order(1)
전략들을 List로 받아와서 순서대로 실행하는데, 이 때 전략의 실행 순서가 중요했기 때문입니다!

2023-05-24 23:36 UTC, BackFoxx commented on src/main/java/subway/application/SectionService.java
>          }
요것도 못 고쳤네요 😭

2023-05-24 23:36 UTC, BackFoxx commented on src/main/java/subway/application/SectionService.java
> +            }
오!

2023-05-24 23:37 UTC, BackFoxx commented on src/main/java/subway/application/LineService.java
> +    public static final int SURCHARGE = 100;
이번 미션에서 전략패턴이 정말 다양한 곳에 유용하게 쓰였습니다 ;)

2023-05-24 23:37 UTC, BackFoxx commented on src/main/java/subway/application/LineService.java
> +    }
푸쉬했어요! 죄송합니다 ｡ﾟ(ﾟ´ω`ﾟ)ﾟ｡

2023-05-24 23:38 UTC, BackFoxx commented on src/main/java/subway/application/LineService.java
> +    }
경로를 조회하는 Navigation 이라는 도메인을 설계한 후에 해당 도메인으로 작업을 위임했습니다!

2023-05-24 23:38 UTC, BackFoxx commented on src/main/java/subway/application/LineService.java
> +    }
택시 미터기에서 이름을 따와, FareMeter라는 도메인을 설계하여 해당 도메인으로 작업을 위임했습니다!

2023-05-25 01:04 UTC, pjy1368 commented on src/main/java/subway/ui/exceptionhandler/CommonControllerAdvice.java
>      }
엄밀한 계층 분리를 통한 예외 전략을 가져가려면 계층 별로 exception을 따로 두고, presentation에서는 application의 각종 exception을 보고 알아서 400, 401, ... 등의 상태 코드로 변환하는 방법이 있습니다.
하지만 이번 미션에서는 예외 전략을 섬세하게 가져가는 것이 중요한 건 아니라고 판단하였고, 가장 구현하기 쉬우면서 예외 계층을 나누는 방식을 알려드린 것입니다 ㅎㅎ
지금 하신 것처럼 HttpException을 둘 수도 있고, 아니면 NetworkException이라는 계층을 하나 더 두고 그 아래에 HttpException, GrpcException(또 다른 프로토콜)을 두는 방법도 있습니다. 다만 이번에는 여우께서 가능한 계층을 적게 두는 방안을 사용해 보시면 좋겠습니다.

2023-05-25 01:07 UTC, pjy1368 commented on src/main/java/subway/application/strategy/sectioninsertion/UpDirectionSectionInsertionStrategy.java
> +@Order(1)
아하.. 순서가 필요하군요. 이 부분은 가능하다면 전략들을 임의의 순서로 List로 받아오더라도 애플리케이션 단에서 순서를 다시 맞춰주고 실행되면 더 좋을 것 같습니다~

2023-05-25 01:08 UTC, pjy1368 approved these changes
안녕하세요 여우!
DM으로 이야기 드린 것처럼 마지막 리뷰 요청 시간이 지났다보니 바로 머지를 하겠습니다.
이번 미션 고생 많으셨어요 앞으로도 화이팅입니다 :)

2023-05-25 01:08 UTC, pjy1368 approved these changes
안녕하세요 여우!
DM으로 이야기 드린 것처럼 마지막 리뷰 요청 시간이 지났다보니 바로 머지를 하겠습니다.
이번 미션 고생 많으셨어요 앞으로도 화이팅입니다 :)

2023-05-25 01:08 UTC, merged