[2단계 - 경로 조회 기능] 이리내(성채연) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #121
Opened 2023-05-17 07:49 UTC by hectick

2023-05-18 15:13 UTC, Be-poz commented
> 그동안은 도메인이 온전하게 모든 기능을 가지고 있어야 한다고 생각했었는데, 데이터베이스를 쓰는 환경이라면 데이터베이스에서 데이터를 불러오는 것과 도메인이 기능을 갖는 것을 적당히 저울질해서 더 가성비가 좋은(?) 방향의 코드를 짜면 되는 것일까요..?

일반적으로는 도메인에서 처리할 수 있으면 도메인에서 처리하는 것이 좋긴 하겠습니다만, Lines의 경우에는 단순 검증만 체크하기 위해 모든 데이터를 select 해오기에는 너무 비효율적이어서 코멘트 달았습니다. 가성비라고 한다면 가성비를 따지는 게 맞는 것 같긴 합니다...

2023-05-18 15:14 UTC, Be-poz requested changes
안녕하세요 이리내 2-3단계 미션제출하신 것 잘 확인했습니다.  
크게 리뷰할 것이 없긴한데 변경할만한 점을 일부 코멘트 남겼으니 확인해주시면 감사하겠습니다!

2023-05-18 15:14 UTC, Be-poz commented on src/main/java/subway/domain/Age.java
> +public enum Age {
AgeGroup이면 조금 더 좋을 것 같습니다! path api 호출 시에 내부 코드를 보기 전이어서 dto가 age이길레 나이를 입력했네요!

2023-05-18 15:14 UTC, Be-poz commented on src/main/java/subway/controller/PathController.java
> +            @RequestParam("age") String age
사용자가 본인이 어느 나이면 이 연령 그룹에 속하고 그것을 일일이 입력하는 것은 조금 불친절 한 것 같습니다.  
차라리 age를 실제 나이로 받고 로직상으로 연령대를 구해주는 것이 더 좋을 것 같습니다!

2023-05-18 15:14 UTC, Be-poz commented on src/main/resources/application.properties
> +spring.sql.init.mode=always
profile에 따라 인메모리 이용, 로컬 이용을 정할 수 있으면 좋을 것 같습니다.

2023-05-18 15:14 UTC, Be-poz commented on src/main/java/subway/controller/SectionController.java
> +    public ResponseEntity<LineResponse> createSection(@PathVariable final long lineId, @Valid @RequestBody final SectionCreationRequest request) {
👍

2023-05-18 15:14 UTC, Be-poz commented on src/main/java/subway/domain/Line.java
> +        this.extraFare = extraFare;
바로 3단계 적용 👍👍

2023-05-18 15:14 UTC, Be-poz commented on src/main/java/subway/domain/Line.java
> +    public String toString() {
디버깅용으로 사용하신걸까요?

2023-05-18 15:14 UTC, Be-poz commented on src/main/java/subway/domain/Line.java
> +    public Section getDownwardEndSection() {
public으로 변경하신 이유가 있으실까요?

2023-05-18 15:14 UTC, Be-poz commented on src/main/java/subway/dto/response/PathResponse.java
> +    private Integer fare;
Integer로 두게되신 이유를 듣고 싶습니다!

2023-05-19 09:05 UTC, hectick commented on src/main/java/subway/controller/PathController.java
> +            @RequestParam("age") String age
훨씬 직관적이고 좋네용!! 바로 반영하겠습니다

2023-05-21 12:22 UTC, hectick commented on src/main/java/subway/domain/Line.java
> +    public String toString() {
넵 디버깅할때 유용하게 사용하였습니다..!

2023-05-21 12:23 UTC, hectick commented on src/main/java/subway/domain/Line.java
> +    public Section getDownwardEndSection() {
처음에는 모든 구간을 가져오는 메서드만 존재했고,
양 끝 구간을 뺀 모든 구간이 필요해서 public으로 돌려서 양 끝 구간을 가져와 제외하려고 했는데요,
양 끝 구간을 뺀 모든 구간을 반환하는 메서드를 만들어서 필요가없게 되었네요 ...!!
수정하겠습니다

2023-05-21 12:26 UTC, hectick commented on src/main/java/subway/dto/response/PathResponse.java
> +    private Integer fare;
이유가 없었네요.. int로 충분한 상황이네요.. 수정하겠습니다

2023-05-22 08:51 UTC, hectick commented
기존에 리뷰주신 내용 반영하였습니다!
그외에는 기존에 readme에 있던 데이터 요청을 http 파일로 분리하고,
기존 인수테스트를 보강해서 더미데이터sql 파일 없이 동작할 수 있도록 하였습니다!

2023-05-22 14:02 UTC, Be-poz approved these changes
안녕하세요 이리내 피드백 반영해주신 것 잘 확인했습니다.  
이번 단계는 이만 머지하도록 하겠습니다. 수고하셨습니다! 😆

2023-05-22 14:02 UTC, Be-poz commented on http-request.http
> +### 노선 조회 요청
좋네요 👍

2023-05-22 14:02 UTC, Be-poz commented on src/main/java/subway/domain/AgeGroup.java
> +    }
👍

2023-05-22 14:02 UTC, Be-poz commented on src/test/java/subway/integration/SectionIntegrationTest.java
> +            long 용산역_아이디 = 역_생성하고_아이디_반환(용산역);
👍  최근에 인수테스트 강의가 있었나요? 리뷰 요청 주신 크루들이 인수테스트 도입을 많이들 하셔서 여쭤봅니다!

2023-05-22 14:02 UTC, Be-poz approved these changes
안녕하세요 이리내 피드백 반영해주신 것 잘 확인했습니다.  
이번 단계는 이만 머지하도록 하겠습니다. 수고하셨습니다! 😆

2023-05-22 14:03 UTC, Be-poz approved these changes
안녕하세요 이리내 피드백 반영해주신 것 잘 확인했습니다.  
이번 단계는 이만 머지하도록 하겠습니다. 수고하셨습니다! 😆

2023-05-22 14:03 UTC, merged