[2단계 - 경로 조회 기능] 김석호(에단) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #122
Opened 2023-05-17 08:05 UTC by cookienc

안녕하세요! 검프😄 2단계가 되면서 코드를 많이 바꼈습니다. 보시기 힘들것 같은데 미리 죄송합니다. 
[1단계에 질문 해주셨던 부분](https://github.com/woowacourse/jwp-subway-path/pull/7)은 답변 달아놨습니다 확인부탁드립니다!
2단계 진행하면서 고민했던 부분에대해서 아래에 댓글 남겨놓겠습니다.
리뷰 감사드립니다!!🙇‍♂️🙇🙇‍♀️

2023-05-17 08:19 UTC, cookienc commented on src/main/java/subway/application/SectionService.java
> +    private final SectionDeleter sectionDeleter;
### 서비스 필드에 많은 인스턴스 변수가 있는것 같습니다.
전략패턴을 사용해서 기능을 분리하고, DI를 하도록 변경해주었습니다. 이렇게 하다보니 어쩔 수 없이 인스턴스 변수들이 많이 생겼습니다. 이 때문에 레벨1 때 배운 객체지향 생활 체조에 어긋나 괴리감이 느껴집니다. 이 문제를 해결할 방법이 있나요?

2023-05-17 08:32 UTC, cookienc commented on src/main/java/subway/domain/section/Section.java
> +    private final Long id;
### 도메인에 persist layer의 값인 id가 있어도 되나요?
일단 제 입장은 가지고 있어도 괜찮다 입니다. 코드를 짜는 데 있어서 id와 함께 도메인 내부 값을 다룰 일이 많은데, 따로 있으면 코드를 짜기가 불편할 것 같습니다. 이상도 좋지만 현실도 중요하니까요!
제가 생각하기에 단점은 두 가지 정도가 있습니다.
먼저 DB에 종속되는 도메인이 된다는 점입니다. DB가 바뀌면 id도 바뀔 가능성이 있을 것 같습니다. 그러면 불필요하게 도메인을 수정해되겠죠. 그래서 다른 크루들이 이야기를 하는 것을 들었는데 UUID를 id로 설정하고 데이터베이스에 추가적으로 넣어준다는데, 저는 이 방식이  지금 고려할 단계는 아닌것 같아서 따로 반영은 하지 않았습니다.
두 번째는 save를 할 때 id에 Null 값이 들어간다는 단점이 있습니다. id가 식별자라는 의미인데 저장하기 전에는 Null로 채워져, null로 초기화하는 생성자가 필요합니다. Null값을 함부로 넣는다는 점에 있어서 단점으로 느껴집니다.
검프는 도메인에 db의 id가 있는것을 어떻게 생각하시나요? 프로그래머의 편의성을 위해서 타협해도 되는 부분일까요?

2023-05-17 08:39 UTC, cookienc commented on src/main/java/subway/domain/section/SingleLineSections.java
> +public class SingleLineSections {
### SingleLineSections의 책임이 많은 것 같습니다.
전략패턴을 사용하면서 Service의 코드의 수는 줄었습니다. 적절하게 책임을 전략이나 도메인이 가져갔기 때문인데요. 그렇게 하다보니 SingleLineSections의 책임이 많아진 것 같습니다.  지하철 노선이라는 도메인이 이 정도인데, 실무에서는 훨씬 많은 책임들이 객체들에게 위임이 되어있을것 같습니다. 만약 같이 일한다면 너무 많은 코드가 있기 때문에 원래 있던 코드가 있는줄 몰라서 새롭게 기능 구현하는 일도 자주 발생할 것 같습니다. 이러한 생각을 하다보니 ‘SingleLineSections이 많은 로직을 가지고 있는게 아닌가?’라는 생각이 듭니다. 이 정도면 무리없는 수준일까요?

2023-05-19 11:29 UTC, Livenow14 commented on src/main/java/subway/application/SectionService.java
> +    private final SectionDeleter sectionDeleter;
결국 어딘가에서는 여러 의존성을 가져야합니다. 

해당 부분에서 Service를 역할에 따라 나누면, controller에서 여러 서비스를 의존해야겟죠. 
이를 해소하기 위해 facade 패턴이라는게 존재하지만, 현재 해당 의존성을 해소하기 위한 방법으로는 별로라고 생각합니다. (결국 facade도 여러 service를 의존하게 되거든요) 

한번 역할에 따라 서비스를 분리해보시는건 어떨까요? 
ex) repository를 직접 의존하지 않고, Sevice를 추가

2023-05-19 11:54 UTC, Livenow14 commented on src/main/java/subway/domain/section/Section.java
> +    private final Long id;
해당 객체는 엔티티로 표현하는게 조금더 잘어울린다 생각하고, 그렇기에 persist layer 값인 id가 있어도 아무런 문제가 없다고 생각합니다. 

> DB에 종속되는 도메인

DB가 바뀐다고 속성값인 id가 바뀔 수 있나요? 꼭 db의 속성과 엔티티의 속성을 맞출 필요는 없다 생각하는데, id의 경우엔 거의 모든곳에서 식별자로 사용하고 있기에 변경에 대한 우려는 과한 걱정이라 생각됩니다. 

> save를 할 때 id에 Null 값이 들어간다는 단점

엔티티 식별자 생성 전략에 대해 잘 고민해주셨네요 :) 
식별자의 빠른생성과 늦은생성에 대한 고민인것 같아, 우선 전략에 대해 설명드리면.
- 사용자가 식별자 제공
- 애플리케이션이 식별자 제공 
- 영속성 메커니즘(DB)이 식별자 제공
- 다른 도메인이 식별자 제공
로 정리할 수 있을 것 같고, 크루들이 말씀해주신 부분은 애플리케이션이 식별자를 빠르게 제공하는 전략이겠네요 :) 

단순히 save전 null이 들어가는것이 단점으로 느껴지는게 이유라면, 저는 현재처럼 영속성 메커니즘이 늦게 식별자를 제공하는 것이 낫다 생각하고,
null로 인한 예외가 발생하면 크루들이 선택했던 방식도 나쁘지 않을 것 같아요 :)

2023-05-19 12:02 UTC, Livenow14 commented on src/main/java/subway/domain/section/SingleLineSections.java
> +public class SingleLineSections {
일급 컬렉션을 사용하는 의도가 무엇일까요? 
단순히 자신만의 타입으로 설정한 컬렉션을 만드는 의도라면 이정도의 책임은 적당하다 생각합니다. 

하지만 특정한 역할을 같는 객체로 설정한것이 의도라면, 조금 과하다 생각이 들어요. 
만약 특정한 역할을 갖는 객체라면, is~~ 와 같은 객체들이 정말 필요할까요? 

요리사에게 "요리해!" 하기 전에 항상 "너 요리사야? 맞으면 요리해" 라고 한다면 매번 자신의 상태를 체크해야하는 불편함이 있지 않을까요?

2023-05-19 12:36 UTC, Livenow14 requested changes
안녕하세요 에단! 구현잘해주셨어요. 
상세한 테스트들이 맣아 코드를 이해하는데 편했어요 :) 

간단한 리뷰 남겼으니 확인부탁드려요. 
질문에 대한 답변은 각각의 코멘트에 남겼습니다

수고하셨어요..!

2023-05-19 12:36 UTC, Livenow14 commented on src/main/java/subway/application/fare/DistanceRateFareCalculator.java
> +        if (DEFAULT_DISTANCE.isShorterThan(distance)) {
해당 부분들을 객체로 관리해볼 수 있을 것 같네요.

2023-05-19 12:36 UTC, Livenow14 commented on src/main/java/subway/application/fare/DistanceRateFareCalculator.java
> +}
이 부분들도요 :)

2023-05-19 12:36 UTC, Livenow14 commented on src/main/java/subway/application/fare/FareCalculator.java
> +
제공하는 메서드가 하나라면 @FunctionalInterface를 활용해봐도 좋을 것 같아요.

2023-05-19 12:36 UTC, Livenow14 commented on src/main/java/subway/application/path/JgraphtPathFinder.java
> +        final DijkstraShortestPath<Station, DefaultWeightedEdge> path = new DijkstraShortestPath<>(graph);
인스턴스화를 구현체를 직접하지 말고, 추상화를 사용해보는건 어떨까요?  ShortestPathAlgorithm
더 나아가서, 해당 부분은 의존을 받아도 좋겠네요.

2023-05-19 12:36 UTC, Livenow14 commented on src/main/java/subway/application/strategy/delete/DeleteBetweenStation.java
> +
list index 검색을 피하는 방법은 무엇이 있을까요?

2023-05-19 12:36 UTC, Livenow14 commented on src/main/java/subway/application/strategy/delete/DeleteUpTerminal.java
> +    private final SectionRepository sectionRepository;
전체 구현 객체가 해당 repository를 의존한다면 interface가 아닌 추상클래스를 사용해보는건 어떨까요?

2023-05-19 12:36 UTC, Livenow14 commented on src/main/java/subway/application/strategy/insert/InsertBetweenSection.java
> +    }
update와 insert가 분리되어야할 이유가 있을까요?

2023-05-19 12:36 UTC, Livenow14 commented on src/main/java/subway/application/LineService.java
로직이 정말 간단해졌네요 💯

2023-05-19 12:36 UTC, Livenow14 commented on src/main/java/subway/application/StationService.java
DB접근이 한번뿐이라 문제가 없었을 것 같지만,
@Transactional 을 기입해주시면 좋을 것 같아요.

2023-05-19 12:36 UTC, Livenow14 commented on src/test/java/subway/integration/IntegrationTest.java
>  }
Integration Test의 성격보단 E2E Test의 성격이 더 느껴지는데, 의도된걸까요?

2023-05-19 12:36 UTC, Livenow14 commented on src/test/java/subway/application/SectionServiceTest.java
> +    class 중간_지점에_구간을_추가한다 {
저는 Nested 테스트의 경우 ~~ 한다면 등으로 작성합니다 :)

2023-05-19 12:42 UTC, Livenow14 commented on src/main/java/subway/application/strategy/delete/DeleteStationStrategy.java
> +}
💯

2023-05-19 12:42 UTC, Livenow14 commented on src/main/java/subway/application/strategy/insert/InsertStationStrategy.java
> +}
💯

2023-05-22 07:25 UTC, cookienc commented on src/main/java/subway/application/SectionService.java
> +    private final SectionDeleter sectionDeleter;
찾아보니 CQRS 패턴이란게 존재해서 SubwayReadService를 만들어서 Read관련 메서드를 담당하게 변경했습니다.

2023-05-22 07:38 UTC, cookienc commented on src/main/java/subway/domain/section/SingleLineSections.java
> +public class SingleLineSections {
SingleLineSections에서 추가할 때 한번만 사용되는 메서드를 전략들이 가지고 있게 했습니다. 
변경한 이유는 다음과 같습니다.
1. SingleLineSections에 위치하면 정작 중요한 기능들이 눈에 잘 안보일것 같습니다.  
2. 추가 전략이 추가 할 수 있는지 없는지 확인하는 것도 자연스럽다고 생각했습니다.
도메인으로 계속 책임을 빼는 연습을 했는데, 이런 방법도 있었네요. 새로운 시각을 배워갑니다 감사합니다 :)

2023-05-22 07:38 UTC, cookienc commented on src/main/java/subway/application/fare/DistanceRateFareCalculator.java
> +        if (DEFAULT_DISTANCE.isShorterThan(distance)) {
전략패턴으로 분리해봤습니다. 요금 정책이 추가되면, OCP 원칙을 지키면서 추가할 수 있게 List로 주입받게 변경했습니다.

2023-05-22 07:38 UTC, cookienc commented on src/main/java/subway/application/fare/FareCalculator.java
> +
메서드가 하나이고 여기서 더 이상 추가되지 않을것 같아서 @FunctionalInterface를 붙였습니다.

2023-05-22 07:38 UTC, cookienc commented on src/main/java/subway/application/path/JgraphtPathFinder.java
> +        final DijkstraShortestPath<Station, DefaultWeightedEdge> path = new DijkstraShortestPath<>(graph);
처음에는 자주 바뀔것 같아서 빈을 등록해서 사용했었는데, ShortestPathAlgorithm과 Graph를 주입받는게 더 낫겠네요! 수정했습니다. 이렇게 바꾸면 해당 클래스가 DijkstraShortestPath인 줄 몰라도 되니 최단 거리 기준으로 찾는 의미만 남겨 클래스 명을 ShortestPathFinder로 바꾸겠습니다. PathFinder 인터페이스는 최소 환승과 같은 기능이 추가 될 수 있으니 남겨놓겠습니다.

2023-05-22 07:39 UTC, cookienc commented on src/main/java/subway/application/strategy/delete/DeleteBetweenStation.java
> +
stream api를 사용해 찾아오는 방식으로 변경했습니다.

2023-05-22 07:39 UTC, cookienc commented on src/main/java/subway/application/strategy/delete/DeleteUpTerminal.java
> +    private final SectionRepository sectionRepository;
삭제할 때는 SectionRepository가 항상 필요하니까 분리하는게 타탕할 것 같습니다! 수정했습니다.

2023-05-22 07:39 UTC, cookienc commented on src/main/java/subway/application/strategy/insert/InsertBetweenSection.java
> +    }
둘의 기능을 같이 하는 메서드를 추가했습니다.

2023-05-22 07:39 UTC, cookienc commented on src/main/java/subway/application/StationService.java
서비스가 변경됐을 때 나중에 붙여있는줄 알고 @Transactional을 안붙일수도 있으니 미리 붙이는게 나을것 같습니다! 수정했습니다.

2023-05-22 07:39 UTC, cookienc commented on src/test/java/subway/integration/IntegrationTest.java
>  }
E2E이긴 하지만 외부 API와 연동하는게 없어서 Integration Test 역할을 하는 것 같아서 안바꿨습니다.

2023-05-22 07:40 UTC, cookienc commented on src/test/java/subway/application/SectionServiceTest.java
> +    class 중간_지점에_구간을_추가한다 {
꿀팁 감사합니다.

2023-05-24 13:46 UTC, Livenow14 approved these changes
안녕하세요 에단 :) 구현잘해주셨어요. 

전반적으로 코드가 깔끔해진 것 같아. 이번 미션은 여기서 마무리해도 될 것 같아요..!

긴 시간동암 리뷰반영한다고 고생많으셨어요 ! 남은미션도 화이팅

2023-05-24 13:46 UTC, merged