[2단계 - 경로 조회 기능] 리오(오영택) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #124
Opened 2023-05-17 09:53 UTC by Jaeyoung22

안녕하세요 서브웨이! 리뷰이 리오입니다!
2단계도 잘 부탁드려요!!!

1단계 merge 하시면서 남겨주신 커멘트와 이전 커멘트들 중 resolve되지 않은 커멘트들에 대한 답변을 여기에 다시 적어볼게요!
https://github.com/woowacourse/jwp-subway-path/pull/11#discussion_r1195491275
> 앗 그렇군요!! 그렇게 리팩터링 하겠습니다!!!

https://github.com/woowacourse/jwp-subway-path/pull/11#discussion_r1195502915
> 2단계를 진행하면서, 다행히 Sections와 Subway 도메인에는 별다른 로직이 추가되지는 않았습니다!
> 
> 하지만 SectionService가 엄청 비대해졌습니다ㅠㅠ 이로 미루어보아 각 객체들에게 책임이 적절하게 퍼져있지 않은 것 같아요..
> 
> 하지만 로직 중에 DAO를 계속 호출하는 경우가 태반이라 지금으로서는 도메인에게 책임을 분리할 방법이 마땅히 떠오르지가 않네요...
> 이러한 경우에는 로직을 다시 수정하는 것이 나을까요..?ㅠㅠ

[1단계 - 지하철 정보 관리 기능 리오(오영택) 미션 제출합니다. by Jaeyoung22 · Pull Request #11 · woowacourse/jwp-subway-path · GitHub](https://github.com/woowacourse/jwp-subway-path/pull/11#discussion_r1195511420)
> 우려하신대로 2단계를 구현한 후에 서비스가 매우 비대해졌습니다ㅠㅠ
> 말씀하신대로 리팩터링을 고려해봐야할 것 같아요…!
> 3단계를 진행하면서 함께 진행해보겠습니다…!

위에 커멘트에서 말씀드린대로 서비스가 비대해져서 고민입니다…
대대적인 리팩터링이 필요할 듯 한데, 우선 2단계 기능 구현을 마쳐서 리뷰요청 드립니다…!
현재 로직으로는 중간에 계속 DAO에 접근을 해야해서 조금 더 고민해보고 진행하려고 합니다. 
이 부분에 대해서 질문을 드리고 싶은 점이 있는데요,  
지금 생각으로는 객체 내부에서 로직을 전부 진행한 뒤에 batchUpdate를 하는 방법을 생각하고 있습니다.
그런데, 데이터의 양에 따라 batchUpdate를 하는 것과 변경되는 데이터에만 접근하는 것이 trade-off 인 점이 분명히 존재할 것 같습니다.
batchUpdate를 하는 방법을 선택하면, 더욱 객체지향적인 코드를 작성할 수 있게 되지만 성능이나 데이터의 안정성?의 측면에서는 단점이 존재할 것 같습니다.
변경되는 데이터에만 접근하는 현재의 로직은 객체지향적이라고 하기에는 SectionService에 로직이 집중되어 있어서 비대해진 느낌이지만 속도 등의 성능에서는 장점이 존재할 것 같습니다. 
어느 정도의 데이터의 양이 두 방법을 선택하는 기준이 될까요?

더해서, 사소한 고민인데 distance와 fee 같은 원시값에 대해서 객체로 포장할 마땅한 이유를 아직 찾지 못해서요… 
distance의 경우 validate 로직이 포함될 수 있을 거 같고,
fee의 경우 할인율이 적용되는 경우 해당 로직이 포함될 수 있을 것 같지만
객체로 따로 빼는 비용을 들일 정도의 책임인가 하는 생각이 들어서 우선 원시값으로 두었습니다..!
어떻게 하는 것이 좋을까요?!

질문이 뭔가 애매하고 조금 무책임한 것 같아서 죄송합니다...!
다시 한 번 잘 부탁드립니다!!

2023-05-18 19:23 UTC, joseph415 requested changes
안녕하세요. 리오

2단계 변경사항이 크지 않아서 리뷰가 많지 않네요ㅎㅎ
기능 구현은 잘해주신 것 같아서 간단한 리뷰 몇가지 남겼습니다 확인부탁드려요!

2023-05-18 19:23 UTC, joseph415 commented on src/main/java/subway/domain/fee/NormalFeeStrategy.java
> +public class NormalFeeStrategy implements FeeStrategy {
해당 도메인은 돈계산하는 중요한 비지니스 규칙들인데, 테스트가 따로 있어야하지 않을까요? 단위테스트 작성이 필요해보입니다.

도메인 패키지 내의 기능들은 1단계에서 말씀드린 것처럼 단위테스트가 작성되어야 한다고 생각해요

2023-05-18 19:23 UTC, joseph415 commented on src/main/java/subway/domain/PathInfoFinder.java
> +    public int findFee(Long departureId, Long destinationId) {
PathFinder에서 findFee를 하는 것은 해당 객체가 갖을게 아니라, 전체 지하철을 관리하는 Subway가 더 맞는 위치 아닐까요?
pathFinder에서 요금에 대한 전략을 갖고있는것도 이쪽 책임이 아닌것 같아요.

2023-05-18 19:23 UTC, joseph415 commented on src/main/java/subway/domain/PathInfoFinder.java
> +        FeeCalculator feeCalculator = new FeeCalculator(feeStrategy);
이렇게 사용하는거라면, 더욱이 pathFinder에서 feeStrategy를 갖을 필요가 없지 않을까 의견드려요

2023-05-18 19:23 UTC, joseph415 commented on src/main/java/subway/domain/PathInfoFinder.java
> +    private final Graph<Long, DefaultWeightedEdge> graph;
이거는 몇가지 의견을 드려볼 수 있을 것 같은데요.

1. 도메인에 특정 기술의 의존성을 분리
원래 도메인은 특정 기술과 직접적인 의존을 최대한 피하는 것이 좋은데요. 지금 이렇게 되면, jgrapht라는 곳과 아주 강결합이 되어버리기 때문에, jgrapht가 변하게 된다면, PathInfoFinder 를 사용하고 있는 모든곳이 영향을 받을 수 있습니다.

따라서, PathInfoFinder라는 도메인 명세와 세부 구현을 나눠보는건 어떤가 의견드립니다. 구현부는 도메인패키지 외부로 빼고요.

2. 이건 참고로 한번 봐주세요. (1번에 대한 리뷰를 적용하지 않을 경우 봐주세요ㅎㅎ)
Section은 지금 역과 역사이의 정보를 갖고 있는 도메인 객체인데요. DefaultWeightedEdge 또한 같은 정보를 들고 있습니다. 따라서 지금 동일한 역할을 하는 것들이 이곳저곳에서 사용되고 있는 느낌이 있는데요.
즉, DefaultWeightedEdge => section 이고, Graph<Long, DefaultWeightedEdge> graph => Sections 가 될 수 있을것 같습니다.
DefaultWeightedEdge를 상속하는 Section을 만들어 보는건 어떤가요?

2023-05-18 19:23 UTC, joseph415 commented on src/main/java/subway/ui/SectionController.java
> +    @PostMapping("/path")
find 요청인데 왜 post받고 201이 내려가고 있는건가요?

2023-05-18 19:23 UTC, joseph415 commented on src/main/java/subway/application/SectionService.java
> +        List<Station> allStations = stationDao.findAll();
사용하는것을 보면 전부 가져올 것이 아니라, 필요한 역들만 가져와도 될 것 같은데요ㅎㅎ

2023-05-18 19:30 UTC, joseph415 commented
### 쓰기지연
>  batchUpdate를 하는 것과 변경되는 데이터에만 접근하는 것이 
서비스 메서드가 끌날때 dao 한번 접근 vs 메서드 흐름에 따라 단건 업데이트가 필요할 경우 진행

저는 이렇게 이해했고 이에 대한 답변드릴게요.

변경된 데이터를 임시로 모았다가 마지막에 한번에 보내는 것도 좋은 해결방법이 될 수 있을 것 같습니다. 디비를 여러번 접근하지 않고 한번에 처리가 가능한 상황이면 그렇게 푸는것도 좋아보여요. 근데, 그게 안되는 상황이 있는데 그런거라면 단건 업데이트를 직접 해야하지 않을까 해요.

dao 단건 요청을 하면 왜 객체지향적으로 풀 수 없는 것인지 말로만 풀어져 있어서 잘 이해가 안가지만, 한번에 처리할 수 있는 상황이면 그렇게 한번 해보시고 요청 주세요.

### 원시값 포장
- 저는 개인적으로 지금처럼 원시값을 사용하나 포장하나 큰차이가 없는거라면 안해도 된다고 생각합니다. 관리비용만 늘어난다고 생각해서요.
객체지향적으로 원시값을 포장해서 객체들끼리 의사소통을 하는 것이라면 의미가 있지만, 그렇지 않은 상황에서는 저도 리오처럼 했을 것 같습니다.

2023-05-19 01:32 UTC, Jaeyoung22 commented on src/main/java/subway/domain/fee/NormalFeeStrategy.java
> +public class NormalFeeStrategy implements FeeStrategy {
저도 이 부분이 좀 고민이었는데, 
서비스에서 똑같은 기능을 검증하는 테스트가 존재해서요...
중복이더라도 도메인에 단위테스트를 추가하는 것이 나을까요?
일단 추가해놓겠습니다!

2023-05-19 02:20 UTC, Jaeyoung22 commented on src/main/java/subway/domain/fee/NormalFeeStrategy.java
> +public class NormalFeeStrategy implements FeeStrategy {
조금 더 고민해봤는데, 만약 현재 구현대로 PathInfoFinder가 FeeStrategy의 구현체에 의존하고 있다면
mocking을 해서 진행해야겠네요..! 뭔가 잘못생각하고 있었습니다ㅠㅠ
리팩터링 후 모든 도메인에 단위테스트 작성하도록 하겠습니다!

2023-05-19 16:47 UTC, Jaeyoung22 commented on src/main/java/subway/domain/PathInfoFinder.java
> +    public int findFee(Long departureId, Long destinationId) {
경로라는 범주에 거리와 요금까지 포함해서 생각했던 것 같아요..!
Subway에 위치하지는 않지만, PathService를 새로 만들어서 findFee를 하도록 분리했습니다!
리뷰 감사합니다!!!

2023-05-19 16:47 UTC, Jaeyoung22 commented on src/main/java/subway/domain/PathInfoFinder.java
> +        FeeCalculator feeCalculator = new FeeCalculator(feeStrategy);
네 맞아요..! 분리해서 리팩터링 했습니다!!

2023-05-19 16:53 UTC, Jaeyoung22 commented on src/main/java/subway/domain/PathInfoFinder.java
> +    private final Graph<Long, DefaultWeightedEdge> graph;
외부 라이브러리를 사용하는 것이 처음이라 결합도까지 고려하지 못했었는데, 서브웨이의 리뷰를 받고 더 깊게 생각할 수 있게 됐습니다..!

특정 라이브러리에 의존하지 않도록 인터페이스를 사용해서 추상화 해봤습니다!
감사합니다!!

2번 리뷰의 경우 상당히 재밌어보이고 도전의식이 끓어오르네요...!
이런 방법으로 구현하도록 생각할 수도 있을 것 같습니다!
다만, 지금은 1단계에서부터 점점 요구사항이 더해지면서 기존 코드를 추가, 확장 해보는 연습을 하고 있는 것으로 알고 있어서
기존의 방법을 아예 갈아 엎는 것은 최대한 지양하고 싶습니다!
우선 3단계까지 현재 방법(인터페이스로 의존성 역전)으로 구현해 본 뒤에 시간적 여유가 있다면 시도해보겠습니다!
아니면 방학 기간 중에 재구현 해보겠습니다!
좋은 아이디어 알려주셔서 감사해요!!!!!

2023-05-19 16:56 UTC, Jaeyoung22 commented on src/main/java/subway/ui/SectionController.java
> +    @PostMapping("/path")
처음에 path들에 대해서도 영속화해서, 같은 경로 조회 요청이 있을 시에 빠르게 가져오도록 하는 도메인 로직을 구상했다가
그냥 영속화하지 않도록 하는 방향으로 설계를 틀었는데
탑다운으로 진행하다가 맨 처음 클래스를 수정하지 못했습니다..! 죄송해요ㅠㅠ

2023-05-19 17:38 UTC, Jaeyoung22 commented on src/main/java/subway/application/SectionService.java
> +        List<Station> allStations = stationDao.findAll();
그렇네요...!
DB 접근을 한번만 하자는 생각에 사로잡혀서 그 생각을 못했네요ㅠㅠ
List<Long> id로 필요한 station들만 가져오는 메서드를 stationDao에 만들어서 사용하도록 리팩터링 했습니다! 감사합니다~!

2023-05-20 18:16 UTC, joseph415 commented on src/main/java/subway/domain/fee/NormalFeeStrategy.java
> +public class NormalFeeStrategy implements FeeStrategy {
네네! 잘 고민해주신것 같습니다! 중요한 도메인은 별개로 단위테스트로 검증이 필요하다고 생각합니다!

2023-05-20 18:18 UTC, joseph415 commented on src/main/java/subway/domain/PathInfoFinder.java
> +    private final Graph<Long, DefaultWeightedEdge> graph;
넵 알겠습니다ㅎㅎ 나중에 한번 현재 구현된 코드에서 리펙토링하는 연습도 해보셔도 좋을 것 같아요ㅎㅎ 굴러가는 자동차의 바퀴를 바꿔보는 경험도 좋은 경험이 될 것 같다고 생각이 드네요!

2023-05-20 18:41 UTC, joseph415 approved these changes
안녕하세요. 리오

2단계 리뷰 반영해주신 잘 반영해주셨네요💯
반영해주신 부분에 간단한 코멘트 남겼습니다. 요건 다음단계 구현해주시면서 적용해주세요~
요구사항은 잘 반영해주신 것 같아서, 이번단계는 이만 merge할게요! 
3단계 구현해주세요!

2023-05-20 18:41 UTC, joseph415 commented on src/main/java/subway/config/SubwayConfiguration.java
> +    @Bean
이거는 도메인에 spring 코드가 들어가지 않도록하기 위해서 @Component가 아니라 여기서 선언해주신거죠!?

2023-05-20 18:41 UTC, joseph415 commented on src/main/java/subway/domain/path/PathFindByDistanceStrategy.java
> +package subway.domain.path;
domain 외부로 구현부를 빼면 좋을 것 같다고 의견드렸었는데, 핵심은 명세와 구현이 분리가 되는거라 따로 코멘트없이 현상태로 유지하도록 해요!

2023-05-20 18:41 UTC, joseph415 commented on src/main/java/subway/application/PathService.java
> +        Map.Entry<List<Long>, Integer> pathAndTotalDistance = getPathAndTotalDistance(pathFindingRequest);
지금 맵의 key value 형태가 path, totalDistance 로 잡혀있는데, 차라리 path와 totalDistance를 따로 호출해서 가져오는게 어떤가요? 맵형태가 적절한가 생각해볼수 있을 것 같아요.

key값이 유일함이 보장이 안되는것 같다는 생각이 들어요. 아니면 메서드 네이밍을 ShortestPath 라고 명시했으면 좋겠습니다.
key에 어떤한 `List<Long>`가 다들어갈 수 있는 형태라서요ㅎㅎ;

2023-05-20 18:41 UTC, joseph415 commented on src/main/java/subway/application/PathService.java
> +public class PathService {
PathService로 빼는게 훨씬더 명확한거 같아서 좋네요

2023-05-20 18:41 UTC, merged

2023-05-21 04:44 UTC, Jaeyoung22 commented on src/main/java/subway/config/SubwayConfiguration.java
> +    @Bean
네, 말씀해주신 이유처럼 도메인에 spring 코드가 들어가고 싶지 않게 한 이유도 있고
학습한 Configuration 방법들을 적용해보기 위한 이유도 있습니다!!

그런데, @component를 도메인에 붙여주는 방법과 이렇게 따로 @configuration이 붙은 클래스를 정의해 두고 @bean 으로 관리하는 것의 차이를 찾아보니까,
개발자가 컨트롤이 불가능한 외부 라이브러리들을 @bean으로 주로 등록해둔다고 하더라구요. 

이렇게 제가 만들어놓은 인터페이스에 @bean 등록을 해두는 것은 지양해야할까요?

2023-05-21 04:47 UTC, Jaeyoung22 commented on src/main/java/subway/application/PathService.java
> +        Map.Entry<List<Long>, Integer> pathAndTotalDistance = getPathAndTotalDistance(pathFindingRequest);
이 부분은 잘 이해가 안돼서 다시 질문 드려봅니다!

path와 totalDistance를 따로 호출하게 하면,
경로를 찾는 과정을 각각에 대해서 수행해야하므로 두번 일어나지 않을까요?

그리고 ShortestPath로 네이밍을 하지 않은 이유는 후에 경유지가 추가된다던가, 혹은 최단거리의 경로를 찾지 않는 경우로 확장이 될 수 있을 것 같아서 그냥 Path라고 두었습니다!
그런데 이 경우에 key 값의 유일함이 보장 되지 않는다는 부분에 대해서 조금 더 설명을 부탁드려도 될까요?

2023-05-21 05:53 UTC, joseph415 commented on src/main/java/subway/config/SubwayConfiguration.java
> +    @Bean
아 아니요ㅎㅎ 그냥 단순 질문이였습니다~

2023-05-21 05:59 UTC, joseph415 commented on src/main/java/subway/application/PathService.java
> +        Map.Entry<List<Long>, Integer> pathAndTotalDistance = getPathAndTotalDistance(pathFindingRequest);
아 요거는 이런생각으로 리뷰달았는데요!

[1,2,3] 의 역의 길이 있을 때, 갈림길이 있어서 만약 갈 수 있는 distance가 여러개 일 때, 덮어씌워지는 현상이 생길 수 있을 것 같아서 말씀드렸습니다.

갈림길이 있어서 `[1,2,3] - 6` `[1,2,3] - 7` 이렇게 있으면 getPath이니 2가지 모두 나올거라 생각할 수 있는데, 하나는 덮어져서  [1,2,3] - 7만 나올거같아서요.

나중에 갈림길이 추가가 됐을 때 해당부분 테스트가 명확하게 작성되어있지 않거나, 놓치면 버그가 생길 수 있지 않을까해서요