[2단계 - 경로 조회 기능] 푸우(백승준) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #139
Opened 2023-05-18 13:17 UTC by BGuga

안녕하세요 시카!! 2단계 미션 기능 구현 완료하였습니다 🫡
[지난번에 주신 리뷰](https://github.com/woowacourse/jwp-subway-path/pull/23#pullrequestreview-1423935229)를 반영한 후 경로 조회기능을 추가 및 DB 환경을 분리했습니다ㅎㅎ

현재 DB 환경을 분리하란 요구사항을
main 패키지에
<img width="280" alt="image" src="https://github.com/woowacourse/jwp-subway-path/assets/103228463/3d14730b-f412-48f1-a9f1-1216d065f17e">
두 가지 properties 로 만들었습니다.

실제 embeded DB 에 접속하고 싶다면 아래와 같은 설정을 통해 접근할 수 있도록 변경했습니다.
<img width="729" alt="image" src="https://github.com/woowacourse/jwp-subway-path/assets/103228463/9e3117b6-2a27-4b04-837e-88b3462e3af5">

만약 test 코드에서 application.properties 에 대한 세부 설정이 없다면 기본적으로 실제 DB 에 접속하기에 조금 더 방어적 접근을 위해 이렇게 만들었습니다!

2023-05-20 05:55 UTC, dks301 requested changes
안녕하세요 푸우, 리뷰어 시카입니다. 😄

1단계도 꼼꼼하게 학습하시고, 2단계도 요구사항에 맞춰 잘 구현해주셨네요! 👍
몇 가지 코멘트 남겨드렸으니 확인부탁드려요.

추가로 궁금한 점이 생기면 언제든지 DM 주세요 ㅎㅎ

2023-05-20 05:55 UTC, dks301 commented on src/main/java/subway/application/LineService.java
> +    private List<SectionEntity> toEntities(final Long lineId, final List<Section> sections) {
entity를 변환해주는 것도 어디서 해주는 것이 좋을지 각각의 장단점에 대해서 고민해보면 어떨까요??
1. 현재처럼 private method로 service에서 변환
2. entity에서 변환
3. 도메인 class에서 변환
4. mapper사용
5. 더 나은 새로운 방법(?)

등등 여러가지가 있을텐데 각각의 장단점에 대해서 고민해보아요

2023-05-20 05:55 UTC, dks301 commented on src/main/java/subway/application/LineService.java
> +    public Line findLineById(final Long lineId) {
Service에서 domain class를 바로 반환하는 부분과 dto로 변환해서 반환하는 것이 혼용되어있는데요...!
1. 어떤 차이가 있는 걸까요??
2. 각각의 장단점에 대해서 고민해보고 통일해보면 어떨까요??

2023-05-20 05:55 UTC, dks301 commented on src/main/java/subway/application/LineService.java
> +    @Transactional(readOnly = true)
https://github.com/woowacourse/jwp-subway-path/pull/23#discussion_r1194610036
트랜잭션에 대해서 굉장히 많이 공부하고 잘 정리해주셨네요! 💯👍
제가 실무에서 빌링 관련 프로젝트를 하다보니 이 부분이 굉장히 중요한데요...! 
지금 정리한 부분을 가지고 가시면서 이슈가 발생하거나 필요할때마다 이번에 적용하지 않은 부분들도 적용해보시면 좋을 것 같아요 ㅎㅎㅎ

2023-05-20 05:55 UTC, dks301 commented on src/main/java/subway/application/LineService.java
> +    private final StationService stationService;
https://github.com/woowacourse/jwp-subway-path/pull/23#discussion_r1194997711
정답은 없기 때문에 고민하신 부분에 대해서 이런식으로 고민해본 부분을 차츰 적용하면서 다른 개발자들이 다른 방식을 선택한 것을 보았을 때 참고하면 되지 않까요?? ㅎㅎㅎ

여기서는 추가로
1. SectionDao는 SectionService를 만들지 않은 이유가 있을까요?
2. LineService에서 여러 테이블에 접근해야 해서 LineDao만 DI한 것이 아니라 다른 서비스들과 DAO를 DI한 것으로 보이는데요...! 객체 지향 관점에서 이부분은 새로운 서비스를 만들어서 처리 해야하는 역할인지 고민해보면 어떨까요??

2023-05-20 05:55 UTC, dks301 commented on src/main/java/subway/domain/SubwayRouteMap.java
> +    public SubwayRouteMap(final List<Section> sections) {
외부 라이브러리를 참조하는 전용클래스를 만드셨는데요...!

1. Spring에서 제공하는 Configuration을 통해 bean으로 만들지 않은 이유가 있을까요??
2. 코드에 intellij에서 제공하는 경고(Raw use of parameterized class 'DijkstraShortestPath')가 보이는데요 사소해 보일 수 있지만 경고는 모두 없애보면 어떨까요??

2023-05-20 05:55 UTC, dks301 commented on src/main/java/subway/dto/StationResponse.java
> +    public StationResponse(final Long id, final String name) {
https://github.com/woowacourse/jwp-subway-path/pull/23#discussion_r1195054836
Request 변경사항이 2단계에서는 없어서 여기에 남길게요 ㅎㅎㅎ
그래서 우리는 Maven이나 Gradle을 사용해 빌드를 하는데요...! 관리의 편리성등 [여러가지 장점](https://kotlinworld.com/311)이 있지만, 이 경우에는 gradle을 사용해 동일한 환경에서  빌드할 수 있는 장점을 가져가는 것 아닐까요??

2023-05-20 05:55 UTC, dks301 commented on src/main/java/subway/entity/LineEntity.java
> +    public LineEntity(final Long id, final String name, final String color) {
정답이 없는 부분이지만 개인적으로는 [Rich Domain Model](https://www.linkedin.com/advice/3/what-benefits-drawbacks-using-anemic-domain-models)을 좋아하는데요 ㅎㅎㅎ

특히 작은 도메인 규모에서 이렇게까지 분리하지는 않아도 괜찮지 않을까? 라는 생각이 있는데요 ㅎㅎ 단순히 Line.class에 id만 추가하면 되지 않는지? 어떤게 더 나을지 고민해보면 어떨까요??

2023-05-20 05:55 UTC, dks301 commented on src/main/java/subway/domain/Line.java
> +    private void validate(final Section section) {
final 키워드를 사용하셨네요 😄
변수나 메서드 명으로 많이 명시해주셨지만, 비즈니스 로직이 복잡해지면서 동시에 객체의 상태가 많이 변화되어 코드 레벨도 복잡해지고 있는 것 같아요 ㅎㅎ
도메인 객체들을 최대한 [불변 객체](https://tecoble.techcourse.co.kr/post/2020-05-18-immutable-object/)로 만들어서 안전성과 다른 장점들을 가져가보면 어떨까요??

2023-05-22 05:16 UTC, BGuga commented on src/main/java/subway/application/LineService.java
> +    private List<SectionEntity> toEntities(final Long lineId, final List<Section> sections) {
> 현재처럼 private method로 service에서 변환
장점 : 적절한 장점이 생각나지 않습니다.
단점 :
1.  entity로 변환하는 로직의 위치가 조화롭지 않습니다.
2. 1번관 연관되어서 해당 entity 변환로직이 중복될 가능성이 높습니다.

> entity에서 변환
장점 : 
1. entity 로 변환하고자할 때 기능이 entity 에 포함되어 있다면 그 책임이 적절합니다.
2. 적절한 책임 분배로 해당 로직의 중복을 제거할 수 있습니다.
단점 : 
1. entity 변환로직이 많아지는 경우에 entity의 로직이 커지게 됩니다.

> 도메인 class에서 변환
장점 :
1. entity 변환 로직의 로직의 위치를 예상하기가 쉽습니다.
단점 : 
1. 영속화를 위한 entity 반환 로직이 domain 객체에 있다는 것은 도메인이 DB 변경에 종속적으로 바뀌게됩니다.
2. 종속적이기 때문에 entity 가 바뀔 때 마다 domain 의 로직을 수정하게 됩니다.

> mapper 사용
장점 :
1.  변환만을 담당하는 mapper 이기 떄문에 entity 변환 로직이 커졌을 경우에 해당 부분만 집중할 수 있게 됩니다.
그렇다면 entity 에는 복잡한 생성로직을 위임하고 자신은 기능 로직에만 집중할 수 있습니다.

단점:
1. 위임을 함으로써 entity 에 대한 로직이 여러 객체로 나누어졌습니다.
그로인해 entity 에 대한 로직이 하나의 class 안에 담기지 못하여 개발자가 이해해야하는 포인트가 늘어나게 됩니다.

제가 정리한 장단점에 크게 문제가 없다면 저는 1. entity에서 반환과 2. mapper 사용을 섞을 것 같습니다.
우선적으로는 entity에 반환로직이 있을 경우 저는 이해하기가 더 좋았습니다.
entity 안에 반환로직을 만들다 생성이 너무 복잡해지기 시작하면 mapper 로 빼낼 것 같습니다.

2023-05-22 10:58 UTC, BGuga commented on src/main/java/subway/application/LineService.java
> +    public Line findLineById(final Long lineId) {
최근에 근로를 하면서 osiv 와 jpa 을 어럼풋이 알게되었습니다!
그래서 두 개념을 살짝만 섞어서 비교해보겠습니다 ㅎㅎ

> 어떤 차이가 있는 걸까요??

### domain 을 반환한다.
장점:
- 도메인을 반환하기 서비스의 기능을 나누기 좋다.
이번 미션을 하면서 느낀 것이 Line 이라는 여러 도메인을 묶을 수 있는 도메인의 서비스에 로직이 많이 몰린다는 것을 느꼈습니다.
만약 현재 보다도 더 큰 개념의 도메인이 생기고 해당 도메인에 대한 로직을 하나의 서비스에 다 넣을 경우에는 클래스의 크기가 너무 커질 것 같습니다.

단점:
1. osiv를 만약에 off 한다면 controller 에서 dto 만드는 로직에 제약이 걸린다.
그러므로 Service Layer에서 lazy loading 으로 설정된 데이터를 호출한 후 넘겨줘야 한다.
이는 presentation layer의 로직이 application layer의 로직에 변경을 가하는 꼴이다.

2. view layer에 도메인에 로직이 작성될 수 있다.

### dto 를 반환한다.

장점:
1. 도메인이 view layer에 노출되지 않는다.

단점:
1. dto 로 반환할 경우 영속화 된 객체를 받지 못한다. 
그로인해 서비스에서 다른 서비스를 호출하지 못한다.

2023-05-22 11:51 UTC, BGuga commented on src/main/java/subway/application/LineService.java
> +    public Line findLineById(final Long lineId) {
> 각각의 장단점에 대해서 고민해보고 통일해보면 어떨까요??

현재는 domain을 반환하는 것으로 통일한 후 domain <-> dto 로직을 controller에 두었습니다.
하지만 이것은 1. 도메인 로직이 view에 노출되며 2. osiv 로 인한 controller 로직이 service에 노출된다는 큰 단점이 있는 것 같습니다.

그래서 앞으로는 dto 를 반환하는 방향으로 코드를 짤 것 같습니다.
```
그로인해 서비스에서 다른 서비스를 호출하지 못한다
```
그럼 해당 문제를 해결해야할 것인데 저는 이것이 현재 Service Layer에 너무 많은 로직을 넣어서 생긴 문제라 생각합니다.
현재 Service가 가지고 있는 책임이
1. 테이블로부터 domain 객체를 생성하는 책임
2. domain 들로 로직을 실행하는 책임

현재 반환 타입에서 Domain <-> dto 를 선택해야하는 이유가 Domain을 서비스에서 만들기 떄문입니다.
모든 Service에서 제가 만들어둔 domain 을 사용할 수 있어야 하기 때문에 도메인을 생성하는 로직을 Service 에 위치 시키는 것은 중복 로직 혹은 다른 서비스 호출로 이어질 수 밖에 없습니다.
만약 중복을 제거하기 위해 하나의 도메인 로직 생성을 하나의 서비스에만 위치시키는 것도 어느 서비스가 도메인을 생성해야하는지 결정하기 모호합니다.
그래서 도메인을 생성하는 역할을 담당하는 Repository 계층을 도입할 것 같습니다.
그 결과 Service Layer는 도메인들의 협력으로써 정의되는 기능만을 담당할 수 있습니다.

정리하자면 Repository 를 도입함으로써 Service는 현재 기능만을 담고 있는 상황입니다.
그렇다면 Service가 Service의 메서드를 호출할 때는 그 반환값이 도메인이여할 필요는 없을 것 같습니다.
해당 서비스에 책임의 위임한다면 반환은 확인을 위한 dto 정도만 있어도 충분할 것 같습니다.

2023-05-22 12:26 UTC, BGuga commented on src/main/java/subway/application/LineService.java
> +    public Line findLineById(final Long lineId) {
도메인으로 통일해보니
응답을 위한 도메인이 또 생기는 것 같네요..!
직접 써보니 dto 를 반환하는 것이 확실히 더 좋아보이네요 ㅎㅎ;;

2023-05-22 15:13 UTC, BGuga commented on src/main/java/subway/application/LineService.java
> +    @Transactional(readOnly = true)
감사합니다 ㅎㅎ

2023-05-22 16:11 UTC, BGuga commented on src/main/java/subway/application/LineService.java
> +    private final StationService stationService;
> SectionDao는 SectionService를 만들지 않은 이유가 있을까요?

Section을 만드는 로직이 이곳 저곳 중복되어 있더군요 SectionService를 만들어서 분리했습니다!

> LineService에서 여러 테이블에 접근해야 해서 LineDao만 DI한 것이 아니라 다른 서비스들과 DAO를 DI한 것으로 보이는데요...! 객체 지향 관점에서 이부분은 새로운 서비스를 만들어서 처리 해야하는 역할인지 고민해보면 어떨까요??

여러 Dao 와 Service 가 들어간 이유가
1. Line 생성을 위해서
2. Line 로직을 위해서
두 가지가 있을 것 같습니다.
1번의 경우는 따로 repository로 분리하는 것이 좋기 때문에 해당 서비스의 역할이 아니라고 봅니다.
하지만 2번의 경우에는 Line 안에는 Station 도 있기 때문에 StationService 혹은 StationRepository 를 DI 해서 처리해도 괜찮을 것 같은데 이 부분도 Line의 역할이라 볼 수 없나요..?

2023-05-22 16:17 UTC, BGuga commented on src/main/java/subway/domain/SubwayRouteMap.java
> +    public SubwayRouteMap(final List<Section> sections) {
> Spring에서 제공하는 Configuration을 통해 bean으로 만들지 않은 이유가 있을까요??

해당 객체는 변하는 상태를 가지는 객체이기 때문에 싱글톤 bean 으로 등록시 동시성 문제가 발생할 것 으로 예상되어 bean 으로 만들지 않았습니다.

> 코드에 intellij에서 제공하는 경고(Raw use of parameterized class 'DijkstraShortestPath')가 보이는데요 사소해 보일 수 있지만 경고는 모두 없애보면 어떨까요??

제거했습니다~!

2023-05-22 16:17 UTC, BGuga commented on src/main/java/subway/dto/StationResponse.java
> +    public StationResponse(final Long id, final String name) {
?! 테스트 실행 속도가 너무 느리진 않나요?.?

2023-05-29 13:14 UTC, BGuga commented on src/main/java/subway/entity/LineEntity.java
> +    public LineEntity(final Long id, final String name, final String color) {
Rich Domain Model이 서비스에 로직이 작성되기 보단 Domain 에 로직을 작성하는 것을 권장하는 것으로 이해됩니다!!
현재 대부분의 로직은 도메인에 작성되었는데 시카가 제시해주시는 방향성은 DB Entity에 로직을 추가하란 뜻 맞을까요??

2023-05-29 13:16 UTC, BGuga commented on src/main/java/subway/domain/Line.java
> +    private void validate(final Section section) {
감사합니다!! 반영했습니다

2023-05-30 08:52 UTC, dks301 approved these changes
안녕하세요 푸우, 리뷰어 시카입니다. 😄

이번 미션에서는 정답이 없고 깊이 고민해볼 만한 내용을 중점적으로 코멘트 드렸는데요...!
많은 고민을 하면서 충분히 성장하신 것 같아요 💯👏
이번 미션은 이만 머지하겠습니다. 수고하셨습니다!

추가로 궁금한 점이 생기면 언제든지 DM 주세요 ㅎㅎ

2023-05-30 08:52 UTC, dks301 commented on src/main/java/subway/application/LineService.java
> +    private List<SectionEntity> toEntities(final Long lineId, final List<Section> sections) {
이 부분도 역시 정답은 없기때문에, 각각의 장단점에 대해서 고민해보고 선택하면 되는 문제인데요...!
이번 기회에 장단점에 대해 많이 고민해보신것으로 충분해보입니다 👍👍

2023-05-30 08:52 UTC, dks301 commented on src/main/java/subway/entity/LineEntity.java
> +    public LineEntity(final Long id, final String name, final String color) {
DB entity에 로직을 추가한다기보다는 현재처럼 Domain과 entity가 분리되어야 하는지에 대해서 고민해볼 여지가 있는 것 같아서 코멘트 드렸습니다 ㅎㅎㅎ

2023-05-30 08:52 UTC, dks301 commented on src/main/java/subway/dto/StationResponse.java
> +    public StationResponse(final Long id, final String name) {
테스트 실행 속도가 느리다는 단점은 새로이 풀어야하는 문제라고 생각해요 ㅎㅎㅎ
현재는 intellij를 모두가 사용할 것 같지만, 예를들어 다른 os, 다른 ide 등등 다른 환경에서 다르게 동작하거나 빌드가 안되는 등 차이가 발생할 수 있다는 단점이 더 크지 않을까요??

2023-05-30 08:52 UTC, dks301 commented on src/main/java/subway/application/LineService.java
> +    private final StationService stationService;
역할과 책임이라는 것은 경계가 모호하기 때문에 그렇게 볼 수 도있고, 아닐 수도 있다고 생각하는데요...! ㅎㅎㅎ
해당 역할이라고 본다는 관점에서는 푸우의 생각이 맞겠지만,
반대로 역할이라고 보지 않는다면 Line안의 Station을 분리해야하는지 등등에 대해서 고민해볼 수 있을 것 같습니다 :)

2023-05-30 08:52 UTC, merged