[2단계 - 경로 조회 기능] 이오(이지우) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #152
Opened 2023-05-19 08:57 UTC by LJW25

안녕하세요 완태, 이오입니다.

2단계의 경로 조회와, 요금 계산 기능을 구현 완료하였습니다.

사용한 Docker의 설정은 다음과 같습니다.

```
version: "3.9"
services:
  db:
    image: mysql:8.0.28
    platform: linux/x86_64
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chess
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d
```

또한 아래의 쿼리를 사용하여 테이블을 생성할 수 있습니다.

```
CREATE DATABASE subway DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
```

리뷰해주셔서 감사합니다! :)

2023-05-21 03:49 UTC, wannte requested changes
안녕하세요! 이오!

step 1에서 진행한 리팩터링덕분인지 빠르게 step 2를 진행해주셨네요!

간단한 피드백 몇가지 남겼으니 확인부탁드려요!

2023-05-21 03:49 UTC, wannte commented on src/main/java/subway/application/LineService.java
> +        lineRepository.saveSectionsByLine(line);
`saveLine` 과도 통일시킬 수 있을 것 같아요!

2023-05-21 03:49 UTC, wannte commented on src/main/java/subway/domain/PathFinder.java
> +        return new PathFinder(graph);
1. station.name 보다는 station 자체를 vertex 로 두는 게 어떨까요? (edge 도 마찬가지)
2. line 을 구성하는 station 으로 vertex 를 등록하는 것은 어떨까요?

2023-05-21 03:49 UTC, wannte commented on src/main/java/subway/application/LineService.java
> +        return SectionResponse.of(sectionIds.get(0), section);
Line 에 section을 추가하는 service인데, LineResponse 를 내려주는 것은 어떨까 해요.

LineResponse 가 Section의 정보를 가지고 있어야 하지 않나 싶기도 하네요!

2023-05-21 03:49 UTC, wannte commented on src/main/java/subway/domain/Path.java
> +        }
magic number 처리를 하면 좋겠네요!

2023-05-23 10:43 UTC, LJW25 commented on src/main/java/subway/domain/PathFinder.java
> +        return new PathFinder(graph);
1. 말씀하신 구조로 변경하였습니다! 
해당 구조로 변경하는 것이 더 직관적이라고 느껴지는데, 혹시 이외의 장점이 더 있을까요?

2. 기존에 line의 station을 사용하면 서로 다른 노선 사이에 역이 중복될 수 있어 station을 읽어와 사용하였는데, DB를 읽어오는 것 보다 중복이 있더라도 line을 구성하고있는 station을 사용하는 것이 더 효율적이라고 느껴 말씀하신 구조로 변경하였습니다!

2023-05-23 10:51 UTC, LJW25 commented on src/main/java/subway/application/LineService.java
> +        lineRepository.saveSectionsByLine(line);
`saveLine`과 `saveSectionsByLine`은 역할이 달라 통일시키기 어려울 것이라고 생각합니다. 
`saveLine`은 노선의 이름, 색상 등 역이나 구간의 상태와 관계 없는 정보만을 저장하고 있습니다. 
반면 `saveSectionsByLine`은 반대로 노선 자체의 특징이 아닌 역과 구간의 상태만을 저장하는 메소드입니다.
즉 두 메소드는 용도가 다르고 호출하는 API도 다르기 때문에 통일은 어렵다고 생각합니다!

2023-05-23 11:07 UTC, LJW25 commented on src/main/java/subway/application/LineService.java
> +        return SectionResponse.of(sectionIds.get(0), section);
LineResponse를 반환하도록 구조를 수정하였습니다!

혹시 LineResponse가 Section의 정보를 가지고 있어야 하는 이유를 알려주실 수 있으실까요?
저는 보통 지도를 검색할 때에 어느 역을 지나가는지를 궁금해하고, 각 역 사이가 얼마나 떨어져있는지를 궁금해하지는 않을 것이라고 생각하여 지금과 같이 Line에 포함되어있는 station들의 목록만을 순서에 맞춰 반환해 주었습니다.

2023-05-23 17:40 UTC, wannte commented on src/main/java/subway/domain/PathFinder.java
> +        return new PathFinder(graph);
> 해당 구조로 변경하는 것이 더 직관적이라고 느껴지는데, 혹시 이외의 장점이 더 있을까요?

name 으로 저장한다면, 해당 역에 대한 정보를 찾기 위해서는 name 으로 db 를 조회해야 하는 추가 작업이 필요합니다. 현재 요구 사항에서는 이름만 보여주지만, 이후에 역에 대한 다른 정보들을 보여주는 요구 사항이 추가된다면, 쉽게 처리할 수도 있을 것 같네요!

>  line의 station을 사용하면 서로 다른 노선 사이에 역이 중복될 수 있어 

이건 Line 의 책임이지 않을까 해요!

2023-05-23 17:40 UTC, wannte commented on src/main/java/subway/application/LineService.java
> +        return SectionResponse.of(sectionIds.get(0), section);
아 넵 Section의 이미가 실제 Section 도메인을 의미한 다기 보다는, Line 을 구성하는 역들의 관계를 의미했던 부분입니다! 잘 처리하신 것 같네요!

2023-05-23 17:46 UTC, wannte approved these changes
안녕하세요! 이오!

리뷰 사항도 잘 반영해주셨네요!

이번 미션의 요구 사항들도 잘 만족한 것 같아 이만 머지하겠습니다 🙇 
다음 미션도 화이팅입니다!

2023-05-23 17:46 UTC, merged