[2단계 - 경로 조회 기능] 제리(권현재) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #154
Opened 2023-05-19 11:04 UTC by Hyeonjae-K

코다 안녕하세요! 리뷰이 제리입니다🐭
2단계 요구사항의 난이도에 비해  굉장히 오랜 시간이 걸린 것 같습니다😭

이전에 달아주신 질문에 대한 답과 새로운 질문 함께 남깁니다.
감사합니다🙇

## 이전 질문에 대한 답변

https://github.com/woowacourse/jwp-subway-path/pull/8#discussion_r1192923583
>serivce가 다른 service를 의존하는 것에 대한 질문인가요 ? ㅎㅎ
제리가 말씀해주신 ServiceRepository 레이어를 잘 이해하지 못한 것 같아요 ㅠㅠ

Repository 레이어를 말해야 했는데 급하게 작성하다 보니 ServiceRepository라고 작성하여 오해가 있었던 것 같습니다ㅠㅠ
이전 코드에서 service 레이어 간의 의존을 통해 Line에서 Section에 대한 정보가 필요할 경우 SectionService를 통해 정보를 가져와야 했습니다.
이렇게 구성을 하고 보니 만약 SectionService에서 Line에 대한 정보가 필요할 경우 LineService를 의존하게 되므로 순환참조가 생길 위험이 있었고 이전의 SectionService와 같이 컨트롤러와 무관하게 서비스를 위해 존재하는 클래스가 특별한 역할 없이 DAO의 결과를 단순히 전달하기만 하는 등 불필요한 중복이 발생하는 것 같았습니다.
따라서, 이번 미션에서는 Service와 DAO 사이에 Repository 레이를 추가해 Respository 레이에서 필요할 경우 다른 테이블의 DAO들을 참조하여 서비스에서 바로 사용할 수 있는 도메인 형태로 객체를 반환할 수 있도록  함으로써 도메인과 테이블 간의 간극을 해소하는 것을 Repository에 위임하여 서비스에서는 비즈니스 로직에만 집중할 수 있었습니다.
코다는 이번 미션에서 추가한 Repository 레이어가 적절하다고 생각하시나요?

https://github.com/woowacourse/jwp-subway-path/pull/8#discussion_r1192926007
>"null을 그냥 반환할 경우 null 전파로 인한 힙 오염이 일어날 수 있나요?"
아하 ! 그런 얘기가 있었군요 ?
저도 잘 모르겠어요 ㅎㅎ 앞뒤 맥락을 조금 더 이해하면 좋을 듯 하네요

결국 저 말을 한 크루는 찾지 못했지마 검색을 통해 약간의 단서를 찾을 수 있었습니다.
메서드에서 `null`을 반환할 경우 다른 메서드로 `null`이 전달되는 것을 'null 전파'라고 하며
이럴 경우 `null`을 참조하는 객체가 생성되어 힙에 메모리 누수가 발생할 수 있다고 합니다.
제가 생각했던 힙이 오염되는 경우는 아니었던 것 같습니다.

https://github.com/woowacourse/jwp-subway-path/pull/8#discussion_r1192923624
>추가되는 section은 55번 줄에서 구한 데이터 그대로인 것이죠 ? 또 다시 찾을 필요가 있나요 ?

저도 처음에 리뷰를 보고 불필요한 로직 같아 제거했지만 다시 생각해 보니 필요한 경우가 있어서 추가했습니다.
예를 들어 [a-b, b-c]가 있다고 가정할 때, b와 c 사이에 x역을 추가하는 경우 [a-b, b-x, x-c]가 되어야 합니다.
따라서, 새로 추가되는 역은 [b-x, x-c] 두 개이므로 차집합을 통해 구해야 했습니다.

https://github.com/woowacourse/jwp-subway-path/pull/8#discussion_r1192924476

>addSection() 시 새로운 Line이 반환된다면 객체에 대한 안정성은 올라가지면 구간이 매우 많은 경우 그만큼 리소스를 잡아먹을 수도 있겠네요 !

맞습니다ㅠㅠ
저도 리소스를  많이 사용한다는 단점을 느꼈지만, 현재는 객체에 대한 안정성이 더욱 중요하다고  생각했으며
추후 리소스 관련 문제가 생길 경우 모든 도메인 객체에 대해 불변을 유지하는 것이 아닌 선택적으로 불변을 유지하는 방식을 취할 것 같습니다.

https://github.com/woowacourse/jwp-subway-path/pull/8#discussion_r1192924668

>어떤 서비스는 `@Transactional`을 추가하고 여기는 없네요.
readOnly 속성도 있으니 키워드 공부해보시고 필요한 곳에 추가하면 좋을 것 같아요 ~

미션에 눈이 멀어 기존 뼈대 코드까지 신경쓰지 못했습니다...
readOnly 속성을 사용할 경우 최적화로 인한 성능적 이점과 충돌 방지에 도움이 될 수 있다는 점을 배웠습니다.
나중에 시간이 난다면 뼈대  코드에도 `@Transactional`을 추가하겠습니다.

https://github.com/woowacourse/jwp-subway-path/pull/8#discussion_r1192924878

> 여기가 testcode가 깨지는 원인이군요 !
요렇게 구현하면 어떤 이슈가 있을지 고민해보아요 🙌

새로 생성된 객체는 id를 갖고있지 않아 발생하는 문제였습니다.
따라서, 새로  생성된 객체도  결국 같은 객체라고 보고 id를 추가할 것인지 다른 객체라고 보고 테스트를 수정할 것인지 선택해야 했습니다.
저는 수정이 일어난 객체는 아직 db에 저장되지 않으므로 다른 객체이고 db에 업데이트가 일어날 경우 필요하면 객체에서도 id를 업데이트하는 것이 맞다고 생각하여 id로 검증하는 테스트를 수정했습니다.

https://github.com/woowacourse/jwp-subway-path/pull/8#discussion_r1192925104

> 이러면 갈림길이 생기는 것에 대한 방어가 안될 것 같은데 제리는 어떻게 생각하시나요 ?

처음엔 미션에 갈림길에 대한 것은 고려하지 않는다는 조건이 있어서 왜 질문하신지 몰랐습니다.
하지만, 나중에 경로를 조회하기 위해 모든 노선을 가져와야 했고 이럴 경우 다른 노선들로 인해 갈림길이 발생할 수 있었습니다.
이를 해결하기 위해 SectionsGraph라는 도메인을 새로 만들어 갈림길이 있어도  문제가  발생하지 않도록 했습니다.

https://github.com/woowacourse/jwp-subway-path/pull/8#discussion_r1192925119

> 요것과 아래 메서드가 static인 이유가 있나요 ?

인텔리제이가 그랬어요!!
메서드  추출을 하면서 자동으로 `static`이 붙었습니다ㅠㅠ

https://github.com/woowacourse/jwp-subway-path/pull/8#discussion_r1192925173

> 예외가 해당 section을 찾을 수 없다 는 말씀이시죠? ㅎㅎ
그런데 노선에 마지막 구간이라면 beforeSection, nextSection 중 하나가 없는 경우도 있을 수 있지 않을까요 ?

현재 노선은 Section 단위로 이루어져 있으므로 비어있는 경우는 없습니다.
처음에 Linked List 방식의 Node 단위로 구성을 했을 때, 첫 역과 마지막 역이 빈 역을 참조해야 하는 문제가 있었습니다.
이때, Null Object Pattern을 이용할 것인지, Node가 아닌 Section 방식으로 넘어갈 것인지 선택해야 했습니다.
결과적으로 Section 방식이 추후  구현에 빈 객체에 대한 처리를 해주지 않아도 되므로 안정성이 높고 구현 난이도에 크게 차이가 없다고 판단하여 Section 방식을 선택했습니다.

https://github.com/woowacourse/jwp-subway-path/pull/8#discussion_r1192925301

>result.stream()
     .filter(section -> !otherSections.getSections().contains(section))
     .findAny(); 
위와 같이 작성하면 어떤 역할을 하는 메서드인지 더 직관적으로 보여서 가독성이 좋을 것 같은데 제리 생각은 어떤가요 ? 🤔

저는 복사본에서 지우고 새로운 객체로 반환한다는게 더 직관적이라 느껴져서 고치지 않았습니다,,

## 새로운 질문

현재 Line과 Station 테이블의 경우 name 값이 유일하므로 id 컬럼을 제거하고 name을 식별자로 사용할 수 있습니다.
1단계에서 페어와 name을 primary key로 사용하면 name에 한글 값이 들어가므로 `@PathVariable`을 통해 URI에서 Line이나 Station을 조회하면 URL 경로 창에서 인코딩되어 한글이 깨질 수 있고 인덱싱에 의해 VARCHAR 타입을 사용할 경우 성능 차이가 발생할 수 있는 등의 문제를 고려하여 id 컬럼을 추가했습니다.
하지만 저장하기 전까지 id가 `null`인 상태로 있게 되는 문제와 name을 알기 위해 id로 다시 조회해와야 하는 등 불편한 상황들이 있었습니다.
실제로 이런 불편한 상황들이 예상되는 경우 식별을 위한 값(id, uuid 등)이 아닌 유일한 실제 값을 식별자로 사용하기도 하는지 궁금합니다.

https://github.com/woowacourse/jwp-subway-path/pull/8#discussion_r1192925441

>dto도 의존성 관리를 해야합니다 ! 아니면 dto 패키지에서 금방 의존관계가 얽힐 수 있어요 ㅎㅎ
이 dto는 어떤 레이어에 속하나요 ?

위의  이전 리뷰에서 dto도 의존성을 관리해야 한다고 하셨는데 잘 이해하지 못했어요.
다시 설명해 주실 수  있을까요?
또한, 이번 미션을 진행하며 다음과 같은 구조를 생각했습니다.
<img width="506" alt="image" src="https://github.com/woowacourse/jwp-subway-path/assets/71651608/5a19a4cd-b6fe-4e0d-ad1e-8cb173ea83db">
위와 같은 구조를 생각한 이유는 만약 여러 컨트롤러에서 서비스를 호출할 경우 서비스에  전달되는 Request나 서비스로부터 필요한 Response가 조금씩 다를 수  있는데 이를 DTO로 한 번 변환하여 서비스에 필요한 데이터만 넘겨줄 수 있고 DTO에 담겨있는 데이터 중 필요한 데이터만 추출하여 Response 객체를 만들어 반환해줄 수 있다고 생각했기 때문입니다.
코다는 위 구조에 대해  어떻게 생각하시나요? 대부분의 크루들은 DTO와 Request/Response가 같으므로 불필요하다는 의견이었습니다.
그리고 Repository의 경우 domain과 entity 간의 간극을 제어하고 Service 레이어가 비즈니스에만 집중할 수 있도록 하기 위해 추가했습니다.

2023-05-20 17:19 UTC, yjksw requested changes
안녕하세요 제리 🙇‍♀️ 코다 입니다 

레벨2 구현 잘 해주셨네요 ! 크게 리뷰할 부분이 없었습니다 ㅎㅎ
이전 리뷰에 대한 답변도 잘 읽어보았어요 

몇가지 코멘트는 다음 리팩토링 시 참고해주세요 ~!

2023-05-20 17:19 UTC, yjksw commented on build.gradle
> +    // https://mvnrepository.com/artifact/org.jgrapht/jgrapht-core
안쓰는 주석은 지워주세요 ~!

2023-05-20 17:19 UTC, yjksw commented on src/main/java/subway/application/SectionService.java
> +        final int fare = SectionGraph.calculateFare(distance);
sectionGraph에서 fare를 계산하는 것이 조금 어색한 것 같은데 제리는 어떻게 생각하시나요 ?
이미 생성된 객체에 대한 static 호출이나, 그래프와 관련 없는 로직을 해당 객체에서 하는 이유가 있을 것 같아요 ~

2023-05-20 17:19 UTC, yjksw commented on src/main/java/subway/domain/section/SectionGraph.java
> +public class SectionGraph {
클래스 명에서 내부 구현체를 반영하고 있다는 느낌이 조금 드네요~! 
이름을 보고 어떤 책임을 가진 클래스인지 유추하기 조금 힘든 것 같기도 하구요 ! 
내부 구현을 보기 전까지 Sections와 SectionGraph의 차이점이 무엇인지 궁금할 수 있을 것 같아요.

2023-05-20 17:19 UTC, yjksw commented on src/main/java/subway/domain/section/SectionGraph.java
> +        this.stationMap = extractStationAsMap(sections);
이미 잘해주셔서 지급 고민하기 중요한 부분은 아니지만 코멘트 드립니다 ㅎㅎ 
여기서 메모리가 거대한 DB가 되는 느낌이 드는데요, 
실제로 사용되는 애플리케이션이고, station의 개수가 매우 많으면 이 구현은 사용되지 못하겠군요

2023-05-20 17:19 UTC, yjksw commented on src/main/java/subway/domain/section/SectionGraph.java
> +    public static int calculateFare(final double distance) {
service에서도 언급했지만, 이 메서드가 이 클래스에서 제일 어색한 것 같아요 ! 
클래스 명을 수정하거나, 계산 로직 책임을 더 적절한 곳에서 수행하거나, 고민해보면 좋을 것 같네요

2023-05-20 17:19 UTC, yjksw commented on src/main/java/subway/domain/section/Sections.java
> +    private final List<Section> values;
values와 같은 의미를 유추하기 힘든 네이밍은 최대한 지양하는 것이 좋아요 ! 
클래스가 다양하고 커질수록, 아래 로직을 보며 values가 어떤 값이었는지 클래스 위로 올라와서 계속 확인해야할 수도 있답니다 ㅎㅎ

2023-05-20 17:19 UTC, yjksw commented on src/main/java/subway/domain/section/Sections.java
> +    }
생성 시 정렬된 상태로 저장하기는 하지만, 해당 컬렉션이 끝까지 정렬된 상태를 유지한다고 보장할 수 있을지 고민해봐도 좋을 것 같아요 ~ 
여러 개발자들과 협업하면서, 누군가 어디선가 정렬을 깨뜨리는 로직을 수행하게 된다면 애플리케이션 큰 오류가 생길 수 있지 않을까요 ?

2023-05-20 17:19 UTC, yjksw commented on src/main/java/subway/persistence/repository/LineRepository.java
> +public class LineRepository {
질문 주신 부분이군요 ! 
제리가 repository를 따로 분류하신 이유에 대해서는 잘 이해했어요. 서비스가 비즈니스에 더 집중할 수 있도록 하는 좋은 의도라고 생각해요 ㅎㅎ 

추가 고민거리를 던져보자면, 
지금은 repository가 persistence 레이어에 머물러 있게 되면서 persistence에서 수정이 일어나면 service에도 영향이 미칠 수 있겠군요 !

2023-05-20 17:19 UTC, yjksw commented on src/main/java/subway/persistence/repository/SectionRepository.java
> +        );
이 부분이 persistence가 도메인의 내부구조까지 깊이 알고 있다는 생각이 드는데, 제리는 어떻게 생각하시나요 ?

2023-05-20 17:19 UTC, yjksw commented on src/main/java/subway/ui/request/PathRequest.java
> +public class PathRequest {
질문주신 부분인데요 ! 
dto가 웹 레이어의 의존성에도 영향을 미치니 준수해야한다는 의미였습니다. 

지금은 이 dto로 인해 ui -> service -> ui 에 의존하는 순환참조가 있네요 !

2023-05-20 17:19 UTC, yjksw commented on src/main/java/subway/ui/response/LineResponse.java
>      public static LineResponse from(final Line line) {
ui가 도메인을 아는 것에 대해서 제리는 어떻게 생각하시나요 ?

2023-05-20 17:19 UTC, yjksw commented on src/main/java/subway/ui/response/LineResponse.java
> +        if (line.getSections().getValues().isEmpty()) {
디미터 법칙을 준수해서 내부구현을 메시지 안으로 숨길 수 있겠네요

2023-05-20 17:19 UTC, yjksw commented on src/main/java/subway/ui/response/LineResponse.java
>          }
중간에 빈 리스트인 상태를 만들지 않고 stream등을 사용해서 간단하고 가독성 좋게 리팩토링 해볼 수 있을 것 같아요 !

2023-05-20 17:19 UTC, yjksw commented on src/test/java/subway/domain/SectionGraphTest.java
> +class SectionGraphTest {
도메인에 중요한 로직이 많은 것에 비해 테스트가 적게 되고 있군요 !

2023-05-20 17:19 UTC, yjksw commented on src/test/java/subway/domain/SectionsTest.java
> +        final Station stationA = new Station(1L, new StationName("A"));
요 클래스도 마찬가지로 테스트되지 않는 메서드가 많은 것 같아요 !

2023-05-20 17:19 UTC, yjksw commented on src/test/java/subway/integration/SectionIntegrationTest.java
> +        lineService.registerStation(LINE3.getId(), new SectionRequest(STATION_C.getName().getValue(), STATION_E.getName().getValue(), DISTANCE3.getValue()));
각 테스트코드에서 의존하고 있는 데이터가 다른데 setup에서 공통으로 다 하는게 맞을지 고민해보면 좋겠어요 !
애플리케이션이 커지고 테스트가 많아지면 테스트 간 결합이 생겨 관리가 어려워질 수 있답니다

2023-05-20 17:19 UTC, yjksw commented on src/test/java/subway/jgrapht/jgraphtTest.java
> +public class jgraphtTest {
자료구조를 테스트하기보다 도메인에서 테스트하면 어떨까요?

2023-05-20 17:24 UTC, yjksw commented
제리 질문에 대한 답변 드립니다 😊

> 실제로 이런 불편한 상황들이 예상되는 경우 식별을 위한 값(id, uuid 등)이 아닌 유일한 실제 값을 식별자로 사용하기도 하는지 궁금합니다.

제리가 말씀주신 불편함 잘 이해가 되어요 ! 다른 기술들이 이러한 데이터, 애플리케이션 괴리에 대한 해결을 어떻게 하는지 다음 레벨부터 차차 알아갈 수 있을 듯 하여 이번에 하신 고민을 기억하면 도움이 될 것 같아요 ㅎㅎ 

현업에서는 주로 id, 그리고 기술적인 필요에 의해서 가끔 복합키를 사용하기도 합니다 (드문 경우에요)
주로 id를 사용하는 이유는, 제리가 말씀주신 것처럼 다른 식별자가 있을 수 있는 상황이 많지만 의미를 가진 칼럼인 경우 계속 식별자로 사용할 수 있을지에 대한 보장이 없기 때문이에요. 단적인 예로, 주민번호를 id로 사용했다가 개인정보보호법으로 인해 더 이상 id를 사용할 수 없게된 경우도 있어요.  


> 위의 이전 리뷰에서 dto도 의존성을 관리해야 한다고 하셨는데 잘 이해하지 못했어요.
다시 설명해 주실 수 있을까요?

리뷰에서 언급했습니다 !

2023-05-21 05:28 UTC, Hyeonjae-K commented on src/main/java/subway/domain/section/SectionGraph.java
> +public class SectionGraph {
맞습니다ㅠㅠ
그래서 이 커밋을  보면 [refactor: 경로 검색 책임 분리](https://github.com/woowacourse/jwp-subway-path/pull/154/commits/2b9070f193b5463304886b30a841874d495ee6a5)
이전까진 Service 레이어에서 그래프를 생성하고 경로를 검색하는 등 모든 로직을 수행했습니다.
하지만 이렇게 할 경우 서비스와 도메인 간의 책임 분리가 모호해지는 문제가 있었습니다.
따라서, 경로와 관련된 로직을 처리하기 위해 `SectionGraph`라는 도메인 객체를 만들었고 `Sections`와 추상화하려 했지만 둘의 역할이 달라 공통된 책임 없어 결국 `Sections`와 `SectionGraph`라는 이름만 봐서는 구분하기 힘든 모호한 두 객체가 만들어 졌습니다😭
이 부분에 대해서는 좀 더 고민해 보도록 하겠습니다,,

2023-05-21 05:42 UTC, Hyeonjae-K commented on src/main/java/subway/domain/section/Sections.java
> +    }
헉...현재 Sections에 대해 변경할 수 있는 로직인 `add()`와 `remove()` 모두 새로운 객체를 생성하여 반환하고 정렬을 보장하는 메서드이므로 깨질 수 없다고 생각했는데 `getValues()`가 리스트를 그대로 반환하므로 변경할 수 있겠군요!!

`getValues()` 메서드를 방어적으로 복사한다면 일단은 정렬이 보장될 것 같습니다.
Section 객체는 상태를 변경할 수 있는 메서드가 없으므로 깊은 복사까진 안해도 될 것 같아요.

2023-05-21 05:58 UTC, Hyeonjae-K commented on build.gradle
> +    // https://mvnrepository.com/artifact/org.jgrapht/jgrapht-core
위와 같은 출처 url을  남겨두는 경우는 없는지 궁금합니다.
잘 알려진 라이브러리의 경우 굳이 출처 url을 남길 필요가 없어 보이지만
위와 같이 비교적 잘 알려지지 않은 라이브러리의 출처 url을 남길 경우 프로젝트를 처음 보는 사람이 라이센스나 마지막 업데이트 등 사용중인 라이브러리에 대한 신뢰성을 빠르게 확인할 수 있다는 장점이 있을 수도 있다고 생각되어 남겨두었습니다😀

2023-05-22 11:07 UTC, hyeonjerry commented on src/main/java/subway/persistence/repository/SectionRepository.java
> +        );
저도 `SectionGraph`를 생성하는 과정에서 내부 필드가 너무 많이 노출된다고 생각합니다😭
이를 해결하기 위해 도메인에서 엔티티를 알고 생성자에서 엔티티만 받아 생성하는 것도 생각해 봤지만 비즈니스 로직에서 모델을 알게 하고 싶지 않았고 `SectionEntity`  뿐만 아니라 `StationEntity`도 함께 알아야 해서 차선으로  선택한 방법이었습니다.
코다는 위와  같은 상황에서 어떻게 하셨을 것 같나요?

2023-05-22 11:51 UTC, Hyeonjae-K commented on src/main/java/subway/ui/response/LineResponse.java
>      public static LineResponse from(final Line line) {
결국 도메인을  보호하여 표현하기 위해 Response 객체로 변환하여 반환하는 것이므로 생성을 위해서는 알아도 된다고 생각합니다.
또한, (여기까지 의도한 것은 아니지만) 도메인 객체가 불변이므로 실수에 의해 영향을 받을 일이 없어 이번 경우에는 안심하고 사용해도 되지 않을까요?

2023-05-22 12:41 UTC, Hyeonjae-K commented
코다 안녕하세요~
피드백 반영하면서 생긴 추가적인 궁금증 질문 드립니다.

위에서 말씀해 주신 ui 패키지와 service 간의 순환참조를 막기 위하여 application 패키지에 dto 패키지를 추가하여 service에서는 dto 객체만 주고받도록 함으로써 의존성을 끊으려 했습니다.
하지만 이렇게 할 경우 request와 response의 형식이 달라 하나의  dto로 해결이  불가능하며 제 2의 request/response 객체를 만드는 일이라  느껴져 request/response를 application 패키지로 옮기고 dto처럼 사용하도록 했습니다.
코다는 dto를 만드는 것에 대하여 어떻게 생각하나요? 지금은 제 2의 request/response를 만드는 것 같아도 유지보수를 위해 추가하는게 좋아보이나요?

2023-05-23 17:22 UTC, yjksw approved these changes
안녕하세요 제리 🙇‍♀️ 코다 입니다 ! 

리뷰 적용해주신 것 잘 확인했어요 ~! 
고민해주신 부분에 대한 답변도 리뷰에 추가해두었습니다. 

잘 해주셔서 머지하고 미션 마무리하면 될 것 같아요. 
앞으로 남은 교육도 화이팅 입니다 😊

2023-05-23 17:22 UTC, yjksw commented on build.gradle
> +    // https://mvnrepository.com/artifact/org.jgrapht/jgrapht-core
아하 그러셨군요 ! ㅎㅎ
그런 의도라면 현업에서도 종종 주석을 남기긴 해요. 제리의 의도가 있다면 남겨두어도 좋을 것 같네요

2023-05-23 17:22 UTC, yjksw commented on src/main/java/subway/persistence/repository/PathRepository.java
> +        );
[이 코멘트](https://github.com/woowacourse/jwp-subway-path/pull/154#discussion_r1200359837)에 답변을 여기에 남깁니다 ㅎㅎ 

제리가 말씀하신 부분 이해가 잘 갑니다 ! 
저도 도메인에서 entity를 인자로 받으면 그것이 더 큰 문제일 것 같아요 ! 왜냐하면 persistence의 변경 영향범위에 domain이 포함되기 때문이에요.

코멘트를 남길 당시, 매핑하는 방식에 관련해서 이야기했기보다, 웹 계층에 대한 이야기를 하고 싶었어요.
repository는 완전 DB 종속도 아니고, DB의 책임을 어느 정도 지면서 비즈니스의 니즈에 적합하게 구현된 역할인 것 같은데요, 
repository의 DIP에 대해서 공부해보면 도움이 될 듯 해요 ㅎㅎ repository가 persistence가 아닌 domian 레이어에 속하면 이 고민도 어느정도 해결이 될 것 같네요

2023-05-23 17:22 UTC, yjksw commented on src/main/java/subway/application/response/LineResponse.java
>      public static LineResponse from(final Line line) {
[이 코멘트](https://github.com/woowacourse/jwp-subway-path/pull/154#discussion_r1200408356) 에 대한 답변입니다 !

아하 제리가 말씀주신 것처럼 이 부분이 지금 큰 문제는 아닙니다 ㅎㅎ 
다만 인자로 넘기는 객체도 의존객체로 보고, ui가 도메인을 알고 있다고 여겨 좀 엄격하게 제한하는 경우도 있어서 말씀드려보았어요.
지금은 위치가 application으로 변경되어서 더더욱 문제가 없겠군요

2023-05-23 17:22 UTC, yjksw commented on src/main/java/subway/application/request/StationRequest.java
> +package subway.application.request;
이 부분이 코멘트에서 말씀주신 순환참조 해결을 위해서 패키지 위치를 리팩토링 한 부분이군요 !

제리가 하신 방법도 좋은 방법이라고 생각합니다 ㅎㅎ
실제로 제리가 말씀해주신 것처럼 클래스가 많아지고 매핑 비용이 드는 것을 줄이기 위해 request, reponse를 application 레이어에 위치시켜서 구현하는 경우도 많은 것 같아요. 
물론 팀 마다 다르겠지만, 엄격하게 레이어별 dto를 분리해두고 완전매핑전략을 가져가기도 합니다. 

저는 지금 이대로 잘 구현해주신 것 같아요 !

2023-05-23 17:23 UTC, merged