[2단계 - 경로 조회 기능] 썬샷(오진택) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #159
Opened 2023-05-19 18:26 UTC by Ohjintaek

안녕하세요 코일!! 2단계 리뷰도 잘 부탁드립니다.

우선 1단계 때 제 표현이 불명확해서 제대로 전달이 되지 않았던 질문에 대해서 다시 한 번 질문드리면서 시작하겠습니다.
1. Repository의 존재는 persistent layer의 데이터를 이용하여 domain을 만들어주는 것으로 알고 있습니다. Service는 Domain이 필요하다면 Repository에게 그 역할을 맡기면 되기 때문에 굳이 Dao에까지 접근할 필요가 없게 됩니다. 하지만 Dao에서 반환되는 자료형이 Domain과 거의 흡사하다면 굳이 Repository를 통해야 하는 의문이 생겼습니다. 이번 미션을 구현할 때를 예로 들자면 DB의 `Line`과 Domain의 `Line`은 내부 필드나 기능이 상당히 다릅니다. 이런 경우에는 Repository 계층을 만드는 것에 대해 충분히 납득이 됩니다. 하지만 Station이나 Section의 경우 DB에서의 구조나 Domain에서의 구조가 거의 동일해 Service 계층에서 간단히 도메인을 만들어낼 수 있습니다. 혹은 만약 `Entity`를 도메인과 같이 활용하려고 한다면 Dao에서 직접 도메인을 반환해도 괜찮구요. 그렇다면 이런 상황에서 어떤 Service는 Repository를 통해서 도메인을 얻고, 어떤 Service는 Dao를 통해서 도메인을 얻게 되는데 이런 방식이 자주 사용되나요? 아니면 Repository를 사용할 것이라면 모든 도메인의 경우에 대해 일관적으로 적용하나요? 이 문제는 사실 2단계 진행하면서도 가장 고민을 많이 해 보고 시간을 쏟은 부분이었습니다. 일단 Repository는 도입하지 않은 채로 도메인 계층에서 복잡한 내부 구조를 가지게 된 `Line`만 Dao에서 `LineEntity`를 반환해주는 것으로 구현을 해 놨는데요. 이런 상황에 대한 코일의 생각이 궁금합니다.

2. Service 단위 테스트를 작성하면서 의문점이 생겼습니다. `LineService 내부의 `updateLine`, `deleteLine`, `registerStation`, `deleteStation` 등의 메서드들이 반환값도 없고 Service 내부의 상태를 바꾸지도 않기 때문에 어떻게 테스트를 작성해야 할지 감이 잡히지 않았습니다. 결국 DB에 담긴 정보를 바꾸기 위한 메서드들인데 해당 메서드들을 테스트하기 위해서는 접근된 DB를 살펴봐야 하는 걸까요? 아니면 단순히 내부 메서드들이 호출되는지만 확인하는 것으로 검증이 의미가 있는 걸까요?

어떻게든 구현만 하라고 하면 훨씬 수월한 미션인 것 같은데 웹 프로그래밍 구조에 대해서 많은 고민을 하게 되니 더 어렵게 느껴졌습니다. 많은 고민을 했음에도 여전히 괜찮다는 생각은 들지가 않네요ㅎㅎ
어떤 피드백이든 달게 받겠습니다~!! 다시 한 번 감사드립니다!!

2023-05-20 16:44 UTC, iphwade requested changes
안녕하세요 썬샷-!
리뷰를 맡은 코일입니다-!
지하철은 도메인이 어려우셨을텐데 잘 구현해주셨습니다-!
리뷰를 몇가지 남겼는데요-! 한번 읽어보시고 반영 or 의견 남겨주시면 다음 리뷰 때 같이 얘기해보면 좋을 것 같아요-!
수고 많으셨습니다-! :)

2023-05-20 16:44 UTC, iphwade commented on src/main/java/subway/ui/LineController.java
>      @DeleteMapping("/{id}/station")
RESTful API 를 지향하신 걸까요?
그렇다면 url을 복수형으로 설정하는 것은 어떨까요?

2023-05-20 16:44 UTC, iphwade commented on src/main/java/subway/domain/Line.java
> +    public Line(final String name, final String color) {
LineEntity를 매개변수로 받는 생성자에 대해서 고민해보셨나요?

2023-05-20 16:44 UTC, iphwade commented on src/main/java/subway/dto/LineResponse.java
> +    public static LineResponse from(final Line line) {
👍 
저는 DTO에서 생성 로직을 가져가는 걸 좋아하는데요-!
썬샷께서도 이런 방식을 선택하게된 이유가 무엇인가요?

2023-05-20 16:44 UTC, iphwade commented on src/main/java/subway/domain/Line.java
>  public class Line {
LineEntity와 Line을 분리하신 이유는 무엇인가요?

2023-05-20 16:44 UTC, iphwade commented on src/main/java/subway/application/LineService.java
> +    public LineResponse saveLine(final LineRequest request) {
Service에 LineRequest와 같이 뷰와 연관지어지는 DTO가 전달되고 있네요-!
이 방식은 어떤 단점이 있을까요-?

2023-05-20 16:44 UTC, iphwade commented on src/main/java/subway/application/LineService.java
> +                .map(line -> LineResponse.from(configureLine(line.getId())))
findAll을 통해 조회한 Line을 configureLine에서 다시 DB를 통해 조회하고 있네요-! 
이런 구조가 나오게된 이유는 무엇인가요?

2023-05-20 16:44 UTC, iphwade commented on src/main/java/subway/application/LineService.java
> +                )));
가독성을 위해 Sections에 전달되는 매개변수를 분리하는 것이 좋아보입니다-!

2023-05-20 16:44 UTC, iphwade commented on src/main/java/subway/application/LineService.java
> +                )));
`stationDao.findById(section.getUpperStation()` 는 두번 조회되고 있네요-!
더 효율적인 방법에 대해 고민해보면 좋아보입니다-!

2023-05-20 16:44 UTC, iphwade commented on src/main/resources/schema.sql
>      distance int not null,
애플리케이션 단에서 거리 정보에 대한 검증이 존재하니, DB 단에서도 양수만 받을 수 있도록 유효성을 부여해보는 것은 어떨까요?

2023-05-20 16:44 UTC, iphwade commented on src/main/resources/schema.sql
> +    lower_station bigint not null,
👍

2023-05-20 16:44 UTC, iphwade commented on src/main/java/subway/domain/Sections.java
> +    }
어떤 과정을 거쳐 어떤식으로 소팅이 되는지에 대해 가독성을 좀 더 신경 쓸 수 있는 방법들이 있어보입니다.
조건에 이름을 부여하는 등 여러 방식으로 리팩토링해보면 어떨까요?

2023-05-20 16:44 UTC, iphwade commented on src/main/java/subway/domain/Sections.java
> +    private final Map<Station, Section> sections;
Sections의 키는 어떤 것을 의미하는지 밸류는 어떤 것을 의미하는지에 대한 설명이 부족합니다.
키도 밸류도 모두 래핑이 가능해보이네요-!

2023-05-20 16:44 UTC, iphwade commented on src/main/java/subway/domain/Sections.java
> +    public List<Station> getSortedStations() {
마찬가지로 어떤 식으로 소팅이 된건지에 대한 정보를 해당 코드만으로는 이해하기가 어렵네요-!

2023-05-20 16:44 UTC, iphwade commented on src/main/java/subway/domain/Sections.java
> +        return sortedSections;
저는 한 메서드로 생산해낼 수 있는 경우에는 메서드화를 지향하는 편입니다.
그 이유는 코드 안에서 여러 표현 방식을 가져갈 수 있기 때문인데요-!
썬샷은 어떻게 생각하시나요?

2023-05-20 16:44 UTC, iphwade commented on src/main/java/subway/application/LineService.java
> +        List<Station> stations = sections.getSortedStations();
소팅된 스테이션을 가져왔는데 변수명에 표현되어 있지 않네요-! 
썬샷께서 코드를 잘 짜주셔서 메서드당 코드량이 적어 문제가 적지만 
현업을 하다보면 레거시를 만나기도 하고 레거시 속 메서드 코드는 굉장히 깁니다.
상세한 변수명은 긴 코드 속에서 의미를 부여하기 좋습니다.

2023-05-20 16:44 UTC, iphwade commented on src/main/java/subway/domain/Line.java
> +    private final List<Station> stations;
어떤 상황에서는 LinkedList로 어떤 상황에서는 ArrayList로 생성하고 계시네요-!
어떤 상황에 이런 차이가 부여되는 걸까요?

2023-05-20 16:44 UTC, iphwade commented on src/main/java/subway/application/LineService.java
>          lineDao.deleteById(id);
cascade 정책을 활용하는 방법도 존재하는데 애플리케이션에서 구현한 이유가 궁금합니다-!

2023-05-20 16:44 UTC, iphwade commented on src/main/java/subway/ui/LineController.java
>          return ResponseEntity.noContent().build();
id에 해당하는 line이 없는 경우에는 어떻게 동작하네요-?

2023-05-20 16:44 UTC, iphwade commented on src/main/java/subway/domain/Line.java
> +            throw new IllegalArgumentException("역이 존재하는 노선에 두 역을 한 번에 등록할 수 없습니다.");
조건문을 없앨 수 있는 방법이 있지않을까요-?

2023-05-20 16:44 UTC, iphwade commented on src/main/java/subway/domain/Line.java
> +            throw new IllegalArgumentException("역이 존재하는 노선에 두 역을 한 번에 등록할 수 없습니다.");
조건문의 순서에 대해 고민해보셨나요-? 
이 경우가 아니더라도 어떤 조건문이 가장 위에 있고 hit될 확률을 높일 수 있을까 생각해보면 좋을 것 같습니다-!

2023-05-20 16:44 UTC, iphwade commented on src/main/java/subway/application/LineService.java
> +        sectionDao.insertAll(SectionDto.makeList(line.getId(), line.getSections()));
모든 secion을 지우고 다시 insert하네요-!
더 나은 방법은 없을까요-?

2023-05-20 16:44 UTC, iphwade commented on src/main/java/subway/dto/PathRequest.java
> +    private final Long to;
from, to가 의미하는 것은 무엇인가요-?
Long 타입으로 이게 아이디라는 것을 인지할 수 있을까요-?

2023-05-20 16:44 UTC, iphwade commented on src/main/java/subway/application/SubwayService.java
> +        List<Section> allSection = sectionDao.findAll()
모든 스테이션과 모든 section을 불러오고 있네요-!
더 적은 스테이션과 더 적은 section로 처리할 수는 없을까요-?

2023-05-20 16:44 UTC, iphwade commented on src/main/java/subway/application/SubwayService.java
> +                        stationDao.findById(sectionEntity.getLowerStation()),
위에서 가져온 allStation의 List에서 스테이션을 가져오는 것과 디비에 커넥션을 맺고 디비 서버에 스테이션을 조회하는 것 둘 중 어느 것이 더 적은 리소스일까요?

2023-05-20 16:44 UTC, iphwade commented on src/main/java/subway/application/SubwayService.java
> +        List<SectionResponse> sectionResponses = sections.getSortedSections()
이 메서드는 SectionResponse에 존재하는 것은 어떨까요?

2023-05-20 16:44 UTC, iphwade commented on src/main/java/subway/dto/PathResponse.java
> +    private final int fare;
int 로 설정하신 이유는 null이 아닌 경우만 존재하기 때문일까요-?

2023-05-20 16:53 UTC, iphwade commented
`첫번째 질문`
우선 제가 경험한 현업에서는 Repository 패턴을 사용하였습니다-!
또, MSA라는 단어가 생소할 수 있겠지만 MSA로 잘 분리된 모듈은 (멀티 모듈이 될 수도 있겠네요) 생각보다 엔티티와 도메인이 거의 같은 클래스로 표현되곤합니다. 또, ORM에 대해서도 많이 들어보셨을텐데 이런 경우도 마찬가지로 Repository에서 도메인 객체로 치환되는 패턴을 자주 사용하곤합니다.
즉, 자연스럽게 영속 계층, 도메인 계층에서 사용되는 객체를 구분짓지 않게되는데요-! 
지금처럼 레이어가 잘 구분되어 있고 도메인이 직관적이라면 굳이 DAO와 Repository를 나눌 필요는 없다고 생각합니다-! 

`두번째 질문`
 아마 알고계시겠지만 여러 테스트의 종류가 있습니다. 말씀하시는대로 메서드의 실행으로 테스트하는 방법도 있구요-! 어떤 개념을 테스트하고 싶어지느냐에 따라 달라집니다-! DB에 접근하는 것도 메서드의 호출만을 테스트 하는 것 모두 테스트의 의미가 있습니다. 그 이유는 앞으로의 코드가 어떻게 변화될지 모르기때문인데요-! 오랜 기간 개발된 레거시, 다른 사람이 짠 코드 등에 대해 변화를 반영하고 변화에 대한 영향을 인지하기 위해 충분히 의미가 있어보입니다-!

2023-05-23 12:36 UTC, Ohjintaek commented on src/main/java/subway/ui/LineController.java
>      @DeleteMapping("/{id}/station")
그러네요~
url에서 요청하는 것이 노선에 포함된 station의 컬렉션이므로 복수형으로 설정해주는 것이 더 좋은 거 같습니다

2023-05-23 12:56 UTC, Ohjintaek commented on src/main/java/subway/domain/Line.java
> +    public Line(final String name, final String color) {
생각은 해 보았지만 현재 코드에서 DB(영속성 레이어)에서의 Line과 도메인에서의 Line이 다릅니다. 새로운 Line을 등록하거나 등록된 노선이 없는 경우 LineEntity만으로도 도메인 Line을 구축할 수 있지만, 노선이 등록된 Line의 경우 LineEntity만으로 Line 도메인을 만들 수 없습니다.
  어떤 Line을 만들 때는 LineEntity만으로, 어떤 Line을 만들 때는 다른 DB까지 끌고와야 하는 상황에서 LineEntity를 받는 생성자가 있다는 건 LineEntity만으로 Line을 만들 수 있다는 인상을 주는 것 같아 추가해주지 않았습니다.

2023-05-23 13:00 UTC, Ohjintaek commented on src/main/java/subway/dto/LineResponse.java
> +    public static LineResponse from(final Line line) {
저는 별다른 이유 없이 도메인 혹은 서비스 내부에 DTO를 생성하는 로직을 없애는 것만으로도 좀 더 깔끔한 느낌이 되는 거 같아 사용하게 되었습니다.

2023-05-23 13:01 UTC, Ohjintaek commented on src/main/java/subway/domain/Line.java
>  public class Line {
Section이나 Station과 달리 현재 도메인 Line이 DB의 Line과 비교해 가지는 기능이 엄청 커졌다고 생각합니다. 무엇보다 영속성 계층의 정보만으로 도메인 Line을 만드는 것이 불가능한데 `LineDao`에서 Line을 반환하는 것이 이상하다고 생각해서 따로 LineEntity를 만들어주게 되었습니다

2023-05-24 11:51 UTC, Ohjintaek commented on src/main/java/subway/application/LineService.java
> +    public LineResponse saveLine(final LineRequest request) {
프로그램의 구조를 계층으로 나누는 구조는 추후의 변경에 대한 영향을 인접한 계층까지만 전달되도록 하기 위해서도 있다고 생각합니다. 하지만 뷰와 연관지어지는 DTO가 Service까지 전달되는 건 컨트롤러까지 전달되어야 할 변경에 대한 영향이 불필요하게 Service까지 전달될 수 있다는 단점이 있다고 생각합니다

2023-05-24 13:47 UTC, Ohjintaek commented on src/main/java/subway/application/LineService.java
> +                .map(line -> LineResponse.from(configureLine(line.getId())))
LineService 내에서 DB의 정보를 이용해 도메인 Line을 만드는 메서드인 `configureLine`이 id를 파라미터로 받도록 만든 것이 불필요하게 Dao로의 접근을 늘리고 있었네요. configureLine 메서드를 수정해서 한 개의 도메인 Line을 만들 때는 lineDao에 한 번만 접근하도록 바꿔주었습니다

2023-05-24 17:01 UTC, Ohjintaek commented on src/main/java/subway/application/LineService.java
> +                )));
좀 더 고민했으면 충분히 메서드 분리해야 할 것이라고 생각해봤을 부분이었네요...
중복해서 Dao에 접근하는 부분 역시 개선해주었습니다!!

2023-05-25 01:53 UTC, Ohjintaek commented on src/main/resources/schema.sql
>      distance int not null,
이전에도 sql에 unsigned를 붙여주려고 했었는데 syntax error가 나서 실패한 적이 있었습니다. 이번에 다시 한 번 찾아보니 아무래도 h2 데이터베이스에서 unsigned를 지원하지 않는 거 같아 constraint를 사용하는 제약조건으로 추가해주었습니다.

2023-05-25 07:26 UTC, Ohjintaek commented on src/main/java/subway/domain/Sections.java
> +    }
`Sections`는 처음 생성될 때 출발역부터 도착역까지의 Station과 Section이 담긴 Map 자료구조를 가집니다.
따라서 정렬되었다는 의미를 가진 sort보다는 순서대로 배치된 Station과 Section을 얻는다는 의미가 되도록 `soredt`를 `ordered`로 바꿔주었고, 두 메서드의 알고리즘을 거의 비슷하게 작성해서 이해가 용이하도록 했습니다. 또한 정렬하는 방식에 첫 시작 역을 찾는 것이 매우 중요하므로 `findStartStation`이라는 메서드를 분리시켜주어 어떻게 시작하게 되는지 좀 더 잘 보여주도록 했습니다.

다만 코일이 말씀하신 조건에 이름을 부여한다는 뜻이 잘 이해가 되지 않는데 혹시 어떤 방식을 생각하셨는지 알려주시면 감사하겠습니다!!

2023-05-25 07:27 UTC, Ohjintaek commented on src/main/java/subway/domain/Sections.java
> +    public List<Station> getSortedStations() {
위의 `getSortedSections`와 동일한 방식으로 리팩터링해주었습니다

2023-05-25 07:39 UTC, Ohjintaek commented on src/main/java/subway/domain/Sections.java
> +    private final Map<Station, Section> sections;
제 생각으로는 Sections 내부의 한 필드를 위해 이미 도메인 객체인 Station과 Section을 다시 래핑해주는 것이 불필요하다고 생각합니다. 단순히 래핑해서 클래스 이름을 바꾸더라도 그 클래스가 무엇인지 파악하기 위한 추가적인 리소스가 들어갈 수도 있어서요.

이와 관련해 추가적인 방법을 생각해본 것이 주석의 사용입니다. 지금까지 주석은 정말로 필요한 상황에서만 사용하는 것을 추천해서 아직까지 사용한 적은 없습니다. 하지만 약간의 주석 사용으로 코드의 이해가 쉬워진다면 사용할 수 있을 거 같은데 코일의 생각은 어떠신가요?

2023-05-25 08:10 UTC, Ohjintaek commented on src/main/java/subway/domain/Sections.java
> +        return sortedSections;
죄송하지만 제가 이 코멘트에 대해서 제대로 이해를 못 하겠어서요...
코드 안에서 여러 표현 방식을 가져갈 수 있다는 것이 무슨 뜻인지도 궁금합니다!!
일단 `start`를 찾는 부분은 메서드 분리를 해 주었습니다

2023-05-25 08:13 UTC, Ohjintaek commented on src/main/java/subway/application/LineService.java
> +        List<Station> stations = sections.getSortedStations();
오른쪽에 있는 메서드명으로도 추론이 가능하다고 생각해서 중복해서 적어주지 않았던 부분입니다.
하지만 나중에 해당 메서드로 추출된 변수만 따로 쓰이는 경우에는 혼동될 여지가 있을 수 있으니 변수명도 잘 적어주는 게 좋겠네요. 코멘트 감사드립니다!!

2023-05-25 09:01 UTC, Ohjintaek commented on src/main/java/subway/domain/Line.java
> +    private final List<Station> stations;
원래 처음 설계 때 line 도메인 내부에서 해당 라인의 노선 및 역을 전부 관리했었습니다. 그 때 노선을 추가 및 제거할 때 LinkedList를 사용하는 것이 유리하다고 생각해서 LinkedList를 사용했던 흔적이 남아 있네요.

Section과 Sections를 추가한 뒤에는 굳이 LinkedList의 특성을 활용할 필요가 없어져서 제거해 주려고 했는데 `lineService`에 하나 남아있어서 제거해주었습니다

2023-05-25 10:47 UTC, Ohjintaek commented on src/main/java/subway/application/LineService.java
>          lineDao.deleteById(id);
아 단순히 cascade라는 걸 몰라서 사용하지 않았습니다!!
cascade에 대강 학습하고 나서 적용한 뒤 `deleteAllByLineId`를 제거해주었는데 잘 작동하는 것을 확인했습니다. cascade에 대해서는 조금 더 학습을 해야겠네요

2023-05-25 12:20 UTC, Ohjintaek commented on src/main/java/subway/ui/LineController.java
>          return ResponseEntity.noContent().build();
DB에 존재하지 않는 id로 조회하거나, 수정, 삭제하는 경우 query문에서는 예외가 발생하지 않아 클라이언트 단에서는 내가 한 요청이 어떻게 되었는지 알기 힘들다는 문제가 있는 거 같습니다. 내부적으로 `DataNotFoundException`이라는 예외를 발생시켜 존재하지 않는 데이터라는 것을 알려주도록 했습니다

2023-05-25 12:39 UTC, Ohjintaek commented on src/main/java/subway/dto/PathRequest.java
> +    private final Long to;
어떤 데이터를 원하는지 조금 더 명확히 알 수 있도록 네이밍에 `Station`을 추가해주었습니다.

2023-05-26 03:56 UTC, Ohjintaek commented on src/main/java/subway/application/SubwayService.java
> +                        stationDao.findById(sectionEntity.getLowerStation()),
db에 접근하는 것 자체가 리소스가 훨씬 적게 들겠네요
이전의 코멘트에서도 그렇고 db에 접근하지 않아도 되는 경우에 재접근 하는 경우를 최대한 지양해야한다는 것을 배웠습니다.

2023-05-26 04:19 UTC, Ohjintaek commented on src/main/java/subway/application/SubwayService.java
> +        List<SectionResponse> sectionResponses = sections.getSortedSections()
정적 팩토리 메서드를 만드는 것과 동일하게 만들어줄 수 있다고 생각합니다. 그런데 제가 전에 도메인에 자기 자신의 리스트를 만드는 정적 팩토리 메서드를 만든 적이 있는데 그 경우는 별로 추천하지 않는 것 같더라구요.
이건 프로그래머별로 취향 차이일까요? 아니면 DTO와 Domain의 차이 때문일까요?

2023-05-29 15:51 UTC, Ohjintaek commented on src/main/java/subway/dto/PathResponse.java
> +    private final int fare;
현재 wholeDistance의 경우 사용할 때 거리의 값이 양수인지를 검증하는 Distance 도메인을 거친 뒤 넣어주기 때문에 null이 아닌 경우만 존재합니다. fare 역시 현재 0 이상의 거리가 들어온다면 null이 존재하지 않도록 FareCalculator에서 검증하고 있어 null이 반환될 경우가 없다고 생각해서 기본형을 사용했습니다

2023-05-29 17:20 UTC, Ohjintaek commented on src/main/java/subway/application/LineService.java
> +        sectionDao.insertAll(SectionDto.makeList(line.getId(), line.getSections()));
새로 등록한 역과 연결된 section은 추가해주고 등록 때문에 수정된 section을 update하는 것으로 할 수 있습니다. 그런데 하다 보니 어느 역이 새로 등록되는 역인지에 따라 메서드 내부에서 너무 분기가 많아져서 다시 revert했는데요. 분기를 나누는 부분이 `Line` 도메인에 존재해서 `LineService` 내부에서도 똑같은 분기를 나누는 것이 별로인 것으로 생각됐습니다. `Line` 도메인 내부에 역을 넣어주면 다음 역과 다음 역까지의 거리를 얻을 수 있는 메서드를 넣어주면 좀 더 쉽게 처리할 수 있을 것 같은데, 도메인 내부에 DB의 수정을 위한 메서드가 존재해도 되는지도 의문이 듭니다.

2023-05-29 17:29 UTC, Ohjintaek commented on src/main/java/subway/application/SubwayService.java
> +        List<Section> allSection = sectionDao.findAll()
이 부분은 고민해봐도 좋은 방법이 떠오르지를 않습니다.
물론 출발역과 도착역이 있을 때 절대 거리상으로 빨라질 수 없는 노선에 대한 정보는 가져오지 않는 것이 좋지만 전부 가져와서 그래프로 만들기 전에는 그게 어딘지 알기가 힘듭니다.

예를 들어 현재 경로와 관련된 제 테스트 코드에는 역들을 가지는 4개의 노선이 있습니다. 그 중 1호선은 역들 간의 사이를 100으로 나머지 노선들은 5로 설정해두었습니다. 그래서 1호선의 양 끝단에 있는 역 사이의 최단 경로를 탐색했을 때 2, 3, 4호선을 경유하는 경로가 나오게 됩니다. 이런 경우까지 처리 가능한 방법이 있나요?

2023-05-31 13:18 UTC, iphwade commented on src/main/resources/schema.sql
>      distance int not null,
아 요건 제가 h2에 대해서 인지하지 못하고 드린 코멘트였네요 ㅠ_ㅠ

2023-05-31 13:20 UTC, iphwade commented on src/main/java/subway/domain/Sections.java
> +    }
제가 생각한 의미는 변수 명에서 sortedSections면 어떤 것을 기준으로 소팅되었는지가 분리되어 있으면 좋겠다는 생각을 했습니다-! 
다만 위 상황에서 100프로 일치하지는 않을 수 있겠네요!

2023-05-31 13:23 UTC, iphwade commented on src/main/java/subway/domain/Sections.java
> +    private final Map<Station, Section> sections;
썬샷께서 말씀하셨듯 가장 좋은 방법은 주석을 사용하지 않는 것입니다.
주석은 요구사항의 변경에 필수적으로 변경되지 않으므로 보통은 사용하지 않는데요-!
말씀하셨듯 어쩔수없는 경우들이 생기곤 합니다-!

위 경우는 썬샷께서 말씀하신 바가 근거가 있어보여 충분히 주석으로 작성할 수 있어보입니다-! 
(현업에서도 어쩔수없이 사용되곤 합니다.)

2023-05-31 13:25 UTC, iphwade commented on src/main/java/subway/domain/Sections.java
> +        return sortedSections;
블락으로 묶은 부분은 충분히 하나의 메서드로 분리할 수 있는 부분으로 보입니다-!
메서드로 분리하면 메서드명, 매개변수명 등을 사용하여 코드의 의도를 표현할 수 있는 방식과 힌트들을 노출시켜줄 수 있다는 의미로 리뷰했습니다-! :)

2023-05-31 13:30 UTC, iphwade commented on src/main/java/subway/application/LineService.java
> +        sectionDao.insertAll(SectionDto.makeList(line.getId(), line.getSections()));
어디까지가 도메인 로직이라고 바라보느냐에 따라 달라질 수 있는 문제로 보이네요-!
(저는 Service단도 도메인이라고 생각하고 리뷰하고 있습니다-!)

Line 도메인 내부에 메서드를 작성하지 않고 새로운 도메인 클래스를 만들어보는 것은 어떨까요-?
혹시나 어렵다면 분기가 많더라도 Service에서 처리하는 것이 좋아보입니다-!

2023-05-31 13:33 UTC, iphwade commented on src/main/java/subway/application/SubwayService.java
> +        List<Section> allSection = sectionDao.findAll()
allStation을 통해 allSection의 필드로 존재하는 역들을 가져올 수 있어보이는데 StationDao를 통해 다시 Station을 조회하고 있어 드린 코멘트입니다-! :)

2023-05-31 13:34 UTC, iphwade commented on src/main/java/subway/application/SubwayService.java
> +                        stationDao.findById(sectionEntity.getLowerStation()),
@Ohjintaek 요건 잘못말씀하신 걸까요-?
DB에 접근하는 것이 리소스가 더 든다고 말씀하신건가요-?

2023-05-31 13:36 UTC, iphwade commented on src/main/java/subway/application/SubwayService.java
> +        List<SectionResponse> sectionResponses = sections.getSortedSections()
아 요건 취향차이로 나눠지는 것 같아요-!
저는 DTO에 충분히 존재해도 된다고 생각합니다-!

또, 말씀하신대로 DTO와 Domain 의 차이여서 나온 고민이기도 하구요-!
도메인이었으면 당연히 분리하면 좋은 것이나 DTO여서 고민하게 만드는 포인트라고 생각합니다-! :)

2023-05-31 13:45 UTC, iphwade approved these changes
수고하셨습니다-! 썬샷-!
리뷰량이 적지 않아서 기존 미션과 병행하기 쉽지않으셨을텐데 고민한 흔적들도 많이 보이고 심지어 잘 해내셨습니다-! 
이제 마지막 미션에 조금 더 열중하여 유종의 미를 거두시길 바라겠습니다-!

기존 코멘트에 답글과 몇가지 간단한 코멘트 작성하였습니다-!
크게 변경이 필요하지 않아보이니 요런 방법도 있겠구나(?) 정도로 넘어가셔도 괜찮을 것 같아요!
혹시 코멘트에 대해 이해가 가지 않으시면 DM 주세요-!

수고하셨습니다-! :)

2023-05-31 13:45 UTC, iphwade commented on src/main/java/subway/application/LineService.java
> +            Station lowerStation = stationDao.findById(sectionEntity.getLowerStation());
요건 사실 별건 아닌데 이런 상황에서 성능 개선을 할 수 있는 방법들이 있을 수 있겠네요-!
지금은 퓨어한 JDBC 형태를 사용하고 있으니 커넥션을 프로그래머가 자체적으로 최소화를 하면 좋아보입니다-! 
findByIds 와 같은 메서드로 여러 Id를 한번에 가져와 보는 것과 같은 방법도 있겠네요-!

2023-05-31 13:45 UTC, iphwade commented on src/main/java/subway/exception/DataNotFoundException.java
> +public class DataNotFoundException extends RuntimeException {
@ResponseStatus와 같은 기능도 있습니다-!

2023-05-31 13:45 UTC, merged