[2단계 - 경로 조회 기능] 오도(문민혁) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #165
Opened 2023-05-20 09:09 UTC by odo27

안녕하세요 웨지~ 😊
2단계 리뷰도 잘 부탁드립니다!!

2023-05-21 10:25 UTC, sihyung92 requested changes
안녕하세요 오도~~ 웨지입니다
2단계도 잘 구현해주셨네요 ㅎㅎ
몇 가지 질문과 리뷰를 드렸는데요, 확인해주시고 다시 요청주세용~!

2023-05-21 10:25 UTC, sihyung92 commented on src/main/java/subway/controller/LineController.java
> +    public ResponseEntity<LineResponseWithSections> findLineWithSections(@PathVariable final Long id) {
url이 section의 id를 넘겨야 할 것처럼 느껴지네요

2023-05-21 10:25 UTC, sihyung92 commented on src/main/java/subway/controller/LineController.java
> +    }
클라이언트 입장에서 이 두개의 API를 별도로 필요로 할지 모르겠어요. 어떤 유즈케이스가 있을까요?

2023-05-21 10:25 UTC, sihyung92 commented on src/main/java/subway/controller/PathController.java
> +    @GetMapping("/{departureId}/{arrivalId}")
paths/{시작}/{도착} 이 URL의 규칙에서 헷갈릴 수도 있다고 느껴져요. `/`를 상위 카테고리에서 하위 카테고리로 넘어가는 용도로 많이 쓰인다고 생각해서요. 
PathVariable이 아닌 parameter로 넘기는건 어떨까요?

2023-05-21 10:25 UTC, sihyung92 commented on src/main/java/subway/domain/Distance.java
> +    private int value;
final을 포기할 필요는 없었을 것 같아요.

2023-05-21 10:25 UTC, sihyung92 commented on src/main/java/subway/domain/Distance.java
> +    public int subtract(final Distance other) {
getValue가 있으니 해당 객체는 또다른 Distance를 반환하는건 어떨까요? (불변패턴)

2023-05-21 10:25 UTC, sihyung92 commented on src/main/java/subway/domain/SectionMap.java
> +    private final Map<Line, Sections> sectionsByLine;
StationMap, SectionMap, StationGraph 등 Station, Line, Section 관계를 규정짓는 객체가 많은데 도메인을 수정할 때 네이밍과 기능이 중복되는 객체들이 있는거 같습니다. 
Line이 key이고 Sections를 갖는 SectionMap, Station이 key고 Sections가 value인 StationGraph, Line이 key이고 Section이 value인 StationsMap... 

예컨데 Section은 Station들의 집합이기 때문에 StationsMap이 StationGrpah를 대체할 수 있는 등, 다소 도메인 관계가 복잡하다는 생각이 듭니다.

또 StationGraph와 StationMap의 차이는 무엇이며, SectionMap은 어떤 용도인지 객체명만 봐서는 짐작하기가 어렵습니다. 

Line이 Sections를 필드로 가지는 구조로 간다면 SectionMap은 필요없을 듯 한데요, 꼭 이런 방식일 필요는 없지만 도메인이 알기 쉬운 방식으로 구성되었으면 하는 아쉬움이 있습니다.

2023-05-21 10:25 UTC, sihyung92 commented on src/main/java/subway/domain/PathFinder.java
> +        final WeightedMultigraph<Station, DefaultWeightedEdge> graph = new WeightedMultigraph<>(DefaultWeightedEdge.class);
WeightedMultigraph을 따라가다보면 Graph 인터페이스를 만날 수 있는데요, 가급적 추상화를 활용해 확장성을 도모할 수 있습니다.
```suggestion
        final Graph<Station, DefaultWeightedEdge> graph = new WeightedMultigraph<>(DefaultWeightedEdge.class);
```

2023-05-21 10:25 UTC, sihyung92 commented on src/main/java/subway/domain/PathFinder.java
> +    private DijkstraShortestPath<Station, DefaultWeightedEdge> getDijkstraShortestPath() {
직전 리뷰와 마찬가지 리뷰로, ShortestPathAlgorithm 인터페이스를 반환한다면 차후 알고리즘에 있어 확장성을 가져갈 수 있습니다.
```suggestion
    private ShortestPathAlgorithm<Station, DefaultWeightedEdge> getDijkstraShortestPath() {
```

2023-05-21 10:25 UTC, sihyung92 commented on src/main/java/subway/domain/PathFinder.java
> +    public Path findShortestPath(final Station departure, final Station arrival) {
알고리즘을 다른 로직과 격리하고 Path로 추상화해주신 부분 좋네요 ㅎㅎ

2023-05-21 10:25 UTC, sihyung92 commented on src/main/java/subway/domain/SubwayFareCalculator.java
> +        }
FareCalculator라는 인터페이스를 만들었으니 각 distance에 걸맞는 요금제를 적용할 수 있을 것 같아요.
요금제가 추가될때마다 if문을 추가하지 않고 수정하려면 어떤 방식이 있을까요?

2023-05-21 10:25 UTC, sihyung92 commented on src/test/java/subway/domain/StationGraphTest.java
> +    @DisplayName("노선의 역 조회 테스트 1")
어떤 식으로 테스트하는건지 displayName에 맥락을 풍부하게 해주거나 주석을 통해 설명해주었다면 좋았을 것 같아요 ㅎㅎ

2023-05-22 01:19 UTC, odo27 commented on src/main/java/subway/controller/LineController.java
> +    }
원래 기존의 `LineSearchResponse` 는 1단계 요구사항의 노선 조회와 노선 목록 조회에 대한 기능이었습니다 😊
기존의 노선 조회에서는 현실에서의 지하철 노선도를 생각해 1호선에 존재하는 모든 역을 순서대로 (상행종점부터 하행종점까지) 나열해 응답으로 내려주는 기능을 구현했습니다. 현실의 지하철 노선도에서는 A역에서 B역까지의 거리가 얼마인지는 알려주지 않는다고 생각했기 때문에 역들에 대한 정보로만 나열했습니다.

다음으로 웨지가 남겨주신 프론트 개발을 위한 새로운 노선 조회 요구사항이 생겼고 요구사항에 포함된 `역간 거리와 역 간의 관계(앞뒤에 무슨 역이 있는지), 어떤 노선에 속하는지 정보` 등을 포함하기 위해 구간들의 정보를 포함한 응답이 필요하게 되어 위와 같이 2개의 노선 조회 기능을 나누게 되었습니다.

2023-05-22 01:37 UTC, odo27 commented on src/main/java/subway/domain/Distance.java
> +    public int subtract(final Distance other) {
반영했습니다 😊

2023-05-22 01:41 UTC, odo27 commented on src/main/java/subway/domain/PathFinder.java
> +        final WeightedMultigraph<Station, DefaultWeightedEdge> graph = new WeightedMultigraph<>(DefaultWeightedEdge.class);
반영했습니다 😊

2023-05-22 01:41 UTC, odo27 commented on src/main/java/subway/domain/PathFinder.java
> +    private DijkstraShortestPath<Station, DefaultWeightedEdge> getDijkstraShortestPath() {
반영했습니다 😊

2023-05-22 02:13 UTC, odo27 commented on src/main/java/subway/domain/SubwayFareCalculator.java
> +        }
`FareStrategy` 인터페이스를 만들고 각각의 거리별 요금제를 구현체로 만들어두고 `List<FareStrategy>`를 주입받아 리스트 내부를 순회하며 요금제를 찾아 요금을 계산하도록 변경했습니다 😊

2023-05-22 05:45 UTC, odo27 commented on src/main/java/subway/domain/Distance.java
> +    private int value;
반영했습니다 ☺️

2023-05-22 06:14 UTC, odo27 commented on src/main/java/subway/controller/PathController.java
> +    @GetMapping("/{departureId}/{arrivalId}")
`parameter`를 사용해 `/paths?departureId=1&arrivalId=2`로 변경했습니다 😁

2023-05-22 06:31 UTC, odo27 commented on src/test/java/subway/domain/StationGraphTest.java
> +    @DisplayName("노선의 역 조회 테스트 1")
반영했습니다 😁

2023-05-22 06:34 UTC, odo27 commented on src/main/java/subway/controller/LineController.java
> +    public ResponseEntity<LineResponseWithSections> findLineWithSections(@PathVariable final Long id) {
`lineId`로 변수명을 변경했습니다 😆

2023-05-22 07:30 UTC, odo27 commented on src/main/java/subway/domain/SectionMap.java
> +    private final Map<Line, Sections> sectionsByLine;
`SubwaySectionMap`, `SubwayStationMap`으로 클래스명을 변경했습니다 😄
또한 패키지를 분리함으로써 `SectionMap`, `StationMap`은 지하철 노선도임을 표현했고 `StationGraph`는 그래프 자료구조임을 나타내 보았습니다 😄

2023-05-23 05:45 UTC, sihyung92 requested changes
안녕하세요 오도~~ 
리뷰 잘 반영해주셨네요!
`Sections` URL path에 대한 리뷰가 마음에 걸려 머지하지는 않았습니다 ㅎㅎ
해당 리뷰 반영하고 요청주시면 머지하겠습니당!

2023-05-23 05:45 UTC, sihyung92 commented on src/main/java/subway/controller/LineController.java
> +    }
넵 2단계에 추가된 API가 기존 API의 요구사항까지 커버할 수 있을 것으로 보이는데요, API의 유지보수 관리포인트를 줄이기 위해 기존 API를 제외해도 될거같아요.

2023-05-23 05:45 UTC, sihyung92 commented on src/main/java/subway/domain/fare/SubwayFareCalculator.java
> +                .filter(strategy -> strategy.isApplicable(distance))
strategy간의 `isApplicable()` 조건이 상호 배타적이어야 한다는 한계점(논리적 의존)이 있지만 어느정도 확장성 있게 구성해주셨네요 ㅎㅎ 저도 자주 사용하는 방식입니다.

적용해볼 수 있는 다른 디자인 패턴으로는 [컴포지트 패턴](https://mygumi.tistory.com/343)도 있습니다.

2023-05-23 05:45 UTC, sihyung92 commented on src/main/java/subway/domain/subwaymap/SubwaySectionMap.java
> +public class SubwaySectionMap {
패키지 분리를 진행해주시니 코드 가독성이 눈에 띄게 좋아졌네요 👍 성공적인 리팩토링이었던 것 같아요.

SubwaySectionMap과 SubwayStationMap이 따로 있는 것에는 아직 의문점이 남아있긴 합니다. 
Section이 Station의 자료구조이므로 SubwaySectionMap가 기존의 SubwaySectionMap과 SubwayStationMap의 요구사항을 모두 충족할 수 있을것으로 보여서요. (네이밍이 SubwayMap으로 바뀌겠네요)

나중에 Section을 join하지 않고 역만 확인하는 등의 최적화가 필요하다면 구현하신대로 분화될 가능성도 있겠지만요, 도메인 특성(데이터량이 많지 않음)을 생각해봤을 때 그렇게까지 최적화가 필요할것 같지 않네요~!

2023-05-23 05:45 UTC, sihyung92 commented on src/test/java/subway/controller/LineControllerTest.java
> +        final JsonPath jsonPath = response.jsonPath();
기존 타입 캐스팅 대신 JsonPath를 활용해주셨는데요, 이렇게 변환하신 이유가 있을까요? 기존 테스트 코드가 다른 개발자가 봤을때 훨씬 파악이 쉬운 형태인것 같아서요 :)

2023-05-23 05:45 UTC, sihyung92 commented on src/test/java/subway/domain/fare/SubwayFareCalculatorTest.java
>      }
특정 요금이 어떻게 계산되는지는 각 단위테스트에서 검증 되었으니, "각 distnace일 때 어떤 Strategy가 할당되는지?"를 테스트 해봤어도 좋았을 것 같아요. distance와 fare에 이해도가 높다면 어떤 strategy가 선택되었는지 추론할 수 있지만, 시간이 지나거나 해당 코드를 처음 보는 사람은 파악이 어려울 것 같네요.

이 때 활용할 수 있는 도구가 Mockito의 verify 키워드 이고, mock 객체가 아닌 실제 객체로 테스트 해볼 수 있는 키워드는 Mocito의 Spy 입니다!

2023-05-23 05:45 UTC, sihyung92 commented on src/main/java/subway/controller/LineController.java
> +    @GetMapping("/sections/{lineId}")
[URL 규칙](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Identifying_resources_on_the_Web) 상 path는 자원의 위치를 나타내는데요, `sections/{숫자}` 형태의 url은 특정 Section의 ID를 나타낼거라는 기대를 하게 만드는 감이 있습니다. 
url 규칙은 조율해나가기 나름이므로 클라이언트와 조율 가능한 부분이긴 하지만, `lines/{lineId}/sections`같은 URL이 path만 보았을 때 좀 더 자연스러운 흐름으로 보이긴 합니다 :)

2023-05-23 10:09 UTC, odo27 commented on src/main/java/subway/controller/LineController.java
> +    }
기존 API 제거했습니다 😆

2023-05-23 10:11 UTC, odo27 commented on src/main/java/subway/domain/subwaymap/SubwaySectionMap.java
> +public class SubwaySectionMap {
기존 API를 제거하는 과정과 함께 SubwayStationMap을 제거하였고 기존의 SubwaySectionMap 또한 SubwayMap으로 클래스명을 변경했습니다! 😄

2023-05-23 10:22 UTC, odo27 commented on src/test/java/subway/controller/LineControllerTest.java
> +        final JsonPath jsonPath = response.jsonPath();
기존 테스트 코드 `response.jsonPath().getList(".", LineResponseWithSections.class);` 에서 다음과 같은 오류가 발생했었습니다. 🥹
`com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of subway.domain.section.Section (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)`

기존에는 Section에 기본 생성자를 사용하고 있어서 문제가 되지 않았었는데 `테스트에서 파싱하는 과정의 특정 메서드`에서 이러한 문제가 생겨서 기본 생성자를 두고 final 키워드를 붙이지 않는 것은 안좋은 것 같아 다음과 같이 테스트의 코드를 수정하게 되었습니다 😄

2023-05-23 10:39 UTC, odo27 commented on src/test/java/subway/domain/fare/SubwayFareCalculatorTest.java
>      }
오오 Mockito의 verify와 spy를 활용해 탄탄한 테스트를 만들 수 있었습니다 😆

2023-05-23 10:42 UTC, odo27 commented on src/main/java/subway/controller/LineController.java
> +    @GetMapping("/sections/{lineId}")
기존 API 제거하면서 `/lines` 와 `/lines/{id}` 로 조회할 수 있게 개선했습니다 😁
`sections/{숫자}`는 section의 id를 생각하게 만드는 것 같네요, 제가 변수명으로 lineId라 한들 실제 api를 사용하는 사람 입장에서는 그걸 모르니 해당 자리에 section의 id를 넣어야한다 생각이 들겠군요..
`lines/{lineId}/sections`와 같은 방식을 염두해 두겠습니다! 감사합니다 😄

2023-05-23 12:31 UTC, sihyung92 commented on src/main/java/subway/controller/LineController.java
> +    @GetMapping("/sections/{lineId}")
넵 클라 입장에서 생각해보는 습관을 기르면 커뮤니케이션 비용과 버그가능성이 낮아져 생산성이 좋아진다고 생각해요 ㅎㅎ 같이 일하고 싶은 사람도 될 것이고요

2023-05-23 12:33 UTC, sihyung92 approved these changes
안녕하세요 오도~~ 
금방 반영해주셨군요 ㅎㅎ
이만 머지하겠습니다!
남은 미션도 마무리 잘 하셔서 성공적인 2단계 보내세용~~

2023-05-23 12:33 UTC, merged