[2단계 - 경로 조회 기능] 홍고(홍여진) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #167
Opened 2023-05-20 10:42 UTC by hgo641

안녕하세요, 디디! 잘 지내고 계시나요?😀😀
2단계 리뷰도 잘 부탁드립니다! 감사합니다!

2023-05-22 03:57 UTC, fucct requested changes
안녕하세요 홍고! 피드백이 늦어져서 죄송합니다 :(  

역시 전체적인 흐름과 구조가 잘짜여져 있어서 코드 이해하기 정말 좋았습니다 :) 
가독성이 훌륭한 코드인것 같습니다. 일부에 피드백 남겨드렸으니 확인해주시고, 시간 여유되신다면 3단계도 진행해보시면 좋을것 같습니다 :) 

이해안되는 부분 있으시면 DM주세요!

2023-05-22 03:57 UTC, fucct commented on src/main/java/subway/config/FareCalculatorConfig.java
> +        DistanceFareStrategy Over50KmDistanceFareStrategy = new DistanceFareStrategy(8, 50);
두 전략을 인터페이스로 두고, 서로다른 구현체를 활용해보는건 어떨까요?

그리고 10~50, 50초과를 서로다른 전략 구현체로 구분하신 이유가 궁금합니다.
개인적인 의견인데, 구현체 분리 기준이 버전이라고 생각해서, 자칫 동일한 정책이 분산되어보일까봐 질문드립니다.
ex) 
version1: 기본운임(10㎞ 이내): 기본운임 1,250원
  이용 거리 초과 시 추가운임 부과
  10km~50km: 5km 까지 마다 100원 추가
  50km 초과: 8km 까지 마다 100원 추가

version2: 청소년: 운임에서 350원을 공제한 금액의 20%할인
어린이: 운임에서 350원을 공제한 금액의 50%할인

2023-05-22 03:57 UTC, fucct commented on src/main/resources/schema.sql
> +    name                VARCHAR(255)          NOT NULL,
station 개념이 생겼군요!
station의 이름이 중복된다면 구분할 수 있을까요?

2023-05-22 03:57 UTC, fucct commented on src/main/java/subway/business/domain/SubwayGraph.java
> +    private final WeightedGraph graph;
도메인에서 Dao를 직접의존하지 않기 위해 Repository를 만들고, 도메인을 리턴하도록 설계하신것처럼
도메인에서 WeightedGraph를 직접 의존하지 않도록 리팩토링 해볼 수 있을까요?

2023-05-22 03:57 UTC, fucct commented on src/main/java/subway/business/domain/SubwayGraph.java
> +    private final WeightedGraph graph;
또, 필드에 제네릭 타입 선언이 빠진것 같습니다

2023-05-22 03:57 UTC, fucct commented on src/main/java/subway/ui/StationController.java
> +    public ResponseEntity<Void> createStation(@RequestBody StationRequest stationRequest) {
@Valid 사용해주시는것도 추천드립니다 :)

2023-05-22 03:57 UTC, fucct commented on src/main/java/subway/persistence/repository/DbStationRepository.java
> +    }
항상 DB find를 하실때는, nullable  고려를 해주셔야 합니다. 보통 findById와 같은 메서드는 리턴타입에 Optional을 활용하곤 합니다 :)

2023-05-22 03:57 UTC, fucct commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:file:/data/demo
applicationProperties도 local - production을 profile 기준으로 분리할 수 있습니다.
이런것도 연습해보시면 좋을것 같아요! (이미 알고계신 내용이면 굳이 반영안해주셔도 괜찮습니다 :)

2023-05-22 03:57 UTC, fucct commented on src/test/java/subway/fixtures/station/StationFixture.java
> +    public static StationEntity 성수역Entity = new StationEntity(4L, "성수역");
Fixture 좋네요! 

Fixture 사용 사례를 하나 추천드리자면 저희팀에선 static 메서드로 제공해서, 파라미터로 이름과 같은 필드를 설정할 수 있도록 제공하기도 합니다.
(더 나아가 Lombok을 사용하시게 된다면 builder를 리턴하는식으로도 제공합니다.)

2023-05-22 03:57 UTC, fucct commented on src/main/java/subway/business/service/PathService.java
> +    public ShortestPathResponse getShortestPath(Long sourceStationId, Long destStationId) {
만약 source에서 도달할 수 없는 dest를 제공하면 어떻게되나요?

시연을 해보고싶은데 프론트엔드는 요구사항이 아니었나보네요!? (라떼는..)

2023-05-22 23:53 UTC, hgo641 commented on src/main/resources/schema.sql
> +    name                VARCHAR(255)          NOT NULL,
같은 이름의 역이 두 개이상 존재할 수도 있다는 가정하에 설계했습니다! id로 구분하면 괜찮지 않을까요? 😃

2023-05-24 10:54 UTC, hgo641 commented on src/main/java/subway/persistence/repository/DbStationRepository.java
> +    }
`LineRepository`와 `StationRepository` 의 findById메서드에서 Optional 객체를 받게 수정했습니다!!👍👍

2023-05-25 02:33 UTC, hgo641 commented on src/main/java/subway/business/domain/SubwayGraph.java
> +    private final WeightedGraph graph;
디디의 말씀처럼 외부 라이브러리를 도메인에서 분리하는 게 좋겠군요! 👍
도메인 계층에 `PathCalculator`라는 인터페이스를 만들고, 어플리케이션 계층(서비스)에서 `WeightedGraph`를 사용한 구현체를 만들었습니다!

2023-05-25 08:16 UTC, hgo641 commented on src/main/java/subway/business/service/PathService.java
> +    public ShortestPathResponse getShortestPath(Long sourceStationId, Long destStationId) {
헉 jgrapht 라이브러리의 `DijkstraShortestPath`에서 IllegalArgumetException을 던지네요! IllegalArgumetException의 message내용만 바꿔서 다시 던지게 변경했습니다!

2023-05-25 08:17 UTC, hgo641 commented on src/test/java/subway/fixtures/station/StationFixture.java
> +    public static StationEntity 성수역Entity = new StationEntity(4L, "성수역");
static 메서드도 활용해봐야겠네요!! 감사합니다!

2023-05-30 01:42 UTC, hgo641 commented
안녕하세요 디디! 
두번째 리뷰요청 드립니다. 제가 너무 늦었죠ㅠㅠ 죄송합니다!!!

현재 주신 코멘트를 반영하고, `Line`에 `fare` 필드를 추가한 상태입니다.
3단계까지 금방 할 수 있을 것 같아 함께 진행중이었는데, 이번 미션과 병행하려니 시간이 더 걸릴 것 같아 지금 단계에서 리뷰 요청드리게 되었습니다! 

한 가지 질문이 있는데,
`Line` 에 새로운 필드인 `fare`를 추가하려니 도메인(Line), 도메인과 관련된 dto들, Dao, Entity까지 많은 코드들을 수정해야했습니다...!
처음 설계가 바뀐 것이니 이런 수정 비용은 어쩔 수 없는 것일까요? 아니면 더 효율적으로 도메인 설계를 변경할 수 있는 방법이 있을까요? 

감사합니다!

2023-05-30 12:44 UTC, fucct approved these changes
안녕하세요 홍고. 

간단한 피드백 몇가지만 남겨드렸으니 확인해주세요 :) 
3단계 진행하실건지 몰라서 우선 approve 하도록 하겠습니다.
그리고 질문주신 fare의 경우 요구사항이 새로 추가된거라 어쩔수 없는 코드 변경이 발생하는것 같아요. 이게 Entity와 domain이 나뉘어져 있기 때문에 코드 변경이 더 많아질수밖에 없고요. 

다만 entity와 domain이 나뉘어져 있는걸 활용해보자면, 기존 lineEntity를 놔두고 LineFareEntity라는 개념으로 풀어볼수도 있을것 같아요. 
도메인 Line 에는 fare가 들어있는 하나의 객체로 사용되고, 엔티티에선 두 엔티티(테이블) LineEntity와 LineFareEntity로 분리해볼 수 있을것 같아요. 
물론 반영해달라는 말은 아니고, 이렇게 함으로써 main이 되는 Line테이블을 건드리지 않고 (칼럼 추가와 같은) fare요구사항을 수용할 수 있다는 말씀을 드리고 싶었어요. 운영상에서 중요한 테이블에 대한 변경은 부담스러울 수 있기 때문에, Entity와 도메인을 분리해놓은 이점을 이런식으로 가져갈 수 있다는걸 기억해주시면 좋습니다 :)

2단계 진행하시느라 수고 많으셨고 혹시 3단계 진행하실 예정이라면 DM한번 부탁드립니다 :)

2023-05-30 12:44 UTC, fucct commented on src/main/java/subway/business/service/path/PathCalculatorImpl.java
> +        DijkstraShortestPath path = new DijkstraShortestPath(graph);
제네릭 타입은 항상 함께선언해주세요! 
```DijkstraShortestPath<Station, DefaultWeightedEdge>```

2023-05-30 12:44 UTC, fucct commented on src/main/java/subway/business/service/PathService.java
> +        List<String> stationNamesOfShortestPath = pathCalculator.getShortestPath(sourceStation, destStation).stream()
여기는 약간 고민되긴 하네요. 

1. 최단거리를 계산할때마다 모든라인을 불러와서 subway를 만들고 pathCalculator를 통해 Graph를 생성하는 방법
2. PathCalculator를 bean으로 선언해놓고, station이 add/delete될때마다 Graph에 vertex, edge를 항상 add/delete 해주는 방법.

어떤게 나을지 고민해보세요 :)

2023-05-30 12:44 UTC, fucct commented on src/main/resources/schema.sql
>  );
이건 팁인데, foreign key는 실제 서비스에서 잘 적용하지 않습니다.
foreign key가 있으면 운영상에 이슈가 많기 때문입니다. 

1. 테스트를 어렵게 함
2. 테이블 구조 확장이 어려움 
3. DB 성능 튜닝을 어렵게함

사실 아직은 JPA와 같은 ORM을 활용하지 않기때문에 사용해도 괜찮지만, JPA를 사용하면 관계를 설정할 수 있다보니 foreign key를 잘 적용하지 않는것 같아요 :)

2023-05-30 12:44 UTC, merged