[2단계 - 경로 조회 기능] 스플릿(박상현) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #168
Opened 2023-05-20 14:37 UTC by splitCoding

안녕하세요 럿고😊

뼈대 코드를 참고해서 다시 진행해보고 싶어서 처음 부터 다시 하다보니 많이 늦어졌습니다ㅠㅠ😭

정말 많이 신경써서 해보았는데 부족한 부분이 많을까 걱정이 되긴 합니다🥲

리뷰로 또 한번 성장해보겠습니다!! 잘부탁드려요😃

2023-05-22 10:08 UTC, ksy90101 commented on src/main/java/subway/application/LineService.java
> +            .flatMap(line -> Stream.of(findById(line.getId())))
findAll에 findBy를 또 한다면 N+1 쿼리일거 같아요.
line 수 만큼 쿼리가 날라갈거 같네요.

2023-05-22 10:09 UTC, ksy90101 commented on src/main/java/subway/application/SectionService.java
> +            .orElseThrow(() -> new LineDoesNotContainStationException("노선에 역이 존재하지 않습니다. ( " + stationName + " )"));
sections에 있어야 할 로직 같아요.
레벨1을 생각해봅시다!

2023-05-22 10:10 UTC, ksy90101 commented on src/main/java/subway/dao/LineRepository.java
> +    }
DB의 cascading을 찾아보심녀 좋을거 같습니다 :)

2023-05-22 10:12 UTC, ksy90101 commented on src/main/java/subway/dao/LineRepository.java
> +public class LineRepository {
사실 Dao가 Repostiory일거고 이러한 행위는 사실 service에서 해야 한다고 생각합니다.
우리가 생각하는 계층에 사실 service - repository - dao 이렇게 한단계가 더 있는거 같아요.
사실 5layer 계층에선 아래 사진과 같이 DB와 통신하는 계층이 하나만 있는것뿐이니깐요.

![image](https://github.com/woowacourse/jwp-subway-path/assets/53366407/b94e3ce8-a820-4f1c-8be6-e868f079c063)

2023-05-22 10:12 UTC, ksy90101 commented on src/main/java/subway/dao/LineRepository.java
> +public class LineRepository {
개인적으로 관리하는 측면만 추가적으로 생긴다고 생각이 들었어요.

2023-05-22 10:13 UTC, ksy90101 commented on src/main/java/subway/dao/SectionRepository.java
> +            .orElseThrow(() -> new StationNotExistException("해당 이름의 역이 존재하지 않습니다. ( " + downStationName + " )"));
2개 정도는 괜찮지만, Inquery로도 충분했을거 같다는 생각이 문득 들었어요 ㅎㅎ

2023-05-22 10:13 UTC, ksy90101 commented on src/main/java/subway/dao/StationDao.java
> +@Repository
다른 Dao는 Component던데 여긴 Repostiory네요 ㅎㅎ

2023-05-22 10:14 UTC, ksy90101 commented on src/main/java/subway/domain/FareCalculator.java
> +public final class FareCalculator {
Fare는 전략이 있을거 같은데요.
전략패턴으로 한번 만들어 보면 어떨까요?

2023-05-22 10:15 UTC, ksy90101 commented on src/main/java/subway/domain/SubwayMap.java
> +import org.jgrapht.graph.WeightedMultigraph;
외부 라이브러리는 언제든 갈아끼우기 쉽게 interface로 추출해서 사용하는게 좋은거 같습니다.
대표적으로 jgrapht가 그런걸 하기엔 좋은 거 같습니다.

2023-05-22 10:15 UTC, ksy90101 commented on src/main/java/subway/ui/LineController.java
> +        return ResponseEntity.ok().build();
내려줄 값이 없다면 no_content가 어울려 보여요~

2023-05-22 10:17 UTC, ksy90101 commented on src/test/java/subway/domain/FareCalculatorTest.java
> +
여기 있는 테스트를 parameterziedTest로 작성이 가능했을수도 있을거 같네요.

2023-05-22 10:17 UTC, ksy90101 requested changes
안녕하세요 :)
어려운 미션이였을텐데, 고생 많으셨어요.
간단한 피드백을 남겼으니 한번 확인해보시면 좋을거 같습니다. 
질문이 있다면 언제든 DM주세요~

2023-05-28 14:00 UTC, splitCoding commented on src/test/java/subway/domain/FareCalculatorTest.java
> +
parmeterizedTest로 다시 작성해보았습니다!! 가독성이 훨씬 좋아지는게 바로 느껴집니다👍

2023-05-28 14:00 UTC, splitCoding commented on src/main/java/subway/ui/LineController.java
> +        return ResponseEntity.ok().build();
저도 no_content가 더 좋은 것 같습니다!!😄

2023-05-28 14:00 UTC, splitCoding commented on src/main/java/subway/domain/SubwayMap.java
> +import org.jgrapht.graph.WeightedMultigraph;
럿고 의견에 매우 동의합니다!!👍

2023-05-28 14:00 UTC, splitCoding commented on src/main/java/subway/domain/FareCalculator.java
> +public final class FareCalculator {
FarePolicy라는 인터페이스를 통해 거리, 나이, 노선 별 추가 요금 전략을 각각 구현한 뒤 

FarePolicies라는 객체를 통해 순서대로 전략을 적용하는 방식을 적용해보았습니다!!😁

2023-05-28 14:00 UTC, splitCoding commented on src/main/java/subway/dao/SectionRepository.java
> +            .orElseThrow(() -> new StationNotExistException("해당 이름의 역이 존재하지 않습니다. ( " + downStationName + " )"));
Inquery로 충분했을 거 같다는 말이 제가 이해한 내용이 맞는지 확실하지 않아 우선 제가 이해한대로 적용해보았는데 설명한번만 더 해주시면 감사하겠습니다!!😁

조회하려는 역의 이름이 없는 것이 예외라는 것을 dao가 알 필요하는 없다고 생각하여 dao에서 처리를 해주지 않았는데 역이름으로 역을 조회할 때마다 중복 코드가 계속 생길 것 같아요😅

 우선은 메서드로 분리해주는 방식을 택했습니다!

2023-05-28 14:00 UTC, splitCoding commented on src/main/java/subway/dao/LineRepository.java
> +public class LineRepository {
제가 이번에 Repository를 사용했던 이유는 Service에서 너무 많은 Dao를 필드로 가지게 되어 너무 많은 의존성이 생기는것 같아 repository를 통하여 의존성을 낮추려고 사용했던게 목적이였습니다. 🧐 

럿고의 리뷰를 보고 제가 dao와 repository의 차이에 대해서 잘 모른다는 생각을 하여 찾아보았는데도 잘 이해가 안되더라구요ㅠㅠㅠ😭 

혹시 럿고가 생각하는 dao와 repository의 차이에 대해서 말씀해주시면 감사하겠습니다😃

2023-05-28 14:00 UTC, splitCoding commented on src/main/java/subway/dao/LineRepository.java
> +    }
```
CREATE TABLE IF NOT EXISTS LINE_SECTION
(
    id              BIGINT  NOT NULL AUTO_INCREMENT,
    distance        INTEGER NOT NULL,
    up_station_id   BIGINT  NOT NULL,
    down_station_id BIGINT  NOT NULL,
    line_id         BIGINT  NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (up_station_id) REFERENCES STATION (id) ON DELETE CASCADE,
    FOREIGN KEY (down_station_id) REFERENCES STATION (id) ON DELETE CASCADE,
    FOREIGN KEY (line_id) REFERENCES LINE (id) ON DELETE CASCADE
);
```

테이블 스키마에 ON DELETE CASCADE를 추가해줬습니다!!

2023-05-28 14:00 UTC, splitCoding commented on src/main/java/subway/application/SectionService.java
> +            .orElseThrow(() -> new LineDoesNotContainStationException("노선에 역이 존재하지 않습니다. ( " + stationName + " )"));
DB와 객체지향을 섞어서 하다보니 너무 정신이 없네요ㅠㅠ 

럿고말에 완전 동의합니다!👍 

sections에게 해당 이름의 역을 반환하는 기능 추가하였습니다!😊

2023-05-28 14:00 UTC, splitCoding commented on src/main/java/subway/application/LineService.java
> +            .flatMap(line -> Stream.of(findById(line.getId())))
JOIN문을 사용하여 한번에 모든 데이터를 조회하여 DTO를 통해 LineResponse를 만드는 방식으로 바꿔봤습니다!! 

JOIN을 사용해보지 않았다보니 JOIN을 사용하는 좋은 경우가 맞는지가 많이 헷갈리더라구요ㅠ 😭

혹시 럿고의 JOIN문을 사용하는 기준이 있는지 궁금해요😊

2023-05-28 14:01 UTC, splitCoding commented on src/main/java/subway/dao/StationDao.java
> +@Repository
앗 그러네요... 더 신경썻어야하는데 부끄럽습니다아😅

2023-05-29 23:34 UTC, ksy90101 commented on src/main/java/subway/application/LineService.java
> +            .flatMap(line -> Stream.of(findById(line.getId())))
쿼리가 배로 날라가는것보다 JOIN이 무조건 좋습니다 ㅎㅎ

2023-05-29 23:35 UTC, ksy90101 commented on src/main/java/subway/dao/LineRepository.java
> +public class LineRepository {
dao와 repostitory의 차이점은 전 없다고 생각해요.
결국 동일하게 DB와 통신하기 위한 레이어일뿐이다 라고 생각합니다 ㅎㅎ

2023-05-29 23:37 UTC, ksy90101 commented on src/main/java/subway/application/ShortestPathService.java
> +    private Line findMostExpensiveLine(final List<LineStation> path) {
사용하지 않는 메서드같은데요?ㅎㅎ

2023-05-29 23:42 UTC, ksy90101 commented on src/main/java/subway/domain/subwaymap/Station.java
> +    private static void validate(final String name) {
이것도 사용하지 않는 메서드 같습니다.

2023-05-29 23:42 UTC, ksy90101 commented on src/main/java/subway/domain/subwaymap/Section.java
> +    public boolean containsStation(final Station station) {
이것도 사용하지 않는 메서드네요.

2023-05-29 23:52 UTC, ksy90101 requested changes
사용하지 않는 메서드가 많이 있어보여요.
마지막으로 코드 정리를 해보면 어떨까요?
IDE의 힘을 빌리면 좋을수 있는데요.
<img width="391" alt="image" src="https://github.com/woowacourse/jwp-subway-path/assets/53366407/f5a8cf46-cdf6-4964-bc2c-b242568a762c">

- Reformat Code
- Optimize Code
로 코드 정리를 한번 해보시면 좋을거 같습니다.

https://moonsiri.tistory.com/11

이 기능을 이용해 사용하지 않는 메서드들을 한번 확인해보시면 좋을거 같아요

2023-05-29 23:52 UTC, ksy90101 commented on src/main/java/subway/domain/fare/FarePolicy.java
> +    default void validate(final int fare, final int distance, final int age) {
👍

2023-06-05 09:01 UTC, splitCoding commented on src/main/java/subway/application/ShortestPathService.java
> +    private Line findMostExpensiveLine(final List<LineStation> path) {
Analyze라는 기능이 있었군요!!😁

자주 이용할것 같습니다!! 좋은 정보 감사합니다~~

2023-06-06 06:25 UTC, ksy90101 approved these changes
마지막 코드 정리까지 고생 많으셨습니다~
이만 지하철 미션은 마무리 할게요!
마지막 까지 파이팅입니다~

2023-06-06 06:25 UTC, merged