[2단계 - 경로 조회 기능] 블랙캣(송우석) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #178
Opened 2023-05-22 02:43 UTC by Songusika

안녕하세요 소니!
새로 배운 @Configuration 에 대해서 학습 후 적용하느라 PR이 늦었네요..😭
2단계 경로 조회 제출합니다!

1단계 코멘트에 대해서 답변 드립니다!
> * Optional.of()와 Optional.ofNullable()은 어떤 차이가 있을까요?
> * EmptyResultDataAccessException 은 언제 발생할까요?

 - Optional.of() 는 매개변수는 null이 아니어야 합니다. 즉, 매개변수가 null인 경우 NullPointerException이 발생합니다.
 - Optional.ofNullable() 는 매개변수는 null일 수 있습니다.
 - EmptyResultDataAccessException 는 단일 결과를 반환하는 쿼리에서 결과가 없을 때 발생합니다!

이번 미션을 구현하면서 질문이 있습니다!

## 외부 라이브러리 의존성을 어떻게 줄일 수 있을까요?

현재 외부 라이브러리를 사용하여 최단 경로를 계산하는데요!
일단 해당 라이브러리와 도메인 객체간 의존성을 줄이고자 인터페이스로 분리하였습니다.
이후 실제 구현체는 스프링 빈으로 등록하였습니다. 
혹시 이 방법이 옳은 방법일까요?

2023-05-22 05:22 UTC, sonypark requested changes
블랙캣 안녕하세요.
2단계 미션 구현하느라 수고 많으셨습니다.
몇가지 코멘트 남겼으니 확인 부탁드립니다!

`외부 라이브러리 의존성을 주입하기 위해 인터페이스 생성 후 bean으로 등록해서 사용` -> 네 잘하셨습니다. 인터페이스를 사용해서 의존성을 주입하면 특정 구현체에 강결합되는걸 피할 수 있습니다.

2023-05-22 05:22 UTC, sonypark commented on src/test/java/subway/domain/fare/DistanceFareStrategyTest.java
> +    void 거리가_10에서_50_이내이면_5km_마다_100원_추가된다() {
경계값 위주로 테스트를 해주면 좋을 것 같습니다.(10,15,50,58)

```
- 기본운임(10㎞ 이내): 기본운임 1,250원
- 이용 거리 초과 시 추가운임 부과
    - 10km~50km: 5km 까지 마다 100원 추가
    - 50km 초과: 8km 까지 마다 100원 추가
```

2023-05-22 05:22 UTC, sonypark commented on src/test/java/subway/domain/path/JgraphPathFinderTest.java
> +
가장 중요한 로직인만큼 테스트를 꼼꼼히 작성해주세요

- 출발역/도착역 중 하나라도 없으면 예외가 발생하는지
- 최단거리 정보 정상적으로 반환하는지
- 경로가 없는경우는 어떻게 되는지 등

2023-05-22 05:22 UTC, sonypark commented on src/main/java/subway/domain/path/JgraphPathFinder.java
> +        final Stations pathStations = new Stations(path.getVertexList());
- 항상 출발/도착역에 대한 경로가 존재한다는 걸 보장할 수 있을까요?
- 해당 경로가 존재하지 않을 경우 현재는 어떻게 되고있고, 어떻게 처리 해야할까요?

2023-05-22 05:22 UTC, sonypark commented on src/main/java/subway/domain/fare/DistanceFareStrategy.java
> +        }
if문 내의 로직을 메서드로 추출해서 어떤 역할을 하는지 메서드 네이밍으로 표현하면 가독성이 올라갈 것 같아요! :)

2023-05-22 05:22 UTC, sonypark commented on src/main/java/subway/application/PathService.java
> +    }
이 부분은 PathResponse에서 해도 될 것 같아요. `createStationResponse` 라는 로직이 서비스 클래스에 있을 필요는 없을 것 같습니다.

```java
return PathResponse.from(path, totalFare);
```

2023-05-24 19:19 UTC, Songusika commented on src/main/java/subway/domain/fare/DistanceFareStrategy.java
> +        }
거리별 계산로직을 전략 패턴으로 분리하였습니다!

2023-05-24 19:19 UTC, Songusika commented on src/test/java/subway/domain/fare/DistanceFareStrategyTest.java
> +    void 거리가_10에서_50_이내이면_5km_마다_100원_추가된다() {
경계값 위주의 테스트 케이스를 추가하였습니다!

2023-05-25 09:29 UTC, Songusika commented on src/main/java/subway/domain/path/JgraphPathFinder.java
> +        final Stations pathStations = new Stations(path.getVertexList());
1. 역은 존재하지만, 노선에 등록되어 있지 않을 수 있으므로, 전체 경로간 요청한 역이 존재하는지 검증하는 로직을 추가하였습니다.
2. 경로가 존재하지 않는 경우 즉, `path == null` 인 경우를 검사하여, 예외를 반환하도록 로직을 추가하였습니다.

2023-05-25 09:31 UTC, Songusika commented on src/test/java/subway/domain/path/JgraphPathFinderTest.java
> +
아래 각 테스트를 추가하였습니다!
- 상행 출발역에서 하행 출발역으로 가는 경로 테스트 
- 하행 출발역에서 상행 출발역으로 가는 경로 테스트 
- 환승을 통해 가는 경로 테스트
- 경로간 역이 없는 경우 예외 발생 테스트
- 경로가 이루어지지 않는 경우 예외 발생 테스트

2023-05-26 09:53 UTC, Songusika commented on src/main/java/subway/application/PathService.java
> +    }
DTO에 정적 팩터리 메서드를 추가하였습니다!

이 코멘트를 보고 DTO 변환 로직 위치에 대해서 다시 고민이 드는데요
- Service 에서 도메인 객체 반환 후 Controller 에서 DTO로 반환
- Service 에서 도메인 객체를 DTO 로 변환 후 Controller 로 반환

혹시 소니는 도메인 객체를 어디서 변환하는 것을 선호하시나요?

2023-05-26 10:16 UTC, sonypark commented on src/main/java/subway/application/PathService.java
> +    }
도메인 객체를 컨트롤러에 노출시키는건 권장하지 않습니다. 컨트롤러 단에서 도메인이 노출 되면 도메인에 대한 원치 않은 변경이 이루어질 수 있습니다. 트랜잭션의 단위인 Service 레이어에서 모든 로직 수행이 다 끝내고 컨트롤러에 도메인 객체를 노출하게 되면 외부 계층에서 추가 조작을 통하여 의도치 않은 응답을 줄 가능성이 남아있게 됩니다. 따라서 DTO로 반환하는게 안전하다고 생각합니다.

2023-05-26 10:18 UTC, sonypark approved these changes
블랙캣 안녕하세요. 아래 리뷰 규칙에 따라 이번 MR은 바로 머지하겠습니다. :) 
`마지막 리뷰 요청이 월요일 오후 6시 후에 온다면 바로 Merge`
질문에 대한 답변은 달아놓았습니다.
지하철 미션 구현하느라 고생 많으셨습니다!😃

2023-05-26 10:18 UTC, merged