[2단계 - 경로 조회 기능] 이레(이다형) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #179
Opened 2023-05-22 02:45 UTC by zillionme

2023-05-22 11:05 UTC, toneyparky requested changes
안녕하세요 이레~!

2단계의 첫 리뷰인지라 빠르게 피드백 드립니다 😬
다음 미션도 있으니 궁금한 사항은 빠르게 DM 주시면 같이 이야기 해보죠..!
코멘트 확인 부탁해요!

2023-05-22 11:05 UTC, toneyparky commented on README.md
> +## 1. api 재설계
API에 대한 여러가지 고민을 해주셨군요!

이렇게 잘 개발한 API는 결국 클라이언트가 사용하게 되죠! 이를 위해서는 API 문서라는 게 필요해요! 
리드미에 적는 방법도 있고 여러가지 툴이 있지만 Swagger라는 툴을 적용해보면 어떨까요~?

가장 간단하기에 시간이 촉박한 지금 가볍게 적용해보시면 좋겠네요! 

참고 글 : https://happy-jjang-a.tistory.com/164

2023-05-22 11:05 UTC, toneyparky commented on src/main/java/subway/config/AppConfig.java
> +}
`@Configuration` 는 어떤 기능을 하고 언제 사용하는 어노테이션이죠~?

`@Component`를 이용하여 `FareCalculator`를 빈으로 등록해도 될텐데 `@Configuration`를 사용하신 이유가 있을까요~?

2023-05-22 11:05 UTC, toneyparky commented on src/main/java/subway/domain/routestrategy/DijkstraRouteStrategy.java
> +    //todo 2 : IllegalArgumentException이 아닌 예외 만들기
완료되지 않은 TODO가 프로젝트에 있을 경우 코드를 읽는 사람은 어떤 생각을 하게 될까요~?

2023-05-22 11:05 UTC, toneyparky commented on src/main/java/subway/domain/Distance.java
> +        }
이 상황은 발생하나요~?

추가로 `Distance` 객체에 대한 테스트도 있으면 좋겠네요!

2023-05-22 11:05 UTC, toneyparky commented on src/main/java/subway/domain/fare/FareStrategy.java
> +}
인터페이스를 통해 여러 과금 전략을 추상화할 수 있게 되었네요 💯 

잘 해주셨습니다! 메서드의 오타만 수정해볼까요~?

2023-05-22 11:05 UTC, toneyparky commented on src/main/java/subway/application/LineService.java
>      }
두번째 질문에 대해 이야기 해봐요.

>  트랜잭션을 사용한 메서드를 다른 메서드에서 사용하면 해당 트랜잭션은 적용이 안되나요?

제가 질문을 잘 이해하지 못했어요. 트랜잭션이 달린 메서드를 호출하면 트랜잭션이 시작되고 그 메서드가 끝날 때에 트랜잭션이 끝난다는 답변으로 궁금증이 해소되셨을까 싶네요..!

학습에 도움이 될 영상도 첨부드려요 : 
https://youtu.be/taAp_u83MwA

2023-05-22 11:05 UTC, toneyparky commented on src/main/java/subway/application/LineStationService.java
> +    public void addStation(Long lineId, LineStationAddRequest request) {
첫 질문이네요!

> 레포지토리를 통해 데이터를 저장하기 전, 데이터의 유효성 검사는 어디서 진행되어야 한다고 생각하시나요?

유효한 역이 저장되어야한다는 건 도메인상의 제약 조건일까요? DB 상의 제약 조건일까요? 전자라면 서비스, 도메인에서 진행해야겠죠? 그러려면 서비스에서 DB의 값을 조회해야하구요..!
`StationRepository.findStationByName()`를 사용하여 실제로 존재하는 역을 가져와서 로직을 수행하면 어때요?

2023-05-22 11:05 UTC, toneyparky commented on src/main/java/subway/ui/RouteController.java
> +    }
`/subway/route` 를 통해 API를 호출하겠네요!

클라이언트 입장에서 이 API가 어떤 경로인지 알기 힘들 것 같아요. URL을 통해 가장 짧은 경로임을 표현할 수 있을까요?

2023-05-22 11:05 UTC, toneyparky commented on src/test/java/subway/integration/RouteIntegrationTest.java
> +        노선에_구간_추가(4,"내방", "고속터미널", "UP", 5);
인수테스트처럼 이해하기 쉽게 작성해주셨네요..! 너무 좋습니다 👍

2023-05-22 11:05 UTC, toneyparky commented on src/test/resources/initializeTestDb.sql
> +    id          bigint            not null      auto_increment,
노선과의 의존성이 사라졌네요. 1단계에서 리뷰 드린 내용에 대해서 고민하고 선택하셨으리라 생각됩니다 😊
엔티티간의 관계에 대해서 조금 더 생각해볼 기회가 되었길 바라요..!

2023-05-22 11:05 UTC, toneyparky requested changes
안녕하세요 이레~!

2단계의 첫 리뷰인지라 빠르게 피드백 드립니다 😬
다음 미션도 있으니 궁금한 사항은 빠르게 DM 주시면 같이 이야기 해보죠..!
코멘트 확인 부탁해요!

2023-05-25 04:56 UTC, zillionme commented on README.md
> +## 1. api 재설계
좋은 정보 감사합니다!
의존성 추가해서 협업미션에도 잘 쓰고 있습니다~

2023-05-25 05:29 UTC, zillionme commented on src/main/java/subway/config/AppConfig.java
> +}
@Configuration, @Component 두 어노테이션 모두 특정 클래스를 스프링 빈으로 등록할 때 사용하는 주석입니다.
@Configuration과 같은 경우, 설정클래스를 나타내는 주석으로 1. @Bean 주석을 사용하여 스프링 빈을 정의하고 구성할 수 있고,
2. WebMvcConfigurer를 구현한 클래스와 함께 사용해 스프링 mvc 구성을 커스터마이징할 수 있고,
3. @Profile을 사용해 특정 환경에만 적용되는 Bean 정의를 생성하는 등 환경별로 설정값을 갖게 할 수있습니다.

두가지 이유로 @Configuration를 사용했는데요

2023-05-25 05:35 UTC, zillionme commented on src/main/java/subway/domain/routestrategy/DijkstraRouteStrategy.java
> +    //todo 2 : IllegalArgumentException이 아닌 예외 만들기
혼자 보는 프로젝트라고 생각해서 todo 주석을 남겨놓았는데 삭제하도록 하겠습니다

2023-05-29 01:16 UTC, zillionme commented on src/main/java/subway/application/LineStationService.java
> +    public void addStation(Long lineId, LineStationAddRequest request) {
유효한 역인지 조회하는 기능만을 위해서 레포지토리를 추가해도 되나 고민하고 있었는데, 제안처럼 수정했습니다.

2023-05-29 01:33 UTC, zillionme commented on src/test/resources/initializeTestDb.sql
> +    id          bigint            not null      auto_increment,
어떤 과정을 통해, 제안주신 내용을 적용하게 되었는지 리뷰에 적지 않았던것 같습니다.
1. 처음 페어 미션을 통해서 station과 line db는 의존성을 갖지 않았는데
2. 실제 사용하는 네이버 지도에서 길찾기 기능을 이용할 때, 같은이름이지만 다른 노선에 있는 역 사이의 거리도 계산하는 것을 보고, 역을 "다른 노선에 있는 역은 서로 다른 역"으로 재정의하게 되었습니다.
3. 이후, 토니의 리뷰와 다른 크루와의 토론 결과, 
- 역이 폐쇄된다면, 해당 역을 가진 노선에서 역이 모두 삭제되는 것이 맞고
- 지하철에서는 동일 구간을 허용하지 않기때문에, "다른 노선에 있는 역은 서로다른 역"이라고 정의했을 때, 구간 중복 오류가 발생할 수 있음을 인지했습니다.
- 2호선 잠실역과 3호선 잠실역 사이의 거리는 서로다른 출구간의 거리라고 생각하면 되기 때문에

다시 토니의 제안대로 "하나의 역을 여러 역에서 동일 사용 가능"하도록 했습니다.

2023-05-29 01:34 UTC, zillionme commented on src/main/java/subway/ui/RouteController.java
> +    }
/subway/shortest-route로 수정했습니다!

2023-05-29 01:36 UTC, zillionme commented on src/main/java/subway/application/LineService.java
>      }
감사합니다!
이전 코드에서는 
```
@Transactional(readOnly = true)
    public Line findLineById(Long lineId) {
        return lineRepository.findLineById(lineId);
    }

```
트랜잭션이 붙은 `findLineById` 메서드를, 같은 클래스의 다른 메서드가 사용하는 경우가 있었는데,
이러한 경우 @transactional이 지속이 되는지 여부가 궁금했습니다.

2023-05-29 01:36 UTC, zillionme commented on src/main/java/subway/application/LineService.java
>      }
영상 감사합니다!

2023-05-29 01:42 UTC, zillionme commented on src/main/java/subway/domain/Distance.java
> +        }
순간 long타입과 착각해서 해당 내용을 넣은 것 같습니다. 삭제했습니다!

2023-05-29 02:08 UTC, zillionme commented
안녕하세요 토니!

일주일만에 pr을 보내는 것에 대해 변명의 여지없이 죄송합니다...
1단계에서 리뷰주신 swagger, transactional 관련 내용과 2단계 리팩터링 피드백 내용을 적용했고
추가로 3단계를 구현했습니다.
부족함이 많은 코드이지만 항상 꼼꼼한 리뷰 주셔서 감사합니다.

+)1단계에서 리뷰주신 액션 리소스, swagger 적용, transactional관련 자료, 영상 모두 꼼꼼히 찾아보았고 정말 큰 도움이 되었습니다! 감사합니다

2023-05-29 03:25 UTC, toneyparky commented on src/main/java/subway/domain/fare/PassengerAge.java
> +public enum PassengerAge {
연령 정책을 객체로 풀어낸거 좋네요~! 
더 나아가면 승객이라는 개념이 나오고 승객이 나이, 출발, 도착역 등의 정보를 가질 수 있겠어요. 
추후 요구사항이 확장되어 국가 유공자 할인이라거나 장애우 할인이라는 개념이 등장하면 승객 객체에 넣기 적절하겠죠?
이렇게 도메인을 도출하는게 중요하고, 백엔드 개발의 재미 중 하나에요! 잘 해주셨습니다 👍

2023-05-29 03:25 UTC, toneyparky commented on src/main/java/subway/domain/fare/DiscountStrategy.java
> +public interface DiscountStrategy {
할인 정책과 가격 정책 객체를 적절하게 구성하셔서 3 단계 요구사항도 쉽게 반영하셨네요. 확장성 있는 설계입니다!

2023-05-29 03:25 UTC, toneyparky commented on src/main/java/subway/application/StationService.java
>  public class StationService {
보통 최상위에 `@Transactional`을 달아주는 경우에는 여러 서비스간의 컨벤션을 맞춰요. `@Transactional`로 일관되게 간다거나 `@Transactional(readOnly = true)` 로 일관되게 맞춰줘요. 이는 컨벤션을 유지하여 혼란을 방지하기 위함이에요.

물론 하나의 서비스가 조회만 하거나 CUD만 할경우에는 그에 맞는 설정을 달아줘야겠지만요?

2023-05-29 03:25 UTC, toneyparky commented on src/main/java/subway/domain/fare/FareCalculator.java
> +public class FareCalculator {
저라면 이 친구만 빈으로 등록하고 다른 전략 객체는 POJO로 유지하여 이 객체 내에서 초기화 및 할당해줄 것 같아요. 굳이 빈으로 등록할 필요가 없으니까요~!

2023-05-29 03:25 UTC, toneyparky commented on src/main/java/subway/config/AppConfig.java
> +}
저는 스프링이 아닌 라이브러리의 클래스를 빈으로 등록할 때, 환경(프로파일)이 다를 때에 주로 컨피규레이션을 사용해요. 이 상황에 대해서 설정 클래스를 나타낸다고 판단하고 있어요. 그 이외의 빈 등록은 컴포넌트를 사용합니다. 

이레가 예시로 주신 1번 이유도 여러 구현체의 종류를 담은 클래스를 설정 클래스로 생각한다면 충분히 적용할 수 있다고 생각해요.
명확한 정답이 있는게 아니기에 이레의 기준을 세우고 팀 프로젝트에서 팀원들과 함께 논의하면 도움이 될 것 같네요.

2023-05-29 03:25 UTC, toneyparky commented on README.md
> +## 1. api 재설계
잘 쓰고 계시다니 다행이네요~! 굳굳

2023-05-29 03:25 UTC, toneyparky commented on src/main/java/subway/domain/routestrategy/DijkstraRouteStrategy.java
> +    //todo 2 : IllegalArgumentException이 아닌 예외 만들기
네~ PR을 작성한다는 것은 나만의 코드가 아닌 참여자와 함께 공유하는 코드라 생각해요. 그렇기에 혼란을 야기할 수 있는 주석이나 사용하지 않는 코드는 제거해주시면 좋습니다. 

팀 프로젝트에서는 요 부분이 더 중요할거에요 😉

2023-05-29 03:25 UTC, toneyparky commented on src/main/java/subway/domain/Distance.java
> +        }
넵~

2023-05-29 03:25 UTC, toneyparky commented on src/main/java/subway/application/LineService.java
>      }
요 부분은 트랜잭셔널 어노테이션의 propagation와 isolation 에 대해서 추가로 학습해보시면 좋겠네요~!

2023-05-29 03:25 UTC, toneyparky commented on src/main/java/subway/application/LineStationService.java
> +    public void addStation(Long lineId, LineStationAddRequest request) {
유효한 역인지 조회하는 기능이 도메인 로직에 필수적인 부분이라 생각하기에 지금처럼 수정해주신 내용 좋습니다~

2023-05-29 03:25 UTC, toneyparky commented on src/main/java/subway/ui/RouteController.java
> +    }
저번 액션 리소스도 그렇지만 API는 의도를 명확하게 표현해야해요. 고생많으셨습니다~

2023-05-29 03:25 UTC, toneyparky commented on src/test/resources/initializeTestDb.sql
> +    id          bigint            not null      auto_increment,
넵~ 초기 설계의 부족함을 인지하고 수정하신 부분이 좋네요~!

도메인을 파악하는 행위는 일차원적이지 않기에 깊게 고민할 수록 간결한 문장으로 정리할 수 있을거에요. 이번에는 오히려 너무 깊게 파악하며 발견한 `환승시 걷는 거리`라는 개념이 혼란을 야기한 것 같네요. 고생하셨습니다~

2023-05-29 03:31 UTC, toneyparky approved these changes
안녕하세요 이레..!

이슈가 있으셨음에도 잘 마무리해주셨네요! 고생 많으셨습니다. 
질문 주신 부분에 대해서는 답변 남겼고 개발하신 내용에 대해 저도 전해드릴 내용 있으면 추가로 댓글 남겼어요. 
시간이 많이 지났기도 했고 구현은 잘 해주셨기에 머지할게요~ 오늘 푹 쉬시고 내일부터 화이팅입니다!

2023-05-29 03:31 UTC, toneyparky commented on src/test/java/subway/integration/RouteIntegrationTest.java
> +    @DisplayName("최단 경로, 최단 거리, 2세일 때, 요금을 조회한다")
요 부분 검증 테스트가 실패하는군요~!

마지막에 꼼꼼하게 확인해주셨으면 좋았겠다 싶어요 😁

2023-05-29 03:31 UTC, merged