[2단계 - 경로 조회 기능] 루쿠(백경환) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #183
Opened 2023-05-22 05:47 UTC by aiaiaiai1

2023-05-22 13:30 UTC, Be-poz requested changes
안녕하세요 루쿠 2단계 미션 요구사항을 잘 구현해주셨네요 잘 확인했습니다. 수고하셨습니다! 👍  
일부 코멘트를 남겼으니 확인해주시면 감사하겠습니다.

2023-05-22 13:30 UTC, Be-poz commented on src/main/java/subway/controller/StationController.java
> +    public ResponseEntity<List<StationResponse>> deleteStation(@Valid @RequestBody StationDeleteRequest stationDeleteRequest) {
2개인 역을 지울 때에 역을 지우면 호선까지 같이 지워지고 있는데 의도된 것인지 궁금합니다.

2023-05-22 13:30 UTC, Be-poz commented on src/main/java/subway/controller/StationController.java
> +    public ResponseEntity<List<StationResponse>> addStation(@Valid @RequestBody StationAddRequest stationRequest) {
어느 호선에 속하지 않고 단순히 역만 추가하는 방법은 없을까요?

2023-05-22 13:30 UTC, Be-poz commented on src/main/java/subway/controller/StationController.java
> +    @DeleteMapping("/station")
LineController에서는 이런 경우에 LineId PathVariable을 사용했는데 이곳에서는 그렇지 않은데 특별한 이유가 있나요?

2023-05-22 13:30 UTC, Be-poz commented on src/main/resources/application.properties
> +spring.datasource.password=
profile에 따라 h2를 인메모리로 사용할 것인지 아닌지를 결정할 수 있게끔 변경할 수 있으면 좋을 것 같습니다.

2023-05-22 13:30 UTC, Be-poz commented on src/main/java/subway/domain/SubwayGraphs.java
> +        WeightedMultigraph subwayMap = new WeightedMultigraph<>(DefaultWeightedEdge.class);
호출될 때 마다 생성이 되는데 공통으로 하나만 두고 사용할 수 있다면 그럴 수 있게끔 변경이 되면 좋을 것 같습니다!

2023-05-22 13:30 UTC, Be-poz commented on src/test/java/subway/integration/Utils.java
> +    public static ExtractableResponse<Response> addStation(
👍

2023-05-22 13:30 UTC, Be-poz commented on src/main/java/subway/controller/StationController.java
> +    // TODO: 2023/05/17 헤더값 문제??
해결되셨다면 TODO 빼주세요!

2023-05-22 13:30 UTC, Be-poz commented on src/main/java/subway/dao/EdgeDao.java
> +import java.util.Map;
이 클래스 포함해서 전체적으로 미사용 import는 모두 삭제해주세요! 인텔리제이를 사용하고 계신다면 optimize import 관련해서 찾아보시면 됩니다

2023-05-22 13:30 UTC, Be-poz commented on README.md
> +| DELETE | `/stations/{stationId}` | 역 제거        |
현재와 다른 url 이네요!

2023-05-22 13:30 UTC, Be-poz commented on src/main/java/subway/controller/PathController.java
> +        return ResponseEntity.ok().body(shortestPathResponse);
Line Controller와 개행 방식이 조금 다르네요!

2023-05-22 13:30 UTC, Be-poz commented on src/main/java/subway/controller/PathController.java
> +    @PostMapping("/paths")
미리 RequestMapping을 해두어도 좋을 것 같습니다!

2023-06-05 13:01 UTC, aiaiaiai1 commented on src/main/java/subway/controller/StationController.java
> +    public ResponseEntity<List<StationResponse>> deleteStation(@Valid @RequestBody StationDeleteRequest stationDeleteRequest) {
의도하였지만 다시 보니 그럴 필요가 있었을까 라는 생각도 드는거같네요!

2023-06-06 06:44 UTC, aiaiaiai1 commented on src/main/java/subway/controller/StationController.java
> +    @DeleteMapping("/station")
노선에 있는 역을 삭제할려고하니 노선정보가 필요해서 dto로 받게 되었습니다.
그래서 노선에 역을 제거하는 api와 그냥 역 자체를 제거하는 api를 분리하는게 더 좋아보이는거같네요

2023-06-06 07:07 UTC, aiaiaiai1 commented
리뷰 요청이 늦었네요 고생하셨습니다~

2023-06-07 12:05 UTC, Be-poz approved these changes
수고하셨습니다 🍻

2023-06-07 12:05 UTC, merged