[3단계 - 요금 정책 추가] 글렌(전석진) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #191
Opened 2023-05-22 07:42 UTC by seokjin8678

안녕하세요 토니!
3단계 요구 사항 완성하고 제출합니다!

이번 단계에서 중심을 둔 부분은 `PricePolicy`를 `PathService`에서 분리하고, `PriceService`를 만들어 적용한 부분과, 할인 정책을 어떻게 기존 코드의 변경을 최소화하면서 기능을 확장할 것인지에 대한 부분이었네요!

개인적으로 신경이 쓰이는 부분은 `Controller`에서 도메인 패키지에 있는 `Path`를 직접적으로 사용하는 점인데, `Path`의 필드는 크게 중요한 부분이 없지만 아무래도 컨트롤러 계층에서 도메인 객체를 사용한다는 것이 신경이 쓰이네요. 😂

사용하지 않게 하려면, PathService에서 요금 계산을 해줘야하나 싶지만, 책임의 분리를 위해 요금 계산 로직을 다른 서비스로 옮기면서 해당 방식을 선택하게 되었습니다!

또한, `Age`라는 객체를 `Converter`를 사용해서 `@RequestParam`의 매개변수로 바로 받게 하였습니다!

노선 별 요금을 측정하기 위해 `LineExtraFeePricePolicy`가 `LineDao`를 사용하고 있는데, `LineEdge`에서 `Line` 혹은 `LineEntity`을 필드로 가지게 할 수 있지만, 그럴 경우 `LineEdge`를 생성할 때 `SectionEntity`가 가진 `LineId`로 매번 데이터베이스에서 조회해야 하므로, 성능 이슈가 생길 것 이라 판단하여, `LineEdge`가 `LineId`를 가지게 한 뒤 경로를 찾은 뒤, 해당 경로에 대해서만 `Line`의 정보를 데이터베이스에서 조회하도록 하였습니다!

리뷰 기다리겠습니다!
감사합니다!

2023-05-22 13:10 UTC, toneyparky requested changes
안녕하세요 글렌~

너무 잘 구현해주셨네요 👍 
글렌이 중점적으로 생각하셨다는 부분에 의견 드렸습니다! 저도 추가로 리뷰 남겼어요. 
코드 수정은 별로 없으니 부담 없이 같이 코멘트로 대화를 조금 더 나누시죠!

2023-05-22 13:10 UTC, toneyparky commented on src/test/java/subway/ui/LineControllerTest.java
> +    void createLine_extraFeeLessThen1OrOverThan10000(long extraFee) throws Exception {
새롭게 추가된 `extraFee` 까지 테스트 잘 챙겨주셨군요! API문서에도 잘 반영되었어요 👍 

<img width="1005" alt="image" src="https://github.com/woowacourse/jwp-subway-path/assets/37579660/50ba0478-62ef-4f3d-8f72-3d7786583944">


메서드 이름만 테스트 내용에 맞춰 수정하면 좋겠네요!

`void createLine_extraFeeLessThen0OrOverThan10000(long extraFee) throws Exception {`

2023-05-22 13:10 UTC, toneyparky commented on src/main/java/subway/application/price/PricePolicy.java
> +}
가격 정책과 할인 정책을 분리하는건 괜찮은 선택이라 생각해요. 기존의 코드에서 변경을  최소화하며 구현하기 위한 최적의 선택이네요!

할인 정책은 가격 정책에 포함되어 있는 개념이지 않을까라는 생각도 지나가네요. 이럴 경우에는 프로젝트의 구조가 더 단순해지지 않을까해요. 이 코멘트는 도메인을 바라보는 개발자의 생각이 다를 수 있음을 의미해요. 추후 팀 프로젝트를 할 경우 이런 부분에 대해 치열하게 논의하고 결정하면 좋겠어요! 이게 다 글렌의 경험이 될거에요. 

지금의 구조도 좋습니다~!

2023-05-22 13:10 UTC, toneyparky commented on src/main/java/subway/application/price/LineExtraFeePricePolicy.java
> +    private final LineDao lineDao;
요 부분은 의미있네요. DAO를 꼭 레포지토리나 서비스에서만 사용할 필요가 없다고 생각해요. 지금처럼 데이터가 필요한 곳에서는 사용할 수 있다고 생각합니다. 다만 저도 글렌이 구현하신 것처럼 상위 레이어로는 서비스만 노출할 것 같네요.

추가로 성능을 구려해주신 부분도 인상적이에요..! 매번 조회하면 아무래도 부담이 가니까요! 
요런 제 관점은 어떻게 생각하시는지 궁금하네요. 지하철 도메인을 분석해봤을 때에 노선의 개수는 제한되어 있지 않을까 해요. 그러므로 노선을 다 조회해도 크게 성능적으로는 무리가 없을거라 생각합니다. 이 상황에서 코드의 단순성와 효율 중 저라면 전자를 택할거에요. 추후 성능에 문제가 생겼을 때에 개선해도 되니까요. 
위에서도 언급했듯 글렌의 방향성도 좋습니다! 이 코멘트에서 전달하고자하는 바는 무조건 효율이나 가독성 중 하나를 택하기보다는 본인이 구현하는 도메인이나 프로젝트의 현재 상황에 따라 선택을 해야한다는 부분입니다 😁

2023-05-22 13:10 UTC, toneyparky commented on src/main/java/subway/domain/discount/Age.java
> +public class Age {
PR 본문에는 Path 만 컨트롤러에 노출되어 있다고 말씀해주셨는데 이 클래스도 노출되어 있군요..!

물론 값 객체로써 값을 변경하는 행위를 하지는 않지만 저는 도메인 객체 자체가 노출되는 상황을 지양해요. 사람이라는게 어찌 오용할지 모르거든요 🥲

특히 Age 객체는 `AgeDiscountPolicy`와 같은 곳에서 사용되는 중요한 객체기도 하구요. `AgeConverter`와 같은 스프링의 기술을 활용하여 변환해주신 것도 좋지만 도메인과 컨트롤러 레이어간의 의존을 끊는 게 개인적으로는 보다 안정적인 프로젝트를 만든다 생각해요.

2023-05-22 13:10 UTC, toneyparky commented on src/main/java/subway/ui/PathController.java
> +        Price discountPrice = ageDiscountService.discount(price, age);
지하철에서 금액(할인을 포함하여)이라는 개념은 결국 경로가 있기에 의미가 있지 않을까라는 생각이 스쳐갔어요. 실제로 금액과 할인 서비스가 노출하는 메서드는 경로라는 도메인 내에서만 사용되구요. 두 서비스가 경로 서비스 내부에 들어간다면 이 관계를 더 잘 표현할 것 같아요. 

글렌은 이 코멘트에 대해 어떻게 생각하시나요? 이야기를 나눠보고 싶어서 남긴 코멘트에요, 수정은 꼭 안하셔도 되어요~!

2023-05-22 13:10 UTC, toneyparky commented on src/main/java/subway/domain/price/Price.java
> +        return new Price(this.amount.add(price.amount));
값 객체를 불변 객체로 유지해주신 부분 좋네요! 사이드 이펙트를 방지할 수 있죠!

2023-05-22 13:10 UTC, toneyparky commented on src/main/java/subway/application/price/PriceService.java
> +public class PriceService {
지난 단계에서 미리 구상하신 서비스가 적절하게 빛을 발하네요..! 굳굳!

여러 금액 관련 정책을 쉽게 추가할 수 있어요.

2023-05-24 13:22 UTC, seokjin8678 commented on src/test/java/subway/ui/LineControllerTest.java
> +    void createLine_extraFeeLessThen1OrOverThan10000(long extraFee) throws Exception {
다른 크루들을 보니 테스트 메소드 이름을 한글로 하는 경우도 있던데, 저도 그렇게 할 걸 그랬나보네요 😂

2023-05-24 13:26 UTC, seokjin8678 commented on src/main/java/subway/application/price/PricePolicy.java
> +}
아무래도 단순한 설계보단, 확장성 있는 설계를 생각하다보니 이런 결과가 나온 것 같네요!
현실적으로 확장될 일이 없는 도메인일 경우엔 단순한 설계가 더 좋을 것 같네요!

2023-05-24 13:29 UTC, seokjin8678 commented on src/main/java/subway/application/price/LineExtraFeePricePolicy.java
> +    private final LineDao lineDao;
새로운 구간을 추가할 때 기존의 구간을 전부 지우고 다시 모두 추가하는 방법도 생각해봤습니다!
만약 도메인에 비즈니스 로직을 몰아줄 경우, 해당 방법을 사용해야 제일 간단한 구조로 만들 수 있었구요!
지금 생각해보면 역을 추가하거나 새로운 구간이 생길 일이 현실에선 정말 드문일인데, 차라리 그렇게 할 걸 싶기도 하네요 😂

2023-05-24 13:31 UTC, seokjin8678 commented on src/main/java/subway/application/price/LineExtraFeePricePolicy.java
> +    private final LineDao lineDao;
또 해당 부분과 관련된 문제를 "Premature Optimization"이라고 하는데, 성급한 최적화가 아니었을까 싶네요

2023-05-24 13:34 UTC, seokjin8678 commented on src/main/java/subway/domain/discount/Age.java
> +public class Age {
`Station` 도메인도 큰 역할 없이 이름만 가진 ID 같은 도메인이라, 편의성을 위해서 `Station`도 해당 방식으로 하면 어떨까 싶었는데, 아무래도 편의성을 댓가로 한 나쁜 코드가 된 것 같네요 😂

2023-05-24 13:37 UTC, seokjin8678 commented on src/main/java/subway/ui/PathController.java
> +        Price discountPrice = ageDiscountService.discount(price, age);
경로라는 것을 하나의 도메인으로 본다면, 경로에는 요금도 포함이 되어야 하는게 맞겠네요..!
따라서 `PathService`에서 요금과 관련된(금액 계산, 할인 계산) 서비스들이 들어가는게 맞을 것 같아요.
하지만 단순히 경로라는 것만 봤을땐, 전혀 금액하고 관련된 것이 안떠오르기도 하고 Sevice에서 다른 Service를 가져가는 것이 과연 좋은가?를 따져봤을 때 지금과 같은 구조를 작성한 것 같네요!

2023-05-24 13:39 UTC, seokjin8678 commented on src/main/java/subway/domain/price/Price.java
> +        return new Price(this.amount.add(price.amount));
책이나 예제를 여럿 봤는데, 금액과 관련된 부분은 아무래도 민감하니 불변 + `BigDecimal`을 사용하더군요!
불변 객체로 만들고 `Zero` 라는 정적 클래스로 성능 최적화도 챙길 수 있었네요!

2023-05-24 13:41 UTC, seokjin8678 commented on src/main/java/subway/application/price/PriceService.java
> +public class PriceService {
스프링을 사용하니 OCP 원칙을 확실하게 지킬 수 있네요 👍

2023-05-24 13:43 UTC, seokjin8678 commented
안녕하세요 토니!
피드백 남겨주신 코멘트에 답글 달았습니다!
항상 꼼꼼히 봐주셔서 너무 감사하네요 🥹
시간 되실 때 천천히 봐주시면 됩니다!
감사합니다!

2023-05-24 20:46 UTC, toneyparky commented on src/test/java/subway/ui/LineControllerTest.java
> +    void createLine_extraFeeLessThen1OrOverThan10000(long extraFee) throws Exception {
저는 `DisplayName`을 한글로하고 메서드는 글렌처럼 영어로 하는걸더 선호해요. 영어로 메서드 이름을 정하다보면 한글로 정할 때와는 또 다르게 해당 테스트의 의미가 명확하게 드러난달까요? 영어 공부는 덤이구요. 대신 명확한 의미 부여를 위해 `createLine_WhenExtraFeeLessThen0OrOverThan10000_ThenThrowExeption` 요렇게 했던 기억이 있네요~

각자의 스타일이니 참고만해주십쇼~

2023-05-24 20:46 UTC, toneyparky commented on src/main/java/subway/application/price/PricePolicy.java
> +}
맞아요 오버엔지니어링은 항상 조심해야해요. 제 기준은 최대한 오버엔지니어링을 하지 않는거에요. 열심히 시간을 쏟았는데 기능이 고도화 되지 않는 경우를 몇번 겪다보니.. ㅋㅋㅋ

2023-05-24 20:46 UTC, toneyparky commented on src/main/java/subway/application/price/LineExtraFeePricePolicy.java
> +    private final LineDao lineDao;
좋은 고민이네요. 제가 현업의 관점으로 도메인을 분석하여 이런 결론을 내렸지만 우테코는 학습을 하는 과정이기에 여러가지 시도를 해보는게 좋다 생각해요. 레벨 3 프로젝트를 진행하실 때에도 `개발 기한`이라는 현실적인 문제를 고려하여 제가 제시한 관점과 학습에 대한 욕구의 밸런스를 잡으시면 좋겠어요..!

2023-05-24 20:46 UTC, toneyparky commented on src/main/java/subway/domain/discount/Age.java
> +public class Age {
`편의성을 위해서 Station도 해당 방식으로 하면 어떨까 싶었는데` Station이 아닌 Age 말씀이시겠죠~?

도메인 레이어를 보호하는건 요구사항에 따른 변경을 최소화하고 프로젝트의 정책을 코드로 쌓을 수 있는 방법이에요. 개발자마다 사상은 다르겠지만 이를 지키는게 장기적으로 좋다고 배웠고 그렇게 하고 있습니다~!

2023-05-24 20:46 UTC, toneyparky commented on src/main/java/subway/ui/PathController.java
> +        Price discountPrice = ageDiscountService.discount(price, age);
글렌의 사고의 흐름을 적어주셔서 감사해요..! 저도 우선은 글렌과 같이 구현했을 것 같아요!

기존 1 단계에서는 없던 경로라는 도메인이 2, 3 단계에서는 추가된거라 보여요. (도메인 객체와는 다른, `개념`이라는 의미의 도메인이에요) 요금도 일종의 도메인인데 경로에 포함되어서 의미가 있다고 보았구요. 

조금 더 나아가보자면 언급해주셨듯 경로라는 도메인에 요금이 포함되었으리라 쉽게 떠오르지 않을 수 있어요. 요 부분은 경로가 단순한 경로가 아닐 수도 있겠다 싶어요. 요금도 함께 반환해주니까요. 이런 면에서는 `PathWithPriceService` 와 같은 서비스에서 `PathService`, `PriceService`를 가지고 있고 두 서비스가 협업하여 행위를 할 수도 있겠어요. 더 명확하게 표현하는거죠. 

`PathWithPriceService.getShortestPath()`, `PathWithPriceService.getCheapestPath()` 등의 유즈케이스가 있을 수도 있겠네요. 그리고 서비스가 서비스를 가지는 구성은 어색할 수 있지만 자주 사용한답니다~

2023-05-24 20:46 UTC, toneyparky commented on src/main/java/subway/domain/price/Price.java
> +        return new Price(this.amount.add(price.amount));
굳굳~ 돈을 관리할 때에는 사이드 이펙트가 나면 안되기에 말씀하신 방법이 좋죠. 또한 환율까지 고려한 돈 객체로 발전할 수도 있으니 객체화하는게 좋다고 생각합니다. `Zero`라는 이름으로 명확히 생성자 표현해주신 부분도 굳!

2023-05-24 20:50 UTC, toneyparky approved these changes
안녕하세요 글렌 😁
협업 미션으로 바쁜 와중에서도 코멘트 확인하시고 답변 달아주셔서 감사해요! 
글렌의 생각을 들을 수 있어서 좋았습니다. 저도 제 생각을 남겼으니 확인 부탁드려요...!

지하철 미션은 난이도가 있었지만 깔끔하게 잘 마무리된 것 같아 기분이 좋네요!
시간이 남으면 이야기 나눴던 엔티티와 도메인과 관련된 리팩터링도 해보십셥~
머지할게요 고생 많으셨습니다!!!

2023-05-24 20:51 UTC, merged