[3단계 - 요금 정책 추가] 주노(최준호) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #199
Opened 2023-05-22 08:23 UTC by Choi-JJunho

2023-05-22 09:29 UTC, sonypark requested changes
주노 안녕하세요.
3단계 빠르게 구현해주셨네요!👍
간단한 코멘트 남겼으니 확인 부탁드려요!

2023-05-22 09:29 UTC, sonypark commented on src/test/java/subway/domain/AgePolicyTest.java
> +                .isEqualTo(agePolicy);
- 경계값 테스트 💯
- 유효하지 않은 나이가 들어왔을 때에 대한 테스트도 있으면 좋겠네요

2023-05-22 09:29 UTC, sonypark commented on src/main/java/subway/domain/AgePolicy.java
> +    BABY(age -> age >= 0 && age < 6,
할인률에 대한 값도 상수로 빼도 될 것 같네요 : )

```java
TEENAGER_DISCOUNT_RATE = 0.7;
CHILDREN_DISCOUNT_RATE = 0.5;
```

2023-05-22 09:29 UTC, sonypark commented on src/main/java/subway/domain/AgePolicy.java
> +                .filter(range -> range.ageRange.test(age))
이펙티프자바에 보면 정적팩토리 메서드 네이밍 관련해서 다음과 같은 예시를 보여주는데요.
주노만의 네이밍 기준이 있을까요~?

```
from: 매개변수를 하나 받아서 타입의 인스턴스를 반환하는 형변환 메서드
Date d = Date.from(instance)

of : 여러 매개변수를 받아 적합한 타입의 인스턴스를 반환하는 집계 매서드
set<Rank> faceCards = EnumSet.of(JACK,QUEEN,KING)
```

https://namget.tistory.com/entry/Effective-Java-%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C-%EC%9E%90%EB%B0%94-3e-1

2023-05-22 09:29 UTC, sonypark commented on README.md
> +
👍

2023-05-23 11:59 UTC, Choi-JJunho commented on src/main/java/subway/domain/AgePolicy.java
> +                .filter(range -> range.ageRange.test(age))
아..! 이거 자주 실수하는 부분인데... 짚어주셔서 감사합니다 😂

2023-05-23 14:04 UTC, sonypark approved these changes
주노 안녕하세요! 3단계까지 잘 마무리하셨네요.👍
고생 많으셨어요!! 마지막 미션까지 화이팅입니다!👏👏👏

2023-05-23 14:04 UTC, merged