[2단계 - 경로 조회 기능] 키아라(김도희) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #202
Opened 2023-05-22 08:44 UTC by kiarakim

안녕하세요 에단.

최단 경로 조회 기능을 구현하는 부분에서 많이 막혀서 크루들에게 도움을 받느라 리뷰 요청이 늦었습니다.

1단계 마지막에 받은 피드백을 거의 반영하지 못해 아쉽지만 미션 종료 후 시간을 내어 반영해보겠습니다.
리뷰 잘 부탁드립니다.

2023-05-22 12:35 UTC, Laterality requested changes
안녕하세요 키아라.

시간이 많지 않았을텐데 코드가 많이 수정됐네요.

코멘트 남겨드린 부분 확인 부탁드려요.

일부 테스트가 실패하고 있는데, 함께 확인해주세요.

2023-05-22 12:35 UTC, Laterality commented on src/main/java/subway/controller/LineController.java
> +		return ResponseEntity.created(URI.create("/lines/" + id)).build();
유효한 URL일까요?

2023-05-22 12:35 UTC, Laterality commented on src/main/java/subway/dao/LineDao.java
> +			.findAny();
이 메서드에서만 다른 파라미터 매핑 방식을 사용하신 이유가 있을까요?

2023-05-22 12:35 UTC, Laterality commented on src/main/java/subway/dto/response/LineResponse.java
> +	private final Long lineId;
래퍼 클래스를 사용할 필요가 있을까요?

2023-05-22 12:35 UTC, Laterality commented on src/main/java/subway/service/StationService.java
> +	public StationResponse findStationEntityById(final Long id) {
메서드의 이름과 반환 타입이 일치할까요?

2023-05-22 12:35 UTC, Laterality commented on src/main/java/subway/service/SubwayService.java
> +	@Transactional(readOnly = true)
메서드 사이는 한 줄씩 띄우면 어떨까요?

2023-05-22 12:35 UTC, Laterality commented on src/test/java/subway/domain/subway/PathTest.java
> +import static subway.fixture.LinesFixture.*;
와일드카드 import는 지양해주세요([참고](https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports)).

2023-05-22 12:35 UTC, Laterality commented on src/test/java/subway/service/LineServiceTest.java
> +	@DisplayName("노선 생신 서비스 테스트")
"갱신"일까요?

2023-05-24 07:05 UTC, kiarakim commented on src/main/java/subway/dto/response/LineResponse.java
> +	private final Long lineId;
음,, 응답은 DB에서 가져온거니까 null 고려를 하지 않아도 될 것 같으니 사용할 필요가 없을 것 같습니다..

2023-05-24 07:14 UTC, kiarakim commented on src/main/java/subway/service/StationService.java
> +	public StationResponse findStationEntityById(final Long id) {
앗 아니요 Entity를 Response로 바꿔주어씁니다.

2023-05-24 07:20 UTC, kiarakim commented on src/main/java/subway/service/SubwayService.java
> +	@Transactional(readOnly = true)
넵!

2023-05-24 07:23 UTC, kiarakim commented on src/test/java/subway/service/LineServiceTest.java
> +	@DisplayName("노선 생신 서비스 테스트")
네 맞아요.. 오타가 있었네요ㅠ

2023-05-24 07:38 UTC, kiarakim commented on src/test/java/subway/domain/subway/PathTest.java
> +import static subway.fixture.LinesFixture.*;
넵..! 자동 정렬 단축키를 누르면 자동으로 import되는 것을 놓쳤네요

2023-05-24 08:24 UTC, kiarakim commented on src/main/java/subway/controller/LineController.java
> +		return ResponseEntity.created(URI.create("/lines/" + id)).build();
음~ lines/id로 GET하는 API가 없어서 유효하다고 볼 수 없을 것 같아요.
lines/lineName으로 GET요청 API가 있으니 차라리 lines/lineName으로 POST 하는 게 좋을 것 같습니다!

2023-05-24 08:48 UTC, kiarakim commented on src/main/java/subway/dao/LineDao.java
> +			.findAny();
그건 아닌데 전체적으로 일관성이 없어보이긴 하네요..
수정하는 게 좋을 것 같아요

2023-05-27 01:24 UTC, Laterality approved these changes
안녕하세요 키아라.

피드백 잘 반영해주셨어요.

이번 미션은 이만 머지하도록 하겠습니다.

남겨드린 피드백은 다음 미션 진행하면서 참고해주세요.

고생 많으셨습니다. 마지막까지 화이팅하세요.

2023-05-27 01:24 UTC, Laterality commented on src/test/java/subway/domain/subway/PathTest.java
> +import static subway.fixture.LinesFixture.*;
`LineControllerIntegrationTest`에도 하나 있네요~

2023-05-27 01:24 UTC, Laterality commented on src/main/java/subway/dao/LineDao.java
> +		}
`lineId`가 일치하는 엔티티가 없으면 null이 반환될까요?

2023-05-27 01:24 UTC, Laterality commented on src/main/java/subway/service/LineService.java
> +	public long findIdByName(final String lineName) {
이곳엔 `@Transactional` 어노테이션이 없어도 될까요?

2023-05-27 01:24 UTC, Laterality commented on src/main/java/subway/service/StationService.java
> +		return stationRepository.insertStation(new Station(stationCreateRequest.getName()));
이미 존재하는 역 이름으로 역을 추가하려고 하면 어떻게 될까요?

2023-05-27 01:24 UTC, Laterality approved these changes
안녕하세요 키아라.

피드백 잘 반영해주셨어요.

이번 미션은 이만 머지하도록 하겠습니다.

남겨드린 피드백은 다음 미션 진행하면서 참고해주세요.

고생 많으셨습니다. 마지막까지 화이팅하세요.

2023-05-27 01:24 UTC, merged