[3단계 - 경로 조회 기능] 헤나(박현서) 미션 제출합니다
woowacourse/jwp-subway-path pull request #211
Opened 2023-05-23 14:10 UTC by hyena0608

안녕하세요 현구막 !
3단계 리뷰도 잘 부탁드립니다 😄

요구사항을 살짝만 변경해서 구현해봤습니다..!
- 요금 할인
  - 승객별(성인, 청소년, 어린이, 아기) 할인 정책
- 요금 부과 정책
  - 기본 요금 정책 (1,250원)
  - 노선별 거리당 추가 요금으로 계산한다.
    - ex) 1호선_5km당_1,000원_요금_추가 -> 1호선 10km = 2,000원
    - ex) 1호선_5km당_1,000원_요금_추가, 2호선_10km당_1,500원_요금_추가 -> 1호선 10km, 2호선 10km = 3,500원

```java
class RouteIntegrationTest extends ControllerTestConfig {

 void 출발역과_도착지가_있을_때_환승을_2번하는_상황에서_최단_경로와_금액을_구한다() {
        final Long 파랑_노선_식별자값 = 노선을_저장한다("1", "파랑");
        final Long 초록_노선_식별자값 = 노선을_저장한다("2", "초록");
        final Long 주황_노선_식별자값 = 노선을_저장한다("3", "주황");

        // === 파랑_노선, 1km당, 100원 요금 추가 ===
        // === 초록_노선, 5km당, 500원 요금 추가 ===
        // === 주황_노선, 10km당, 1,000원 요금 추가 ===
        노선_추가_비용_정책을_수정한다("100", 1, 파랑_노선_식별자값);
        노선_추가_비용_정책을_수정한다("500", 5, 초록_노선_식별자값);
        노선_추가_비용_정책을_수정한다("1000", 10, 주황_노선_식별자값);

        StationAssured
                .클라이언트_요청()
                    .역과_구간을_등록한다(구간_요청_데이터("A", "B", 파랑_노선_식별자값, 1))
                    .역과_구간을_등록한다(구간_요청_데이터("B", "C", 파랑_노선_식별자값, 2))
                    .역과_구간을_등록한다(구간_요청_데이터("C", "D", 파랑_노선_식별자값, 3))
                    .역과_구간을_등록한다(구간_요청_데이터("D", "E", 초록_노선_식별자값, 1))
                    .역과_구간을_등록한다(구간_요청_데이터("E", "F", 초록_노선_식별자값, 2))
                    .역과_구간을_등록한다(구간_요청_데이터("F", "G", 주황_노선_식별자값, 10));

        LineAssured
                .클라이언트_요청()
                    .노선을_조회한다(파랑_노선_식별자값)
                .서버_응답_검증()
                    .노선이_조회된다(파랑_노선_식별자값, "1", "파랑", List.of("A", "B", "C", "D"));

        LineAssured
                .클라이언트_요청()
                    .노선을_조회한다(초록_노선_식별자값)
                .서버_응답_검증()
                    .노선이_조회된다(초록_노선_식별자값, "2", "초록", List.of("D", "E", "F"));

        LineAssured
                .클라이언트_요청()
                    .노선을_조회한다(주황_노선_식별자값)
                .서버_응답_검증()
                    .노선이_조회된다(주황_노선_식별자값, "3", "주황", List.of("F", "G"));

        RouteAssured
                .클라이언트_요청()
                    .최단경로와_총금액_조회한다(20, "A", "G")
                .서버_응답_검증()
                    .최단_경로_조회_검증(
                            최종_경로_정보_응답("A", "G",
                                    List.of("D", "F"),
                                    List.of(중간_경로_응답("A", "B", "1", 1),
                                            중간_경로_응답("B", "C", "1", 2),
                                            중간_경로_응답("C", "D", "1", 3),
                                            중간_경로_응답("D", "E", "2", 1),
                                            중간_경로_응답("E", "F", "2", 2),
                                            중간_경로_응답("F", "G", "3", 10)
                                    ), 19, "2850")); // === 기본 요금 + 추가 요금 - 할인 요금 ===
    }
}
```

## 요금 계산 관련 기능

- 첫 노선 등록시 노선별 거리당 추가 요금 정책을 무료 상태로 등록합니다.
- 노선별 거리당 추가 요금 정책은 수정할 수 있습니다.

- 요금 계산 플로우
  - 최단 경로(Route)를 조회한다.
  - 최단 경로를  FareInfo로 변환하여 요금 계산을 진행한다.
    - ExpenseComposite (프로토타입 빈)
      - DefaultExpensePolicy (싱글톤 빈)
      - LineExpensePolicy (객체)
    - DiscountComposite (싱글톤 빈)
      - PassengerDiscountPolicy (싱글톤빈)

![image](https://github.com/woowacourse/jwp-subway-path/assets/82203978/c73f23ea-fb91-49e2-8bba-0d5a0fa95747)

## 요금 계산 고려한점

- 고려한 점
  - 싱글톤 빈의 상태가 변경되지 않도록 구현했습니다.
  - 클라이언트의 요금 계산 요청이 들어올 때 노선별 거리당 추가 요금 정책(LineExpensePolicy)를 데이터베이스에서 조회하여 객체를 생성하여 이용합니다.
  - ExpenseCompose를 프로토타입 빈으로 만들어서 빈이 아닌 일반 객체로 이용하고 있습니다.
 
![image](https://github.com/woowacourse/jwp-subway-path/assets/82203978/4a8d68ac-74b6-4aa1-af2b-9e62599e71ba)

![image](https://github.com/woowacourse/jwp-subway-path/assets/82203978/b26da026-f226-4e80-a3a6-e9bf86520045)

- 문제점
  - 클라이언트의 요청마다 정책을 데이터베이스에서 조회해야 합니다. (비효율적입니다.)
  - 클라이언트의 요청마다 ExpenseComposite을 생성해야 합니다. (비효율적입니다.)
- 해결 방법
  - ExpenseComposite을 싱글톤 빈으로 두고 상태를 개발자가 관리합니다. (혹시나 위험하지 않을까 고민됩니다. 🤔)

![image](https://github.com/woowacourse/jwp-subway-path/assets/82203978/75d2ba01-ac4a-4679-9a41-5282de8f9290)
 
---

현재 구현된 코드는 ExpenseComposite을 프로토타입 빈으로 만들어서 클라이언트 요청마다 데이터베이스에 접근해서 요금 계산을 진행합니다.

이것이 비효율적인 것을 알고 있지만 해결하기 위해서는 ExpenseComposite을 싱글톤 빈으로 두고 상황에 맞게 ExpenseComposite의 상태를 관리하면 됩니다.

다만 싱글톤 빈이기 때문에 상태가 잘못된다면 큰 위험이 발생할 수 있어서 개발자가 직접 상태를 수정해도 좋을지 잘 모르겠습니다. 🤔

2023-05-24 16:37 UTC, Hyeon9mak requested changes
안녕하세요 헤나, 3단계 진행 고생하셨어요.
미션 요구사항인 요금 정책이나 할인 정책 반영은 모두 달성된 것 같아요! 👍 

구현 방법에 대해서만 이야기를 나눠보면 될 것 같은데...
요금 정책과 힐안 정책이 spring bean 으로 등록되어야 하는 이유를 이해하지 못했어요. 🙏 

고민하신 부분을 정성스레 공유해주셔서 저도 최대한 고민 해봤는데,
아무래도 헤나의 설명이 더 필요할 것 같아요... 😭 
코멘트에 질문 남겼으니 확인 후 설명 부탁드려요...!

2023-05-24 16:37 UTC, Hyeon9mak commented on src/main/java/subway/application/RouteService.java
> +    private final StationRepository stationRepository;
`RouteService` 와 `CalculateFareService` 는 같은 `application` 패키지에 속해서
같은 계위를 나타내는 것 같은데요, 이 때 발생할 수 있는 문제점은 어떤 것들이 있을까요?
https://hyeon9mak.github.io/legacy-system-refactoring-techniques/#1-%EC%9D%98%EC%A1%B4%EC%84%B1%EC%9D%84-%ED%95%9C-%EB%B0%A9%ED%96%A5%EC%9C%BC%EB%A1%9C-%EC%A0%95%EB%A6%AC%ED%95%98%EB%9D%BC

2023-05-24 16:37 UTC, Hyeon9mak commented on src/main/java/subway/application/RouteService.java
> +        final List<Line> lines = lineRepository.findAll();
- `getStationOrThrowException` 라는 명칭을 가졌다면, `getStationOrThrowException` 메서드 내부에서 메세지를 결정해줄 수 있지 않을까요?
- 메세지에 '출발역', '도착역' 대신에 검색한 역 명칭을 나타내주면 사용자가 자신이 입력한 출발역, 도착역에 대해 인지할 수 있겠네요!

2023-05-24 16:37 UTC, Hyeon9mak commented on src/main/java/subway/repository/FareRepository.java
> +    }
request scope 로 생성된 `ExpenseComposite` 이 쓰이기 시작하는 지점이 여긴 것 같은데,
당장 코드를 봐서는 request scope bean 의 메리트를 잘 모르겠어요.
bean 이 아닌 일반 인스턴스로 생성하는 것 대비 어떤 장점이 있는 걸까요?

2023-05-24 16:37 UTC, Hyeon9mak commented on src/main/java/subway/domain/fare/discount/DiscountComposite.java
> +    }
음... 사실 `DiscountComposite` 도 꼭 Bean 등록이 필요한건지 잘 모르겠어요..!
헤나의 설명이 필요해요.

2023-05-24 16:37 UTC, Hyeon9mak commented on src/main/java/subway/config/fare/FarePolicyConfig.java
> +                passengerDiscountPolicy()
현재 `DiscountComposite` 과 `ExpenseComposite` 을 bean 으로 사용하는 것이
일반 인스턴스를 생성해서 관리하는 것 대비 어떤 메리트가 있는 걸까요?
제가 코드를 읽으면서 느낀 점은 "IoC 덕분에 통합 테스트 작성이 편리하다." 정도인거 같은데,
어떤 메리트가 더 있는지 설명해주시면 추가 리뷰가 가능할 것 같아요.

2023-05-25 23:52 UTC, hyena0608 commented on src/main/java/subway/repository/FareRepository.java
> +    }
`ExpenseComposite`에 싱글톤 빈으로 들어가는 `DefaultExpensePolicy`가 있습니다.

`DefaultExpensePolicy`는 기본 요금 정책으로 모든 사용자가 공통으로 사용하고 있습니다.

때문에 Singleton Bean으로 등록해서 비용을 줄이려고 했습니다.

2023-05-26 00:32 UTC, hyena0608 commented on src/main/java/subway/domain/fare/discount/DiscountComposite.java
> +    }
`DiscountComposite`은 singleton bean으로 이용되기 때문에 효율적이라고 생각했습니다.

직접 singleton 객체로 만들어 이용할 수도 있지만 IoC Container가 관리해주는 편이 더 안전하고 개발자 입장에서도 간편해서 bean으로 등록했습니다.

2023-05-26 00:42 UTC, hyena0608 commented on src/main/java/subway/config/fare/FarePolicyConfig.java
> +                passengerDiscountPolicy()
직접 싱글톤 객체로 만들어 이용하는 것보다 bean으로서 IoC Container로부터 의존성 주입 받아 사용하는 편이 개발자 입장에서 안전하고 사용하기도 편하다고 생각해서였습니다.

bean으로 등록하는 이유에 대해서 검색해봤을 때도 의존성 주입이 가장 큰 메리트라고 생각합니다.

2023-05-26 08:21 UTC, hyena0608 commented on src/main/java/subway/application/RouteService.java
> +    private final StationRepository stationRepository;
![image](https://github.com/woowacourse/jwp-subway-path/assets/82203978/c0bf285f-bc6f-4b94-92ff-eebcf0734b2b)

발생할 수 있는 문제
- Service가 Service를 의존할 경우
  - 트랜잭션을 신경써야하는 경우가 생긴다.
  - 한 Service를 수정할 경우 의존하고 있는 Service의 코드도 수정해야 한다.
  - 다른 Service 내부 구현을 알고 있어야 합니다.

위와 같이 순환하던 구조를 아래와 같이 수정했습니다.

삭제 파일
- CalculateFareService

추가 파일
- FareCompositeRepository

![image](https://github.com/woowacourse/jwp-subway-path/assets/82203978/14c93ad6-e6f9-4c42-aea0-3bfe6e54f5c6)

2023-05-26 08:29 UTC, hyena0608 commented on src/main/java/subway/application/RouteService.java
> +        final List<Line> lines = lineRepository.findAll();
인텔리제이로 메서드 추출해서 했는데 저렇게 됐다는 인식을 못하고 지나갔네요 🥲
수정했습니다 !

```java
    private Station getStationOrThrowException(final String stationName) {
        return stationRepository.findByStationName(stationName)
                .orElseThrow(() -> new IllegalArgumentException(stationName + " 이름으로 조회된 출발역이 존재하지 않습니다."));
    }
```

2023-05-28 00:27 UTC, Hyeon9mak commented on src/main/java/subway/application/RouteService.java
> +    private final StationRepository stationRepository;
> - 트랜잭션을 신경써야하는 경우가 생긴다.
> - 다른 Service 내부 구현을 알고 있어야 합니다.

💯 👍

2023-05-28 01:11 UTC, Hyeon9mak approved these changes
안녕하세요 헤나, 정성스러운 의견 공유 감사해요.

제가 헤나의 코멘트를 제대로 이해한게 맞다면, bean 을 이용하신 대부분의 이유가 성능 때문인 것 같은데요.
말씀해주신 부분들에 대해서는 GC 를 더 신뢰하셔도 괜찮지 않을까.. 라는 생각이 들어요.
싱글톤의 경우 static 으로 만들어낼 수 있고, request scope 는 매 request 마다 인스턴스를 만들어서 해결할 수 있죠.

"spring bean 을 이용하는게 성능적으로 더 유리할 것 같다." 는 설득력이 조금 아쉬운 것 같아요. 
"정말 성능 테스트를 진행해보니 spring bean 이 더 빨랐다." 혹은
"spring bean 이 아주 살짝 느렸지만, 그것 대비 의존성 주입이 편해진다는 큰 장점이 생겼다." 와 같은
구체적인 근거가 있었다면 더 쉽게 이해되었을 것 같아요. 😄 

사실 제가 생각하는 spring ioc 의 컨셉은 "애플리케이션을 구동하는데 필요한 복잡한 설정들은 모두 spring 에게 맡기고, 개발자는 비즈니스 문제 해결에만 집중한다." 에요.
때문에 핵심 비즈니스 로직을 spring bean 을 통해 관리한다는 점이 계속해서 마음에 걸렸어요.

이전 코멘트를 남길 때 생각은 아래와 같았어요.
'애플리케이션을 구동하는데 필요한 정보만 spring 에게 제어권을 넘기는게 낫지 않을까?'
'비즈니스 자체를 해결하는 것도 어려운데, 거기에 프레임워크에 의존적인 코드를 넣어서 복잡도를 올려야할까?'

그렇지만 헤나가 작성해주신 코멘트를 읽으면서 아래와 생각이 들더라구요.
'과연 우리가 자바를 이용한 웹 애플리케이션을 만들 때 스프링을 제외할 수 있을까?'
'앞으로도 10년 이상 대체되지 않을 프레임워크라면, 꼭 분리해서 사용할 필요가 있을까?'
'오히려 그걸 비즈니스 로직에 까지 적극적으로 활용할 줄 아는게 정말 개발을 잘하는게 아닐까?'

어쩌면 너무 닫힌 생각을 갖고 있던게 아닐까 반성하게 되었어요. 🙏 
헤나의 다양한 시도 덕분에 저도 여러가지 시야를 배웁니다 🙇‍♂️ 

몇 가지 간단한 코멘트만 남겼어요. 다음 미션 진행에 참고해주세요.
미션 마지막까지 고생 많으셨어요! 레벨2 마지막 미션도 화이팅입니다 💪

2023-05-28 01:11 UTC, Hyeon9mak commented on src/main/java/subway/application/RouteService.java
> +    }
"출발역이" 말고 다른 표현이 가능하겠네요 😉

2023-05-28 01:11 UTC, Hyeon9mak commented on src/main/java/subway/application/request/CreateLineRequest.java
> +    @NotBlank(message = "노선 색상은 공백일 수 없습니다.")
`@NotBlank` 어노테이션은 null 또한 허용하지 않아요.
때문에 `@NotNull` 어노테이션을 제거해줄 수 있겠네요.

2023-05-28 01:11 UTC, Hyeon9mak commented on src/main/java/subway/dao/entity/LineExpenseEntity.java
> +    }
입력되는 파라미터들을 (특히나 문자열은) 상수로 관리해주면 조금 더 직관적인 의미 부여가 가능하겠네요!

2023-05-28 01:11 UTC, Hyeon9mak commented on src/main/java/subway/domain/PassengerType.java
> +    ADULT(age -> 19 <= age);
경계값 테스트 코드가 작성되면 좋을 것 같아요. 현재 5살은 탑승이 불가능해보이네요.

2023-05-28 01:11 UTC, Hyeon9mak commented on src/main/java/subway/domain/vo/Money.java
> +    public static final Money ZERO = new Money(new BigDecimal("0"));
```suggestion
    public static final Money ZERO = new Money(BigDecimal.ZERO);
```

2023-05-28 01:11 UTC, Hyeon9mak commented on src/main/java/subway/domain/fare/expense/DefaultExpensePolicy.java
> +    private static final Money DEFAULT_EXPENSE = Money.from("1250");
int, long 타입으로 만들 수 있는 생성자나 팩터리 메서드를 만들어줘도 좋겠네요.

```java
    public Money(final long value) {
        this(new BigDecimal(value));
    }

    public static Money from(final long value) {
        return new Money(new BigDecimal(value));
    }
```

2023-05-28 01:11 UTC, Hyeon9mak commented on src/main/java/subway/domain/route/RouteEdge.java
>      }
😉 👍

2023-05-28 01:11 UTC, Hyeon9mak commented on src/main/java/subway/domain/vo/Percent.java
> +    public static final Percent PERCENT_0 = new Percent(BigDecimal.valueOf(0));
음.. 이정도면 enum class 도..?

2023-05-28 01:11 UTC, merged