[1단계 - 지하철 정보 관리 기능] 제나(위예나) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #25
Opened 2023-05-11 08:16 UTC by yenawee

안녕하세요 검프!
1단계 리뷰 요청드립니다!

이번 미션은 너무 어려웠습니다..
우선 기존 구상했던 설계가 계속 바뀌다보니 코드 구현도 계속 바뀌게 되어서 더 어렵다고 느꼈던 거 같아요

미션 요구사항 중 역 삭제 기능은 시간 부족으로 구현하지 못했고 추가, 조회 기능만 구현되어 있습니다!

또한 객체지향 코드와 너무 멀어져버렸네요..
지금 보니 Dao 추상화도 안되있어서 DB 종속적이고 예외 처리도 아직 부족하고 메소드 분리도….

미션 구현하면서는 도메인을 Entity 와 동일하게 가져갈지 아니면 객체를 참조로 가지고 있을지가 가장 고민이었습니다.
예를 들어서 Section 도메인이 Station 을 가지고 있어야 하는지, 테이블과 동일하게 id 를 가지고 있을지 고민하다가 구현의 편의를 위해서 id 를 가지고 있게 했는데 그러다보니 List\<Section\> 을 List\<Station\> 으로 변환하는게 어려워지더라구요..
또한 도메인에서 PK 인 id 를 가지고 있지 않게 하다보니 DB 작업을 할 때 불편했던 경우도 있었습니다. (업데이트한 Section 구간을 DB 에 저장할 때)

시간 관리 실패 및 실력 부족으로 너무 미흡한 코드를 제출하게 되어서 죄송합니다..🥺
최대한 내일까지는 1단계 기능 구현 완료하겠습니다

감사합니다!

참고 : 역 추가 인수테스트들이 auto_increment 값인 id 들은 롤백이 안되어서 한번에 돌리면 실행이 안되고 각각 돌려야 테스트가 통과가 됩니다…😥

2023-05-12 14:01 UTC, giantim requested changes
제나 안녕하세요! 리뷰어 라빈입니다 👋
이번에 난이도가 매우 높은 미션인데 잘 구현해 주셨습니다 👍 아직 시간이 부족하셔서 구현못한 부분에 대해서는 리뷰 과정에서 계속 추가해봐도 좋을것 같아요! 관련해서 테스트 코드도 한번 보강해보면 좋을것 같습니다

2023-05-12 14:01 UTC, giantim commented on src/main/java/subway/application/SectionService.java
> +//        currentLineSections.removeStation(stationId);
아직 삭제에 대해서는 구현이 안되신걸까요? 😉

2023-05-12 14:01 UTC, giantim commented on src/main/java/subway/domain/StationConverter.java
> +public class StationConverter {
static 메소드만 제공하는 클래스는 외부에서 인스턴스를 생성하지 못하도록 제한해볼까요?

2023-05-12 14:01 UTC, giantim commented on src/main/java/subway/ui/ControllerAdvice.java
> +    private static final Logger logger = LoggerFactory.getLogger(ControllerAdvice.class);
스프링에서 정의하는 advice의 의미에 대해서 다시 생각해보면 어떨까요? 해당 클래스는 예외 처리를 위한 컨트롤러인데 좀 더 구체적인 이름을 부여해도 괜찮지 않을까요?

2023-05-12 14:01 UTC, giantim commented on src/main/java/subway/domain/PairId.java
> +    private Long StationId;
항상 생성자를 통해 초기화해주는 필드에는 final을 붙여줘도 좋을것 같네요! 😉

2023-05-12 14:01 UTC, giantim requested changes
제나 안녕하세요! 리뷰어 라빈입니다 👋
이번에 난이도가 매우 높은 미션인데 잘 구현해 주셨습니다 👍 아직 시간이 부족하셔서 구현못한 부분에 대해서는 리뷰 과정에서 계속 추가해봐도 좋을것 같아요! 관련해서 테스트 코드도 한번 보강해보면 좋을것 같습니다

2023-05-15 12:48 UTC, yenawee commented on src/main/java/subway/ui/ControllerAdvice.java
> +    private static final Logger logger = LoggerFactory.getLogger(ControllerAdvice.class);
GlobalExceptionHandler 로 이름 변경했습니다!

2023-05-15 12:49 UTC, yenawee commented on src/main/java/subway/domain/StationConverter.java
> +public class StationConverter {
해당 클래스는 없앴지만 동일한 역할을 하는 SortedStations 를 만들어서 생성자를 private 으로 해서 정적팩토리메소드로만 인스턴스가 생성되게끔 제한을 걸었습니다!

2023-05-15 12:49 UTC, yenawee commented on src/main/java/subway/application/SectionService.java
> +//        currentLineSections.removeStation(stationId);
삭제 기능도 구현했습니다!

2023-05-15 12:50 UTC, yenawee commented on src/main/java/subway/domain/PairId.java
> +    private Long StationId;
생성자를 통해 초기화 해주는 필드들에는 final 키워드 추가했습니다!

2023-05-15 16:03 UTC, yenawee commented
안녕하세요 라빈!🙌

저번에 못다한 기능 구현 및 테스트 코드를 보강해서 다시 리뷰 요청 드립니다.

역 추가 메소드가 SectionService 와 Sections 모두에서 아직 깔끔하지 못한 부분이 있으나 기능 구현 후 라빈의 리뷰를 받고 더 리팩토링 해보는게 좋을거같아서 리뷰 요청 드려요!

미션 진행 과정 중에 고민사항을 아래에 공유드립니다!
1. StationDao 클래스에 
```java    
public StationEntity findById(Long id) {
        String sql = "select id, name from STATION where id = ?";
        return jdbcTemplate.queryForObject(sql, rowMapper, id);
    }

 public int findByName(String name) {
        String sql = "select id from STATION where name = ?";
        return jdbcTemplate.queryForObject(sql, Integer.class, name);
    }
```

이런 메소드들이 있는데 해당하는 데이터가 없을 때를 대비해서 예외처리를 try-catch 를 통해 구현하고 Optional 을 반환 해야 할까요?? 지금 ExceptionHandler 에서 SQLException 들을 다 핸들링 해준다고 생각해서 따로 예외처리를 해주지 않았는데 예외 처리를 해주는 것이 좋을지 고민이 됩니다!

2. SectionService Test 를 Mock 을 이용해서 구현을 해봤는데 어떤 것을 검증하면 되는지 감이 잘 안와서 어려움이 있었습니다 조회 메소드는 반환값과 메소드의 역할이 일치해서 작성이 쉬웠으나 역 추가, 삭제 메소드는 반환값이 쿼리의 성공실패 여부와 관련있거나 반환값이 없어서 어떤걸 검증해야 할지 잘 모르겠습니다 그래서 지금 sectionDao 와의 상호작용만을 테스트하게끔만 구현해뒀는데 Mock 테스트에선 보통 어떤것을 검증하는지 알려주시면 감사하겠습니다!! 🙇‍♀️

리뷰 잘 부탁드립니다 🌱

2023-05-16 17:09 UTC, giantim requested changes
제나 안녕하세요! 라빈입니다 👋
기존 코드에서 많은 부분들이 추가됐네요! 요구사항 기능들도 잘 구현해주셔서 정말 고생 많으셨습니다 👍
미션 요구사항대로 최대한 서비스 계층에서 비즈니스 요구사항을 처리하기보단 도메인에 많은 역할과 책임을 주려 설계하신게 보이네요! 👏 그럼 질문주신 내용에 대해 제 의견 남겨드리겠습니다!!

질문 주신 내용을 보면 1번에 대한 고민 때문에 2번 테스트에 대한 고민까지 생겼다고 저는 이해했습니다. 먼저 SqlException으로 DB관련 예외를 처리했을 때 비즈니스적으로, 사용자 향으로 알려야하는 예외와 기술적인 문제로 인해(개발자가 당장 컨트롤 할 수 없는) 발생한 예외가 모두 잡힐거 같아요. 그래서 엔티티가 없는 경우와 같이 사용자의 잘못된 입력이나 비즈니스적으로 사용자에게 알려야 하는 경우에 대해서 처리를 위해 Optional로 반환해서 처리해보는것도 좋은 방법일거 같네요! 그러면 해당 경우들에 대해 실제로 우리가 작성한 코드가 정상동작함을 테스트하기 위해 mock 객체를 이용해 볼 수 있겠죠? ☺️ 제나가 고민하신 방향으로 인해 개선해볼 부분을 찾을 수 있을거 같아요!

그리고 몇 가지 리뷰 더 남겨드렸는데 고민해보고 반영 부탁드리겠습니다! 1단계 미션 화이팅입니다 👏

2023-05-16 17:09 UTC, giantim commented on build.gradle
> +    annotationProcessor 'org.projectlombok:lombok'
롬복을 사용해주셨네요!
혹시 학습 과정에서는 롬복 사용을 지양해보시면 어떨까요? 어노테이션 기반으로 다양한 반복적으로 작성하는 코드를 쉽게 만들어주지만 해당 코드가 왜필요한지에 대해 무감각해질 수 있어 보여서 학습 과정에서 추천드리기 조금 어렵네요 😉

2023-05-16 17:09 UTC, giantim commented on src/main/java/subway/domain/Subway.java
> +public class Subway {
해당 도메인 클래스를 현재 사용하지 않는것 같은데 삭제하면 어떨까요?

2023-05-16 17:09 UTC, giantim commented on src/main/java/subway/domain/Sections.java
> +            if (addDownEndStation(newSection, preStation)) return null;
if 문의 컨벤션을 지켜보면 어떨까요 😉

2023-05-16 17:09 UTC, giantim commented on src/main/java/subway/exception/SectionException.java
> +public class SectionException extends RuntimeException {
도메인에서 반환하는 예외인데 생성할때 담는 메시지 이외로는 어떤 상황인지 구분이 어려운거 같아요.
조금 더 반환하는 상황에 맞게 의미있는 클래스 이름을 부여해보면 어떨까요?

2023-05-16 17:09 UTC, giantim commented on src/main/java/subway/dao/StationDao.java
> +    public int findByName(String name) {
메소드 이름을 조금 더 일관되게 작성해보면 어떨까요? StationEntity를 반환하는 메소드도 ```find~```이고 아이디 int를 반환하는 메소드도 ```find~```여서 헷갈리는거 같아요!
일반적으로 데이터를 반환하지 않고 특정 컬럼만 반환하는 경우 해당 컬럼을 적어주니 아이디를 반환하는 메소드는 ```findId~``` 이런 식으로 시작해보면 어떨까요?
그리고 엔티티의 아이디를 Long으로 정의했고 테이블 아이디 역시 BIGINT로 설정했는데 int를 반환하는 이유가 있으실까요?

2023-05-16 17:09 UTC, giantim commented on src/main/java/subway/service/SectionService.java
> +    private final StationDao stationDao;
모든 서비스 계층에서 DAO를 의존하는 구조네요!
이번 미션 부터는 DAO에 직접 의존이 아닌 repository를 설계하여 추상화를 해보면 어떨까요? 😉
repository를 설계해 추상화를 하여 영속 계층에 대해 세부 구현을 숨길 수 있고 그에 맞게 더 확장성 있는 구조로 작성해보는 연습을 해보면 좋을것 같네요!

2023-05-17 01:50 UTC, yenawee commented on build.gradle
> +    annotationProcessor 'org.projectlombok:lombok'
롬복 사용방법을 최근에 알아서 학습 목적으로 사용했었습니다!
롬복 사용방법이 간단해서 무지성으로 어노테이션만 달아 필요하지 않은 코드를 작성하게될 위험성이 크다는 라빈의 의견에 동의합니다!
근데 처음 적용해봐서 신기하기도 하고,,,,코드가 깔끔해져서 보기 좋기도 하고,,,, 필요한 어노테이션인지 확인 후 달아주는 과정은 거쳤는데  이번 미션에서는 롬복을 사용해보면 안될까욥,,?😯
그래도 지양하는 것이 좋다면 다음 요청때는 제외하겠습니다!!

2023-05-17 02:24 UTC, yenawee commented on src/main/java/subway/dao/StationDao.java
> +    public int findByName(String name) {
- 확실히 같은 find 이름을 쓰는데 반환값이 다르니 헷갈릴 수 있을 거 같네요! findIdByName 으로 수정했습니다
- int 를 반환한 이유는 사실 구현만 먼저 하려다보니 생각없이 작성한 코드였던 거 같습니다. int 로 반환하고 Service 에서 다시 long 으로 바꿔주는 동작을 하고 있었네요..! Long 을 반환하도록 변경했습니다
- 또한 리뷰에 남겨주신대로 데이터테이블에 값이 존재하지 않을 때 서비스가 다른 로직을 처리할 수 있게 하려면 Optional 을 반환해주는 것이 맞는거같아 Optional 반환 후 해당 데이터가 없으면 서비스가 잘못된 요청이 들어왔다고 클라이언트에게 알릴 수 있게 예외를 던지는 식으로 리팩토링해봤습니다

2023-05-17 02:37 UTC, yenawee commented on src/main/java/subway/exception/SectionException.java
> +public class SectionException extends RuntimeException {
Section 에서 다음 구간을 찾지 못할 때, 이전 구간을 찾지 못할때, 상행 종점을 찾지 못할때, 하행 종점을 찾지 못할때는 추가, 삭제, 정렬 시 공통으로 사용되는 부분이 있어서 기존 SectionException 을 사용하고
추가나 삭제 각각에서만 쓰이는 예외는 SectionException을 상속한 SectionInsertionException, SectionRemovalException을 던지게 해봤습니다!

2023-05-17 13:51 UTC, yenawee commented on src/main/java/subway/service/SectionService.java
> +    private final StationDao stationDao;
Service 에 Repository 를 추가해서 DB 에 접근하는 작업은 해당 객체에 책임을 넘겨줘서 추상화를 진행했습니다 !
Service 에선 요청 정보들만 Repository 에 넘겨주었고 Repository 에서 Entity 로 바꿔서 Dao 와 작업 후 도메인 객체를 만들어 다시 Service 에 반환해주는 식으로 구현해서 Service 에선 DB 동작이 어떻게 일어나는지 모르게, Entity 객체를 모르게 하는데 중점을 두었습니다

구현하다보니 의문이 하나 생겼는데 SectionRepository 에서 Section 객체를 만들기 위해 Line, Station 객체가 필요해서 
```java
private Line findLineById(Long lineId) {
        Optional<LineEntity> lineEntity = lineDao.findById(lineId);
        if (lineEntity.isEmpty()) {
            throw new IllegalArgumentException("존재하지 않는 노선입니다");
        }
        return lineEntity.get().toLine();
    }

private Long findStationIdByStationName(String name) {
        return stationDao.findIdByName(name);
    }
```

해당 메소드들이 존재하게 되었는데 사실 이 메소드들은 각각 LineRepository, StationRepository 에 존재하는 상황입니다! 이렇게 중복이 일어나는 경우엔 Dao 가 아닌 Repository 를 갖고 있게 수정해서 해당 메소드들을 재활용 해야 하는 것일까요?? 
(이번 경우엔 SectionRepository 에서 LineRepository 와 StationRepository 를 갖고 있게 해도 되는지)
Repository 에서 다른 Repository 를 알게 해도 될지가 고민입니다....

2023-05-17 15:40 UTC, yenawee commented on src/main/java/subway/domain/Sections.java
> +            if (addDownEndStation(newSection, preStation)) return null;
메소드 분리를 통해서 indent 들여쓰기를 2 이하가 되지 않게끔 수정했습니다!

2023-05-17 15:45 UTC, yenawee commented
안녕하세요 라빈! 🍨

남겨주신 리뷰를 바탕으로 리팩토링을 진행해봤습니다.
이번에 Repository 를 분리하는 과정에서 의문사항이 생겼는데 리뷰 답글에 남겨두었어요!!
링크 : https://github.com/woowacourse/jwp-subway-path/pull/25#discussion_r1196558898

남겨주신 리뷰 덕분에 코드가 한결 깔끔해진 거 같은 느낌이 들어요 감사합니다

이번에도 리뷰 잘 부탁드립니다 🌱

2023-05-18 23:36 UTC, giantim commented on build.gradle
> +    annotationProcessor 'org.projectlombok:lombok'
네 좋아요! 제나가 학습과정에서 롬복 사용에 대해 지양해야하는 부분에 대해서도 공감해주셨고 롬복에 대한 학습을 하신다고 하니 이번 미션에서 사용해보셔도 좋을것 같네요. 다음 미션때 페어와 합의해서 어떤 기술을 사용할지 서로 의견 나누면서 적용해봐도 좋을것 같아요 ☺️

2023-05-18 23:46 UTC, giantim commented on src/main/java/subway/service/SectionService.java
> +    private final StationDao stationDao;
Section을 위한 Line, Station의 조회는 반드시 필요한 상황인거 같아요. 그럼 요구사항이 발전하여 Section을 위한 Line, Station을 특정하게 조회하는 기능들이 LineRepository, StationRepository 등에 생길 수 있겠죠? 이때 LineRepository, StationRepository를 사용하는 다른 클라이언트 입장에서 불필요한 API가 열릴 수 있어요. 그래서 DAO를 이용해 조회하는 구조가 더 적합해 보이네요 😉

2023-05-18 23:47 UTC, giantim approved these changes
제나 안녕하세요! 라빈입니다 👋
남겨드렸던 리뷰에 대해서 많은 고민을 해주시고 그것들을 적용해 보시면서 새로운 고민점도 찾으시고 좋네요 😄 코멘트로 질문 주신 내용에 대해 제 생각 남겨드렸는데요! 다음 단계 진행하시면서 적용할지 고민해보셔도 좋을것 같아요! 고생하셨습니다~

2023-05-18 23:47 UTC, merged