[1단계 - 지하철 정보 관리 기능] 주디(오은비) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #32
Opened 2023-05-11 08:28 UTC by eunbii0213

안녕하세요 조앤!!!!!대박!!
완전 오랜만이에요!! ㅎㅎㅎ 1단계에서 조앤 만났을 때 꼭 다시 만나고 싶다는 얘기를 적었는데 그래서 다시 만난걸까요?! 신기하네요 ㅎㅎㅎ 너무 반가워요! 잘 지내셨죠?

구현을 아직 다 못했지만 마감 시간이라 일단 PR 보냈어요.
구현 다 끝나면 메세지 꼭 드릴게요 그 때 리뷰 부탁드려도 될까요?🥺
이번 미션도 잘 부탁드려요!

2023-05-11 23:48 UTC, seovalue requested changes
안녕하세요 주디! 롱타임노씨예요ㅎㅎ
우선은 스키마 관련 리뷰만 남겼어요~ 요구사항 모두 구현하신 뒤 다시 리뷰 요청 주세요!
미션 요구사항에서 주어진 대로 TDD를 해보시는 것을 추천드려요!

2023-05-11 23:48 UTC, seovalue commented on src/main/resources/schema.sql
> +    next_station bigint null,
STATION에 next_station이라는 정보를 넣어주신 이유가 무엇일까요? STATION은 지하철에서 단순 역을 의미하는 것 같아서요

2023-05-11 23:48 UTC, seovalue commented on src/main/resources/schema.sql
> +    head_station bigint,
id인 경우에는 컬럼명에도 id를 명시하는게 좋지 않을까요?

2023-05-11 23:48 UTC, seovalue commented on src/main/java/subway/domain/Line.java
> +    }
이런 부분 메서드 순서도 신경써보면 좋을 것 같아요~

2023-05-21 08:54 UTC, seovalue approved these changes
안녕하세요, 주디ㅎㅎ 조앤이에요.
우선 기간이 얼마 안남아서~ 1단계는 여기서 머지할게요.
테스트도 보완하시면 좋을 것 같고 남긴 리뷰 전반적으로 2단계 진행하시면서 반영해주시면 좋을 것 같아요~

2023-05-21 08:54 UTC, seovalue commented on src/test/java/subway/domain/DistanceTest.java
> +class DistanceTest {
테스트 깨져요~

2023-05-21 08:54 UTC, seovalue commented on src/test/java/subway/domain/SectionTest.java
> +class SectionTest {
전반적으로 주석되어있는 테스트가 많은데 최종 제출 전 제거해주세요~
그리고 도메인 테스트가 부족한 것 같아요ㅎㅎ

2023-05-21 08:54 UTC, seovalue commented on README.md
> +- []  거리는 양의 정수이다.
완료된 건 체크해주세요~

2023-05-21 08:54 UTC, seovalue commented on docs/README.md
> +# jwp-shopping-cart
왜 두개죵?

2023-05-21 08:54 UTC, seovalue commented on src/main/java/subway/service/StationService.java
> +    }
cud 기능에는 `@Transactional` 어노테이션을 달아주면 어떨까요? 해당 어노테이션이 어떻게 동작하는지도 학습해보세요!

2023-05-21 08:54 UTC, seovalue commented on src/main/java/subway/service/StationService.java
> +        return new StationEntity(null, stationRequest.getName(), null, null, null);
이름만 받는 생성자가 있는 건 어떨까요

2023-05-21 08:54 UTC, seovalue commented on src/main/java/subway/ui/StationController.java
> +    // @GetMapping("/stations/test")
주석 제거해주세요~

2023-05-21 08:54 UTC, seovalue commented on src/main/resources/schema.sql
> +    next_station bigint,
역이 다음역을 알아야하는 이유가 무엇인가요?

2023-05-21 08:54 UTC, seovalue commented on src/main/java/subway/service/LineService.java
> +    }
한 메서드 안에 비즈니스 로직이 너무 긴데 리팩터링해볼까요?

2023-05-21 08:54 UTC, seovalue commented on src/main/java/subway/service/LineService.java
> +    }
private으로 변경해도 될 것 같은데, 한편으로는 이러한 메서드가 LineService에 있어야하는게 맞을까 의문이 드네요 🤔

2023-05-21 08:54 UTC, seovalue commented on src/main/java/subway/service/LineService.java
> +    private void addDownStation(Long lineId, StationRequest stationRequest, Stations lineStations) {
`addDownStation`, `addUpStation` 메서드가 전반적으로 핵심 로직을 담고 있는데 굉장히 길고 가독성이 떨어져요! 중간 삽입, 양 끝 점 삽입에서 공통된 부분과 그렇지 않은 부분을 분리해서 적절히 조건에 따라 적용될 수 있게 리팩터링해보면 좋을 것 같아요!

2023-05-21 08:54 UTC, seovalue commented on src/main/java/subway/domain/Line.java
> +    private static Long sequence = 1L;
무슨 역할인가요?

2023-05-21 08:54 UTC, seovalue commented on src/main/java/subway/domain/Stations.java
> +            if (station.getId() == id) {
id가 일치한다고 해서 다음 역이 존재한다고 볼 수 있나요?

2023-05-21 08:54 UTC, merged

2023-05-21 12:32 UTC, eunbii0213 commented on src/test/java/subway/domain/DistanceTest.java
> +class DistanceTest {
헉!!!!;; Line이랑 Station domain test들이랑 통합 테스트만 돌렸었군요 ㅠㅠ 이런 기본적인 실수를..! 당장 수정하겠습니다! 짚어주셔서 감사해요!!

2023-05-21 12:34 UTC, eunbii0213 commented on src/test/java/subway/domain/SectionTest.java
> +class SectionTest {
넵!! 주석 제거 및 도메인 테스트 보충하겠습니다 ㅎㅎㅎ

2023-05-21 12:34 UTC, eunbii0213 commented on README.md
> +- []  거리는 양의 정수이다.
이런 ㅜㅜ 미션이 너무 급하다 보니 기본적인걸 정말 많이 놓쳤네요... 짚어주셔서 감사합니다!

2023-05-21 12:35 UTC, eunbii0213 commented on docs/README.md
> +# jwp-shopping-cart
아이고~!! 제가 페어랑 짰던 코드를 다 갈아엎고 새로 작성하는 과정에서... ㅠㅠ 기존 기능 목록을 삭제하지 않았나보네요;;ㅠㅠ

2023-05-22 04:56 UTC, eunbii0213 commented on src/main/resources/schema.sql
> +    next_station bigint,
List처럼 역끼리 연결해주기 위함입니다!! 
이렇게 하면 역의 순서 또한 저장할 수 있겠다는 생각이 들어서 역이 다음역을 가지고 있게 구현했습니다!

2023-05-22 05:37 UTC, eunbii0213 commented on src/main/java/subway/service/LineService.java
> +    }
앗 처음엔 LineService에서 필요로하는 친구니까 LineService에 넣어뒀었는데, 다시 생각해보니 이건 Entity의 역할일 수도 있겠네요! Entity가 내부적으로 변환해줘서 return해주면 될 것 같아요! service가 이 과정을 알 필요는 없을 것 같기도 하구요. 짚어주셔서 감사합니다 😊

2023-05-22 07:32 UTC, eunbii0213 commented on src/main/java/subway/domain/Line.java
> +    private static Long sequence = 1L;
메모리에도 Id값을 적용하기 위함입니다!!
생성할 때 마다 DB처럼 Id를 1부터 할당해주는 역할입니다!
그렇지만 서버가 여러대일 때 동시성 문제가 생길 수도 있을 것 같아서 고민되는 부분입니다 ㅜㅜ

2023-05-22 07:47 UTC, eunbii0213 commented on src/main/java/subway/domain/Stations.java
> +            if (station.getId() == id) {
헉 아니요...! 그렇진 않은 것 같습니다.
하행종점역이라면,  다음 역이 존재하지 않을 것 같아요!
이 부분 검증 로직도 추가하겠습니다 😊

2023-05-26 14:31 UTC, seovalue commented on src/main/java/subway/service/LineService.java
> +    private void addDownStation(Long lineId, StationRequest stationRequest, Stations lineStations) {
아하! 이 부분에서 제가 말씀드리고 싶었던 부분은 upStation의 삽입과 downStation의 삽입에서 공통된 부분과 그렇지 않은 부분을 분리해서, 각 `addUpStation`, `addDownStation` 내부를 몇 단계의 메서드로 분리해보면 어떨까?라는 제안이었어요! 전반적으로 비즈니스로직이 길다보니 가독성이 떨어지는 것 같아서요!