[1단계 - 지하철 정보 관리 기능] 저문(유정훈) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #48
Opened 2023-05-11 08:40 UTC by jeomxon

안녕하세요 웨지! 저문입니다 :)
지난 미션과는 다르게 비즈니스 로직에 대해서 더 고민하게 되는 미션이었던 것 같습니다.
엄청 정신없이 진행했던 미션이었기에 빈틈이 많이 드러났을 것 같은데,
다음 리뷰요청 때 꼭 수정하겠습니다!

Service계층에서 로직을 만들기보다 최대한 객체에 메시지를 던져서 해결하려고 시도해봤습니다.
그리고 Service를 create와 delete로 분리해봤는데요.
create와 delete 각각의 로직이 커지게 되어서 하나의 서비스에 있는 것 보다는 분리하는 것이 좋다고 판단해서였습니다.

그리고 테스트를 통합 -> 도메인 -> DAO -> Service -> Controller순으로 작성을 하려고 했었는데,
시간이 부족할 것이라고 판단되어 통합테스트와 도메인까지 밖에 작성을 하지 못했습니다ㅠㅠ

2023-05-12 12:25 UTC, wannte requested changes
안녕하세요, 저문!

쉽지 않은 미션에도 잘 구현해서 마무리 해주셨네요!

도메인 관점에서 한 번 고민해보았으면 해서 Request Changes 남깁니다.
한 번 고민해보시고 재요청 주세요! 꼭 반영해야 하는 것은 아닙니다 :)

2023-05-12 12:25 UTC, wannte commented on src/main/java/subway/application/LineService.java
> +                .map(foundLine -> new LineResponse(foundLine.getId(), foundLine.getName()))
LineDto 라는 Service <-> Dao 계층의 전달 객체를 사용해주셨네요!

계층 간의 이동에 특별한 장점이 없다면(복잡성이 커지기 때문), dto를 사용하는 것은 저는 지양하는 편인데요!
저문이 생각하는 장점은 어떤 것이 있을까요? 어떤 변화에 유리하다면, 그 사례를 들어주셔도 좋습니다.

2023-05-12 12:25 UTC, wannte commented on src/main/java/subway/application/LineService.java
> +        return new LineStationResponse(line.getId(), line.getName(), stationResponses);
실제 DB 구조를 모두 알고 있어야만 이해할수 있는 코드라 저는 생각합니다.

위의 질문에서 LineDto 에 활용의 장점을 질문했었는데요!, 만약 Dao 에서 Line 도메인 객체를 모두 만들어서 전달해보는 try 도 한 번 해보셔서 비교해 장단을 비교해보시면 좋을 것 같아요!

물론, 정답은 없다고 생각합니다.

2023-05-12 12:25 UTC, wannte commented on src/main/java/subway/application/SectionCreateService.java
> +
DB 가 없이 도메인 객체관점에서 코드를 짜본다면 어떤 형식이 될까요? (레벨 1에서 해왔던 방식이라면)
도메인을 먼저 작성해보고, 이 구조에 Dao 를 맞춰본다면 어떨까요?

정답이라 생각하지는 않지만, 도메인 위주의 코드 작성을 이번 미션에서 경험해봤으면 해요!

2023-05-12 12:25 UTC, wannte commented on src/main/java/subway/ui/LineController.java
> +
`GET /lines` 노선 목록 조회 API 만으로도 충분하지 않을까요?

`LineResponse` 하나로 통일하여 복잡성을 줄일 수도 있을 것 같아요.

2023-05-12 12:25 UTC, wannte commented on src/main/java/subway/domain/Line.java
> +        return sections.stream()
수많은 메소드가 구현되었는데요! create, delete 과정에서의 validation 을 위해 사용되는 값들 같습니다.

`Line.addSection(from, to)` 정도로 Line이란 객체에 직접 책임을 줘보는 것은 어떨까요?

2023-05-14 17:20 UTC, jeomxon commented on src/main/java/subway/ui/LineController.java
> +
저는 처음에 아래와 같은 방식을 생각했습니다.
1. 노선들만 존재하는 조회
2. 한 노선에 포함된 역들만 조회
3. 전체 노선과 각 노선에 해당되는 역들을 조회

따라서 1번과 3번의 요청을 분리하여 작성했었습니다.
하지만 기능 요구사항을 보니 1번은 따로 필요없다는 것을 알게되었네요 ㅠㅠ
말씀해주신대로 통일해보겠습니다!

2023-05-17 04:57 UTC, jeomxon commented on src/main/java/subway/application/LineService.java
> +                .map(foundLine -> new LineResponse(foundLine.getId(), foundLine.getName()))
말씀하신대로 DTO를 사용하면서 복잡성이 커진다는 것을 인지하고 있었습니다.
따라서 도메인 DAO와 Repository를 분리하는 작업을 진행해봤는데요.
DAO에서는 db 테이블과 1대1로 매핑되는 Entity를 도입하여 이를 반환하도록 하였습니다.
Repository에서는 Entity를 도메인 객체로 만들어서 반환하도록 하였습니다.
이를 통해서 Service의 복잡한 로직을 단순화 시킬 수 있고, 책임이 확실히 분리할 수 있다는 장점을 가질 수 있었습니다.

2023-05-17 04:59 UTC, jeomxon commented on src/main/java/subway/application/LineService.java
> +        return new LineStationResponse(line.getId(), line.getName(), stationResponses);
말씀해주신대로 Line도메인 객체를 Repository에서 반환하도록 변경해보았습니다~

> https://github.com/woowacourse/jwp-subway-path/pull/48#discussion_r1192277436

해당 코멘트에 생각을 함께 적어두었습니다!!

2023-05-18 15:09 UTC, jeomxon commented on src/main/java/subway/application/SectionCreateService.java
> +
조언 감사합니다 완태!
제가 이번 미션을 통해서 크게 깨달았던 점은 도메인 로직을 작성함으로써 db에 종속적이지 않은 프로그램을 만들 수 있다는 것입니다.
처음부터 도메인에 로직을 작성했더라면 service가 불필요하게 커질 이유가 없었다고 생각했습니다.
db가 없는 프로그램이라고 생각했을 때도 훨씬 자연스럽게 보였습니다.

완태가 말씀해주신 것처럼 도메인 객체 관점에서 코드를 작성한 후,
이 구조에 DAO를 맞춰서 리팩터링 해봤습니다!

2023-05-18 15:10 UTC, jeomxon commented on src/main/java/subway/domain/Line.java
> +        return sections.stream()
> https://github.com/woowacourse/jwp-subway-path/pull/48#discussion_r1197944898
여기 남겨주신 것처럼 도메인 객체 Line이 역할을 하도록 변경해봤습니다.

2023-05-18 15:12 UTC, jeomxon commented
안녕하세요 완태 :)
새로운 시도들을 하다보니 리뷰요청이 많이 늦어지게 되었습니다🥲
아직 작업해야할 목록들이 조금 남아있는데 이번 리뷰요청 이후에 추가로 구현하도록 하겠습니다!

2023-05-18 17:52 UTC, wannte commented on src/main/java/subway/ui/LineController.java
> +
FE 와 협업을 하면서 느끼는 부분은, 가능한 응답값에 형태를 통일하여 코드의 재사용성을 높이는 것을 선호하는 것 같아요 :)

2023-05-18 18:04 UTC, wannte approved these changes
안녕하세요 저문! 피드백 반영 확인했습니다.

많은 고민을 한 것 같네요! 고생하셨습니다 👍 
간단한 피드백 몇 가지 남겼는데, 다음 단게 진행하면서 확인 부탁드려요!

2023-05-18 18:04 UTC, wannte commented on src/main/java/subway/application/SectionService.java
> +        Section section = new Section(leftStation, rightStation, distance);
생성자 오버로딩으로 한 줄 간소화도 가능해보이네요. 자연스러울 것 같기도 하고요

2023-05-18 18:04 UTC, wannte commented on src/main/java/subway/application/SectionService.java
> +        sectionRepository.saveAllByLineId(lineId, line.getSections());
section 전체를 삭제하고 저장하는 로직을 service layer 의 책임일까요?

`lineRepository.save(line)` 정도로 구현하고, 어떻게 저장할지에 대한 결정은 repository 에 넘겨주는 것은 어떨까요?

2023-05-18 18:04 UTC, wannte commented on src/main/java/subway/application/SectionService.java
> +        sectionRepository.saveAllByLineId(lineId, line.getSections());
위의 피드백을 동일하게 적용해 볼 수도 있을 것 같아요.

2023-05-18 18:04 UTC, wannte commented on src/main/java/subway/domain/Line.java
> +    }
Section의 책임으로 두는 것은 어떨까요?

2023-05-18 18:04 UTC, wannte commented on src/main/java/subway/domain/Line.java
> +        int newSectionDistance = newSection.getDistance();
저는 관련 로직이 복잡해진다면, 해당 역할이 너무 많은 것은 아닌지 고민해보고 분리할 시점이지 않은가 고민해봅니다!

2023-05-18 18:04 UTC, merged

2023-05-22 07:03 UTC, jeomxon commented on src/main/java/subway/domain/Line.java
> +    }
좋은 의견 같습니다!
반영하겠습니다~

2023-05-22 07:34 UTC, jeomxon commented on src/main/java/subway/application/SectionService.java
> +        Section section = new Section(leftStation, rightStation, distance);
distance를 생성하는 책임도 Section에 넘겨주는 방식도 있었네요..!
간소화 하겠습니다~

2023-05-22 08:19 UTC, jeomxon commented on src/main/java/subway/application/SectionService.java
> +        sectionRepository.saveAllByLineId(lineId, line.getSections());
repository에 저장하는 방식에 대한 책임을 넘기니
service에서의 로직이 훨씬 눈에 들어오는 것 같네요.
다만 궁금한 점은 repository의 책임을 어떻게 어디까지 정해야하는지가 궁금합니다.

위와 같은 방식으로 repository에 책임을 넘기는 경우에는 단순히 save하는 것 같지만,
실제 내부적으로는 delete후 save를 하고 있는데요.
이런 경우 여러가지 책임을 가지는 것으로는 보여지지 않나요?

2023-05-22 16:25 UTC, wannte commented on src/main/java/subway/application/SectionService.java
> +        sectionRepository.saveAllByLineId(lineId, line.getSections());
제 개인적인 생각을 적으면 (사람마다 생각은 다를 수 있어요), 

어떤 방식으로 domain 을 persist 할지에 대한 책임을 repository에 줄 것 같아요.

현재 방식은
`(rdb) 전체 delete하고 전체 save 하는 방식` 을 사용하고 있는데,

여러가지 구현체가 가능할 것 같아요.
`(rdb) 다른 값만 찾아서 추가/삭제`
`(nosql, api) 등 그 구현체가 rdb가 아닐 수도 있을 것 같아요`


그 내부 구현보다는, domain 을 persist 한다의 책임으로 보면 어떨까 싶어요!