[1단계 - 지하철 정보 관리 기능] 루쿠(백경환) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #49
Opened 2023-05-11 08:41 UTC by aiaiaiai1

2023-05-13 03:11 UTC, Be-poz requested changes
안녕하세요 루쿠, 파즈입니다.  
미션 잘 확인했습니다. 구현이 미흡한 것은 다음번 요청 때 다 완료하시고 하시면 될 것 같습니다.  
일단 코드에 코멘트는 남겨놨으니 확인해주시면 감사하겠습니다!

2023-05-13 03:11 UTC, Be-poz commented on src/main/java/subway/domain/Line3.java
> +public class Line3 {
Line과 Line3으로 나뉘어져있길레 도메인과 엔티티를 나누려고 하셨던걸까? 했는데 Entity는 별도로 또 있군요. -> 아 LineEntity는 unused로 되어있군요~  

주석으로 처리하면 나중에 놓치기 쉽습니다. ``//TODO`` 이렇게 기록을 해두면  
![image](https://github.com/woowacourse/jwp-subway-path/assets/45073750/f8753ce2-e3bb-4771-9e5e-da34000887eb)

intellij 에서 TODO 인 것들만 확인이 가능하니 활용하면 좋을 것 같습니다.

2023-05-13 03:11 UTC, Be-poz commented on src/main/java/subway/domain/Line3.java
> +    }
사용안되는 기본생성자는 접근제어자를 변경해서 외부에서 접근못하게 해주세요

2023-05-13 03:11 UTC, Be-poz commented on src/main/java/subway/domain/SubwayGraph.java
> +    private final DefaultDirectedWeightedGraph<Station, DefaultWeightedEdge> graph = new DefaultDirectedWeightedGraph<>(DefaultWeightedEdge.class);
2단계 까지 한 번에 구현해야 한다고 생각하셨던 걸까요 ㅜ.ㅜ

2023-05-13 03:11 UTC, Be-poz commented on README.md
> +    - [x] 새 역 등록
커밋을 보니깐 일부 커밋에서 mockMvc Test를 추가하고 controller 부터 작성하는 식으로 tdd를 진행하신 것 같은데,  
조금 더 작은 단위로 가져가면 좋을 것 같습니다.

2023-05-13 03:11 UTC, Be-poz commented on README.md
> +    - [x] 새 역 등록
루쿠도 이미 알고 있으시겠지만, 처음 설계를 할 때에 하나씩 생각하면 조금 더 편합니다.  
아마 리팩토링을 거의 처음부터 쭉 하시게 될 것 같은데요, 도메인간의 관계를 그림으로 그려보고 추가되어야 할 세부 기능들을 어느쪽 도메인에 넣어야할지 적어가면서 한 번 해보시면 어떨까요?  정말 작게작게 기능을 가져가면 이후 리팩토링을 할 때에도 더 편할거에요!  너무 어렵게 생각하지마시고 레벨1 때를 떠올리면서 차근차근 해보면 별거 없을겁니다!

2023-05-13 03:11 UTC, Be-poz commented on src/main/java/subway/domain/Station3.java
> +public class Station3 {
3으로 두게된  히스토리를 알고 싶습니다. 기존에 Station으로 진행하다가 이건 아니다 하고 리팩토링을 진행하고 Station3으로 모두 갈아치우고 난 다음에 Station을 지우자 는 방향으로 가게되신걸까요?  
차라리 StationTemp 라고 두었으면 더 이해가 편했을 것 같습니다. 커밋내역에는 다 남으니까요!

2023-05-13 03:11 UTC, Be-poz commented on src/main/java/subway/domain/Station3.java
> +public class Station3 {
아니면 차라리 모두 날리고 처음부터 진행하셨으면 오히려 더 진행이 빨랐을 수도 있습니다.  
완전 완성단계 급으로 만든 것이 아니면 이 정도 규모의 미션에서는 리팩토링보다는 새롭게 시작하는 것이 정말 빠르긴하거든요! 어떤식으로 클래스를 두고 이 로직은 이곳에다가 두겠다는 결정이 이미 머릿속으로 그려져있으면 코드치는 시간만 있을뿐이고 시간 소요가 얼마 되지 않습니다! 다음에 이런일이 있으면 한 번 처음부터 해보시면 좋은 경험이 되실겁니다.

2023-05-13 03:11 UTC, Be-poz commented on src/main/resources/schema.sql
> +CREATE TABLE LINE
EDGE에도 station_order가 있고 LINE에도 station_order가 있습니다. 어떤식으로 하려고 했던건지 듣고 싶습니다~!  
station_order에는 station들의 id를 String으로 두어서 한 번에 저장하려고 하셨던 것일까요?

2023-05-13 03:11 UTC, Be-poz commented on src/main/java/subway/domain/StationEdge.java
> +    private final int distance;
LINE 1
STATION  홍대 - 잠실

이 있으면 이 경우에는 어떤 Station이 필드에 들어가게 되나요 ?

2023-05-13 03:12 UTC, Be-poz commented
구현을 당연히 완료하지 못할 수도 있습니다. 너무 조급해하지 마시고 천천히 리팩토링 하시고 제출해주시면 되겠습니다.  
막히면 크루들한테 의견을 물어보고 수용할 것들은 수용하고 내칠 것들은 내치고 루쿠만의 생각을 정립해나가시면 될 것 같습니다. 기다리고 있겠습니다!

2023-05-15 01:42 UTC, aiaiaiai1 commented
안녕하세요 파즈 
저번에 미션을 진행할때 기본 뼈대코드가 주어졌는데 기본 뼈대 그대로 두고 미션을 진행해서 그런지 코드들이 뒤죽박죽 섞이게 되었습니다. 또 중간에 설계를 바꾸는 과정에도 중복된 코드가 존재하게 되서 읽기 힘든 코드가 되었던것 같습니다 지저분한 코드 읽게 해서 죄송합니다 🙏

2023-05-15 16:17 UTC, Be-poz approved these changes
안녕하세요 루쿠 구현해주신 것 봤습니다.  
마지막 리뷰 요청은 5.22이어서 제가 조급해하지마시고 천천히 리팩토링하고 제출하면 된다고 말씀을 드렸는데, 코멘트에 리팩토링 단계가 남았고 중복코드가 존재한다고 스스로 말씀하셔서 조금 당황스러웠습니다.  

주제넘지만 쓴소리를 조금 하겠습니다. 미션을 통해서 학습이 목적이지 미션을 해치우는 것이 목적이 절대 아닙니다. 루쿠가 구현을 끝까지 못하시더라도 루쿠가 이번 미션을 통해서 충분히 학습을 했고 얻어간 것이 있다면 그건 성공적인 미션이라고 저는 생각합니다. 불과 몇 달만 지나게된다면 이렇게 넉넉하게 시간을 가지고 학습에 몰두할 수 있는 때는 오지 않을 겁니다. 후회없는 시간을 보내셨으면 좋겠습니다.  

이번 단계는 바로 머지하겠습니다. 다음 단계에서는 2단계의 요구사항과 더불어서,  

1. 요구사항이 충족하는지 로컬에서 여러 케이스를 테스트 해보시고
2. 충족이 된다면 코드 리팩토링을 추가로 더 하시고
제출하셨으면 좋겠습니다. 제출이 늦어져도 상관없습니다. 마지막 리뷰요청 전 까지만 보내주세요.

스프링을 사용하면서 어떤 식으로 코드를 작성해야하고 어떤 메서드를 써야하고 어떤 어노테이션을 사용해야하는지 감이 안잡히고 모르겠으면 정말 사소한 것이라도 질문을 모두 남겨주세요. 또는 DM으로 질문을 막 보내주셔도 됩니다.  

기분 나쁘실 수도 있으실 것 같은데 죄송합니다. 하지만 우테코 경험자로서 말해야 할 말을 한 것 같습니다.  
1단계 수고하셨습니다.

2023-05-15 16:17 UTC, Be-poz commented on src/main/java/subway/controller/LineController.java
> +@RestController
공통된 url은 ``@RequestMapping`` 을 이용해서 공통화 할 수 있습니다!

2023-05-15 16:17 UTC, Be-poz commented on src/main/java/subway/controller/LineController.java
> +                .body(lineName);
'.' 으로 체이닝 되는게 싫어서 모두 개행을 하셨나요? 이 정도는 한 줄에 둬도 상관없긴합니다. 찝찝하시다면  
```java
	/**
	 * A shortcut for creating a {@code ResponseEntity} with the given body
	 * and the status set to {@linkplain HttpStatus#OK OK}.
	 * @param body the body of the response entity (possibly empty)
	 * @return the created {@code ResponseEntity}
	 * @since 4.1
	 */
	public static <T> ResponseEntity<T> ok(@Nullable T body) {
		return ok().body(body);
	}
```

ok 안에 body 값을 넣는 방법도 있어요

2023-05-15 16:17 UTC, Be-poz commented on src/main/java/subway/controller/StationController.java
> +    public ResponseEntity<StationResponse> createStation(@RequestBody StationAddRequest stationRequest) {
Station을 만드는 api 라고 생각했는데, 호선에 구간을 등록하는 기능까지 같이 가지고 있네요.  
Request만 보면 Station을 만드는 api 라고 생각하기도 어려운 것 같습니다.  
2개의 기능을 api 분리가 되면 더 좋을 것 같아요

2023-05-15 16:17 UTC, Be-poz commented on src/main/java/subway/dto/LineCreateRequest.java
> +public class LineCreateRequest {
StationAddRequest랑 다른점이 없어보입니다!

2023-05-15 16:17 UTC, Be-poz commented on src/main/java/subway/controller/StationController.java
> +    public ResponseEntity<StationResponse> createStation(@RequestBody StationAddRequest stationRequest) {
Line을 a 역, b 역 , 10 이렇게 생성하고 
stations 추가에 c, b, 5  이렇게 하면 모두 이미 존재하는 역이라고 뜨네요

2023-05-15 16:17 UTC, Be-poz commented on src/main/java/subway/controller/StationController.java
> +    public ResponseEntity<StationResponse> deleteStation(@RequestBody StationDeleteRequest stationDeleteRequest) {
``노선에 등록된 역이 2개 인 경우 하나의 역을 제거할 때 두 역이 모두 제거되어야 합니다.`` 요구사항을 충족이 안되네요

2023-05-15 16:17 UTC, Be-poz commented on src/main/java/subway/dao/StationDao.java
> +public interface StationDao {
Station만 인터페이스로 두고 나머지는 구체 클래스로 둔 이유가 있을까요?

2023-05-15 16:17 UTC, Be-poz commented on src/main/java/subway/domain/SubwayGraphs.java
> +    // TODO: 반환 타입 어떤걸로
해결된 TODO는 전부 지워주세요. intellij에서 TODO list를 확인하실 수 있으십니다!

2023-05-15 16:17 UTC, Be-poz commented on src/main/java/subway/entity/LineEntity.java
> +public class LineEntity {
Line과 무엇이 다른건지 잘 모르겠습니다!

2023-05-15 16:17 UTC, Be-poz commented on src/main/java/subway/entity/StationEntity.java
> +public class StationEntity {
마찬가지로 Station과 동일하네요

2023-05-15 16:17 UTC, merged