[1단계 - 지하철 정보 관리 기능] 디투(박정훈) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #65
Opened 2023-05-11 08:50 UTC by shb03323

안녕하세요 제이미, 만나뵙게 되어 영광입니다.
돌아가는 코드정도로만 만들어 보았습니다.
테스트가 몇개 터지고 있어요...
수정해보겠습니다.

아래는 API 링크입니다.
https://documenter.getpostman.com/view/18147836/2s93ebSqSY

2023-05-11 15:50 UTC, jamie9504 requested changes
디투, 안녕하세요. 리뷰어 제이미입니다 😄 

코멘트 조금 남겨두었습니다.
문의주신 부분도 코멘트에 포함되어 있습니다.

이번엔 테스트코드를 보지 않아서, 다음 리뷰할 때 테스트코드 위주로 확인하겠습니다 😄

2023-05-11 15:50 UTC, jamie9504 commented on README.md
> +# jwp-subway-path
- 노선에 역 등록
    - 🔺 노선에 등록되는 역의 위치는 자유롭게 지정할 수 있어야 합니다.
        - ❌ 거리 정보는 양의 정수로 제한합니다.
            - `POST http://localhost:8092/sections {"lineName": "2호선", "direction": "DOWN", "distance": -1000, "standardStationName": "신도림", "additionalStationName": "온수"}`
    - ❌ 노선에 역이 하나도 등록되지 않은 상황에서 최초 등록 시 두 역을 동시에 등록해야 합니다.
        - ❌ 노선에 역이 하나도 없는 경우에 역 하나만 등록을 하려 할 경우 거리 정보를 가질 수 없기 때문입니다.
            - `POST http://localhost:8092/lines {"name": "Jamie", "color": "JamieColor", "distance": 100, "firstStation": "JamieA", "secondStation": "jamieB"}` 
    - ❌ 노선 가운데 역이 등록 될 경우 거리는 양의 정수라는 비즈니스 규칙을 지켜야 합니다.
        - ❌ B-C가 3km인데 B-D거리가 3km면 D-C거리는 0km가 되어야 하는데 거리는 양의 정수여야 하기 때문에 이 경우 등록이 불가능 해야합니다.
- 노선에 역 제거
    - ❌ 노선에서 역이 제거될 경우 역과 역 사이의 거리도 재배정되어야 합니다.
        - ❌ A-B가 2km, B-C가 3km, C-D가 4km인 경우 C역이 제거되면 B-D 거리가 7km가 되어야 합니다.
            - `DELETE http://localhost:8092/stations/8` -> section Table 확인

\+++

- 노선 조회 ❌ 
`GET http://localhost:8092/lines/3` -> 예상한 값을 내려주고 있나요?
`DELETE http://localhost:8092/lines/3`을 한 후 `GET http://localhost:8092/lines/3`를 다시 해볼까요?

---

> 1. 노선 추가에서 비즈니스 규칙을 변경해도 괜찮을까요?
- 제공된 비즈니스 규칙은 변경 불가합니다. 아래 말씀주신 부분은 제공된 부분에 대한 변경으로 보여서, 변경하지 않고 진행해주세요.
    - 이 규칙을 보면 한쪽 길이만 요청으로 보내는데, 양쪽 길이를 요청을 보내도 괜찮을지 여쭈어보고 싶습니다.
    - 또, 만약 종점에서의 구간 추가면 해당 부분은 api를 따로 두어도 괜찮을지에 대해도 여쭈어보고 싶어요.
- 정의되지 않은 비즈니스 규칙은 능동적으로 결정 가능합니다.
    - ex) Station을 먼저 등록하던지, 노선을 추가하면서 Station을 함께 등록하던지 ... etc

2023-05-11 15:50 UTC, jamie9504 commented on src/main/java/subway/application/LineService.java
> +        final Long lineId = lineDao.insert(LineConverter.toEntity(lineDto));
1. `@Transactional`을 설정해둔 메서드와 설정하지 않은 메서드는 어떤 차이가 있을까요?
2. `@Transactional`의 readOnly 속성에 대해 알아볼까요?
3. 해당 save로직을 호출하기 위해, controller에서 `LineRequest`를 `lineDto`와 `SectionCreateDto`로 나누고 있는데 파라미터 하나로 넘겼을 때와 두 개로 나눠서 넘겼을 때의 장/단점은 무엇이 있을까요?
4. converter는 어떠한 영역의 데이터를 가공한다고 보아야할까요? 현재는 dto, response(dto), domain, entity 등등을 서로 변환해주고 있는데, 너무 많은 레이어를 담당하고 있는 것이 아닐까요?
5. converter를 통해 dto에서 entity로 바로 변환이 되는데 domain은 어디에서 필요한건가요?

2023-05-11 15:50 UTC, jamie9504 commented on src/main/java/subway/application/LineService.java
> +            throw new IllegalArgumentException("존재하지 않는 노선입니다.");
`GET http://localhost:8092/lines/999` 처럼 없는 ID를 요청했을 때, 어떤 응답코드를 내려주고 있나요?
HTTP STATUS CODE 400번대를 알아보고, 어떤 것을 내려주는 것이 가장 적합할지 고민해볼까요?

2023-05-11 15:50 UTC, jamie9504 commented on src/main/java/subway/dao/LineDao.java
> +        return insertAction.executeAndReturnKey(params).longValue();
아래와 같이 요청을 하면 어떤 응답을 내려줄까요? 그건 디투가 의도한 응답일까요?
1. `POST http://localhost:8092/lines` + body `{}`
2. `POST http://localhost:8092/stations` + body `{"name": "jamieA"}`
`POST http://localhost:8092/stations` + body `{"name": "jamieB"}`
`POST http://localhost:8092/lines` + body `{"name": "Jamie", "color": "JamieColor", "distance": 100, "firstStation": "jamieA", "secondStation": "jamieB"}` 
`POST http://localhost:8092/lines` + body `{"name": "Jamie", "color": "JamieColor", "distance": 100, "firstStation": "jamieA", "secondStation": "jamieB"}`

2023-05-11 15:50 UTC, jamie9504 commented on src/main/java/subway/entity/LineEntity.java
>          return Objects.equals(id, line.id) && Objects.equals(name, line.name) && Objects.equals(color, line.color);
1. Line과 LineEntity의 형태가 동일한데, 분리한 이유가 있나요?
2. Entity란 무엇인가요? Entity의 식별자는 무엇인가요?
3. `equals`와 `hashCode`는 식별자로 현재 구현되어 있지 않는데요, 이렇게 구현한 이유는 무엇인가요?

2023-05-11 15:50 UTC, jamie9504 commented on src/main/java/subway/ui/GlobalExceptionHandler.java
> +package subway.ui;
1. 패키지명이 ui가 된 이유는 무엇일까요?
예를 들자면 console에서 요청을 할 수도 있는거라, ui와 관련이 있다고 보긴 어렵지 않을까요?
2. `ExceptionDto`는 응답용으로만 쓰이는 것으로 보이는데, 접미사가 `dto`인 이유가 있을까요? 다른 부분들은 `response`를 쓰고 있는 것 같아서요!
3. 겸사겸사 매직넘버들은 상수화해줘볼까요?
4. 겸사겸사 불필요한 주석들도 제거해볼까요?

2023-05-11 15:50 UTC, jamie9504 commented on src/main/java/subway/ui/SectionController.java
> +}
`SectionResponse`에는 sectionId인 `id`를 내려주네요!
1. add 메서드에서 응답시 `URI.create("sections")`를 내려주는 이유가 있을까요? 201은 보통 어떤 응답을 내려줄까요?
2. remove 메서드에서 식별자를 사용하지 않고, `lineId`와 `stationId`를 사용한 이유가 있을까요?
3. add랑 remove는 뭔가 집합에 추가/제거하는 느낌이 드는데, section은 독립된 개체라서 이게 조금 어색하게 느껴지기도 하네요. 디투는 어떻게 생각하시나요?

2023-05-11 15:50 UTC, jamie9504 commented on src/main/java/subway/ui/StationController.java
>  import java.sql.SQLException;
1. 전반적으로 validate가 필요할 것 같아요.
`POST http://localhost:8092/stations` + body `{"name": ""}`
2. 노선에 두 역이 중복 등록되는 경우는 의도한 바인가요?
`POST http://localhost:8092/stations` + body `{"name": "jamie"}`
`POST http://localhost:8092/sections` + body `{"lineName": "1호선", "direction": "DOWN", "distance": 1, "standardStationName": "온수", "additionalStationName": "jamie"}`
`POST http://localhost:8092/sections` + body `{"lineName": "1호선", "direction": "UP", "distance": 1, "standardStationName": "온수", "additionalStationName": "jamie"}`
의도했다면 노선을 조회했을 때는 한 역만 나오는데 이 부분 수정이 필요할 것 같고, 의도하지 않았다면 한 노선에 여러 역이 등록되지 않도록 해야할 것 같아요.

2023-05-11 15:50 UTC, jamie9504 commented on src/main/java/subway/ui/dto/request/LineRequest.java
> +    private final String color;
1. 요구사항을 구현하는데 있어, `color`가 필요한가요?
2. `previousStation/nextStation`, `firstStation/secondStation` 등 여러 용어가 현재 프로그램에서 혼재되어 있네요.
이렇게 관리하는 것이 의도한 바인가요? 의도했다면, 어떤 효과를 얻기 위해서 분리하였나요?

2023-05-11 15:50 UTC, jamie9504 commented on src/test/java/subway/dao/LineDaoTest.java
> +class LineDaoTest {
코멘트를 남겨주어 확인은 했지만, 디투의 의견이 궁금하네요!
1. Commit시 Test가 터져도 괜찮을까요?
2. 그렇다면 현재처럼 테스트를 성공시키지 못했을 때, Commit시 어떻게 이 파일을 수정해서 올려야할까요?

2023-05-16 15:46 UTC, shb03323 commented on README.md
> +# jwp-subway-path
### 노선에 역 등록
#### 노선에 등록되는 역의 위치는 자유롭게 지정할 수 있어야 합니다.
- 해당 부분 예외 처리 완료했습니다.
#### 노선에 역이 하나도 등록되지 않은 상황에서 최초 등록 시 두 역을 동시에 등록해야 합니다.
- 노선을 동록하기 위해서 두 개의 역을 추가로 입력해주어야 합니다.
- 노선에 추가 역을 이어주는 경우에는 기준 역과 추가될 역을 입력해야 합니다.
#### 노선 가운데 역이 등록 될 경우 거리는 양의 정수라는 비즈니스 규칙을 지켜야 합니다.
- 예외 처리 진행했습니다.
### 노선에 역 제거
#### 노선에서 역이 제거될 경우 역과 역 사이의 거리도 재배정되어야 합니다.
- 수정했습니다.
### 노선 조회
- DELETE /lines 메소드는 필요한 것 같다고 느끼지 못해 제거했습니다.

---
### 제공된 비즈니스 규칙은 변경 불가합니다. 아래 말씀주신 부분은 제공된 부분에 대한 변경으로 보여서, 변경하지 않고 진행해주세요.

Station을 먼저 등록한 후에 노선에 추가할 수 있도록 처리했습니다.

2023-05-16 16:24 UTC, shb03323 commented on src/main/java/subway/application/LineService.java
> +        final Long lineId = lineDao.insert(LineConverter.toEntity(lineDto));
1. 하나의 트랜잭션으로 보고 `@Transactional` 설정한 메소드의 경우 중간에 실패한 경우 롤백이 됩니다. (query를 저장하고 있다가 마지막에 DB 통신을 합니다.)
2. 저는 저장하는 기능이라 `readOnly = true` 를 붙이지 않았습니다. `readOnly = true`를 붙이게 되면 데이터가 변하는 것을 막을 수 있습니다. 보통 Read 쿼리만 사용할 때 쓰입니다. Read 할 때 해당 속성을 추가하는 이유는 불필요한 자원 사용을 막아주기 때문에 속도적으로 이점이 생기기 때문입니다. 
3. 두개로 넘겼을 때 장점은, 데이터를 논리적 기준으로 나누었기 때문에 가독성이 좋다고 생각합니다. 정보가 많아지면 많아질수록 하나의 dto로 정보를 전달한다면 가독성이 떨어질 것 같아서 이렇게 설계했습니다. 단점은 데이터를 전달할 때 두 개의 DTO를 함께 처리해야 하기 때문에 조금 복잡한 것 같습니다. (의도한 것은 각각의 dto를 통해 line과 section domain을 유지보수가 쉽고 확장성 좋게 만들어 비즈니스 로직을 처리하려 했습니다.)
4. 말씀해주셔서 감사합니다. 너무 많은 레이어가 섞여있어 분리하였습니다.
5. 도메인 로직을 작성하고자 했는데, 구현에 급급한 나머지 작성하지 못했습니다. 수정본에는 도메인 로직을 실행시키고 converter를 통해 변환해주었습니다.

2023-05-16 16:25 UTC, shb03323 commented on src/main/java/subway/application/LineService.java
> +            throw new IllegalArgumentException("존재하지 않는 노선입니다.");
말씀해주셔서 감사합니다. 예외 처리를 하지 못했는데, 리팩토링하며 더 꼼꼼하게 분기 처리 했습니다!

2023-05-16 16:33 UTC, shb03323 commented on src/main/java/subway/dao/LineDao.java
> +        return insertAction.executeAndReturnKey(params).longValue();
1. validation 라이브러리를 통해 예외처리 진행했습니다!
2. 중복 구간 예외 처리 진행했습니다!

2023-05-16 17:20 UTC, shb03323 commented on src/main/java/subway/entity/LineEntity.java
>          return Objects.equals(id, line.id) && Objects.equals(name, line.name) && Objects.equals(color, line.color);
1. SectionDetailEntity를 그대로 쓰기에는 필드가 너무 많아 가독성이 떨어질 것 같다고 생각했습니다. 그래서 SectionDetailEntity에 있는 line_id, previous_station_id, next_station_id 필드를 풀어 Line, PreviousStation, NextStation로 객체 분리를 하며 가독성을 높였습니다. LineEntity와 Line의 형태가 같더라도 도메인 로직을 위하고 있다는 것을 명시하고 싶었구요. 그래서 Section에 LineEntity가 아닌 Line을 필드로 두었습니다. 만약 SectionDetailEntity를 그대로 사용하여 정렬을 했다면, 데이터 변경을 막기 위해 `@Transactional(readOnly=true)` 속성을 걸어주었을 것 같습니다.
2. Entity는 실체입니다. id를 식별자로 가지고 있으며 이 id를 통해 Entity를 식별합니다. id 외의 정보가 바뀌더라도 Entity는 다른 객체가 되지 않습니다.
3. 제 불찰입니다. 정렬할 때 key 값으로 설정하기 위해서 일단 equals 와 hashcode를 넣고 시작했었습니다.

2023-05-16 17:28 UTC, shb03323 commented on src/main/java/subway/ui/GlobalExceptionHandler.java
> +package subway.ui;
1. 넵! 패키지명 변경했습니다!
2. 통일감 있는 dto로 네이밍했습니다.
3. 필요한 매직넘버는 상수화했습니다.
4. 주석들도 제거했습니다.

말씀해주셔서 감사합니다:)

2023-05-16 17:31 UTC, shb03323 commented on src/main/java/subway/ui/SectionController.java
> +}
`/lines`에서 해야하는 작업이라는 생각이 들었습니다. 노선에 역을 추가하고 제거하는 작업이기 때문에 patch가 적절해보입니다. 전달해야하는 정보가 많았기 때문에 redirect uri 대신 body를 사용했고, 마찬가지로 remove도 request body를 받았습니다. 지금은 patch를 사용으로 문제들을 해결했습니다.

2023-05-17 00:23 UTC, shb03323 commented on src/main/java/subway/ui/dto/request/LineRequest.java
> +    private final String color;
1. 요구사항 구현에는 필요하지 않지만, main 코드로 주어진 entity에 color 필드가 들어가있어 그대로 사용했습니다. 제거해야할까요?
2. 용어를 구분해서 쓴건 급해서입니다. 차마 수정하지 못했네요. 지금은 수정완료 상태입니다! previousStation와 nextStation로 통일했습니다.

2023-05-17 06:16 UTC, shb03323 commented on src/main/java/subway/ui/StationController.java
>  import java.sql.SQLException;
모든 예외처리 진행했습니다:)

2023-05-17 06:18 UTC, shb03323 commented on src/test/java/subway/dao/LineDaoTest.java
> +class LineDaoTest {
1. 공동 작업 브랜치에서는 동료 개발자가 다시 정상 커밋으로 돌아가고 싶을 수 있기 때문에 test가 터지면 안된다고 생각하고, 개인용 브랜치에서는 상관 없다고 생각합니다.
2. 터지는 테스트를 주석처리하고, commit 상세 메시지로 남겨두어야 한다고 생각합니다.

2023-05-17 06:59 UTC, shb03323 commented
안녕하세요 제이미, 어느정도 완료된 것 같아 재리뷰 요청 드립니다!
남겨주신 피드백&코멘트 확인하고 댓글 남겼습니다. 꼼꼼히 봐주셔서 감사합니다.

[포스트맨 문서](https://documenter.getpostman.com/view/18147836/2s93ebSqSY)에 구현한 API와 사용 방법 정리했습니다. 저번에 미흡했던 예외 케이스도 정리되어 있으니 참고하시고 프로그램을 실행시키면 더 편하실 것 같습니다!

---
### 궁금한 점
#### 도메인이 id를 가지고 있는게 맞나?
요즘 크루들 사이의 이야기 주제입니다.
- 반대파: 도메인에 id를 넣으면 database에 의존적인 도메인이 되는 것이 아닌가요?
- 찬성파(제 생각): response로 보낼 때 id도 전달해주어야 한다고 생각했기 때문에 id를 넣었습니다. 이게 DB를 안다고 할 수 있을까요? 제 생각은 아닙니다.
제이미의 생각은 어떠신가요? 제가 놓치고 있는 생각이 있을까요?

#### query 최적화
구현한 쿼리에서 코드에서 join을 최대 3번까지 사용합니다. 이렇게 된다면 같은 line에 대해 계속해서 join을 걸기 때문에 n+1 문제가 발생합니다. jdbc로는 이 문제를 해결할 수는 없을까요? 검색을 시도해보았지만 JPA 관련 글만 나오더라구요. 제가 검색할 키워드를 잘 못 찾은 것 같아요. 혹시 검색해볼만한 키워드 알려주실 수 있을까요?

+) line과 station table에서 findById를 하고 section의 line id와 station id를 코드로 매핑 시키는 방법도 좋은 방법이라고 생각합니다. `@Transactional`이 적용되어 있는 상태이기 때문에 한 번에 쿼리가 나가 속도 차이가 거의 없을 것 같아서요. 이런 방법을 적용한다면 제 코드에서 SectionDetailEntity가 없어질 것 같고, 가독성 좋고 더 편하게 개발할 수 있을 것 같아요. 하지만 query join 관련해서 더 공부해보고 싶어 이렇게 짰습니다.

---
### 미흡한 사항
1. `/PATCH /lines/{id}/register` API의 request body에 enum 타입으로된 SubwayDirection이 있습니다. Config 파일에 Converter를 추가했는데, request body로 잘못된 string을 입력하면 converter의 오버라이드 된 `convert()`를 실행하기도 전에 json 역직렬화 관련 예외가 발생합니다. 아직 해결하지 못하고 있습니다.

2.

2023-05-17 16:03 UTC, jamie9504 requested changes
디투, 안녕하세요. 리뷰어 제이미입니다 😄 

코멘트 남겨두었는데, 의견을 자유롭게 달아주셔도 되고 반영을 해주셔도 됩니다.

궁금한 점으로 남겨주셨던 부분은 리뷰 코멘트로 달아두었고,
미흡한 사항은 해결해보시고, 만일 도움이 필요하시면 다음 리뷰 때 남겨주세요 😉 

화이팅입니다. 💪

2023-05-17 16:03 UTC, jamie9504 commented on src/main/java/subway/application/LineService.java
> +        final Long lineId = lineDao.insert(LineConverter.toEntity(lineDto));
1. 👍 
2. 👍 아래 `findAll` 메서드에서는 사용하지 않길래 달아놨던 코멘트였습니다.
`readOnly = true`를 사용하면 JPA에서 성능이 좋아지는 점도 있지만, 다른 개발자들에게 명백히 해당 속성을 사용한 애너테이션을 단 메서드에서는 조회만 한다는 의미를 담아줄 수도 있습니다 😉
3. 현재 코드는 `save(final LineDto lineDto, final SectionCreateDto sectionCreateDto)`과 같이 변경되었는데요.
lineDto는 단순히 Entity로 변환을 해주고, SectionCreateDto는 내부의 값으로 Dao를 조회한 후 Entity로 변환을 해주네요!

    `LineRequest`를 `lineDto`와 `SectionCreateDto`로 나눈건, 클래스명을 다르게 가져가서 조금 더 직관적으로 보일 수 있게 하기 위함으로 이해했습니다. 이 부분은 취향의 범주인 것 같긴 합니다. 😄`
(단점은 말씀주신 부분에 보태서 1개의 Dto로 보냈을 때보다 Dto가 더 많고, 변환 과정이 필요하고, `request`과 `dto`가 항상 같이 수정되어야 할 것 같기도 하네요.)

    >  각각의 dto를 통해 line과 section domain을 유지보수가 쉽고 확장성 좋게 만들어 비즈니스 로직을 처리하려 했습니다.

    라고 하셨는데, Dto를 나누어서 의도한 바를 얻으셨는지 궁금하네요!

4. 👍 
5. 👍 converter가 있는 것과, converter의 역할을 domain / entity / dto에서 가지고 있는 것은 어떠한 차이가 있을까요?
6. `LineService`의 `IS_END_STATION`는 상수명만 보았을 땐, boolean 값을 가지고 있을 것 같은 느낌이네요.
7. `LineDetailResponse`은 뭔가, `LineResponse`가 존재할 것 같은 느낌이에요.
8. `LineService`의 `save` 메서드는 이름만 보았을 땐, Line을 저장할 것 같은 느낌이네요.
9. `sortAndReturnToResponse` 조금 더 적합한 메서드명이 없을까요?
10. `sortAndReturnToResponse(sectionDao.findSectionDetailByLineId(newSectionEntity.getLineId()))` 처럼 괄호가 많이 중첩되면 가독성이 떨어지는 것 같아요. 보통은 코드를 좌->우로 읽는데, 괄호가 많이 중첩되면 이 흐름이 깨지게 되니까요! 전반적으로 괄호 중첩이 많아보이긴 한데, 가독성은 어느정도 취향을 타니까 참고만 해주세요 😄 
11. station을 name으로 호출`findIdByName`하는 이유가 있을까요? name을 이용하는 방법과 id를 이용하는 방법은 어떠한 차이가 있을까요?
12. `sectionDao.findByLineIdAndPreviousStationIdOrNextStationId(lineId, stationId).isEmpty()` 부분은 empty인지 확인만 하고 있는데, 이렇게 되면 존재하는지 여부를 boolean으로 반환하는 메서드를 사용하는 것과 어떠한 차이가 있을까요?
13. `registerDownMidStation`, `registerEndStation`, `registerUpperMidStation`, `cascadeLine`은 private 메서드들인데요. dao에 작업을 하는 로직을 가지고 있습니다. 이 로직들이 `List<SectionDetailEntity>`를 반환하지 않고, `LineDetailResponse`를 반환하는 이유가 있을까요? 두 가지 역할을 하는 것 같아서요 😄 
14. `firstEntity`, `secondEntity`는 이름만으로는 어떤 Entity인지 짐작이 어려울 것 같긴 해요.
15. `Objects.equals(firstEntity.getNextStationId(), secondEntity.getPreviousStationId())`
    - 첫번째 섹션의 다음 역 ID와 두번째 섹션의 이전 ID가 같은지 비교하는 로직인데요. 이 역할은 `SectionEntity`가 수행할 수 없을까요?
    - `matchOrderOfTwoSectionEntities` 역할 자체를 `SectionEntity`가 수행할 수는 없을까요?
    - `bindSections`에서 `lineId`는 어차피 `SectionEntity`가 알고 있고, `relatedSectionEntities`는 무조건 2개가 들어오는 상황이니 `List`가 아니라 `SectionEntity`로 1개씩 낱개로 받는것도 가능하겠네요. 그리고 그 이후에 `SectionEntity`가 `concatSectionEntity`을 만들어주는 역할까지도 수행할 수 있지 않을까요?
    - 비슷하게 `registerUpperMidStation`의 `newNext`를 생성하는 로직도 고민해볼까요?
16. `cascadeLine(현재 사용중인 메서드명)`과 `deleteLine`은 어떠한 의미 차이가 있을까요?
17. `unregisterStation`에서 `IS_END_STATION`이 아니면 DB에 몇 번 delete 쿼리를 보내게 될까요? 이를 개선할 방법이 있을까요?
    ``` java
    sectionDao.delete(relatedSectionEntities.get(0));
    if (relatedSectionEntities.size() == IS_END_STATION) {
        return cascadeLine(lineId);
    }
    sectionDao.delete(relatedSectionEntities.get(1));
    ``` 
18. LineService가 조금 커진 것 같은데, 서비스를 적절한 크기로 분리해봐도 좋을 것 같네요 😄

2023-05-17 16:03 UTC, jamie9504 commented on src/main/java/subway/entity/LineEntity.java
>          return Objects.equals(id, line.id) && Objects.equals(name, line.name) && Objects.equals(color, line.color);
> 도메인이 id를 가지고 있는게 맞나?
> 요즘 크루들 사이의 이야기 주제입니다.
> 
> 반대파: 도메인에 id를 넣으면 database에 의존적인 도메인이 되는 것이 아닌가요?
> 찬성파(제 생각): response로 보낼 때 id도 전달해주어야 한다고 생각했기 때문에 id를 넣었습니다. 이게 DB를 안다고 할 수 있을까요? 제 생각은 아닙니다.
> 제이미의 생각은 어떠신가요? 제가 놓치고 있는 생각이 있을까요?

이 부분은 여기서 다뤄보도록 할까요?
(참고로 맞다 틀리다는 존재하지 않습니다 😃)

1의 설명은 DB와 1:1으로 매핑되는 Entity를 뜻하고 있고, 2와 3의 설명은 식별자를 가지는 객체인 Entity를 뜻하고 있네요.

이 둘은 어떠한 차이가 있을까요?
디투가 사용하고 있는 Entity는 Domain인가요?

2023-05-17 16:03 UTC, jamie9504 commented on src/main/java/subway/ui/GlobalExceptionHandler.java
> +package subway.ui;
1. 👍 
    - `presentation`이라는 패키지명은 조금 어색한 느낌이 있네요! 보편적으로 패키지명을 어떻게 사용하는지 알아볼까요?
    - `config`와 `controller`가 같은 패키지에 위치하는 것이 적절할까요?
    - `persistence` 패키지에 `entity`가 위치하는 것이 적절할까요?
    - `domain`과 `service`가 같은 패키지에 배치한 이유는 무엇인가요?
2. 👍 
3. 👍 
4. 👍 
5.`GlobalExceptionHandler`에서 편하게 핸들링하기 위해 `BadRequestException` 등이 생겨난 것 같은데, 이렇게 되면 `exception` 패키지는 개념이 `presentation` 패키지에 의존하게 되는 것 같아요. 이게 좋은 방향일까요?
6. `handleRuntimeException(RuntimeException e)` 에서 파라미터를 사용하지 않는다면 지워줘도 좋을 것 같아요.

2023-05-17 16:03 UTC, jamie9504 commented on src/main/java/subway/ui/dto/request/LineRequest.java
> +    private final String color;
1. 불필요하다고 생각하긴 했지만, 놔둔다고 해도 상관없을 것 같아요.
2. 👍

2023-05-17 16:03 UTC, jamie9504 commented on src/test/java/subway/dao/LineDaoTest.java
> +class LineDaoTest {
1. Github에 Push하는 순간부터는 다른 동료도 확인이 가능하므로, 모두의 코드라고 생각하면 좋을 것 같아요.
혼자 작업한 브랜치더라도 PR을 올리게 되면 동료가 리뷰를 해야하고, 상황에 따라 동료가 브랜치의 특정 커밋들만 cherry pick을 하는 등 commit을 사용할 수도 있으니까요! 😄 
2. 👍 최대한 테스트가 터지지 않아야 하지만, 어쩔 수 없다면 성공하지 못한 테스트 메서드를 주석처리하거나, 검증부만 주석처리를 하는 등의 작업을 하고 (TODO로 남겨도 좋겠네요) 동료들과 공유한 후, 최대한 빠르게 테스트를 보완해서 커밋 or PR을 올려주면 좋겠죠! 😄

2023-05-17 16:03 UTC, jamie9504 commented on README.md
> +  - [ ] Controller 프로덕션 코드 작성
이건 왜 이름으로 삭제하는 걸까요?

2023-05-17 16:03 UTC, jamie9504 commented on src/main/java/subway/business/StationService.java
> +    }
1. 여긴 `@Transactional` 애너테이션을 사용하지 않는 이유가 있을까요?
2. `update`, `delete`시 해당하는 id가 없을 때의 로직을 dao에서 처리하고 있는데요. dao의 역할과 service의 역할은 각각 무엇인가요? 없을 때 예외를 발생시키는 로직은 어디에 위치하는 것이 더 적절할까요?

2023-05-17 16:03 UTC, jamie9504 commented on src/main/java/subway/business/domain/LineSections.java
> +    public static LineSections createWithSort(final Line line, final List<LineSection> unsortedSections) {
`LineSections`라는 도메인이, 항상 정렬된 `sections`를 가져야만 할까요?
  - Y라면, 생성자에서 정렬해주는 방식과 현재 방식은 어떤 차이가 있을까요?
  - N라면, 정렬되지 않는 `sections`도 받아주는 메서드가 생성되어야 할까요?

2023-05-17 16:03 UTC, jamie9504 commented on src/main/java/subway/persistence/LineDao.java
> +public class LineDao {
> query 최적화
> 구현한 쿼리에서 코드에서 join을 최대 3번까지 사용합니다. 이렇게 된다면 같은 line에 대해 계속해서 join을 걸기 때문에 n+1 문제가 발생합니다. jdbc로는 이 문제를 해결할 수는 없을까요? 검색을 시도해보았지만 JPA 관련 글만 나오더라구요. 제가 검색할 키워드를 잘 못 찾은 것 같아요. 혹시 검색해볼만한 키워드 알려주실 수 있을까요?
> 
> +) line과 station table에서 findById를 하고 section의 line id와 station id를 코드로 매핑 시키는 방법도 좋은 방법이라고 생각합니다. `@Transactional`이 적용되어 있는 상태이기 때문에 한 번에 쿼리가 나가 속도 차이가 거의 없을 것 같아서요. 이런 방법을 적용한다면 제 코드에서 SectionDetailEntity가 없어질 것 같고, 가독성 좋고 더 편하게 개발할 수 있을 것 같아요. 하지만 query join 관련해서 더 공부해보고 싶어 이렇게 짰습니다.

이 부분에 대해서는 여기서 다뤄보도록 할까요?

1. 디투가 알고 있는 n+1 문제란 무엇인가요?
2. join을 걸었을 때는 어떠한 특징이 있을까요?
3. join을 걸지 않았을 때는 어떠한 특징이 있을까요?

2023-05-17 16:03 UTC, jamie9504 commented on src/test/java/subway/business/LineServiceTest.java
> +@ExtendWith(MockitoExtension.class)
> mock 테스트
> mock 테스트를 열심히 해보았는데, 어느정도까지 검증해야할지 감이 잡히지 않아서요. 대부분의 크루들은 간단하게 verify로 호출 횟수만 검사하는데 저는 mock 테스트라도 원하는 값을 return하도록 stub해야한다고 생각하거든요. 제가 불필요하게 테스트를 과하게 작성했다는 느낌도 드는데요. 제이미의 생각은 어떠신가요?

이 부분은 여기서 다뤄보도록 할까요?

1. verify로 호출 횟수만 검사하는 경우, 테스트는 어떠한 부분을 검증(혹은 기대)하는 것일까요?
2. stub을 하는 경우, 테스트는 어떠한 부분을 검증(혹은 기대)하는 것일까요?
3. 디투가 생각하는 각각의 장/단점은 무엇이 있을까요?

---

다음과 같은 기능을 통해 Test Coverage를 확인할 수 있는데요.
현재 테스트가 되지 않는 구간들이 있는 것 같아요. (주로 validate 분기)
이 부분들도 테스트를 추가해볼까요?
<img width="735" alt="image" src="https://github.com/woowacourse/jwp-subway-path/assets/59511689/72d6bafa-439d-4379-b437-68d54331f5e3">

2023-05-18 02:01 UTC, shb03323 commented on src/main/java/subway/application/LineService.java
> +        final Long lineId = lineDao.insert(LineConverter.toEntity(lineDto));
2. `findAll`이라는 네이밍으로도 동료 개발자에게 조회만 하는 메서드라는 것을 전달할 수 있다고 생각하여 어노테이션을 붙이지 않았습니다. 붙여주는 것이 오히려 성능 저하를 만들기 때문이라고 생각해서요😄 또 궁금한 점이 있습니다! 제이미 말씀대로 어노테이션을 붙여준다면 `findById`에 대해서도 붙여야한다고 생각하는데, `findAll`만 말씀해주신 이유가 있을까요? 다중 검색 특화된 무언가가 있나요?

2023-05-18 02:06 UTC, shb03323 commented on src/main/java/subway/application/LineService.java
> +        final Long lineId = lineDao.insert(LineConverter.toEntity(lineDto));
5. 이전에 converter의 역할을 각각 객체의 정적 팩토리 메서드로 감싸면 어떨지도 생각해보았습니다. 만약 domain <-> entity 변환을 각각의 객체의 정적 팩토리 메소드로 만들게 된다면 양방향 의존이 생길 것 같아 converter를 두었습니다. 지금 구현에서는 entity -> domain -> response로 전달되기 때문에 문제가 되진 않지만, domain에서 다시 entity로 바꾸게 된다면 문제가 생길거라고 생각합니다.

2023-05-18 02:13 UTC, shb03323 commented on src/main/java/subway/application/LineService.java
> +        final Long lineId = lineDao.insert(LineConverter.toEntity(lineDto));
6. 상수 명이 너무 길어질 것 같아서 짧게 해보았는데, gpt의 힘을 빌려 상수명을 정해보았습니다.

2023-05-18 02:16 UTC, shb03323 commented on src/main/java/subway/application/LineService.java
> +        final Long lineId = lineDao.insert(LineConverter.toEntity(lineDto));
7. 처음에 LineResponse가 존재했어서 LineDetailResponse 네이밍으로 사용했었는데, LineResponse가 쓰이지 않아 삭제했습니다. 삭제하고나서 LineDetailResponse를 LineResponse 로 바꾸어주지 못했네요. 말씀해주셔서 감사합니다!

2023-05-18 02:24 UTC, shb03323 commented on src/main/java/subway/application/LineService.java
> +        final Long lineId = lineDao.insert(LineConverter.toEntity(lineDto));
8. 노선을 처음 만드는 것인데 station과 함께 만들어지기 때문에 어색하다는 느낌이 들어요. 말씀해주셔서 감사합니다. 수정했습니다😃

2023-05-18 02:37 UTC, shb03323 commented on src/main/java/subway/application/LineService.java
> +        final Long lineId = lineDao.insert(LineConverter.toEntity(lineDto));
9. sort라는 것을 service가 알 필요는 없다고 생각해 `convertToResponse`로 메서드 명을 변경했습니다!
10. 아 놓치고 있었던 부분이었어요. 말씀해주셔서 감사합니다. 분리했습니다😆

2023-05-18 02:41 UTC, shb03323 commented on src/main/java/subway/application/LineService.java
> +        final Long lineId = lineDao.insert(LineConverter.toEntity(lineDto));
11. 초기 노선을 생성할 때 역 2개를 입력해주어야 하는데요. request body로 역의 id를 받는 것은 어색하다고 느껴졌습니다. 사용자의 편의에 맞게 역의 이름으로 입력받고, 개발자는 조금 불편하더라도 findByName으로 정보 그대로 받아야된다고 생각했습니다. 하지만 id만 사용하는데 `findIdByName`을 사용하지 않고 `findByName`을 사용한 점은 잘못한 것 같습니다. 수정했습니다 😀

2023-05-18 04:03 UTC, shb03323 commented on src/main/java/subway/application/LineService.java
> +        final Long lineId = lineDao.insert(LineConverter.toEntity(lineDto));
12. `sectionDao.findByLineIdAndPreviousStationIdOrNextStationId(lineId, stationId)`의 반환을 Optional로 두어 처리하도록 변경했습니다.`isEmpty()`일 때 boolean을 반환하는 메소드를 사용하게 되면, 반환값을 받은 메서드에서 예외 처리를 하게됩니다. 이 경우에 예외가 더 늦게 반환되어 디버깅할 때 힘들 수 있다고 생각했습니다. "예외는 가능한 빨리 터트린다."는 레벨1때 읽은 이펙티브 자바에 있는 내용을 떠올렸습니다.

2023-05-18 04:28 UTC, shb03323 commented on src/main/java/subway/application/LineService.java
> +        final Long lineId = lineDao.insert(LineConverter.toEntity(lineDto));
13. 말씀해주신대로 하게 되면 코드가 길어질까봐 걱정되었습니다. 메소드를 분리할 부분도 보이지 않았구요. 그래도 가장 상위에 있는 메소드에서만 response를 반환해야 동료 개발자들이 오해하지않을 것 같아요. 말씀해주셔서 감사합니다. 수정했습니다!!

2023-05-18 04:40 UTC, shb03323 commented on src/main/java/subway/application/LineService.java
> +        final Long lineId = lineDao.insert(LineConverter.toEntity(lineDto));
14. 의미를 조금 더 부여했습니다. 이 부분 변수명 고민했었는데, 말씀해주셔서 감사합니다:)

2023-05-18 07:07 UTC, shb03323 commented on src/main/java/subway/application/LineService.java
> +        final Long lineId = lineDao.insert(LineConverter.toEntity(lineDto));
15. 객체지향적으로 변경했습니다. 놓치고 있었는데 말씀해주셔서 감사합니다😄
16. 너무 DB 관점으로 본 것 같아요. 수정했습니다!

2023-05-18 07:08 UTC, shb03323 commented on src/main/java/subway/application/LineService.java
> +        final Long lineId = lineDao.insert(LineConverter.toEntity(lineDto));
17. `batchUpdate`로 해결했습니다. 말씀해주셔서 감사합니다:)

2023-05-18 07:43 UTC, shb03323 commented on src/main/java/subway/entity/LineEntity.java
>          return Objects.equals(id, line.id) && Objects.equals(name, line.name) && Objects.equals(color, line.color);
1:1로 매핑되는 Entity는 RowMapper를 위한 entity 같다고 느꼈습니다. (그저 VO라고 느꼈습니다.) 

2,3의 Entity는 table과 1:1로 매핑되는 entity입니다!

제가 사용하고 있는 도메인은 테이블과 1:1로 매핑되는 개념보다는 실세계에 매핑되는 구조입니다. 그래서 노선 안에 여러 역들이 연결되어 있는 실세계 구조처럼 도메인을 설계했습니다. (비즈니스 로직을 위한 객체) id는 일반 유저에게 필요하지 않을 수 있지만 응답을 받는 클라이언트 개발자들에게는 path parameter로 요청을 보낼때 필요하기 때문에 넣어주었습니다.

2023-05-18 07:58 UTC, shb03323 commented on src/main/java/subway/ui/GlobalExceptionHandler.java
> +package subway.ui;
1-1. 레이어로 이름을 표현하기보다 `controller`, `service`, `repository` 구조로 네이밍하는 것 같습니다!
1-2. `config`는 레이어와 관련이 없기 때문에 밖으로 빼주었습니다.
1-3. `entity`는 db와 매핑되는 것이고, `repository`는 data를 활용하는 부분이라서 명확성을 위해 구분했습니다. (굳이 구분하지 않아도 된다고 생각합니다. `repository` 내부에 `entity` 패키지가 있어도 괜찮다고 생각합니다.)
1-4. 비즈니스 로직을 위한 객체이기 때문에 `business` 패키지에 있어도 된다고 생각합니다. 하지만 변경 코드에서는 구분했는데, 만약 Service와 Dao 사이에 Repository가 만들어진다면, 이때 domain은 `service`와 `repository` 모두에서 사용될 것 같았기 때문입니다.

2023-05-18 08:04 UTC, shb03323 commented on src/main/java/subway/ui/GlobalExceptionHandler.java
> +package subway.ui;
> GlobalExceptionHandler에서 편하게 핸들링하기 위해 BadRequestException 등이 생겨난 것 같은데, 이렇게 되면 exception 패키지는 개념이 presentation 패키지에 의존하게 되는 것 같아요. 이게 좋은 방향일까요?

exception을 구분하지 못한 것 같아요. 부모인 badrequest와 nonfound는 controller으로 옮겼습니다. 하지만 여전히 기존 커스텀 예외에서 extends BadRequestException를 사용하는데, 이 부분 또한 의존적인 것으로 보아야할까요?

2023-05-18 08:06 UTC, shb03323 commented on src/main/java/subway/ui/GlobalExceptionHandler.java
> +package subway.ui;
>handleRuntimeException(RuntimeException e) 에서 파라미터를 사용하지 않는다면 지워줘도 좋을 것 같아요.

넵 말씀해주셔서 감사합니다! 수정했습니다😄

2023-05-18 08:09 UTC, shb03323 commented on src/test/java/subway/dao/LineDaoTest.java
> +class LineDaoTest {
아하 말씀해주신대로 동료들이 직접 이용할 수도 있고, 리뷰할 때 불편할 수도 있다고 생각합니다! 다음부터 고려해보겠습니다. 말씀해주셔서 감사합니다. 테스트 코드의 경우에도 최대한 돌아가도록 만들고 push하는 것이 좋을 것 같군요!

2023-05-18 08:10 UTC, shb03323 commented on README.md
> +  - [ ] Controller 프로덕션 코드 작성
리드미를 업데이트하지 않았네요ㅠㅠ 죄송합니다. 예전 문서였습니다ㅠㅠㅠㅠ

2023-05-18 08:30 UTC, shb03323 commented on src/main/java/subway/business/StationService.java
> +    }
1. 한 번의 insert이기 때문에 insert에 실패해도 롤백할 필요가 없다고 생각했습니다.
2. update와 delete를 학습할 때 왜 update된 row수를 dao의 메소드에서 반환하는지 이해되지 않았습니다. service가 update된 data 수를 알아야할까? 차라리 반환해줄거면 업데이트 된 상태의 data를 반환하거나 id를 반환하는 것이 좋지 않을까? 생각했습니다. 여전히 이해되지 않아 변경점이 없는 경우 예외를 dao에서 발생시켰습니다. 혹시 제가 놓치고 있는 부분이 있을까요?

2023-05-18 08:38 UTC, shb03323 commented on src/main/java/subway/application/LineService.java
> +        final Long lineId = lineDao.insert(LineConverter.toEntity(lineDto));
18. 맞아요... 너무 많은 일을 하고 있다고 느꼈습니다. 하지만 모두 Line 관련 기능들이라 분리하기 어렵다고 느껴져서요. line에 역 등록과 삭제 메소드를 새로운 service로 만드는 것이 좋을까요? 그렇다면 controller와 service가 1:1로 매핑되지 않을 것 같아서요. 꼭 controller와 service가 1:1로 매핑되어야할까요? 만약 아니라면 쪼갤 것 같습니다!

2023-05-18 08:48 UTC, shb03323 commented on src/main/java/subway/business/domain/LineSections.java
> +    public static LineSections createWithSort(final Line line, final List<LineSection> unsortedSections) {
현재 요구사항에서는 Y입니다. 정렬된 LineSections를 사용하지 않는 부분이 없기 때문에 윗 코드와 같이 작성했습니다. 생성자에서 정렬하지 않은 이유는 조금의 로직이 있기 때문에 정적 팩토리 메소드를 써야한다고 생각했기 때문입니다.
만약 정렬되지 않은 상태의 LineSections도 요구사항으로 필요하다면 private 생성자를 public으로 바꾸어주기만 하면 되기 때문에 지금처럼 정적 팩토리 메소드를 활용하는 것이 확장성에 좋을 것 같습니다.

2023-05-18 08:57 UTC, shb03323 commented on src/main/java/subway/persistence/LineDao.java
> +public class LineDao {
1. 여러 query를 호출하는 경우에 이미 이전에 join을 한 경우(같은 fk인 경우만)에 db와 통신하여 같은 join을 계속하여 데이터를 들고오는 것을 말합니다.
2. 해당 테이블 뿐만 아니라 다른 테이블과도 연관지어 검색하게 됩니다.
3. txt 파일을 읽는 것처럼 해당 테이블에서만 정보를 읽어옵니다.

2023-05-18 12:37 UTC, shb03323 commented on src/test/java/subway/business/LineServiceTest.java
> +@ExtendWith(MockitoExtension.class)
1. 제 생각에 mocking된 객체의 메소드가 올바르게 호출되었는지 정도를 검증한다고 생각합니다.
2. 단위 테스트를 진행할 때 실행에 호출되는 다른 mock 객체의 메서드에 예상되는 올바른 입력과 출력을 세팅하고, 원하는대로 기대값이 나오는지 검증하는 용도입니다. tdd하기는 되게 편했습니다.
3. verify의 경우 함수의 올바른 기대값을 기대하기 보다는 호출 횟수정도만 기대하기 때문에 빠른 테스트 제작이 가능한 반면에 순전히 테스트를 믿기는 어려울 것 같습니다. stub의 경우, 미리 출력을 설정해놓기 때문에 verify보다는 안심됩니다.

2023-05-18 14:28 UTC, jamie9504 requested changes
디투, 안녕하세요. 리뷰어 제이미입니다.

추가 코멘트 남겨두었습니다 😄 💪

2023-05-18 14:28 UTC, jamie9504 commented on src/main/java/subway/application/LineService.java
> +        final Long lineId = lineDao.insert(LineConverter.toEntity(lineDto));
_2. 👍  코멘트를 하나 달았을 때, 이하 동일한 구조의 요소는 같은 의미이기 때문에 하나만 말씀드린 부분이었습니다 😄 
> findAll이라는 네이밍으로도 동료 개발자에게 조회만 하는 메서드라는 것을 전달할 수 있다고 생각하여 어노테이션을 붙이지 않았습니다. 붙여주는 것이 오히려 성능 저하를 만들기 때문이라고 생각해서요😄 또 궁금한 점이 있습니다! 제이미 말씀대로 어노테이션을 붙여준다면 findById에 대해서도 붙여야한다고 생각하는데, findAll만 말씀해주신 이유가 있을까요? 다중 검색 특화된 무언가가 있나요?

_5. 관련된 convert 로직을 한 객체에서 담당한다면 단방향 의존일까요?
ex) domain to dto / dto to domain을 해야한다면, domain이나 dto 중 한 객체에서 두 convert를 모두 처리
> 이전에 converter의 역할을 각각 객체의 정적 팩토리 메서드로 감싸면 어떨지도 생각해보았습니다. 만약 domain <-> entity 변환을 각각의 객체의 정적 팩토리 메소드로 만들게 된다면 양방향 의존이 생길 것 같아 converter를 두었습니다. 지금 구현에서는 entity -> domain -> response로 전달되기 때문에 문제가 되진 않지만, domain에서 다시 entity로 바꾸게 된다면 문제가 생길거라고 생각합니다.

_6. 👍  `SIZE_OF_END_POINT_STATION`도 괜찮고, `END_POINT_STATION_SIZE`도 괜찮을 것 같네요!
> 상수명이 너무 길어질 것 같아서 짧게 해보았는데, gpt의 힘을 빌려 상수명을 정해보았습니다. `SIZE_OF_END_POINT_STATION`로 변경했습니다.

_7. 👍 
> 처음에 LineResponse가 존재했어서 LineDetailResponse 네이밍으로 사용했었는데, LineResponse가 쓰이지 않아 삭제했습니다. 삭제하고나서 LineDetailResponse를 LineResponse 로 바꾸어주지 못했네요. 말씀해주셔서 감사합니다!

_8. 이 부분은 save는 저장하는 느낌이라서, 뭔가 새로 만들어주는 부분이라 예를 들자면 `create` 느낌의 메서드가 더 어울리지 않을까 생각했던 부분이었어요! 메서드명에선 `section`을 만들어주는지는 따로 밝히지 않아도 될 것 같긴 하네요 😄 
> LineService의 save 메서드는 이름만 보았을 땐, Line을 저장할 것 같은 느낌이네요.
> 노선을 처음 만드는 것인데 station과 함께 만들어지기 때문에 어색하다는 느낌이 들어요. 말씀해주셔서 감사합니다. 수정했습니다😃 createLineWithSection로 변경했습니다!

_9. 👍 
> sort라는 것을 service가 알 필요는 없다고 생각해 convertToResponse로 메서드 명을 변경했습니다!

_10. 👍 
> 아 놓치고 있었던 부분이었어요. 말씀해주셔서 감사합니다. 분리했습니다😆

_11. station의 식별자는 name인가요? 디투는 유저 입장에서 알기 쉬운 정보로 요청하는 것과, 정확한 식별자로 요청하는 것 중 어떤 부분이 더 중요하다고 생각하고 있나요?
> 초기 노선을 생성할 때 역 2개를 입력해주어야 하는데요. request body로 역의 id를 받는 것은 어색하다고 느껴졌습니다. 사용자의 편의에 맞게 역의 이름으로 입력받고, 개발자는 조금 불편하더라도 findByName으로 정보 그대로 받아야된다고 생각했습니다. 하지만 id만 사용하는데 findIdByName을 사용하지 않고 findByName을 사용한 점은 잘못한 것 같습니다. 수정했습니다 😀

_12. 앗, 이 의미는 boolean을 반환할 수 있는 쿼리를 호출하는 dao 메서드로 만들어보는 건 어떨까라는 의미였어요!
해당 조건이 1건이라도 존재한다면 아예 true를 반환하는 쿼리요 😄 
> sectionDao.findByLineIdAndPreviousStationIdOrNextStationId(lineId, stationId)의 반환을 Optional로 두어 처리하도록 변경했습니다.isEmpty()일 때 boolean을 반환하는 메소드를 사용하게 되면, 반환값을 받은 메서드에서 예외 처리를 하게됩니다. 이 경우에 예외가 더 늦게 반환되어 디버깅할 때 힘들 수 있다고 생각했습니다. "예외는 가능한 빨리 터트린다."는 레벨1때 읽은 이펙티브 자바에 있는 내용을 떠올렸습니다.

_13. 👍 한 메서드에 한 책임을 주면, 활용하기도 유지보수하기도 좋습니다.
> 말씀해주신대로 하게 되면 코드가 길어질까봐 걱정되었습니다. 메소드를 분리할 부분도 보이지 않았구요. 그래도 가장 상위에 있는 메소드에서만 response를 반환해야 동료 개발자들이 오해하지않을 것 같아요. 말씀해주셔서 감사합니다. 수정했습니다!!

_14. 👍 
> 의미를 조금 더 부여했습니다. 이 부분 변수명 고민했었는데, 말씀해주셔서 감사합니다:)

_15. 👍 
> 객체지향적으로 변경했습니다. 놓치고 있었는데 말씀해주셔서 감사합니다😄

_16. 👍 
> 너무 DB 관점으로 본 것 같아요. 수정했습니다!

_17. 👍 상황에 따라서, db connection 비용이 크지 않다면 기존과 같이 호출을 해도 되고, connection 비용이 크다면 지금과 같이 호출을 하면 됩니다! 😃 
> batchUpdate로 해결했습니다. 말씀해주셔서 감사합니다:)

_18. controller에서 여러 service를 가지고 있을 수 있죠! 마치 service에서 여러 dao를 가지고 있는 것처럼요. 대신 한 controller 메서드에서 한 서비스를 호출하는 것이 좋을지, 여러 서비스를 호출해도 좋을지는 고민해봐도 좋겠네요 😄 
> 맞아요... 너무 많은 일을 하고 있다고 느꼈습니다. 하지만 모두 Line 관련 기능들이라 분리하기 어렵다고 느껴져서요. line에 역 등록과 삭제 메소드를 새로운 service로 만드는 것이 좋을까요? 그렇다면 controller와 service가 1:1로 매핑되지 않을 것 같아서요. 꼭 controller와 service가 1:1로 매핑되어야할까요? 만약 아니라면 쪼갤 것 같습니다!

2023-05-18 14:28 UTC, jamie9504 commented on src/main/java/subway/entity/LineEntity.java
>          return Objects.equals(id, line.id) && Objects.equals(name, line.name) && Objects.equals(color, line.color);
설명이 조금 추상적이었던 것 같아서 덧붙여봅니다.

1의 설명은 DB와 1:1으로 매핑되는 Entity를 뜻하고 있습니다.
말씀주신대로 RowMapper를 위한 느낌의 DTO 같은 개념으로 `SectionDetailEntity`를 구현하고 있죠!
Table의 각 컬럼들과 1:1 매핑이되는 객체입니다.

2와 3의 Entity는 다음과 같은 특징을 가지고 있었습니다.
- Entity는 실체
- id를 식별자로 가지고 있으며 이 id를 통해 Entity를 식별 - 따라서 Equals&HashCode를 ID 기반으로 구현
- id 외의 정보가 바뀌더라도 Entity는 다른 객체가 되지 않음

위의 특징을 가진 부분은 디투가 `table과 1:1로 매핑되는 entity`라고 코멘트 남겨주었는데,
DB에 저장하지 않고 Map에다가 저장을 한다면 어떨 것 같나요? 그래도 그 성질을 유지하고 있을까요?
그렇다면 1과 2&3의 Entity는 같은 의미를 가진걸까요?

> 제가 사용하고 있는 도메인은 테이블과 1:1로 매핑되는 개념보다는 실세계에 매핑되는 구조입니다. 그래서 노선 안에 여러 역들이 연결되어 있는 실세계 구조처럼 도메인을 설계했습니다. 

👍 

그렇다면 디투가 구현한 Entity는 1의 Entity인가요, 2&3의 Entity인가요, 1&2&3인 Entity인가요?

> (비즈니스 로직을 위한 객체) id는 일반 유저에게 필요하지 않을 수 있지만 응답을 받는 클라이언트 개발자들에게는 path parameter로 요청을 보낼때 필요하기 때문에 넣어주었습니다.

일반 유저와 클라이언트 개발자를 구분하는 이유가 있을까요?
클라이언트 개발자가 ID를 사용할 수 있다면, 일반 유저도 사용할 수 있을 것 같은데요!

2023-05-18 14:28 UTC, jamie9504 commented on src/main/java/subway/ui/GlobalExceptionHandler.java
> +package subway.ui;
1. 👍 
2. 만약, 해당 프로그램을 Spring WebMvc가 아니라 Console Controller로 전환한다고 한다면, Exception을 전부 수정해야하는걸까요?
Controller단의 변경이 Exception에게 영향을 끼치고, Exception은 다른 레이어에서도 사용이 되는거니까요! 조금 더 순수해야 할 것 같아요.
    > exception을 구분하지 못한 것 같아요. 부모인 badrequest와 nonfound는 controller으로 옮겼습니다. 하지만 여전히 기존 커스텀 예외에서 extends BadRequestException를 사용하는데, 이 부분 또한 의존적인 것으로 보아야할까요?
3. 👍 
4. config레이어에서 사용하는 `StringToSubwayDirectionConverter`는 어디에 위치하는게 좋을까요?
5. `SubwayDirection`는 위의 converter에서도, controller에서도 service에서도 사용중이네요! 어디에 위치하는 것이 좋을까요?
6. `SubwayDirection`에서 convert하는 `from` 메서드를 보면 `.name()`으로 input과 비교를 하게 되는데요. `.name()`을 사용하는 것과 Enum 상수의 멤버변수를 선언해서 `.멤버변수`로 비교하는 것은 어떤 차이가 있을까요?
7. `StationUnregisterInLineRequest`에서 `@JsonCreator`를 사용하고 있는데요, 나중에 시간되면 `@JsonCreator`와 `@JsonValue`에 대해서도 알아봐도 좋을 것 같아요. Enum에서 적용하는 케이스도요!

2023-05-18 14:28 UTC, jamie9504 commented on src/main/java/subway/business/StationService.java
> +    }
1. insert는 성공했는데, dto로 convert에 실패하면 어떻게 될까요? 사용자는 어떠한 응답을 받고 어떠한 동작을 하게 될까요?
2. 아래와 같은 사항들을 고민해보면 좋을 것 같아요.
    - 서비스에서 해당 메서드를 호출할 때, 내부에서 예외를 발생시킬 것을 예상할 수 있을지
    - DAO의 update / delete의 책임은 무엇일지
    - ID가 없으면 예외를 발생시키는 것은 비즈니스 로직일지
    - service가 update된 data수를 알지 않았으면 좋겠다면, 이 부분을 어떻게 검증해볼 수 있을지

2023-05-18 14:28 UTC, jamie9504 commented on src/main/java/subway/business/domain/LineSections.java
> +    public static LineSections createWithSort(final Line line, final List<LineSection> unsortedSections) {
디투가 생각한 `LineSections`라는 도메인 자체가 정렬된 `sections`를 가지고 있는 객체인지, 아니면 그냥 `sections`를 가지고 있는 객체인지가 중요할 것 같아요.

로직 여부로 정적팩터리메서드를 쓸지 생성자를 쓸지는 취향의 차이지만,
만약 `LineSections`가 정렬된 친구를 가지고 있어야 한다면, 생성자에서 정렬할 책임(로직)을 가져도 되겠죠?

또한 `정렬되지 않은 상태의 `LineSections`도 요구사항으로 필요하다면`은 아직 도래하지 않은 상황이니까요.
이 부분까지 고려하는 것은 너무 많은 고려인 것 같기도 해요.
예를 들자면 `StudentName`이라는 도메인이 5글자 이상이면 예외를 발생시킨다고 했을 때, 언젠가 7글자 이상이 될 수도 있으니까 이 부분까지 고려해서 생성자에서 validate를 하면 안되는 걸까요?

2023-05-18 14:28 UTC, jamie9504 commented on src/main/java/subway/persistence/LineDao.java
> +public class LineDao {
1. 👍 요걸 조금 더 자세하게 적어줄 수 있을까요?
2. 👍 
3. 👍 
4. 디투가 생각하는 현재 N+1이 발생하는 포인트는 어느 부분들이 있나요?

2023-05-18 14:28 UTC, jamie9504 commented on src/test/java/subway/business/LineServiceTest.java
> +@ExtendWith(MockitoExtension.class)
위 답변을 적을 때, 디투는 어떤 방식이 더 적절하다고 생각했나요?
물론 정답은 없고 각각의 장/단점 중 어떤 것을 선택할지는 개인(혹은 페어, 팀)의 판단인거니까요.
디투의 관점에서 잘 생각해보고 다른 크루들에게도 장점을 설파해보는 것도 재미있는 경험이 될 거에요! 😃 

1. 불필요하게 과하게 테스트를 작성한 것 같다. verify를 하여 빠르게 테스트 제작을 해야겠다.
2. 조금 과하다 느껴져도 기존처럼 테스트를 작성해서 tdd하기 편하고, 안심할 수 있는 게 좋다.

2023-05-18 14:28 UTC, jamie9504 commented on src/main/java/subway/controller/LineController.java
> +        }
1. noContent를 내려주는 것과 빈 List를 내려주는 것은 어떠한 차이가 있을까요?
2. 지난번 장바구니 미션을 생각해보면서, 위 1번일 때 각각 어떻게 javascript에서 핸들링을 했을지 고민해보는 것도 좋을 것 같아요. (구현 방법을 세세히 고민하는 것이 아닌, 어떤 흐름으로 구현했을지)
3. `unregisterStation`쪽도 함께 고민해보면 좋을 것 같아요!

2023-05-18 14:28 UTC, jamie9504 commented on src/main/java/subway/controller/StationController.java
> +    public ResponseEntity<Void> update(@PathVariable final Long id, @RequestBody final StationRequest stationRequest) {
1. `@valid`가 누락된걸까요?
```suggestion
    public ResponseEntity<Void> update(@PathVariable final Long id, @RequestBody @Valid final StationRequest stationRequest) {
```

2. `@NotNull`, `@NotEmpty`, `@NotBlank` 각 애너테이션은 어떠한 차이가 있나요?

2023-05-18 14:28 UTC, jamie9504 commented on src/main/java/subway/controller/dto/response/LineResponse.java
> +
불필요한 개행은 지워주세요!

2023-05-19 01:47 UTC, shb03323 commented on src/main/java/subway/application/LineService.java
> +        final Long lineId = lineDao.insert(LineConverter.toEntity(lineDto));
5. 말씀해주신 방법대로 한다면 단방향 의존이라고 생각합니다. 좋은 방법 알려주셔서 감사합니다!

2023-05-19 04:19 UTC, shb03323 commented on src/main/java/subway/application/LineService.java
> +        final Long lineId = lineDao.insert(LineConverter.toEntity(lineDto));
8. Section은 Service 외부에서 사용되지 않기 때문에 어색해보이네요. 넵 말씀해주셔서 감사합니다:)
>이 부분은 save는 저장하는 느낌이라서, 뭔가 새로 만들어주는 부분이라 예를 들자면 create 느낌의 메서드가 더 어울리지 않을까 생각했던 부분이었어요! 메서드명에선 section을 만들어주는지는 따로 밝히지 않아도 될 것 같긴 하네요 😄

2023-05-19 04:22 UTC, shb03323 commented on src/main/java/subway/application/LineService.java
> +        final Long lineId = lineDao.insert(LineConverter.toEntity(lineDto));
6. 더 짧게 지을수도 있네요! 감사합니다

2023-05-19 04:35 UTC, shb03323 commented on src/main/java/subway/application/LineService.java
> +        final Long lineId = lineDao.insert(LineConverter.toEntity(lineDto));
11. 정확한 식별자로 정보를 요청하는 것이 중요하다고 생각합니다. 하지만 현재 서비스에서는 name이 unique이기 때문에 식별자를 쓰지 않아도 문제가 된다고 생각하지 않았습니다. 실제 지하철 노선도에서도 부산 <-> 수도권을 비교하는 경우가 아니라면 수도권 지하철 내에서 겹치는 역이 존재하지 않고, 겹치도록 역 이름을 짓는 것 같지 않아서요:)
>station의 식별자는 name인가요? 디투는 유저 입장에서 알기 쉬운 정보로 요청하는 것과, 정확한 식별자로 요청하는 것 중 어떤 부분이 더 중요하다고 생각하고 있나요?

2023-05-19 04:53 UTC, shb03323 commented on src/main/java/subway/application/LineService.java
> +        final Long lineId = lineDao.insert(LineConverter.toEntity(lineDto));
12. dao로 역할 위임을 말씀해주신거군요😆 dao에서 boolean으로 처리하면 좋겠다고 생각했었는데, 그렇게 되면 query 호출 메소드가 private로 되기 때문에 어색하다고 느껴졌거든요. dao의 역할을 DB의 데이터를 뽑아오고 그대로 상위 계층으로 전달해주는 역할이라고 생각했습니다. 제이미께서 말씀해주신 것을 보고 dao에 대해 검색해보았는데 "true/false"로 반환해도 되겠구나! 생각하게 되었습니다. 말씀해주셔서 감사합니다. 
>앗, 이 의미는 boolean을 반환할 수 있는 쿼리를 호출하는 dao 메서드로 만들어보는 건 어떨까라는 의미였어요!
해당 조건이 1건이라도 존재한다면 아예 true를 반환하는 쿼리요 😄

2023-05-19 05:28 UTC, shb03323 commented on src/main/java/subway/application/LineService.java
> +        final Long lineId = lineDao.insert(LineConverter.toEntity(lineDto));
18. 지금 상황에서는 컨트롤러가 2개의 서비스를 갖는다해도 문제가 발생할 것 같진 않아요! 왜 대부분의 코드들이 컨트롤러와 서비스를 1:1로 매칭하는 것으로 짜여있지는 궁금합니다.
>controller에서 여러 service를 가지고 있을 수 있죠! 마치 service에서 여러 dao를 가지고 있는 것처럼요. 대신 한 controller 메서드에서 한 서비스를 호출하는 것이 좋을지, 여러 서비스를 호출해도 좋을지는 고민해봐도 좋겠네요 😄

2023-05-19 05:37 UTC, shb03323 commented on src/main/java/subway/controller/dto/response/LineResponse.java
> +
말씀해주셔서 감사합니다:)

2023-05-19 05:42 UTC, shb03323 commented on src/main/java/subway/controller/StationController.java
> +    public ResponseEntity<Void> update(@PathVariable final Long id, @RequestBody final StationRequest stationRequest) {
1. 감사합니다. 수정했습니다!
2.
`@NotNull`: null만 허용하지 않습니다. ""이나 " "는 허용합니다.
`@NotEmpty`: null과 ""를 허용하지 않습니다. " "는 허용합니다.
`@NotBlank`: null, "", " " 모두 허용하지 않습니다.

지금 프로그램에서는 빈값조차 받으면 안될 것 같다고 생각하여 `@NotBlank`로 수정했습니다. 언급해주셔서 감사합니다😄

2023-05-19 06:00 UTC, shb03323 commented on src/main/java/subway/controller/LineController.java
> +        }
1. 204는 서버가 요청에 대해 성공적으로 처리되었지만 응답 본문에는 내용이 없음을 나타냅니다. 즉 yes or no로 보는 관점인 것 같습니다. 빈 리스트를 반환하는 것은 정보가 0개다 라는 것을 알려주는 것 같습니다. 지금 상황에서는 빈 리스트가 좋은 것 같아요. 말씀해주셔서 감사합니다!
2. 1번일 때 배열로 보고 웹에 그대로 보여주었을 것 같습니다:) 분기처리가 필요하지 않습니다. 비어있다면 비어있는 그대로 보여주고 정보가 들어있다면 들어있는 그대로 보여줬을 것 같습니다.
3. 수정하겠습니다!

2023-05-19 06:44 UTC, shb03323 commented on src/main/java/subway/entity/LineEntity.java
>          return Objects.equals(id, line.id) && Objects.equals(name, line.name) && Objects.equals(color, line.color);
>위의 특징을 가진 부분은 디투가 table과 1:1로 매핑되는 entity라고 코멘트 남겨주었는데,
DB에 저장하지 않고 Map에다가 저장을 한다면 어떨 것 같나요? 그래도 그 성질을 유지하고 있을까요?

2,3에 대한 말씀으로 이해했습니다! 지금 상황에서는 Map의 key값으로 id를 저장하고 value로 정보를 저장해도 성질이 변할 것 같지 않습니다. 식별자가 id인 것은 변하지 않기 때문입니다.

>그렇다면 1과 2&3의 Entity는 같은 의미를 가진걸까요?

1의 경우 만약 식별자가 없는 RowMapper로 정보를 불러온다면 id로 entity를 식별하기 어려울 것 같습니다. table과 그대로 매핑되는 entity라는 생각보다는 db에 있는 필요한 column 정보만 가져오는 인스턴스 느낌이 더 강한 것 같습니다. 저는 `SectionDetailEntity`에 Section id를 식별자로 두긴 했지만, 사실 이 식별자가 사라져도 괜찮다고 생각합니다. 다시 entity로 db에 값을 넣어주지 않을 것이고, response로 필요한 정보를 전달하기 위한 목적의 entity라고 생각하기 때문이죠.

2&3의 경우는 다릅니다. 데이터 베이스에 업데이트를 위한 목적으로 사용될 수도 있기 때문에 식별자가 굉장히 중요하다고 생각합니다. 식별자가 없으면 어떤 객체의 정보를 업데이트 해야하는지 DB는 모르니까요!

>그렇다면 디투가 구현한 Entity는 1의 Entity인가요, 2&3의 Entity인가요, 1&2&3인 Entity인가요?

정보 전달과 도메인 로직을 위한 entity이기 때문에 1의 entity입니다!

>일반 유저와 클라이언트 개발자를 구분하는 이유가 있을까요?
클라이언트 개발자가 ID를 사용할 수 있다면, 일반 유저도 사용할 수 있을 것 같은데요!

물론 일반 유저들도 id를 사용할 수 있을 수 있습니다.
방금 임시로 제가 쓴 글인데요. uri를 확인해보시면 id값이라는 걸 알 수 있습니다.
https://blog.naver.com/shb03323/223106432592

반면에 아래와 같은 테코블 블로그나 앱 환경에서는 사용자에게 id를 노출시키지 않습니다. 웹의 경우 unique한 값만 보여주고, 앱의 경우 uri 자체를 보여주지 않습니다. 반면 클라이언트 개발자는 정보를 받아오기 위해서는 무조건 사용할 수 밖에 없다고 생각합니다.
https://tecoble.techcourse.co.kr/post/2022-10-15-test-code-optimization/

즉, 백엔드 개발자들은 클라이언트 개발자들에게 id값을 주어야 클라이언트 개발자들이 단일 검색 API를 연결할 수 있습니다. 반면에 유저에게 id를 노출시키는 여부는 팀에서 회의를 거쳐서 정해지는 거고, 아직 알 수 없는 사항이기 때문에 클라이언트 개발자와 사용자를 구분한 것입니다. 그리고 유저가 직접 id를 쳐서 조회를 하는 것은 익숙한 flow가 아니라고 생각이 듭니다!

2023-05-19 06:53 UTC, shb03323 commented on src/main/java/subway/ui/GlobalExceptionHandler.java
> +package subway.ui;
2. 아하 감사합니다! exceptionHandler에서 호출되는 메소드의 수를 줄여보고자 했던 것인데, controller 계층에 의존적이 된다면 말씀해주신대로 문제가 발생할 것 같습니다! 수정했습니다!

2023-05-19 08:31 UTC, shb03323 commented on src/main/java/subway/ui/GlobalExceptionHandler.java
> +package subway.ui;
4. 마찬가지로 config에 있어야한다고 생각합니다. 말씀해주셔서 감사합니다!

2023-05-19 08:32 UTC, shb03323 commented on src/main/java/subway/ui/GlobalExceptionHandler.java
> +package subway.ui;
5. request dto로 받아오는 것이기 때문에 request 패키지에 위치했습니다!

2023-05-19 09:08 UTC, shb03323 commented on src/main/java/subway/ui/GlobalExceptionHandler.java
> +package subway.ui;
6. `.name()`의 경우 enum 상수 이름을 가져옵니다. 맴버변수를 선언하더라도 유효합니다! `.맴버변수`의 경우 맴버변수에 설정된 string을 가져오게됩니다.

2023-05-19 09:14 UTC, shb03323 commented on src/main/java/subway/ui/GlobalExceptionHandler.java
> +package subway.ui;
7. `@JsonCreater`의 경우 생성자에서 json 값을 java로 직렬화해줄 때 사용됩니다. 생성이나 초기화 시에 사용됩니다. `@JsonValue`의 경우 반대로 java 반환값을 json으로 변환해줍니다.

2023-05-19 09:19 UTC, shb03323 commented on src/main/java/subway/business/StationService.java
> +    }
1. 아아아 감사합니다! 그런 경우도 있겠군요! 수정했습니다😀

2023-05-19 16:37 UTC, shb03323 commented on src/main/java/subway/business/StationService.java
> +    }
>서비스에서 해당 메서드를 호출할 때, 내부에서 예외를 발생시킬 것을 예상할 수 있을지

저는 예상할 수 있을것 같다고 생각합니다! 실패하면 dao 예외를 발생시컬거라고 생각할 것 같아요:)

>DAO의 update / delete의 책임은 무엇일지

말그대로 수정과 삭제 책임이라고 생각합니다. 실패하면 예외를 던져야한다고 생각해요!

> ID가 없으면 예외를 발생시키는 것은 비즈니스 로직일지

검색된 id가 없는 경우 db 통신이 실패했다는 것을 뜻하기도 하기 때문에 dao의 책임이라고 생각합니다! 예외 발생도 물론 dao에서 해야한다고 생각해요:)

>service가 update된 data수를 알지 않았으면 좋겠다면, 이 부분을 어떻게 검증해볼 수 있을지

update된 data 수를 검증하는 것을 아직 경험해보지 못했기 때문이라고 생각하기도 하는데요. 제 생각을 말씀드리자면, update된 데이터 수를 알기보다 update로 인해 지하철 노선이 올바르게 변경되었는지 확인할 것 같습니다! 처음부터 update 된 data 수를 필요로 하지 않을 것 같아요. 전체 데이터를 보내주어 바뀐 데이터를 보내주는 것이 더 이해하기 쉬운 것 같습니다.

2023-05-19 16:51 UTC, shb03323 commented on src/main/java/subway/business/domain/LineSections.java
> +    public static LineSections createWithSort(final Line line, final List<LineSection> unsortedSections) {
>디투가 생각한 LineSections라는 도메인 자체가 정렬된 sections를 가지고 있는 객체인지, 아니면 그냥 sections를 가지고 있는 객체인지가 중요할 것 같아요.

저는 정렬된 상태의 객체라고 생각했습니다! 지하철 노선도를 보면 항상 정렬이 되어 보여지기 때문입니다.
하지만 가,나,다 순 정렬이라던지, id 순 정렬을 고려한다면 정렬의 기준이 달라질 수도 있다고 생각합니다. 저는 이런 정렬 기준을 위해 정적 팩토리 메소드로 정렬을 하여 생성을 해주었습니다. 정렬의 기준이 달라지면 다른 정적 팩토리 메소드를 만들면 되니깐요! 

>또한 정렬되지 않은 상태의 LineSections도 요구사항으로 필요하다면은 아직 도래하지 않은 상황이니까요.
이 부분까지 고려하는 것은 너무 많은 고려인 것 같기도 해요.
예를 들자면 StudentName이라는 도메인이 5글자 이상이면 예외를 발생시킨다고 했을 때, 언젠가 7글자 이상이 될 수도 있으니까 이 부분까지 고려해서 생성자에서 validate를 하면 안되는 걸까요?

제가 느꼈을 땐 5자에서 7자로 늘리는 것은 많은 고려라고 생각했습니다. 하지만 정적 팩토리 메소드를 사용함으로써 "무언가의 로직이 들어있다"도 표현할 수 있다고 생각합니다. 지금으로는 정렬일텐데, 이 로직이 들어있다는 것을 생성자로 알려주는 것보다 메소드에 의미를 부여함으로써 나타내주고 싶었습니다!

2023-05-19 16:58 UTC, shb03323 commented on src/main/java/subway/persistence/LineDao.java
> +public class LineDao {
지금 상황을 예로 들자면, line_name이 "1호선"에 해당하는 노선도만 보고 싶은데, section에는 line_id로만 매핑이 되어 있어 join을 해야합니다. line_name이 1호선인 line_id는 1이라는 것을 section row 하나하나 불러올 때마다 조회해야합니다. 1호선에 해당하는 역이 20개가 있다면 20번 불러와야하고, 이때마다 join을 해야합니다. 하지만 JPA의 fetch join을 사용한다면 영속성 컨텍스트에 미리 이 join에 해당하는 정보를 저장하고 여기서 join한 테이블의 데이터를 호출하는 것으로 알고 있습니다!
저는 join된 데이터의 정보를 미리 영속성 컨텍스트와 같은 곳에 저장하지 않았기 때문에 n+1 문제가 발생한다고 생각했습니다😀

2023-05-19 17:00 UTC, shb03323 commented on src/test/java/subway/business/LineServiceTest.java
> +@ExtendWith(MockitoExtension.class)
시간이 상대적으로 부족한 페어 프로그래밍에서는 verify로 적용하고, 리팩토링 하면서 stub로 갈 것 같습니다!
금요일 밤이라, 다음주 중에 페어와 여러 크루들과 이야기해보겠습니다:)

2023-05-20 08:37 UTC, jamie9504 approved these changes
디투, 안녕하세요. 리뷰어 제이미입니다.

이번 코멘트는 다음 2단계 때 2단계 PR에 함께 코멘트 주시거나 반영해주세요!
다음 단계도 화이팅입니다 💪 

이만 Approve & Merge하겠습니다.

2023-05-20 08:37 UTC, jamie9504 commented on src/main/java/subway/application/LineService.java
> +        final Long lineId = lineDao.insert(LineConverter.toEntity(lineDto));
_5. 👍 어디에 위치할지는 항상 고민이 되고, 트레이드 오프라서 이런 저런 방향으로 많이 고민해보면 좋을 것 같아요. 물론 레이어를 구분한 구조에서, 의도치 않게 모든 레이어를 어우른다던가 하는 부분이 아니라면 한 방법을 정해서 그 방법으로 통일해가면 좋다고 생각합니다.

_6. 👍 조금 길더라도 `_OF_`형식이 편하면 가도 좋고, 조금 짧은게 좋으시면 `_OF_`를 사용하지 않는 방식으로 가도 좋을 것 같아요. 대신 전반적으로 프로그램에 일관성만 있으면 됩니다!

_8. 👍 

_11. name이 unique하다는 것과 식별자로 사용한다는 같으면서 약간 다른 개념이라고 생각하는데요. 이 부분은 아래 코멘트랑 비슷한 내용인 것 같아서 아래 코멘트에서 얘기해볼게요. `***`를 표시로 달아둘게요! 찾기 기능을 이용해서 내려가도 됩니다.

_12. `findByLineIdAndPreviousStationIdOrNextStationId` 내부의 쿼리 자체를 boolean으로 반환한다는 의미였는데요!
`.isEmpty()`를 체크하는 방식이라면 기존처럼 서비스에 위치하는 것이 더 좋아보이긴 하네요. Dao는 말 그대로 Data Access Object니까요!
SQL의 COUNT 기능을 이용하면 boolean으로 반환할 수 있을 것 같아요!

_18. 굳이 분리할 필요가 없다면 한 서비스로 만들기 때문이죠! 😄 그렇지만 크기가 커진다면 관리를 위해 분리해주는 것도 좋은 선택이라고 생각해요 👍

2023-05-20 08:37 UTC, jamie9504 commented on src/main/java/subway/entity/LineEntity.java
>          return Objects.equals(id, line.id) && Objects.equals(name, line.name) && Objects.equals(color, line.color);
DB의 관점에서 생각을 해볼까요?
- `Section`, `Line`, `Station`을 관리하기 위해 ID 값이 있죠?
- ID는 Table을 식별하기 위한 무언가입니다.

Java의 관점에서 생각을 해볼까요?
- `Section`은 Section으로 무언가 작업을 하지 않고 있기 때문에, 식별자가 별도로 필요 없겠죠?
- `Line`과 `Station`은 작업을 하기 위해 식별자가 필요한거겠죠?

그렇다면 아래와 같이 구분해볼 수도 있겠네요?
- `Section` - DB 테이블
- `Line`, `Station` - DB 테이블 + 식별자가 필요한 무언가

위와 같다고 생각했을 때
1. 식별자를 이용한 무언가의 작업이 Service의 책임이라고 생각하시나요? 아니면 Domain 또는 Entity의 책임이라고 생각하시나요?
2. Entity는 Table과 1:1 매핑이 되고 있는데요. DB를 사용하지 않고, Map이나 List에 저장을 한다고 가정했을 때에도 지금과 같은 구조로 구현할 예정일까요?

---

`***`

식별자란? 무언가를 조회할 때 사용하는 key
- key로 쓰려면 Unique한 값이어야하겠죠? 그렇지만 Unique한 값이라고 key는 아닙니다 :)

1. naver blog - `id`를 식별자로 사용 (posting id)
3. github blog - github에서 url을 식별자로 사용하고 있기 때문에, 파일명을 식별자로 사용 (file name)
    - ex) https://github.com/woowacourse/tecoble/blob/main/src/content/post/2022-10-15-test-code-optimization.md
4. tistory blog - id 또는 `post name을 이용한 식별자` 선택

이렇게 보았을 때, github blog가 사용자를 위해서 id 대신 파일명을 보여줬다고 생각해야할까요?
이 부분은 URL의 식별자가 디렉터리 or 파일명이기 때문에 이를 보여줬다고 보는 것이 맞을 것 같습니다.

Tistory의 경우, 두 방식을 모두 제공하고 있는데 이 부분은 사실 사용자가 편하게 요청을 하라고 있다기 보단, SEO(search engine optimization; 검색 엔진 최적화)를 위해 나온 방식이긴 한데요.
사실 이런 경우엔, 식별자를 2개로 놓았다고 보아야 합니다. 왜냐하면 같은 이름의 포스팅을 등록했을 때, URL에서 사용하는 `post name을 이용한 식별자`는 넘버링이 되기 때문입니다. 이는 블로그 포스팅명을 다시 바꾸더라도 수정되지 않습니다.

즉, 모두 식별자를 이용해서 호출을 하고 있는 부분인건데요.
위에서 지하철명은 확장시 name이 중복이 되거나, 이름이 변경될 수 있는 부분이라고 생각합니다.
그래도 name으로 받는 것이 좋을까요?

2023-05-20 08:37 UTC, jamie9504 commented on src/main/java/subway/ui/GlobalExceptionHandler.java
> +package subway.ui;
_2. 👍 Custom Exception을 비슷한 부류로 추출하여 상위 Exception을 만드는 것도 좋지만, 그 기준이 controller 계층이면 좋지 않겠죠
_4. 👍 
_5. 👍 
_6. 👍 `.name`을 사용하는 경우 Enum 상수명을 바꿨을 때 어떠한 여파가 있을까요? 어떤 방식을 사용하는 것이 좋을까요?
_7. 👍

2023-05-20 08:37 UTC, jamie9504 commented on src/main/java/subway/business/StationService.java
> +    }
> 저는 예상할 수 있을것 같다고 생각합니다! 실패하면 dao 예외를 발생시컬거라고 생각할 것 같아요:)
> 말그대로 수정과 삭제 책임이라고 생각합니다. 실패하면 예외를 던져야한다고 생각해요!

실패하면 DAO에서 예외를 발생시키는게 당연하지만,
수정/삭제시 해당 key가 없어서 아무 동작을 하지 않았을 때, 예외를 발생시키는 것이 좋을지는 고민할만한 포인트라고 생각해요.

> 검색된 id가 없는 경우 db 통신이 실패했다는 것을 뜻하기도 하기 때문에 dao의 책임이라고 생각합니다! 예외 발생도 물론 dao에서 해야한다고 생각해요:)

사용자가 없는 ID로 요청한 경우 DB 통신의 실패가 아닌데, 이 부분이 DAO의 책임일까요?
없는 ID로 조회를 요청한건 사용자의 미스인데, DAO가 이 책임을 가지고 가는게 좋을지 고민되네요 :) 

> update된 data 수를 검증하는 것을 아직 경험해보지 못했기 때문이라고 생각하기도 하는데요. 제 생각을 말씀드리자면, update된 데이터 수를 알기보다 update로 인해 지하철 노선이 올바르게 변경되었는지 확인할 것 같습니다! 처음부터 update 된 data 수를 필요로 하지 않을 것 같아요. 전체 데이터를 보내주어 바뀐 데이터를 보내주는 것이 더 이해하기 쉬운 것 같습니다.

👍

2023-05-20 08:37 UTC, jamie9504 commented on src/main/java/subway/persistence/LineDao.java
> +public class LineDao {
N+1의 궁극적인 문제는, 의도치 않게(혹은 예상하지 못하게) 쿼리가 나뉘어 호출되는 부분이라고 생각합니다.
JPA는 사용자가 직접 쿼리를 질의하지 않기 때문에 이와 같은 문제가 발생할 수 있는데요.
현재는 JDBC를 사용하고 있기 때문에, 디투가 의도하지 않은 쿼리가 발생하진 않는다고 생각해요. 만약 원하지 않는만큼 쿼리가 호출된다면 로직의 문제가 아닐까 의심해볼 수 있겠네요.

2023-05-20 08:37 UTC, jamie9504 commented on src/main/java/subway/controller/LineController.java
> +        }
1. 👍 
2. 👍 
3. 값이 없어서 204를 내려줄지, 값이 없어도 다른 성공건과 동일하게 200을 내려줄지 등등 응답에 대해 디투만의 기준을 가지는 것도 중요하고, 협업하는 사람들과 입장을 어떻게 맞춰볼지 고민해보는 것도 중요할 것 같아요 👍 
(ex. FE에서 성공시 무조건 200으로 내려달라고 한다면 어떻게 할 것인가?)

2023-05-20 08:37 UTC, jamie9504 commented on src/main/java/subway/controller/GlobalExceptionHandler.java
> +    @ExceptionHandler(DuplicatedStationNameException.class)
DuplicatedStationNameException, DuplicatedLineNameException 등 세세하게 도메인+상황별로 CustomException을 만들고 있네요.

Exception을 다루는 다음과 같은 방법들이 있을 수 있는데, 각각 어떠한 장/단점이 있고 디투가 생각하기엔 어떤 방식이 가장 취향인지 고민해볼까요?

1. Java에서 제공하는 Exception 사용
2. Custom Exception 사용 - 현재와 같이 Domain + 상황별 세세하게 분리
3. Custom Exception 사용 - 비슷한 Domain + 상황을 조금 뭉뚱그려 분리
4. Custom Exception 사용 - 3번을 선언하고 상속하여 2번을 구현

2023-05-20 08:37 UTC, jamie9504 commented on src/main/java/subway/controller/GlobalExceptionHandler.java
> +    @ExceptionHandler(LineOrStationNotFoundException.class)
요런 부분은 Test가 되고 있지 않네요! 이것도 추가해볼까요?

2023-05-20 08:37 UTC, jamie9504 commented on src/main/java/subway/service/LineModifyService.java
> +
불필요한 개행은 좋지 않다고 생각해요. 😢

2023-05-20 08:37 UTC, merged

2023-05-22 07:59 UTC, shb03323 commented on src/main/java/subway/application/LineService.java
> +        final Long lineId = lineDao.insert(LineConverter.toEntity(lineDto));
12. COUNT 기능을 놓치고 있었네요. 말씀해주셔서 감사합니다!

상세한 코멘트 정말 감사합니다:)

2023-05-22 08:25 UTC, shb03323 commented on src/main/java/subway/entity/LineEntity.java
>          return Objects.equals(id, line.id) && Objects.equals(name, line.name) && Objects.equals(color, line.color);
식별자를 이용한 무언가의 작업은 Domain과 Entity의 책임이라고 생각합니다. 서비스의 하나의 트랜잭션은 로직을 실행시키기 위한 작업들의 모임이라고 생각합니다. 작업은 Domain이나 Entity에 위임해야한다고 생각합니다. 아니면 서비스가 너무 커질 것 같아요. 그리고 식별자를 가지고 있는건 서비스가 아니라 Entity나 Domain이기 때문에 Entity와 Domain에서 작업해야한다고 생각합니다.

2023-05-22 08:32 UTC, shb03323 commented on src/main/java/subway/entity/LineEntity.java
>          return Objects.equals(id, line.id) && Objects.equals(name, line.name) && Objects.equals(color, line.color);
Map이나 List에 데이터를 저장한다고 가정하면 Section을 제외한 Line, Station와 LineEntity, StationEntity 두 묶음 중 하나를 없앨 것 같습니다. 만약 지금의 Section 도메인처럼 저장할 수 있다면 Entity 관련 모든 객체를 제거할 것 같습니다! (Section에 id가 있다는 가정하에)

제 스스로 만족스러운 답변이 아닐 것 같아요ㅠㅠ 레벨1때와 같은 상황으로 가정하고 답변드렸는데, 이걸 의도하신 것이 맞을까요?

2023-05-22 08:45 UTC, shb03323 commented on src/main/java/subway/entity/LineEntity.java
>          return Objects.equals(id, line.id) && Objects.equals(name, line.name) && Objects.equals(color, line.color);
`***`

식별자를 잘못 사용한다면 발생하는 문제점들 말씀해주셔서 감사합니다. 경각심 크게 느꼈습니다! 식별자를 너무 얕게 본 것 같아요.
지하철 역이 바뀐다고 해도 id로 검색하면 최소한으로 수정할 수 있을 것 같습니다. 말씀해주셔서 감사합니다:)

2023-05-22 08:49 UTC, shb03323 commented on src/main/java/subway/ui/GlobalExceptionHandler.java
> +package subway.ui;
6. `.name()`을 사용하게 된다면 request body로 들어오는 string 또한 달라져야합니다. 의도되지 않았다면 오류가 발생할 것 같습니다. 상수명과 같은 이름이더라도 맴버를 만들어주는 것이 유지보수 면에서 좋을 것 같아요!

2023-05-22 08:55 UTC, shb03323 commented on src/main/java/subway/business/StationService.java
> +    }
아하! 아무 동작을 하지 않았을 때인 경우 db 통신의 문제가 아니기 때문에 service 책임이라고 생각합니다. 알려주셔서 감사합니다:)

2023-05-22 08:56 UTC, shb03323 commented on src/main/java/subway/persistence/LineDao.java
> +public class LineDao {
아하 말씀해주셔서 감사합니다. n+1을 너무 얕게 이해하고 있었어요.

2023-05-22 08:56 UTC, shb03323 commented on src/main/java/subway/controller/GlobalExceptionHandler.java
> +    @ExceptionHandler(LineOrStationNotFoundException.class)
반영했습니다!

2023-05-22 11:40 UTC, jamie9504 commented on src/main/java/subway/entity/LineEntity.java
>          return Objects.equals(id, line.id) && Objects.equals(name, line.name) && Objects.equals(color, line.color);
추가코멘트 - https://github.com/woowacourse/jwp-subway-path/pull/196