[1단계 - 지하철 정보 관리 기능] 이오(이지우) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #66
Opened 2023-05-11 08:50 UTC by LJW25

2023-05-12 13:11 UTC, wannte requested changes
안녕하세요! 이오 :) 이번 미션을 함께할 완태입니다!

쉽지 않은 미션임에도 잘 구현해주셨네요!

고민할 포인트 리뷰 남겼습니다! 혹시 리뷰 관련 이해 안 되는 부분이 있다면, 댓글 남겨주시면 도와드리도록 하겠습니다!

2023-05-12 13:11 UTC, wannte commented on src/main/java/subway/dto/StationRequest.java
> +    private Integer nextDistance;
매번 snake case 로 처리하기 번거로울 것 같은데요!

만약 설정하고 싶다면, jackson 전체적으로 적용할 수 있는 옵션을 찾아보시는 걸 추천드려요!
실수할 여지도 있고, 유지보수하기도 어렵다 생각합니다.

2023-05-12 13:11 UTC, wannte commented on src/main/java/subway/dto/StationRequest.java
> +    private Integer previousDistance;
서버에서의 처리를 용이하게 하기 위해, 너무 많은 값을 request 로 받고 있는 것은 아닌가 싶습니다. 꼭 필요한 값 만을 받는 것은 어떨까요?

 만약 여러 클라이언트가 동시에 서버에 요청을 보내게 된다면, 지금의 구현은 버그를 만들어 낼 수 있다 생각합니다!

2023-05-12 13:11 UTC, wannte commented on src/main/java/subway/application/StationService.java
> +
현재 구현된 saveStation 은 역을 등록하는 것이 아닌 section 을 등록하는 것으로 보입니다.

1. Station을 등록한다.
2. Line에 Section(Station, Station) 을 등록한다.

이 두 가지 기능이 각각 구현되어야 할 것 같습니다.

2023-05-12 13:11 UTC, wannte commented on src/main/java/subway/domain/SubwayMap.java
> +
SubwayMap 이라는 개념이 새롭네요! :+1:

해당 역할에 대한 설명을 요청드려도 될까요?

2023-05-12 13:11 UTC, wannte commented on src/main/java/subway/dto/CreateType.java
> +
희망하기로는, CreateType 을 클라이언트 측에 의존하기보다는 직접 서버에서 구현해보는 것이 어떨까 해요!

(createType 을 구성하기 위해 클라이언트 로직이 매우 복잡해질 것이라 생각합니다.)

2023-05-14 05:02 UTC, LJW25 commented on src/main/java/subway/dto/StationRequest.java
> +    private Integer nextDistance;
조언 감사드립니다! 처음에 전체 적용되는 어노테이션을 사용하였으나, API 에러를 해결하기 위해 이것저것 시도해보다 미처 원상태로 돌리지 못하고 푸시하였네요🥲 수정하겠습니다!

2023-05-14 12:46 UTC, LJW25 commented on src/main/java/subway/dto/StationRequest.java
> +    private Integer previousDistance;
현재 사용하지 않는 값과, 구조를 바꾸며 필요없어진 값을 삭제하여 요구하는 request 파라미터의 수를 줄였습니다!

2023-05-14 12:46 UTC, LJW25 commented on src/main/java/subway/dto/CreateType.java
> +
request의 값에 따라 service에서 생성 요청의 유형을 구분하도록 구조를 변경하였습니다 :)

2023-05-14 12:47 UTC, LJW25 commented on src/main/java/subway/domain/SubwayMap.java
> +
SubwayMap은 지하철 노선도를 그래프의 구조로 나타내기 위한 객체입니다! 그래프 맵은 각 역을 키로, 역이 향하고 있는 길들의 리스트를 값으로 가지고 있습니다. 또한 각 노선별 시작점(상행종점)을 나타내기 위한 맵을 포함하여 노선도의 전체 정보를 담고있습니다. 노선에 새로운 역을 추가하거나 삭제하는 등의 연산도 해당 객체 내에서 수행하고 있습니다.

2023-05-14 12:50 UTC, LJW25 commented on src/main/java/subway/application/StationService.java
> +
해당 기능을 구현하려면 상당히 많은 코드를 수정해야할 것 같습니다. 현재의 코드에는 부족한 부분이 많아 새로 구현을 하려 하는데, 혹시 이 부분은 2단계에서 반영을 해도 괜찮을까요? 기본적인 구조는 유지하되 역할 분리를 다시하고, 말씀해주신 것과 같은 기능을 구현할 수 있도록 로직을 변경하려 합니다!

2023-05-15 01:40 UTC, wannte commented on src/main/java/subway/dto/StationRequest.java
> +    private final Integer nextDistance;
이 정보도 버그를 만들어 낼 수 있다 생각합니다.

ex) A,B 유저가 동일하게 Line 정보를 봄 => A 가 수정 => (실제 데이터는 변경되었으나 원본에 기반하여) B 가 수정

노선에 역을 추가하는 API는 request json은 아래와 같은 형태가 되어야 한다 생각합니다.

```JSON
  {
    "previousStationId" : 3,
    "nextStationId" : 1,
    "distance" : 5
  }
```

추가로, 노선 처음 생성과 노선에 역을 추가하는 api 는 분리되어야 하지 않을까 싶어요

2023-05-15 01:40 UTC, wannte commented on src/main/java/subway/domain/SubwayMap.java
> +
해당 노선이 책임을 가지고 있는 것이 아니라, SubwayMap에 역과 관련된 책임을 주신 것 같네요! (지하철 노선도 전체가 이것을 관리한다)

제 개인적인 생각으로는 노선이 지나는 역에 대한 정보를 가지게 된다면, 로직이 간단해질 것 같은데 이오는 어떻게 생각하시나요?

2023-05-15 01:40 UTC, wannte commented on src/main/java/subway/application/StationService.java
> +
가능하다면, 지금 단계에서 수정을 완료한 후 넘어가는 것은 어떨까요?

Scope 이 너무 커지면 작업자도 힘들어지고, 리뷰하는 입장에서도 쉽지 않아져서요 😭 

의견 주시면, 이오의 의견대로 진행하도록 하겠습니다 👍

2023-05-15 01:40 UTC, wannte requested changes
안녕하세요! 이오!

리뷰 짧게 추가로 남겼어요! 확인 부탁드려요

2023-05-15 01:40 UTC, wannte requested changes
안녕하세요! 이오!

리뷰 짧게 추가로 남겼어요! 확인 부탁드려요

2023-05-17 16:08 UTC, LJW25 commented
안녕하세요 완태, 이오입니다!
이번에 새롭게 코드를 작성하며 구조를 수정하였습니다.
DB 구조는 README를, API는 Line.http를 참고해주시면 됩니다.
리뷰해주셔서 감사합니다 :)

---

### 반영한 피드백

1. SubwayMap이 가지고 있는 역과 경로에 관한 정보를 Line(노선)이 책임을 가지도록 도메인을 변경한다.
    
    → 기존에 노선도를 관리하는 역할을 하던 `SubwayMap`을 삭제하고, `LinkedHashMap<Station, Section> SectionMap`을 새롭게 만들어 `Line`의 필드로 두었습니다. SectionMap은 생성 될 때에 노선의 역 순서에 따라 정렬되며, 역과 구간의 추가, 제거를 수행합니다.
    
2. 새 역을 추가하는 것과 노선에 역을 추가하는 기능을 분리한다.
3. 노선에 첫 역을 추가하는 API를 분리한다.
    
    → 기존의 구조는 확실히 문제가 있었기에 (이미 존재하는 역은 노선에 추가할 수 없는 등) 말씀해 주신 구조로 변경하였습니다. 이에 따라 API도 다음과 같은 방식으로 변경되었습니다.
    
    ```
    POST /lines/{id}/station/init  # 노선에 첫 역 추가
    POST /lines/{id}/station/     # 노선에 처음이 아닌 역 추가
    DELETE /lines/{id}/station/{stationId} # 노선에 역 제거
    ```
    
4. 노선에 역을 추가하는 요청의 RequestJson을 변경한다.
    
    → 이 또한 훨씬 단순한 구조로, 백엔드에서 조회와 판단을 수행할 수 있도록 변경하였습니다.
    
    ```
    POST http://localhost:8080/lines/1/station
    Content-Type: application/json
    
    {
      "upStationId": 1,
      "downStationId": 3,
      "distance": 4
    }
    ```
    

---

### 구조 및 기능

- LineController : Line에 역(구간)을 삽입, 삭제하는 API
- LineService : Controller에서 들어온 요청에 따라 적절한 동작 수행.
- LineRepository: DAO를 통해 DB에 저장된 노선, 구간, 역 정보를 취합하여 완성된 line을 만들고, line에 변화가 생겼을 시(구간 변경 등) 이를 저장.
- LineDao, SectionDao: DB와 직접적으로 데이터를 주고받음.

(Station과 관련된 기능들은 스켈레톤 코드에서 거의 수정하지 않았습니다.)

### 구간 삽입, 삭제 로직

- 첫 역 삽입
    - 노선이 비어있는지 검증 후, 입력받은 구간 삽입
- 이후 역 삽입
    - 입력받은 두 역이 노선에 존재하는지 여부를 확인, 둘 중 존재하는 역을 기준으로 삽입 수행
    - 만약 두 역 모두 존재하거나, 모두 존재하지 않으면 예외 발생
    - 종점역
        - 상행/하행 종점역과 연결되는 역이라면 입력받은 구간 삽입
    - 중간역
        - 기준이 되는 역의 상행/하행 역과의 거리를 비교하여 가능한 거리이면 삽입, 기존 구간 수정
- 마지막 역 삭제
    - 노선에 포함된 구간이 하나 뿐인지 검증 후 SectionMap clear
- 역 삭제
    - 해당 역이 포함된 구간 삭제
    - 중간 역이라면 해당 역의 앞, 뒤 역을 연결

2023-05-18 17:49 UTC, wannte approved these changes
안녕하세요 이오! 피드백 반영 확인했습니다!

간단한 피드백 추가 남겼는데, 이 부분은 다음 단계 진행하면서 함께 고민해보시면 좋을 것 같아요!

2023-05-18 17:49 UTC, wannte commented on src/main/java/subway/ui/LineController.java
> +    @PostMapping("/{id}/station")
`/lines` 와 비슷하게 `/stations` 로 복수형으로 하는 건 어떨까 싶어요!

2023-05-18 17:49 UTC, wannte commented on src/main/java/subway/application/LineService.java
> +    }
요청값에 상관 없이

`lineRepository.save(line)` 정도로 통일해서 처리하는 것은 어떨까요?

서비스에서 Line 이 DB에 어떤 방식에 요청을 보내는 지 모두 알고 있는 듯한 구현이라 생각합니다.
`Line 을 저장한다` 의 기능을 case 별로 개별적으로 처리하는 것이라 생각해요.

2023-05-18 17:50 UTC, merged