[1단계 - 지하철 정보 관리 기능] 후추(주찬민) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #71
Opened 2023-05-11 08:51 UTC by Combi153

안녕하세요 조앤!

백엔드 5기 크루 후추입니다.

이번 지하철 미션은 너무 어려웠습니다. 

시간이 부족해서 미션에서 요구한 테스트 코드, TDD 등을 따르지 못했고, 객체지향, 레이어 아키텍처 등 그동안 따랐던 원칙들을 어겼습니다.

심지어 제 코드가 제대로 돌아가는지 확인을 하지 못하고 제출합니다.

많이 부끄럽고 죄송하네요.

정말 부족한 코드겠지만, 리뷰 잘 부탁드립니다. 

앞으로 계속해서 리팩터링하면서, 성장하는 모습을 보여드리도록 최선을 다하겠습니다! 감사합니다

2023-05-12 00:17 UTC, seovalue requested changes
안녕하세요, 후추! 조앤이에요ㅎㅎ
어려운 미션 그래도 잘 구현해주셨네요! 리뷰 남겼는데, 확인 후 다시 리뷰 요청 주세요~
전반적으로 비즈니스 로직이 복잡하다보니 구현이 길어지는 경우가 꽤 많은데 전반적으로 수정해보시면 좋을 것 같아요!

2023-05-12 00:17 UTC, seovalue commented on README.md
> +## 🤼 페어
ㅋㅋ 깜찍하시네용

2023-05-12 00:17 UTC, seovalue commented on README.md
> +    - `/sections/lineId=?` : 역 추가 (구간 추가)
POST의 경우에는 lineId가 requestBody로 들어가야하지 않을까요?

2023-05-12 00:17 UTC, seovalue commented on src/test/java/subway/integration/LineIntegrationTest.java
> +                .body("stationResponses[3].name", equalTo("로운"));
```suggestion
@DisplayName("지하철 노선과 해당하는 역을 조회한다.")
    @Test
    void findStationsByLineId() {
        // given - when
        ExtractableResponse<Response> response = RestAssured
                .given().log().all()
                .accept(MediaType.APPLICATION_JSON_VALUE)
                .when().get("/lines/{lineId}", 1)
                .then().log().all()
                .statusCode(HttpStatus.OK.value())
                .extract();

        // then
        StationsByLineResponse stationsByLineResponse = response.as(StationsByLineResponse.class);
        LineResponse lineResponse = stationsByLineResponse.getLineResponse();
        List<StationResponse> stationResponses = stationsByLineResponse.getStationResponses();
        assertAll (
                () -> assertThat(lineResponse.getId()).isEqualTo(1L),
                () -> assertThat(lineResponse.getName()).isEqualTo("2호선"),
                () -> assertThat(lineResponse.getColor()).isEqualTo("Green")
        );
        assertAll (
                () -> assertThat(stationResponses.size()).isEqualTo(4),
                () -> assertThat(stationResponses.get(0).getId()).isEqualTo(1L),
                () -> assertThat(stationResponses.get(0).getName()).isEqualTo("후추"),
                () -> assertThat(stationResponses.get(1).getId()).isEqualTo(2L),
                () -> assertThat(stationResponses.get(1).getName()).isEqualTo("디노"),
                () -> assertThat(stationResponses.get(2).getId()).isEqualTo(3L),
                () -> assertThat(stationResponses.get(2).getName()).isEqualTo("조앤"),
                () -> assertThat(stationResponses.get(3).getId()).isEqualTo(4L),
                () -> assertThat(stationResponses.get(3).getName()).isEqualTo("로운")
        );
    }
```
이런 식으로도 할 수 있어요~

2023-05-12 00:17 UTC, seovalue commented on src/main/java/subway/application/StationService.java
> +
아 이거 뼈대코드에서 마음에 들지 않는 부분이 있는데 후추는 어떻게 생각하시는지 궁금해요.

```java
 public StationResponse findStationResponseById(Long id) {
        return StationResponse.of(stationDao.findById(id));
    }
```
위 메서드인데요, 저는 response/request는 presentation layer에서 외부와 값을 주고받는 dto라고 생각을 하는데요, 서비스 내부에서 findStationResponse라는 명칭이 사용되는게 어색하다고 느껴져요. 반환값이 StationResponse인걸 메서드명에 명시할 필요가 있다고 생각하시나요? `findStationById` 가 더 적합해보이는데, 어떻게 생각하시나요?

2023-05-12 00:17 UTC, seovalue commented on src/main/java/subway/application/StationService.java
> +        if (!stationDao.hasId(id)) {
`stationDao.isNotExist` 와 같은 메서드명은 어떠세요?!
근데 findById를 해서 값이 없는 경우 예외를 던져줘도 될 것 같은데, id로 값이 있는지 exist 쿼리를 먼저 날리는 이유는 무엇인가요?!

2023-05-12 00:17 UTC, seovalue commented on src/main/java/subway/domain/Route.java
> +    private final Map<Line, Sections> sectionsByLine;
line을 key로 sections를 갖도록 해주신 이유가 궁금해요!

실제 지하철 노선도를 생각해봤을 때, 1호선 안에 여러 구간들이 등록되어있고 그 구간들은 역으로 이루어져있는 것 같아요. 그렇다면, Line 내부에 Sections가 있어야하는건 아닐까요? 어떻게 생각하시나요오~?

2023-05-12 00:17 UTC, seovalue commented on src/main/java/subway/domain/Sections.java
> +    public void insertInitially(final Station from, final Station to, final int distance) {
만약 이 메서드의 존재를 모르는 다른 개발자라면 삽입 시 아래 insert 메서드를 이용할 수 있을 것 같은데, 통일해보는 것은 어떨까요!

2023-05-12 00:17 UTC, seovalue commented on src/main/java/subway/domain/Sections.java
> +            }
비즈니스 로직이 길어서 가독성이 떨어지는 것 같아요

2023-05-12 00:17 UTC, seovalue commented on src/main/java/subway/domain/Sections.java
> +    public void updateStation(final Station targetStation, final Station updateStation) {
마찬가지로 비즈니스 로직이 너무 길어요~

2023-05-12 00:17 UTC, seovalue commented on README.md
> +);
이건 기존 설계엔 있었다가 deprecated 되었나요?

2023-05-12 00:17 UTC, seovalue commented on src/main/java/subway/application/RouteService.java
> +    private Route route;
너무 많은 멤버를 가지고 있어요! 리팩터링 해 보시면 어떨까요~

2023-05-12 00:17 UTC, seovalue commented on src/main/java/subway/application/RouteService.java
> +        throw new UnsupportedOperationException("처리할 수 없는 요청입니다.");
누구에게 도움이 되는 에러일까요?

2023-05-17 11:44 UTC, Combi153 commented on README.md
> +## 🤼 페어
ㅋㅋㅋ감사합니다 ㅎㅎ

2023-05-17 12:00 UTC, Combi153 commented on README.md
> +    - `/sections/lineId=?` : 역 추가 (구간 추가)
리팩터링 과정에서 수정했습니다!

다만, 어째서 requestBody에 있어야 하는지 정확한 근거는 모르겠습니다.

제가 requestBody로 리팩터링한 이유는 다음과 같습니다.
- 지난 장바구니 미션에서 POST 요청은, 사용자가 데이터를 웹에 입력하고 버튼을 누르는 형태로 이뤄졌습니다. 이러한 배경에서는 데이터로 특정 URL을 만드는 것보다 body에 담는 것이 자연스럽게 느껴졌습니다.

조앤이 어떻게 생각하시는지 궁금합니다!

2023-05-17 12:02 UTC, Combi153 commented on src/test/java/subway/integration/LineIntegrationTest.java
> +                .body("stationResponses[3].name", equalTo("로운"));
감사합니다 😄 안 그래도 보기 불편했던 코드였습니다. 앞으로 response로 추출해서 검증한는 방법을 애용하게 될 것 같아요!!

2023-05-17 12:06 UTC, Combi153 commented on src/main/java/subway/application/StationService.java
> +
저도 `findStationById`가 더 적합하다고 생각합니다.

현재 메서드의 이름이 DTO에 의존적이어서, DTO가 변경되면 메서드 이름도 변경돼야 합니다. Service 메서드의 이름은 DTO에 의존하지 않아야 한다고 생각합니다.

관련 코드를 수정하였습니다! 😀

2023-05-17 12:09 UTC, Combi153 commented on src/main/java/subway/application/StationService.java
> +        if (!stationDao.hasId(id)) {
짧은 시간 안에 구현하느라, 더 쉽게 갈 수 있는 길을 돌아가버렸네요 😅 

findById에서 값이 없는 경우, 예외를 던지도록 수정하였습니다!

한편 메서드명도 isNotExist가 더 적절한 것 같습니다. 추후 비슷한 로직이 있게 된다면,  네이밍에 더 신경쓰겠습니다!

2023-05-17 12:18 UTC, Combi153 commented on src/main/java/subway/domain/Route.java
> +    private final Map<Line, Sections> sectionsByLine;
두 가지 문제가 있었습니다. 먼저, 기존에 있던 뼈대 코드를 잘못 해석했습니다. 그리고 복잡한 도메인 로직을 웹 애플리케이션에서 어떻게 구현할지를 고민하다가 코드가 산으로 가버렸습니다.

- 뼈대 코드에 호선 수정, 호선 삭제 등의 기능이 있어서 전체 Line을 관리하는 객체가 필요하다고 생각했습니다. 그래서 Map에 Key로 Line을 두게 됐고, 자연스럽게 Sections가 Value로 들어갔습니다.
- 2단계 때 그래프를 만들 때 이 자료구조가 편할 것으로 예상했습니다. 

다시 돌아간다면, 분명 만들지 않을 객체입니다. 시간의 압박으로 인해 코드가 부자연스러워졌어요.

레벨1 때 가장 많이 배운 것이 객체지향입니다. 역과 구간과 노선을 객체로 생각한다면, 구간이 노선을 갖는 것이 자연스러운 것 같습니다.

노선이 구간으로 이뤄져있도록 리팩터링하였습니다!

2023-05-17 12:19 UTC, Combi153 commented on src/main/java/subway/domain/Sections.java
> +    public void insertInitially(final Station from, final Station to, final int distance) {
동의합니다. 충분히 통일할 수 있을 것 같습니다. 리팩터링하겠습니다

2023-05-17 12:20 UTC, Combi153 commented on src/main/java/subway/domain/Sections.java
> +            }
로직을 다시 짜고, 메서드를 분리했습니다. 최대한 가독성을 높이려고 했는데, 보기에 괜찮으신지 궁금합니다!

2023-05-17 12:20 UTC, Combi153 commented on src/main/java/subway/domain/Sections.java
> +    public void updateStation(final Station targetStation, final Station updateStation) {
넵 이 메서드도 리팩터링했습니다!

2023-05-17 12:22 UTC, Combi153 commented on README.md
> +);
넵 기존에는 있었다가 DB에 저장할 필요성을 느끼지 못해 삭제했습니다.
README에서는 미처 삭제하지 못했네요.

이번에 제출한 결과물은 정말 꼼꼼하지 못했던 것 같습니다. 반성합니다 😭

2023-05-17 12:23 UTC, Combi153 commented on src/main/java/subway/application/RouteService.java
> +    private Route route;
넵 리팩터링하겠습니다. RouteService가 Route를 갖는 구조 자체도 문제가 있는 것 같다고 생각했습니다. Route는 꼭 빼겠습니다!

2023-05-17 12:25 UTC, Combi153 commented on src/main/java/subway/application/RouteService.java
> +        throw new UnsupportedOperationException("처리할 수 없는 요청입니다.");
이 예외는 로직이 개발자가 예상한대로 흘러간다면 발생하지 않을 예외입니다. 즉 사용자의 잘못된 요청 등에 의한 예외가 아닙니다. 코드에 문제가 있어서 발생한 예외일 것입니다. 따라서 개발자에게 도움이 되는 예외입니다.

위와 같은 예외를 어떻게 처리할지 고민하다가 IllegalStateException을 발생시키도록 하고, 개발자를 대상으로 예외메시지를 작성했습니다.

적절히 예외를 처리한 것인지 궁금합니다!

2023-05-17 12:51 UTC, Combi153 commented
안녕하세요 조앤!

백엔드 5기 크루 후추입니다.

지하철 미션의 리팩터링을 마치고, 재리뷰 요청을 드립니다!

더 일찍 리뷰 요청을 하고 싶었는데, 코드를 싹 갈아 엎고 다시 짜느라 오래 걸렸습니다. 😢 

그래도 TDD, Layered Architecture, 객체지향 등에서 고민과 공부를 할 수 있던 소중한 시간이었습니다.

지난 리뷰에 코멘트를 달았습니다. 확인해주신다면 감사하겠습니다! 😀 

리뷰가 너무 늦어져 죄송합니다. 그래도 잘 부탁드립니다!

## 도전한 부분

### 1. 도메인과 Entity의 분리
코드를 리팩터링하면서 도메인 객체와 DB 테이블의 정보가 서로 매칭되지 않는 것을 발견했습니다. 가령, Line 객체는 Sections를 필드로 갖습니다. 다만 Line Table은 Section과 관련한 정보를 갖지 않습니다.

이러한 문제를 어떻게 처리할지 고민하다가 도메인과 Entity를 분리했습니다. 

### 2. Repository의 도입
도메인과 Entity를 분리한 뒤, 도메인 객체를 생성하는 책임을 질 객체가 필요했습니다. Repository 객체를 만들고 여기에서 도메인 객체를 생성할 수 있도록 했습니다. Repository는 도메인 객체들을 관리하는 일종의 자료구조라고 생각하고 접근했습니다. 

### 3. API 변경
기존의 API는 노선에 역을 추가하는 요청의 URL에 Section 이라는 키워드를 노출했습니다. 그러나 사용자 입장에서 노선에 역을 추가할 때 Section 키워드를 알 필요가 없을 것이라 생각했습니다. 따라서 lines, stations 등의 키워드를 적절히 선택해서 요청을 처리할 수 있도록 API를 변경했습니다.

### 4. 테스트 코드
Controller, Service, Domain 등 각 계층에 맞게 테스트 코드를 작성하려고 했습니다. Controller 단에서는 RestAssured 를 활용한 통합테스트를 진행했고, Service는 Mockito로 단위테스트를 했습니다.

모든 테스트에서 100% TDD를 하지는 못했습니다. 어떤 메서드의 호출과 반환 형태가 어떻게 될지 예상이 되지 않는 경우에는, 구현을 먼저 해보고 테스트를 짰습니다.

## 질문
### 1. 집중한 부분에 대한 질문
- 도메인과 Entity 를 분리한 것이 적절했는지 궁금합니다. 
- Repository에 대해 더 공부할 부분이 있는지 알려주시면 감사할 것 같습니다.
- API 변경, 테스트 코드 등에 대해서도 부족한 점을 알려주신다면 감사할 것 같습니다.

### 2. 뼈대 코드 제거
이번 미션을 수행하면서 가장 힘들었던 점은 뼈대 코드를 이해하는 것이었습니다. 이 프로그램이 구체적으로 어떻게 동작할지 쉽게 이해가 가지 않았습니다. 그래서인지 제가 추가하려는 기능과 기존의 코드에 자꾸 모순점이 생겼습니다.

따라서 기존 코드를 과감히 삭제했습니다. 미션 요구사항에 맞는 기능들만 남겨두었습니다.

다만, 개발자로서 이러한 자세가 부적절했다고 느낍니다. 다른 사람이 작성한 코드를 읽고, 거기에 제 코드를 녹여내는 것이 바람직한 개발이라고 생각하기 때문입니다.

조앤이라면, 뼈대 코드를 어떻게 이해하고 개발하셨을지 궁금합니다.

## 참고사항
코드를 싹 갈아엎고 다시 짜느라, 커밋을 제대로 신경쓰지 못했습니다. 앞으로 개발 시 더 주의를 기울이겠습니다.

2023-05-18 08:33 UTC, seovalue commented on README.md
> +    - `/sections/lineId=?` : 역 추가 (구간 추가)
POST에서 body로 보내길 권장하는 이유는 아래와 같아요~

1. **데이터 크기 제한**: URL에 포함된 파라미터는 길이에 제한이 있어용 대부분의 웹 서버와 브라우저는 URL 길이를 2000~4000자로 제한하는 반면, 요청 본문(body)에는 이러한 제한이 없어 대용량 데이터를 보낼 수 있어요
2. **보안**: URL에 포함된 파라미터는 로그에 기록되거나 브라우저 히스토리에 저장될 수 있어요 (데이터독이나 센트리로도 조회 가능) 이로 인해 민감한 정보가 노출될 위험이 있어욥
3. **구조화된 데이터 전송**: 요청 본문을 사용하면 JSON, XML 등의 구조화된 데이터 형식을 사용하여 데이터를 보낼 수 있어요. 이를 통해 복잡한 데이터 구조를 쉽게 전송하고 처리할 수 있어욥
4. **HTTP 메서드의 의미**: POST 메서드는 서버에 새로운 리소스를 생성하도록 요청하는 데 사용돼요. 이때, 생성할 리소스의 데이터를 요청 본문에 포함시키는 것이 적절해요 반면, GET 메서드는 리소스를 조회하는 데 사용되며, 이때 필요한 정보를 URL의 파라미터로 전달해요

1. [MDN Web Docs - HTTP request methods](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods)
2. [REST API Tutorial - HTTP Methods](https://www.restapitutorial.com/lessons/httpmethods.html)
3. [Stack Overflow - When do you use POST and when do you use GET?](https://stackoverflow.com/questions/3477333/when-do-you-use-post-and-when-do-you-use-get)

2023-05-18 09:32 UTC, seovalue approved these changes
안녕하세요, 후추! 조앤이에요ㅎㅎ
리팩터링 엄청 해주셨군요ㅋㅋ 멋집니다
남겨주신 질문에 대한 답변 및 몇가지 리뷰 남겼어요!
우선 1단계는 여기서 마무리하고, 2단계 진행하시면서 제가 남긴 리뷰 반영해보시면 좋을 것 같아요!

2023-05-18 09:32 UTC, seovalue commented on src/test/java/subway/integration/LineIntegrationTest.java
>  public class LineIntegrationTest extends IntegrationTest {
IntegrationTest에 있는 LocalServerPort 애노테이션 Deprecated 된 거더라구요, 
import org.springframework.boot.test.web.server.LocalServerPort; 요 패키지걸로 변경해보심 좋을것같아요~

2023-05-18 09:32 UTC, seovalue commented on src/test/java/subway/integration/LineIntegrationTest.java
> +        assertSoftly(softly -> {
assertSoftly를 사용해주신 이유가 궁금해요!

2023-05-18 09:32 UTC, seovalue commented on src/test/java/subway/application/LineServiceTest.java
> +    private SectionRepository sectionRepository;
사용되지 않아요~

2023-05-18 09:32 UTC, seovalue commented on src/main/java/subway/step/GlobalExceptionHandler.java
> +package subway.step;
왜 패키지 이름이 `step` 인가요..?

2023-05-18 09:32 UTC, seovalue commented on src/main/java/subway/repository/StationRepository.java
> +public class StationRepository {
Repository를 도메인을 담는 컬렉션으로 보는거 좋다고 생각하는데요, 약간 어색하게 느껴지는 점이 그렇다면 들어오고 나가는 값이 전부 Station 이어야할 것 같은데, 막상 들어오는 값은 StationEntity가 들어오고 그걸 단순히 Station으로 반환하는 역할만 하는 것으로 보여요. 

예를 들어 save를 한다고 가정했을 때, service에서 엔티티로 만들어서 repository에 save를 요청하고, dao에 insert까지 마친 상태에서 `toStation()`을 하게 되는데, 이때서야 Station 도메인의 validateName에 걸리게 되는... 순서가 뒤바뀐 느낌이 들어요!

한번 고민해보시면 좋을 것 같아용!

2023-05-18 09:32 UTC, seovalue commented on README.md
> +    - 삭제 : Delete /lines/{lineId}/stations/{stationId}
이거 API에 담기는 요청/응답도 포함해주시면 좋을 것 같아요~

2023-05-18 09:32 UTC, seovalue commented on src/main/java/subway/repository/LineRepository.java
> +        return generateLine(lineDao.findById(id));
Line을 반환하는 경우 항상 `generateLine`을 호출해서 Line에 Sections 정보를 채워줘야하는데요. 만약 다른 개발자가 이걸 놓치게 된다면 Sections 응답은 비어있는 채로 내려갈거에요! 😨

2023-05-18 09:32 UTC, seovalue commented on src/main/java/subway/step/LineController.java
> +    @GetMapping("/stations")
노선에 담긴 역 정보를 내려주는 것 같은데, 이거 자체가 노선 정보를 내려준다고 볼 수 있지 않을까요? 단순히 GET /lines 만 해도 괜찮을 것 같은데, 어떻게 생각하세요?

2023-05-18 09:32 UTC, seovalue commented on src/main/java/subway/domain/section/Sections.java
> +    }
구간을 바꾼다는 메서드명을 가진 이 메서드가 정확히 어떤 일을 하는지 한눈에 파악하기가 어려워요 😢

2023-05-18 09:32 UTC, seovalue commented on src/main/java/subway/repository/SectionRepository.java
> +    }
구간을 업데이트할 때 삭제 후 업데이트를 하는 이유가 궁금해요!

2023-05-18 09:32 UTC, seovalue commented on src/main/java/subway/repository/SectionRepository.java
> +    public List<Section> findSectionsByLineId(final Long lineId) {
사용되지 않는건 제거할까요~?

2023-05-18 09:32 UTC, seovalue commented on src/main/java/subway/domain/line/Line.java
> +    private final Sections sections;
도메인과 엔티티가 분리된 건 적절한 것 같아요! lineEntity가 sections 정보를 가질 수도 있겠지만, 지금 구조에서는 분리되어 구현되어도 좋아보여요. 다만 어느 시점에 엔티티를 사용하고 어느 시점에 도메인으로 변경해주는 지 등을 잘 관리해야할 것 같아요. 다른 리뷰에서도 남기긴 했지만 그냥 아예 dao에서만 엔티티가 활동하고 그 외의 레이어에서는 전부 도메인으로만 사용해도 좋을 것 같구요. 🤔

2023-05-18 09:32 UTC, seovalue commented on src/main/java/subway/domain/section/Sections.java
> +    }
좌측 끝, 우측 끝이 중복이 잦은데 어떻게 해결할 수 있을까요?

2023-05-18 09:32 UTC, seovalue approved these changes
안녕하세요, 후추! 조앤이에요ㅎㅎ
리팩터링 엄청 해주셨군요ㅋㅋ 멋집니다
남겨주신 질문에 대한 답변 및 몇가지 리뷰 남겼어요!
우선 1단계는 여기서 마무리하고, 2단계 진행하시면서 제가 남긴 리뷰 반영해보시면 좋을 것 같아요!

2023-05-18 09:32 UTC, merged

2023-05-21 11:18 UTC, Combi153 commented on src/test/java/subway/integration/LineIntegrationTest.java
>  public class LineIntegrationTest extends IntegrationTest {
헉 전혀 모르고 있었습니다 말씀해주신 패키지로 변경해서 사용할게요!

2023-05-21 11:22 UTC, Combi153 commented on src/test/java/subway/integration/LineIntegrationTest.java
> +        assertSoftly(softly -> {
assertThat 을 여러 개 사용했을 때, 초기에 검증이 실패할 경우 이후 검증 코드는 실행하지 않게 됩니다.
반면 `assertAll`과 `assertSoftly`는 모든 검증 코드를 실행한 후 실패한 테스트에 대해 예상 값, 실제 값을 출력합니다. 그중에서도 assertSoftly는 실패한 코드의 라인까지 보여줍니다. 따라서 assertSoftly 를 사용하였습니다.

2023-05-21 11:26 UTC, Combi153 commented on src/main/java/subway/step/GlobalExceptionHandler.java
> +package subway.step;
다른 패키지를 step으로 이름을 변경하려고 했습니다만, 의도와 다르게 이 패키지를 변경해버렸네요 😅  얼른 수정하겠습니다!

2023-05-21 12:29 UTC, Combi153 commented on src/main/java/subway/repository/LineRepository.java
> +        return generateLine(lineDao.findById(id));
꼼꼼한 지적 감사합니다!

문제가 되는 지점은 Sections 정보가 채워지지 않아도 문제가 없는 것으로 넘어가는 부분이라고 느꼈습니다. 그래서 Line을 반환하는 경우 반드시 Sections 정보를 채워줘야 하는 코드로 변경했습니다!

코드를 더 세심하게 보는 연습을 의식적으로 해야할 것 같습니다! 감사합니다.

2023-05-21 12:39 UTC, Combi153 commented on src/main/java/subway/repository/SectionRepository.java
> +    }
어떤 값을 "수정" 한다고 했을 때, 그 값을 지우고, 새로운 값을 적는 것이 자연스러운 순서라고 생각했습니다.
종이에 이름을 잘못 적어 수정할 때도, 지우개로 먼저 지우고 이름을 다시 적는 것과 같이요.

데이터베이스를 다룰 때는 우선 변경된 데이터를 입력하고 기존 데이터를 삭제하는 것이 맞는 순서일까요?

혼자서 생각해보았을 때는 변경 데이터를 입력할 때 예외가 발생할 가능성이 더 크니, 예외를 빨리 발생시킨다는 점에서 데이터 입력을 우선하는 게 좋다고 생각이 들었습니다.

조앤은 어떻게 생각하시나요?

2023-05-21 12:41 UTC, Combi153 commented on src/main/java/subway/repository/SectionRepository.java
> +    public List<Section> findSectionsByLineId(final Long lineId) {
"언젠가 사용하지 않을까"라는 마음으로 제거하지 않았습니다. 하지만 돌이켜 생각하니 큰 실수였네요! 

반드시 필요할 때 만드는 것이 오버엔지니어링으로 가지 않는 방법이겠죠. 배운 바를 실천하겠습니다!

2023-05-22 02:15 UTC, Combi153 commented on src/main/java/subway/domain/section/Sections.java
> +    }
다양한 방법이 떠오르지만, 가장 간단하게 할 수 있는 방법은 Direction을 추가하는 것 같습니다. 함수 내부에서 Direction에 따라 로직을 달리 수행하도록 바꾸면 될 것 같습니다. 리팩터링 해보겠습니다!

2023-05-22 07:17 UTC, Combi153 commented on src/test/java/subway/application/LineServiceTest.java
> +    private SectionRepository sectionRepository;
사용하도록 코드를 변경했습니다!

2023-05-22 07:19 UTC, Combi153 commented on README.md
> +    - 삭제 : Delete /lines/{lineId}/stations/{stationId}
넵 포함시키겠습니다!

2023-05-22 07:21 UTC, Combi153 commented on src/main/java/subway/step/LineController.java
> +    @GetMapping("/stations")
호선과 역 두 리소스에 접근한다고 생각해서 /stations 를 추가했습니다.

하지만 사용자 입장에서는 두 가지 리소스에 접근을 하는지 알 필요가 없을 것 같습니다! 따라서 /lines 로도 충분할 것 같습니다! 수정하겠습니다

2023-05-22 07:26 UTC, Combi153 commented on src/main/java/subway/domain/line/Line.java
> +    private final Sections sections;
>어느 시점에 엔티티를 사용하고 어느 시점에 도메인으로 변경해주는 지 등을 잘 관리해야할 것 같아요.

레이어가 분리되고, 점점 관리해야 할 클래스들이 많아지니 선택을 내리기 쉽지 않은 것 같습니다. 말씀해주신 것처럼 dao 에서 엔티티를 사용하고, 다른 Repository, Service 에서는 domain 객체를 사용하도록 리팩터링 하겠습니다!!

2023-05-22 07:26 UTC, Combi153 commented on src/main/java/subway/domain/section/Sections.java
> +    }
메서드를 분리해서 가독성을 높여보겠습니다!

2023-05-22 07:36 UTC, Combi153 commented on src/main/java/subway/repository/StationRepository.java
> +public class StationRepository {
얕은 지식이 드러나는 부분이네요 😂 Repository 가 도메인을 담는 컬렉션 역할을 한다면, 들어오고 나가는 값이 모두 도메인 객체가 되어야 할 것 같습니다! 빠르게 예외를 터뜨리는 관점에서도 도메인 객체를 미리 생성하는 것이 훨씬 좋은 방법이라고 생각됩니다.

Repository를 리팩터링하겠습니다