[1단계 - 지하철 정보 관리 기능] 비버(전인표) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #73
Opened 2023-05-11 08:51 UTC by ingpyo

2023-05-12 14:08 UTC, giantim requested changes
비버 안녕하세요! 리뷰어 라빈입니다 👋
이번 단계 미션이 많이 어려우시죠 🥹 아직 도메인과 다른 계층들에 대한 테스트코드 작성이 부족한거 같아요. 그리고 기능 구현이 아직 덜된것 같은데 해당 부분 마무리 후에 다시 의견 나눠보면 좋을것 같습니다! 작업하시면서 궁금하거나 논의하고 싶으신 내용에 대해서는 편하게 말씀주세요!!

2023-05-12 14:08 UTC, giantim commented on README.md
> +``station``
API 명세에 대해서는 별도의 파일로 작성해보면 어떨까요?

2023-05-12 14:08 UTC, giantim commented on README.md
> +- [ ] 노선을 등록 한다.
기능 구현이 완료되었다면 문서 업데이트를 해도 좋을것 같네요!!

2023-05-12 14:08 UTC, giantim commented on src/main/java/subway/application/SectionService.java
> +
불필요한 공백이 있네요 😉

2023-05-12 14:08 UTC, giantim commented on src/main/java/subway/persistence/SectionRepositoryImpl.java
> +    }
기능 구현이 아직 미완성일까요? 🤔

2023-05-15 07:32 UTC, ingpyo commented on README.md
> +``station``
그게 더 처음 제 코드를 보는 사람들이 이해가 더 빠르게될거같네요! 수정하겠습니다!

2023-05-15 07:32 UTC, ingpyo commented on README.md
> +- [ ] 노선을 등록 한다.
넵! 수정하겠습니다!

2023-05-15 07:32 UTC, ingpyo commented on src/main/java/subway/application/SectionService.java
> +
수정하겠습니다!

2023-05-15 07:32 UTC, ingpyo commented on src/main/java/subway/persistence/SectionRepositoryImpl.java
> +    }
네... 미완성이였습니다...
완벽한(아마...) 코드로 리뷰보내겠습니다!

2023-05-16 16:33 UTC, giantim requested changes
비버 안녕하세요! 라빈입니다 👋
초기에 제출해주셨던 코드보다 정말 많이 개선해주셨네요!! 시간이 별로 없으셨을텐데 고생 많으셨습니다 👍
미션에서 요구했던 사항대로 도메인을 풍부하게 구성하신 점 잘하신거 같아요! 서비스 계층을 단순화하고 도메인에 요구사항을 담당하게 하여 확장성 있을것 같네요. 그리고 처음 적용해보실 아키텍처인거 같은데도 의존성 방향이나 계층을 잘 잡아두셨네요 👏
아직 전반적으로 조금 다듬었으면 하는 부분이 있어서 몇가지 리뷰 드렸습니다. 확인 부탁드릴께요!

2023-05-16 16:33 UTC, giantim commented on src/test/java/subway/application/line/CreateLineServiceTest.java
> +    void createLine() {
현재 테스트 케이스의 경우 예외처리에 대한 테스트를 진행하고 있는데요.
메소드 이름을 그에 맞게 수정해볼까요? DisplayName과 거리감이 있네요 ☺️
그리고 서비스 계층에 대한 전체적인 테스트 커버리지를 높이기 위해 예외케이스 뿐만 아니라 정상적인 케이스에 대해서도 테스트 코드를 작성해보면 어떨까요?

2023-05-16 16:33 UTC, giantim commented on src/test/java/subway/application/section/AttachStationServiceTest.java
> +    void createSection1() {
예외경우처럼 조금 더 의미있는 이름을 붙여보면 어떨까요?

2023-05-16 16:33 UTC, giantim commented on src/test/java/subway/application/section/DetachStationServiceTest.java
> +    @DisplayName("삭제가 잘 되는지 테스트")
위에서와 비슷한 리뷰인데요! DisplayName / 테스트 메소드 명을 모두 테스트하는 대상, 과정 등이 담기도록 작성해보면 더 좋을것 같네요! 테스트코드를 다른 개발자들이 코드를 먼저 파악하는 문서 개념으로 사용할 수 있으니 더 구체적인 문장을 작성하는게 좋아보여요 😉

2023-05-16 16:33 UTC, giantim commented on src/main/java/subway/ui/dto/request/LineRequest.java
> +package subway.ui.dto.request;
ui와 persistence 패키지에 대해서 고민이에요 🤔
현재 헥사고날 아키텍처를 적용해 주셨는데요. 외부와 연결을 담당하는(API 호출, 영속화 계층 등) 계층을 adapter 패키지로 묶어보면 어떨까요? 패키지 구조가 조금 더 응집성있고 다른 개발자들이 봤을 때 이해하기 쉬운 구조일것 같아요!

2023-05-16 16:33 UTC, giantim commented on src/main/java/subway/exception/ExceptionAdvice.java
> +public class ExceptionAdvice {
패키지 구조에 대해 드린 리뷰와 이어지는 리뷰인거 같은데요.
예외 처리하는 컨트롤러가 어느 패키지에 포함되면 좋을까요? 현재 exception 이라는 패키지가 subway 패키지 하위에 정의를 해두어서 해당 패키지 안에 어느 역할을 담당하는 클래스가 존재할지 애매한것 같아요. 예를들어 도메인 예외를 정의했을 때 해당 클래스가 여기에 위치하게 될까요? 예외처리를 담당하는 컨트롤러도 스프링 프레임워크에 의존적이며 HTTP 방식을 사용하기 때문에 adapter 패키지가 더 적합해 보이네요! 😉

2023-05-16 16:33 UTC, giantim commented on build.gradle
> +	annotationProcessor 'org.projectlombok:lombok'
음... 롬복을 사용해주셨군요!
롬복을 사용하면 많은 장점이 있죠. 어노테이션 기반으로 중복적으로 작성하는 코드들을 줄여줄 수 있어서요. 조금 번거롭지만 학습 과정에서는 롬복 사용을 지양해보면 어떨까요? 무의식적인 getter 정의나 생성자 정의를 통해 해당 클래스에 이것들이 왜 필요한지에 대해 무감각해질 수 있을거 같아요...!

2023-05-16 16:33 UTC, giantim commented on src/main/java/subway/domain/Sections.java
> +        return upStations.get(0);
왜 0 번째 인덱스를 가져오는지 매직넘버에 의미를 줘보면 어떨까요? 😉

2023-05-17 02:13 UTC, ingpyo commented on build.gradle
> +	annotationProcessor 'org.projectlombok:lombok'
솔직히 뭔가 좀 멋있어보여서 사용했는데...🥹

2023-05-17 02:17 UTC, ingpyo commented on src/main/java/subway/domain/Sections.java
> +        return upStations.get(0);
매직넘버,,,, 제거하겠습니다!!

2023-05-17 02:18 UTC, ingpyo commented on src/test/java/subway/application/section/DetachStationServiceTest.java
> +    @DisplayName("삭제가 잘 되는지 테스트")
아이고,,, 테스트 코드도 신경쓰면서 작성하겠습니다!🥹🥹🥹🥹🥹🥹

2023-05-17 02:18 UTC, ingpyo commented on src/test/java/subway/application/line/CreateLineServiceTest.java
> +    void createLine() {
정상적인 테스트케이스도 추가해놓겠습니다!🥹🥹🥹🥹🥹🥹🥹🥹🥹

2023-05-17 02:25 UTC, ingpyo commented on src/test/java/subway/application/section/AttachStationServiceTest.java
> +    void createSection1() {
더 신경써서 네이밍 수정해보겠습니다!!

2023-05-17 05:56 UTC, ingpyo commented on src/main/java/subway/ui/dto/request/LineRequest.java
> +package subway.ui.dto.request;
한번 제대로 적용해봐야겠네요!! 수정하겠습니다!!

2023-05-17 05:57 UTC, ingpyo commented on src/main/java/subway/exception/ExceptionAdvice.java
> +public class ExceptionAdvice {
적용해보겠습니다!!

감사합니다 라빈!!

2023-05-18 23:33 UTC, giantim approved these changes
비버 안녕하세요! 라빈입니다 👋
리뷰 드린 내용에 대해서 잘 반영해 주셨네요 ☺️ 다음 단계 진행해도 좋을것 같아요! 고생하셨습니다 👍

2023-05-18 23:33 UTC, merged