[1단계 - 지하철 정보 관리 기능] 키아라(김도희) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #79
Opened 2023-05-11 08:53 UTC by kiarakim

에단 안녕하세요 키아라입니다!
너무 어렵네요
리뷰...잘 부탁드려요ㅠ🫠

2023-05-11 13:48 UTC, Laterality requested changes
안녕하세요 키아라.

리뷰를 맡은 에단입니다.

아직 기능이 다 구현되지 않은 듯하네요.

우선 보이는 곳에 코멘트 남겨드렸습니다. 나머지 기능 구현하면서 참고해주세요.

2023-05-11 13:48 UTC, Laterality commented on src/main/java/subway/application/SectionDeleteRequest.java
> +    private String downStation;
`up/downStation`의 ID인지 이름인지도 필드에 나타내면 어떨까요?

2023-05-11 13:48 UTC, Laterality commented on src/main/java/subway/application/SectionService.java
> +public class SectionService {
서비스에 대한 테스트도 작성하면 어떨까요?

2023-05-11 13:48 UTC, Laterality commented on src/main/java/subway/application/SectionService.java
> +    private final StationRepository stationRepository;
쓰이지 않는 필드네요.

2023-05-11 13:48 UTC, Laterality commented on src/main/java/subway/application/StationService.java
> +    public Station findById(final Long stationIdRequest) {
쓰이지 않는 메서드네요.

2023-05-11 13:48 UTC, Laterality commented on src/main/java/subway/domain/Section.java
> +        return this.distance <= newSection.distance;
`Sections`에서 필요한 검증이라면 `Sections`에서 수행하면 어떨까요?

2023-05-11 13:48 UTC, Laterality commented on src/main/java/subway/domain/Section.java
> +    public boolean validateEqualEndPoint(final List<Station> endPoint) {
비어 있거나 요소가 하나 뿐인 컬렉션이 인자로 전달되면 어떻게 될까요?

2023-05-11 13:48 UTC, Laterality commented on src/main/java/subway/domain/Section.java
> +    public boolean isNowStation(final Station station) {
`NowStation`은 무엇을 의미하는 걸까요?

2023-05-11 13:48 UTC, Laterality commented on src/main/java/subway/domain/repository/LineRepository.java
> +    void deleteById(Long lineIdRequest);
인자 타입으로 래퍼 클래스를 사용할 필요가 있을까요?

2023-05-11 13:48 UTC, Laterality commented on src/main/java/subway/persistence/LineRepositoryImpl.java
> +public class LineRepositoryImpl implements LineRepository {
`Impl`은 이 클래스가 무언가의 구현체라는 것 외에는 아무것도 설명하지 못하는 단어네요. 이 클래스를 더 잘 나타낼 수 있는 이름으로 바꿔보면 어떨까요?

2023-05-11 13:48 UTC, Laterality commented on src/main/java/subway/persistence/SectionEntity.java
> +public class SectionEntity {
도메인 클래스 `Section`에는 `id` 필드가 있는데, 엔티티는 가질 필요 없을까요?

2023-05-11 13:48 UTC, Laterality commented on src/main/java/subway/persistence/SectionRepositoryImpl.java
> +        return null;
구현이 덜 돼 있네요.

2023-05-11 13:48 UTC, Laterality commented on src/main/java/subway/ui/SectionController.java
> +    public void createSection(@PathVariable("line_id") Long line_id, @RequestBody SectionCreateRequest sectionCreateRequest) {
`/stations`인 경로와 `Section` 생성을 처리하는 메서드의 의미가 일치할까요?

2023-05-11 13:48 UTC, Laterality requested changes
안녕하세요 키아라.

리뷰를 맡은 에단입니다.

아직 기능이 다 구현되지 않은 듯하네요.

우선 보이는 곳에 코멘트 남겨드렸습니다. 나머지 기능 구현하면서 참고해주세요.

2023-05-11 13:48 UTC, Laterality requested changes
안녕하세요 키아라.

리뷰를 맡은 에단입니다.

아직 기능이 다 구현되지 않은 듯하네요.

우선 보이는 곳에 코멘트 남겨드렸습니다. 나머지 기능 구현하면서 참고해주세요.

2023-05-11 13:48 UTC, Laterality requested changes
안녕하세요 키아라.

리뷰를 맡은 에단입니다.

아직 기능이 다 구현되지 않은 듯하네요.

우선 보이는 곳에 코멘트 남겨드렸습니다. 나머지 기능 구현하면서 참고해주세요.

2023-05-11 13:49 UTC, Laterality requested changes
안녕하세요 키아라.

리뷰를 맡은 에단입니다.

아직 기능이 다 구현되지 않은 듯하네요.

우선 보이는 곳에 코멘트 남겨드렸습니다. 나머지 기능 구현하면서 참고해주세요.

2023-05-12 05:58 UTC, kiarakim commented on src/main/java/subway/application/SectionDeleteRequest.java
> +    private String downStation;
아 그렇네요, upStation으로만 쓰면 Station 객체라고 생각할 수 있을 것 같아요. upStationName이라고 정정하겠습니다.

2023-05-12 06:09 UTC, kiarakim commented on src/main/java/subway/application/SectionService.java
> +    private final StationRepository stationRepository;
앗 적어놓고 중간에 계획이 바뀌었는데 그 부분은 수정하지 못했네요. 삭제했습니다.

2023-05-12 06:15 UTC, kiarakim commented on src/main/java/subway/domain/Section.java
> +        return this.distance <= newSection.distance;
그런가요? getDistance를 쓰고있지 않아서 두 Section을 비교할 때 Section한테 물어보려고 했었어요. Sections에서 필요한 부분이니 에단이 말씀해주신 방법으로 변경해보겠습니다!

2023-05-12 06:30 UTC, kiarakim commented on src/main/java/subway/domain/Section.java
> +    public boolean validateEqualEndPoint(final List<Station> endPoint) {
NPE가 발생할 것 같습니다. 기능 변경을 하고 해당 메서드 삭제를 잊었네요. 다른 곳에서 같은 예외가 터질 수 있는 부분이 있는지 찾아보겠습니다. 감사합니다.

2023-05-12 06:36 UTC, kiarakim commented on src/main/java/subway/domain/Section.java
> +    public boolean isNowStation(final Station station) {
자하철 방향에 up에서 down으로 가니 출발을 up 즉, now라고 생각하여 표현했습니다. 
한 노선에 있는 역들을 순서대로 조회하고 싶을 때 상행 종점을 찾아 list에 넣고 기준을 상행 종점역으로 설정했습니다.
그 기준이 되는 역을 이 up(now) 역이면, 즉 상행 종점을 up으로 가지고 있는 section이면 그 section의 down 역을 list에 저장합니다. 
isUpStation이 조금 더 일관성이 있어보이는데 혹시 이 이름도 애매한 것 같아보일까요?

2023-05-12 06:52 UTC, kiarakim commented on src/main/java/subway/domain/repository/LineRepository.java
> +    void deleteById(Long lineIdRequest);
이 부분은 시간상의 문제로 큰 고민없이 작성한 코드라고 생각합니다.
Request가 들어왔을 때 null이 들어올 경우 원시값을 사용하면 ObjectMapper에 의해 null이 0으로 매핑되니 이를 방지하기 위해서 래퍼 클래스를 사용했습니다. 
그런데 이런 부분을 repository에서 까지 고려할 필욘 없어서 원시타입을 사용해도 됐었지만 '일단 만들고 보자'라는 생각으로 위에서 사용하던 자료형을 동일하게 사용한 것 같아요. 
결론은, 사용할 필요는 없는 것 같습니다!

2023-05-12 07:11 UTC, kiarakim commented on src/main/java/subway/persistence/LineRepositoryImpl.java
> +public class LineRepositoryImpl implements LineRepository {
앗 그렇네요. Repository를 구현하는 클래스이니 Impl을 붙여줬는데 인터페이스화를 한 이유 중 다양한 구현체를 만들 가능성을 두는 것도 있으니 단순히 Impl을 붙이는 것보단 더 의미있는 이름을 붙여주는 것이 좋을 것 같네요.
LineJdbcRepository는 어떤가요?

2023-05-12 07:50 UTC, kiarakim commented on src/main/java/subway/ui/SectionController.java
> +    public void createSection(@PathVariable("line_id") Long line_id, @RequestBody SectionCreateRequest sectionCreateRequest) {
음... 그럼 기존의 /line/{line_id}/stations 보다 
lines중 하나의 line에 넣는다는 의미로 `/lines/{line_id}`가 좋을까요?
아니면 `/lines/{line_id}/sections`와 같이 /sections를 추가하는 게 좋을까요?

2023-05-14 14:15 UTC, kiarakim commented on src/main/java/subway/application/StationService.java
> +    public Station findById(final Long stationIdRequest) {
쓰임을 추가해주었습니다..!ㅎㅎ
```java
public StationResponse findById(final Long stationIdRequest) {
  final Station station = stationRepository.findById(stationIdRequest);
  return new StationResponse(stationIdRequest, station.getName());
}
```

2023-05-16 06:14 UTC, kiarakim commented on src/main/java/subway/persistence/SectionRepositoryImpl.java
> +        return null;
넵 마저 구현했습니다.

2023-05-16 12:50 UTC, Laterality requested changes
안녕하세요 키아라.

피드백 잘 반영해주셨어요.

몇가지 코멘트 추가로 남겨드렸습니다. 확인 부탁드려요.

전반적으로 테스트에 예외 케이스에 대한 검증이 부족해보이네요. 테스트도 보완해주시면 좋겠습니다.

2023-05-16 12:50 UTC, Laterality commented on src/main/java/subway/ui/SectionController.java
> +    public void createSection(@PathVariable("line_id") Long line_id, @RequestBody SectionCreateRequest sectionCreateRequest) {
특별히 기준이 있는 건 아니에요. 단지 URL 경로와 메서드 시그니처의 의미가 어색해보여서 의견 드렸어요. 의미상 문제 없다고 생각하신다면 굳이 바꾸실 필요는 없습니다.

2023-05-16 12:50 UTC, Laterality commented on src/main/java/subway/persistence/LineRepositoryImpl.java
> +public class LineRepositoryImpl implements LineRepository {
👍

2023-05-16 12:50 UTC, Laterality commented on src/main/java/subway/domain/repository/LineRepository.java
> +    void deleteById(Long lineIdRequest);
여기서 래퍼 클래스를 사용했을 때 어떤 이점이 있나요?

2023-05-16 12:50 UTC, Laterality commented on src/main/java/subway/domain/Section.java
> +    public boolean isNowStation(final Station station) {
말씀하신 `now`의 의미는 이 메서드가 `SectionsgetSortedStations`의 루프에서 호출 될 때만(루프의 현재 `Station`이라는 의미를) 갖지 않나요? 호출되는 입장인 `Section`이 외부에서 호출되는 맥락을 알 필요가 있을까요?

2023-05-16 12:50 UTC, Laterality commented on src/main/java/subway/application/LineService.java
> +import subway.ui.dto.response.LineResponse;
응용 계층의 서비스에서 표현 계층의 DTO에 의존성을 가져도 될까요?

2023-05-16 12:50 UTC, Laterality commented on src/main/java/subway/application/LineService.java
> +            }
들여쓰기를 줄여보면 어떨까요?

2023-05-16 12:50 UTC, Laterality commented on src/main/java/subway/application/StationService.java
> +	public StationResponse findById(final Long stationIdRequest) {
인자 이름의 `Request`는 필요한 단어일까요?

2023-05-16 12:50 UTC, Laterality commented on src/main/java/subway/domain/Line.java
> +	public boolean equals(final Object o) {
`id`가 다르고 `name`이 같은 두 객체는 같다고 볼 수 있을까요?

2023-05-16 12:50 UTC, Laterality commented on src/main/java/subway/domain/Section.java
> +	private void validateDuplication(final Station nowStation, final Station nextStation) {
쓰이지 않는 메서드네요.

2023-05-16 12:50 UTC, Laterality commented on src/main/java/subway/domain/Sections.java
> +public class Sections {
이 클래스에는 `equals`/`hashCode`를 따로 구현할 필요 없을까요?

2023-05-16 12:50 UTC, Laterality commented on src/main/java/subway/domain/Sections.java
> +	public Sections() {
필요한 생성자일까요?

2023-05-16 12:50 UTC, Laterality commented on src/main/java/subway/domain/Sections.java
> +		}
코드를 간결하게 정리해보면 어떨까요?

2023-05-16 12:50 UTC, Laterality commented on src/main/java/subway/domain/Sections.java
> +	public Map<Line, List<Section>> distributeByLine(final List<Section> sectionsContainStation){
외부에서 쓰이지 않는 메서드인데 `public`으로 선언할 필요가 있을까요?

2023-05-16 12:50 UTC, Laterality commented on src/main/java/subway/persistence/SectionJdbcRepository.java
> +    }
서로 다른 노선이 같은 구간을 공유하는 경우에는 둘 이상의 구간이 조회될 수도 있는데, 이 경우는 고려하지 않아도 될까요?

2023-05-16 12:50 UTC, Laterality commented on src/main/java/subway/ui/LineController.java
> +	public ResponseEntity<LineResponse> findLineById(@PathVariable(name = "id") long lineId) {
클라이언트가 존재하지 않는 노선 ID로 조회를 시도하면 어떤 응답을 받게 될까요?

2023-05-16 12:50 UTC, Laterality commented on src/main/java/subway/ui/LineController.java
> +		final long deletedId = lineService.deleteLine(id);
`deletedId`는 쓰이지 않는 변수네요.

2023-05-16 12:50 UTC, Laterality commented on src/main/java/subway/ui/SectionController.java
> +        final URI uri = URI.create("/sections");
유효한 URL일까요?

2023-05-16 12:50 UTC, Laterality commented on src/main/java/subway/ui/dto/request/LineRequest.java
> +public class LineRequest {
`Line`에 대해 무엇을 요청하는 객체일까요?

2023-05-16 12:50 UTC, Laterality commented on src/test/java/subway/application/LineServiceTest.java
> +class LineServiceTest {
예외 상황에 대한 테스트도 추가하면 어떨까요?

2023-05-17 07:32 UTC, kiarakim commented on src/main/java/subway/application/LineService.java
> +            }
나중에 리팩터링 할 때 분리하려했는데 놓친 것 같네요..ㅎㅎ

2023-05-17 07:37 UTC, kiarakim commented on src/main/java/subway/application/StationService.java
> +	public StationResponse findById(final Long stationIdRequest) {
사실 필요없다고 생각했었는데 '있는지도 모르는 id를 요청받았으면 request를 붙여야하나?'라는 생각에 붙였는데 다시 생각해보니 없는게 더 자연스러울 것 같아요.

2023-05-17 08:41 UTC, kiarakim commented on src/main/java/subway/domain/Sections.java
> +	public Sections() {
앗 아니요. 필요했었는데 수정 중 삭제하는 것을 깜빡한 것 같아요

2023-05-17 08:44 UTC, kiarakim commented on src/main/java/subway/domain/Sections.java
> +	public Map<Line, List<Section>> distributeByLine(final List<Section> sectionsContainStation){
앗 전혀요! private으로 수정했습니다!

2023-05-18 04:45 UTC, kiarakim commented on src/main/java/subway/application/LineService.java
> +import subway.ui.dto.response.LineResponse;
가질 순 있다고 생각하는데 하나의 DTO로 서비스까지 쭉 전달하는 것은 컨트롤러와 서비스 간 의존을 강화하는 것이 되니 다른 방법을 찾는 것이 좋을 것 같습니다.
다만, 그럼 컨트롤러에서 DTO를 변환해줘야 하는데 이를 도메인 객체로 변환하자니 컨트롤러는 표현계층인데 도메인을 의존하면 안될 것 같고, 요청된 DTO 내부에서 toLine()으로 새 도메인 객체를 주자니 그건 DTO가 도메인을 의존하게 되고 그래서 고민을 하고 있습니다. 

컨트롤러에서 서비스에 전달하는 또 다른 DTO를 만드는 것이 좋을지, 
아니면 서비스가 요청 DTO를 의존하는 것이 좋을지 잘 모르겠습니다. 

전자의 경우 의존도가 낮아지나 클래스가 늘어나 유지보수가 번거로울 것 같고
후자의 경우 코드 작성을 편하나 의존도 문제를 피할 순 없기 때문입니다.

2023-05-18 05:21 UTC, kiarakim commented on src/main/java/subway/domain/Sections.java
> +		}
많이 지저분하긴 하네요... 다음과 같이 리팩터링 했습니다!
```java
public Map<Line, List<Section>> deleteAndMerge(final Station station, final List<Section> sectionsContainStation) {
  ...
    
    final Section firstSection = sectionInLine.get(0);
    final Section secondSection = sectionInLine.get(1);
    
    addIfDownSame(firstSection, secondSection, station, line);
    addIfDownSame(secondSection, firstSection, station, line );
  }
  
  return distributeByLine(sections);
}

private void addIfDownSame(final Section section, final Section nextSection, final Station station, final Line line) {
  if (isSameDownUp(section, nextSection, station)) {
    final Section mergedSection = mergeSection(section, nextSection, line);
    sections.add(mergedSection);
  }
}
private boolean isSameDownUp(final Section section, final Section nextSection, final Station station) {
    return section.getDownStation().equals(station) && nextSection.getUpStation().equals(station);
}

private Section mergeSection(final Section section, final Section nextSection,
final Line line) {
  return new Section(line, section.getUpStation(),
  nextSection.getDownStation(), addDistance(section, nextSection));
}
```

2023-05-18 05:26 UTC, kiarakim commented on src/main/java/subway/domain/Line.java
> +	public boolean equals(final Object o) {
음... 비교 대상이 Entity라면 다르지만 도메인의 경우엔 같을 수 있다고 생각했습니다.
혹시 도메인에서 id가 다르고 name이 같은 두 객체를 같다고 했을 때 발생할 수 있는 위험성이 있을까요?

2023-05-18 05:31 UTC, kiarakim commented on src/main/java/subway/domain/Sections.java
> +public class Sections {
Section의 경우는 equals/hashCode가 필요할 수 있을 것 같은데 제 생각에 Section을 List로 갖고 있는 Sections 클래스는 equals/hashCode가 따로 필요 없을 것 같아요.

2023-05-18 05:37 UTC, kiarakim commented on src/main/java/subway/domain/Section.java
> +    public boolean isNowStation(final Station station) {
맥락은 미처 생각 못했는데 도메인은 외부 맥락을 알지 않아도 된다고 생각합니다. 그래도 들어온 역과 자신의 상행 역을 비교하는 것이니 isSameUpStation 정도로 변경했습니다!

2023-05-18 06:07 UTC, kiarakim commented on src/main/java/subway/domain/repository/LineRepository.java
> +    void deleteById(Long lineIdRequest);
여기서는 이렇다할 이점이 없는 것 같습니다. 
원시값과 래퍼 클래스의 차이를 null을 받을 수 있는지 없는지로 생각하고 있기 때문입니다.
그렇다면 래퍼 클래스(Long)보단 원시값을 사용하거나 원시값보단 원시값 포장(LineId)을 하는 편이 좋을 것 같습니다!

2023-05-18 06:08 UTC, kiarakim commented on src/main/java/subway/persistence/SectionEntity.java
> +public class SectionEntity {
도메인과 엔티티에 대해 잘 이해가 가지 않아 학습을 한 결과 
엔티티도 id를 가져야 할 것 같습니다.

2023-05-18 06:37 UTC, kiarakim commented on src/main/java/subway/persistence/SectionJdbcRepository.java
> +    }
1호선 : A - B - C - D
2호선 : E - B - C - F
의 경우를 말씀하시는 것이 맞나요? 여기선 그 경우를 고려하지 않았습니다. 서로 다른 노선에 같은 구간은 애초에 생성하지 못하도록 설정했어서요..

2023-05-18 12:17 UTC, kiarakim commented on src/main/java/subway/domain/Section.java
> +	private void validateDuplication(final Station nowStation, final Station nextStation) {
네 삭제했습니다..!

2023-05-18 12:26 UTC, kiarakim commented on src/main/java/subway/ui/LineController.java
> +	public ResponseEntity<LineResponse> findLineById(@PathVariable(name = "id") long lineId) {
레포지토리단에서 
```java

public Line findById(final long lineId) {
  String sql = "SELECT * FROM line WHERE id = ?";
  final Line line = jdbcTemplate.queryForObject(sql, lineRowMapper, lineId);
    if (line == null) {
      throw new NullPointerException("존재하지 않는 노선입니다");
    }
  return line;
}
```
위와 같이 예외를 터트려주도록 했습니다.
지금은 도메인 객체로 받지만 곧 엔티티로 반환할 수 있도록 변경할 예정입니다.

2023-05-18 12:33 UTC, kiarakim commented on src/main/java/subway/ui/LineController.java
> +		final long deletedId = lineService.deleteLine(id);
그렇네요..ㅎㅎ
메서드 호출만 해주었습니다!

2023-05-18 12:50 UTC, kiarakim commented on src/main/java/subway/ui/SectionController.java
> +        final URI uri = URI.create("/sections");
음, /sections에 POST를 요청했는데 /sections를 만드는건 아닌 것 같네요. 
```java
final URI uri = URI.create("/sections" + response.getId());
```
위와 같이 경로를 추가했습니다.

2023-05-18 12:54 UTC, kiarakim commented on src/main/java/subway/ui/dto/request/LineRequest.java
> +public class LineRequest {
Line을 생성하는 요청입니다.
LineCreateRequest 또는 LineUpdateRequest로 바꿔주는 것이 적절할 것 같은데 LineUpdateRequest의 경우 노선의 이름을 바꾸는 경우는 드무니 LineCreateRequest로 명시하도록 하겠습니다!

2023-05-18 14:22 UTC, kiarakim commented on src/test/java/subway/application/LineServiceTest.java
> +class LineServiceTest {
기존에 mock 테스트였던 코드를 잘 다루지 못하고있어 클래식 TDD 방식으로 변경하면서 예외 테스트 코드도 작성했습니다!

2023-05-19 11:05 UTC, Laterality approved these changes
안녕하세요 키아라.

피드백이 많았는데 잘 반영해주셨어요.

다음 단계 진행을 위해 이만 머지하도록 할게요.

남겨드린 코멘트는 다음 단계 진행하면서 참고해주세요.

전체 테스트를 한번에 실행하면 일부 테스트가 실패하는데, 확인 부탁드려요.

진행 중에 궁금하신 점은 언제든 DM 주세요.

2023-05-19 11:05 UTC, Laterality commented on src/main/java/subway/ui/SectionController.java
> +        final URI uri = URI.create("/sections");
POST 요청에 대한 응답으로 `/sections/{sectionId}`를 반환하는데, 이 URL로 GET 요청을 보내면 컨트롤러에서는 `lineId`로 인식하지 않을까요?

2023-05-19 11:05 UTC, Laterality commented on src/main/java/subway/ui/LineController.java
> +	public ResponseEntity<LineResponse> findLineById(@PathVariable(name = "id") long lineId) {
그럼 repository 구현체(i.e. 인프라)가 바뀌면 존재하지 않는 노선 ID로 조회했을 때 던져지는 예외도 바뀔 수 있을까요?

2023-05-19 11:05 UTC, Laterality commented on src/main/java/subway/persistence/SectionJdbcRepository.java
> +    }
네 맞습니다. 

통합테스트에서 아래 케이스를 실행했을 때는 말씀드린 상황이 발생하네요.

```java
    @Test
    void intersection() {
        createStation("A");
        createStation("B");
        createStation("C");
        createStation("D");
        createStation("E");
        createStation("F");
        createLine("1호선");
        addSection("1호선", "A", "B");
        addSection("1호선", "B", "C");
        addSection("1호선", "C", "D");

        createLine("2호선");
        addSection("2호선", "E", "B");
        addSection("2호선", "B", "C");
        addSection("2호선", "C", "F");
    }

    private void createStation(String stationName) {
        RestAssured.given().log().all()
                .contentType(MediaType.APPLICATION_JSON_VALUE)
                .body(new StationUpdateRequest(stationName))
                .when().post("/stations")
                .then().log().all()
                .extract();
    }

    private void createLine(String lineName) {
        RestAssured.given().log().all()
                .contentType(MediaType.APPLICATION_JSON_VALUE)
                .body(new LineCreateRequest(lineName))
                .when().post("/lines")
                .then().log().all()
                .extract();
    }

    private void addSection(String lineName, String upStationName, String downStationName) {
        RestAssured.given().log().all()
                .contentType(MediaType.APPLICATION_JSON_VALUE)
                .body(new SectionUpdateRequest(lineName, upStationName, downStationName, 1L))
                .when().post("/sections")
                .then().log().all()
                .extract();
    }

```

2023-05-19 11:05 UTC, Laterality commented on src/main/java/subway/domain/Line.java
> +	public boolean equals(final Object o) {
동등성을 일관되게 정의했다면 크게 문제는 없습니다(일관되지 않으면 문제가 될 수 있어요). 다만 객체를 식별하는 식별자의 역할을 하는 ID가 서로 다른 두 객체가 같을 수 있다는 게 사람에 따라서는 직관에 반한다고 생각할 수도 있어요.

2023-05-19 11:05 UTC, Laterality commented on src/main/java/subway/application/LineService.java
> +import subway.ui.dto.response.LineResponse;
1. 컨트롤러(표현 계층)에서 서비스(응용 계층)에 의존성을 가진 상황에서 다시 서비스가  컨트롤러에 의존성을 가지면 패키지 수준에서 순환 참조가 생기거나 생길 가능성이 있지 않을까요?
2. 컨트롤러에서 DTO를 도메인 객체로 변환하는 것이 껄끄럽게 느껴지신다면 응용 계층에서 변환해주면 어떨까요?

2023-05-19 11:05 UTC, Laterality commented on src/test/java/subway/application/StationServiceTest.java
> +import static org.assertj.core.api.Assertions.*;
와일드카드 `import`는 지양해주세요([참고](https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports)).

2023-05-19 11:05 UTC, merged