[1단계 - 지하철 정보 관리 기능] 민트(유재민) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #89
Opened 2023-05-11 08:56 UTC by yujamint

안녕하세요 춘식! 지하철 미션 리뷰이 민트입니다 :)
이렇게 좋은 기회로 뵙게 되어 반갑습니다!!
그러나... 이번 미션은 도메인이 너무 어렵기도 하고, 스프링 사용에도 익숙하지 않아서 구현을 끝내지 못했습니다..
돌아가지도 않고, 코드 자체가 난잡하여 리뷰하시기 어려울 것 같네요 죄송합니다🥲
요청 반려하셔도 할 말이 없네요.. 감사합니다!

2023-05-11 15:38 UTC, bimppap requested changes
안녕하세요 민트, 춘식입니다!
복잡한 기능 구현하느라 고생 많았습니다 👍
코멘트 간단하게 남겼으니 확인 부탁드립니다.
궁금하거나 이해가 안 되는 부분은 편하게 DM 주세요 🙂

2023-05-11 15:38 UTC, bimppap commented on src/main/java/subway/domain/Line.java
> +    private final List<Section> sections;
기존의 Line은 color 필드가 있었는데 없어져도 되는 건가요? 👀

2023-05-11 15:38 UTC, bimppap commented on src/main/java/subway/domain/Line.java
> +    public void addSection(Section newSection) {
메서드를 더 작게 쪼개보는 건 어떨까요?

2023-05-11 15:38 UTC, bimppap commented on src/main/java/subway/dto/LineRequest.java
>      }
[Jackson 2.13 버전](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.13) 이후로는 빈 생성자가 없어도 역직렬화가 될텐데 문제가 있었을까요?

2023-05-11 15:38 UTC, bimppap commented on src/main/java/subway/dto/StationsResponse.java
> +    public static StationsResponse from(List<Station> stations) {
response에서 from을 쓸 때도 있고 to를 쓸 때도 있는데 기준이 있나요?

2023-05-11 15:38 UTC, bimppap commented on src/main/java/subway/entity/SectionEntity.java
> +//    public static List<SectionEntity> of(Line line, Long id) {
구현이 덜 된 부분인 걸까요?ㅎㅎ

2023-05-11 15:38 UTC, bimppap commented on src/main/java/subway/exception/DuplicatedNameException.java
> +public class DuplicatedNameException extends RuntimeException {
다른 에러들은 IllegalArgumentException을 쓰던데 리팩토링 될 부분인 거겠죠?

2023-05-11 15:38 UTC, bimppap commented on src/main/java/subway/ui/ControllerAdvice.java
> +    public ResponseEntity<ErrorResponse> handleException(DuplicatedNameException e) {
다른 에러도 이런 방식으로 만들면 ControllerAdviced의 크기가 점점 커질 거에요. SubwayException같은 부모 에러 객체를 만들어 보는 건 어떨까요?

2023-05-11 15:38 UTC, bimppap commented on src/main/java/subway/ui/LineController.java
>      @GetMapping("/{id}")
lineId라고 명시해주는게 가독성에 좋습니다!

2023-05-11 15:38 UTC, bimppap commented on src/main/resources/schema.sql
> +    foreign key (target_station_id) references station(id),
station이 사라져도 section에 남아있을 수 있는 건가요?

2023-05-11 15:38 UTC, bimppap commented on src/main/java/subway/application/LineService.java
>      }
지금은 스케일이 작아 누락된 부분을 찾기 쉽지만 점점 로직이 복잡해지고 커지면 누락된 부분을 찾기 어려워집니다. 이런 경우 todo 주석을 사용하면 도움이 됩니다!

2023-05-11 15:38 UTC, bimppap commented on src/main/java/subway/application/LineService.java
> +    public StationResponse addStation(Long lineId, StationSaveRequest stationRequest) {
Dao와 Repository를 분리해서(참 잘했어요👍) 서비스에서 도메인만 다룰 수 있도록 했던 거 같은데 맞을까요? 로직에 수정이 필요해보이네요ㅎㅎ

2023-05-11 15:38 UTC, bimppap commented on src/test/java/subway/integration/LineIntegrationTest.java
> +        @DisplayName("하나를 조회한다.")
실패하는 테스트가 있네요 🙂

2023-05-11 15:38 UTC, bimppap commented on src/test/java/subway/integration/LineIntegrationTest.java
> +        @DisplayName("하나를 조회한다.")
테스트 되지 않은 메소드도 보이네요. 리팩토링하면서 추가해주세요!

2023-05-11 15:38 UTC, bimppap commented on src/main/java/subway/application/LineService.java
> +    public LineService(LineDao lineDao, LineRepository lineRepository,
public!

2023-05-11 15:38 UTC, bimppap commented on src/main/resources/schema.sql
> +create table if not exists SECTION
created_at, updated_at 같은 audit 데이터를 넣으면 디버깅에 도움이 됩니다. 비즈니스에 필요한 건 아니기에 스키마엔 있으나 도메인에 포함하지 않고 Dao에서만 다루게 해도 좋습니다. 🙂

2023-05-11 15:38 UTC, bimppap commented on src/main/java/subway/application/LineService.java
>  public class LineService {
완료된 코드가 기대되네요^^ 리팩토링 파이팅입니다👍

2023-05-17 15:23 UTC, yujamint commented on src/main/java/subway/domain/Line.java
> +    private final List<Section> sections;
기존의 뼈대 코드에 color 필드가 존재하는 것에 어떠한 의미가 있을까 생각해봤지만, 1단계의 요구사항에선 쓰이지 않는 정보라고 판단하여 제거했습니다..!

2023-05-17 15:36 UTC, yujamint reviewed
안녕하세요 춘식! 리뷰이 민트입니다 :)
첫 리뷰를 매우 빠르게 해주셨는데, 이제서야 재요청을 하게 됐네요 ㅠㅠ.. 중간에 몸 상태가 좋지 않기도 했고, 학습 과정에서 어려움에 부딪혀 멘탈도 좋지 않은 한 주를 보낸 것 같습니다😂
지금은 다시 파이팅하고 있습니다..!!
구현을 제대로 완료하지 못했음에도, 첫 리뷰에서 좋은 내용 많이 남겨주셔서 감사합니다!! 이번 리뷰도 잘 부탁드리겠습니다 춘식 ㅎㅎ

추가로, 궁금한 점에 대해 코멘트로 질문 남기겠습니다. 감사합니다!

2023-05-17 15:36 UTC, yujamint commented on src/main/java/subway/application/LineService.java
> +    public LineService(LineDao lineDao, LineRepository lineRepository,
생성자 의존성 주입 방식을 선택했을 때, 해당 생성자는 `private`으로 설정해도 괜찮다는 사실을 처음 알았네요..! 감사합니다!
`Repository`의 경우에는 테스트 코드에서 직접 생성해주고 있기 때문에 `public`으로 두었는데, 이러한 경우는 `public`으로 유지해도 괜찮을까요?

2023-05-17 15:36 UTC, yujamint commented on src/main/java/subway/application/LineService.java
> +    public StationResponse addStation(Long lineId, StationSaveRequest stationRequest) {
인지하지 못하고 있던 부분이네요..! 짚어주셔서 감사합니다 ㅎㅎ

2023-05-17 15:36 UTC, yujamint commented on src/main/java/subway/dto/LineRequest.java
>      }
필드가 하나뿐인 객체에 대해서는 역직렬화가 되지 않는다는 것을 알게 됐습니다. 그 후로는 request/response 관련 Dto에는 웬만하면 기본 생성자를 만들어줘야겠다는 생각을 가지게 됐습니다!
하지만 굳이 필요하지 않은 것을 만들어주지 않는 게 좋은 것 같기도 하네요😅 지금은 제거했습니다!

2023-05-17 15:36 UTC, yujamint commented on src/main/java/subway/dto/StationsResponse.java
> +    public static StationsResponse from(List<Station> stations) {
기존의 코드에서는 이것저것 혼용해서 사용한 것 같네요..!

현재는 하나의 인자만 받는 정적 팩토리 메서드에 대해서는 모두 `from`이라는 메서드명을 사용하도록 수정했습니다!

2023-05-17 15:36 UTC, yujamint commented on src/main/java/subway/entity/SectionEntity.java
> +//    public static List<SectionEntity> of(Line line, Long id) {
앗.. 급하게 제출하느라 놓쳤네요 ㅎㅎ.. 감사합니다!

2023-05-17 15:36 UTC, yujamint commented on src/main/java/subway/exception/DuplicatedNameException.java
> +public class DuplicatedNameException extends RuntimeException {
넵 그렇습니다..! 
현재는 IllegalArgumentException 대신 모두 커스텀 예외를 사용하도록 수정했습니다!

2023-05-17 15:36 UTC, yujamint commented on src/main/java/subway/ui/ControllerAdvice.java
> +    public ResponseEntity<ErrorResponse> handleException(DuplicatedNameException e) {
좋은 의견 주셔서 감사합니다!! 일일이 핸들러를 추가하는 것은 효율적이지 않다는 생각을 했는데, 춘식이 말씀해주신 방향으로 수정했습니다 :)

2023-05-17 15:36 UTC, yujamint commented on src/main/resources/schema.sql
> +create table if not exists SECTION
말씀해주신대로 created_at, updated_at 컬럼을 추가했습니다!

관련하여 한 가지 궁금한 점 여쭤봅니다!
현재는 entity 클래스가 audit 데이터를 필드로 가지지 않고 있습니다. DB에선 가지고 있는 정보이니, 엔티티도 당연히 가지도록 하는 게 맞을까요??
혹은 DB에서 알아서 갱신해주는 정보이니 엔티티가 가질 필요가 없을까요??

2023-05-17 15:36 UTC, yujamint commented on src/main/resources/schema.sql
> +    foreign key (target_station_id) references station(id),
`on delete cascade` 조건을 추가했습니다!!

2023-05-17 16:06 UTC, yujamint commented on src/main/java/subway/domain/Line.java
> +    private final Long id;
기존에는 도메인 객체는 id 필드를 갖지 않도록 설계했지만, 리팩토링을 하며 id를 갖도록 했습니다.

조회 요청에 대한 응답을 할 때 프론트 단에서 수정/삭제 등의 추가적인 요청을 할 수 있도록 식별자를 포함한 데이터를 응답해야 됐습니다.
하지만 repository 계층에서는 도메인 객체를 반환해주기 때문에, 만약 도메인 객체가 id를 모른다면 응답값에 id를 포함시키는 과정이 복잡해진다는 것을 확인했습니다.

여러 고민을 하다가, 결국 도메인 객체 역시 id를 가지도록 하였습니다.
도메인 객체와 DB의 결합도가 커진다는 점에서 옳지 않은 판단이라고 생각하기도 했지만, 도메인 객체의 id는 결국 repository 계층에서 넘겨주는 식별자를 필드로 가지는 것이기 때문에 결합도 문제는 괜찮을 수 있겠다고 나름의 합리화(?)를 하기도 했습니다..!

해당 문제에 대한 춘식의 의견이 궁금합니다!!

2023-05-17 16:06 UTC, yujamint commented on src/main/java/subway/domain/Station.java
> +    public boolean equals(final Object o) {
도메인 객체가 id를 필드로 갖게 하는 과정에서 궁금증이 생겼습니다.

엔티티의 동등성 검사는 오직 id를 통해서만 진행합니다. 엔티티는 영속성 계층에 속해 있기 때문에 같은 name을 가져도 다른 row이기 때문입니다.

그렇다면, 도메인 객체 역시 id를 가진다면 오직 id를 통해서만 동등성 검사를 하는 게 일관성 있는 것일까요?? 도메인 객체는 비즈니스 레이어에 속해 있기 때문에 id가 아닌 name을 통해서만 동등성 검사를 해도 되는지가 궁금했습니다.

2023-05-17 16:06 UTC, yujamint commented on src/main/java/subway/repository/LineRepository.java
> +    public void deleteStation(final Long lineId, final Long stationId) {
현재 repository에서의 역 제거 로직은 다음과 같습니다.
- A - B - C 구간에서 B 역을 삭제했을 때, A - B 와 B - C를 삭제하고 A - C로 붙여준다.

이는 Line 도메인 객체에서의 역 제거 로직과 같습니다.
여기서 한 가지 궁금증이 생겼습니다.

서비스 계층에서 역 제거 작업을 진행한 뒤의 상태를 그대로 DB에 반영하는 것은 어떨까 생각했습니다.
즉, 역 제거가 발생한 노선의 section row를 DB에서 전체 삭제하고, 제거 작업이 완료된 후의 section 상태를 전체 삽입하는 것입니다.
이러한 생각을 한 이유는 다음과 같습니다.
- 서비스 계층에서 이미 같은 동작을 수행하고 있기 때문에 repository에서는 같은 동작을 수행할 것 없이 서비스 계층에서의 결과를 DB에 간단하게 반영만 하면 된다고 생각했습니다.

하지만, 서비스 계층에서 바뀐 데이터를 그저 반영하기만 하는 것은 'repository 계층의 역할이 너무 부족한 것인가?' 라는 생각이 들었습니다.
다른 사람이 해당 repository 코드를 보면서 '이 메서드는 station을 제거하는 코드다'라는 인지를 할 수 없을 것 같았습니다.

그래서 결국 repository 에서도 같은 로직을 수행하도록 변경했으나, 지금처럼 코드를 작성하면 결국 도메인 객체가 갖는 역할은 **행위에 대한 유효성 검사** 뿐이라고 느껴지기도 했습니다. 
서비스 계층에서 역을 제거하며 `Line.sections`라는 상태를 수정하지만, 결국 실제로 DB에 데이터를 반영하는 로직은 repository에 있기 때문에 이런 생각을 한 것 같습니다.

계층이 많아지고, 도메인도 복잡해지면서 답을 내릴 수 없는 부분이 너무 많아진 것 같습니다..
제가 고민한 두 가지 선택지 중, 현재 상황에서는 어떤 방법이 더 좋다고 생각하시는지 춘식의 의견 남겨주시면 감사하겠습니다!!

(나름 설명한다고 했지만 제 생각을 남기기 위해 주저리주저리 썼네요. 이해하기 어려우실 수 있을 것 같아요... 😅)

2023-05-19 08:41 UTC, woowabrie approved these changes
민트 안녕하세요~ 대타로 온 브리입니다. 
1단계에서 해야할 고민은 충분히 하신 것 같아 머지하겠습니다.
코멘트에 대해 궁금하거나 더 이야기 나눠보고싶은 내용 있으면 DM 주세요~ (오프라인으로 이야기 나눠도 좋습니다 ㅎㅎ)

2023-05-19 08:41 UTC, woowabrie commented on src/main/java/subway/ui/ControllerAdvice.java
> +    }
1. `SubwayException` 이라는 커스텀 예외를 잘 만들어 주셨네요! 👍
2. 위 코드는 아래 내용과 다르게 처리하는 부분이 없는데 분리하신 이유가 있을까요?
https://github.com/woowacourse/jwp-subway-path/blob/c668a28c732b20f9d982d53a7c13a72c9cfb9162/src/main/java/subway/ui/ControllerAdvice.java#L19-L22
3. `SubwayException` 의 하위 Exception들이 많은데 이들을 성격에 따라 분리할 수도 있어 보입니다. 예를 들어, Section 과 관련된 예외로 분리 후, 잘못된 Section 생성/수정 요청에 대해 사용자가 할 수 있는 액션에 대해 좀 더 상세히 응답을 줄 수 있겠네요.

2023-05-19 08:41 UTC, woowabrie commented on src/main/java/subway/domain/Section.java
> +        return source.isSameName(station) || target.isSameName(station);
`station.eqauls()` 사용하면 안되나요? 만약 Station의 동등성 비교 방식이 달라진다면 이 코드도 함께 변경되야하는 걸까요?

2023-05-19 08:41 UTC, woowabrie commented on src/main/resources/schema.sql
> +create table if not exists SECTION
민트가 이번 미션에서 엔티티를 사용한 이유가 무엇인가요?
이 목적에 따라 DB 스키마와 동일하게 유지해야하는지 여부를 결정할 수 있어 보여요.

2023-05-19 08:41 UTC, woowabrie commented on src/main/java/subway/domain/Line.java
> +    private final Long id;
Id라는 값이 꼭 DB에 한정된 값일까요?
DB 연동을 하지 않더라도 id 값을 가지게 만들 수 있을 것 같은데, 이 때는 id를 왜 사용하는 걸까요?

(+) 더 나아가서 DB와의 의존성을 생각할 때, 저는 특정 DBMS와의 의존성에 대해 더 고민해볼 것 같습니다. ㅎㅎ

2023-05-19 08:41 UTC, woowabrie commented on src/main/java/subway/domain/Station.java
> +    public boolean equals(final Object o) {
1. 위의 id가 꼭 DB 연동 시에만 사용되는 값일지에 대한 고민을 먼저 해보셨으면 좋겠어요.
2. 이와는 별개로 현실세계에서 지하철 역의 이름은 변경되는 경우가 많은데요. 
[힙지로 '을지로입구' 부역명, 하나은행으로 바뀐다](https://n.news.naver.com/mnews/article/374/0000292161?sid=101)
역 이름이 달라지면 다른 역이 되는걸까요ㅋㅋ

2023-05-19 08:41 UTC, merged