[1단계 - 지하철 정보 관리 기능] 테오(최우성) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #9
Opened 2023-05-11 07:33 UTC by woosung1223

안녕하세요 제이온 반갑습니다!
학습하면서 제이온 블로그 많이 봤었는데.. 이렇게 뵙니 신기하네요 😄

이번 지하철 미션은 생각보다 힘들었던 것 같아요.
시간적인 제약때문에 버려야 하는 부분이 조금 많았던 것 같습니다 ㅠ

그래도 페어와 함께 의식적으로 풍부한 도메인 모델을 만들기 위해 노력했습니다.

시간 관계 상 DIP는 적용하지 못했으나.. 영속성 개념을 도입하기 전에 도메인 엔티티를 먼저 설계했고,
모든 로직이 도메인 객체 안에 있어 서비스까지도 도메인 규칙이 전혀 새어나가지 않게 만들었습니다.
그리고 이 과정에서 패러다임의 불일치 문제를 뼈저리게 느낄 수 있었던 것 같아요.

부족한 점이 많지만 이번 미션 피드백 잘 부탁드립니다! 감사합니다 👍

2023-05-13 09:30 UTC, pjy1368 requested changes
안녕하세요 테오! 이번 미션에 리뷰어를 맡은 제이온입니다 ✌
복잡한 지하철 정보 관리 기능을 적절히 도메인과 엔티티로 구분하여 잘 작성해 주셨습니다!
전체적으로 구조는 괜찮으나 성능적인 측면이나 몇 가지 개선하면 좋을 포인트가 있어서 코멘트 남겨 두었습니다.
질문이 있다면 코멘트나 DM 부탁드릴게요~

2023-05-13 09:30 UTC, pjy1368 commented on src/main/resources/schema.sql
> +);
1. up, down 대신 상행역, 하행역의 의미를 담는 네이밍을 선택하면 어떨까요?
2. SECTION <-> STATION 사이의 외래키를 설정하지 않으신 이유가 있으실까요?

2023-05-13 09:30 UTC, pjy1368 commented on src/test/java/subway/ui/SubwayControllerTest.java
> +    private SubwayService subwayService;
컨트롤러 슬라이스 테스트를 잘해주셨네요 👍

2023-05-13 09:30 UTC, pjy1368 commented on src/test/java/subway/integration/SubwayIntegrationTest.java
> +public class SubwayIntegrationTest extends IntegrationTest {
현재는 main의 application.properties의 DB 연결 정보를 사용하고 있는데, 만약 main의 DB가 H2에서 MySQL 등과 같은 다른 DB로 바뀌게 되면 해당 E2E 테스트는 어떻게 될까요?

2023-05-13 09:30 UTC, pjy1368 commented on src/main/java/subway/entity/SectionEntity.java
> +         this.id = id;
불필요한 공백이 하나 들어가있네요 ㅎㅎ

2023-05-13 09:30 UTC, pjy1368 commented on src/main/java/subway/entity/SectionEntity.java
> +    private final Integer distance;
작성해주신 스키마를 보니까 모두 not-null인데 Long과 Integer 대신 long, int를 사용해도 괜찮지 않을까요?

2023-05-13 09:30 UTC, pjy1368 commented on src/main/java/subway/entity/LineEntity.java
> +public class LineEntity {
테이블에 매핑되는 엔티티를 잘 적용해주셨네요~
지극히 개인적인 의견이지만, 저는 Entity보다는 Row라는 네이밍을 사용하는 편인데 어떻게 생각하시나요?

2023-05-13 09:30 UTC, pjy1368 commented on src/main/java/subway/application/SubwayService.java
> +                .getRouteMap()
`routeMap()` 이후 `getRouteMap()`으로 코드가 이어지다보니 어떠한 내용물인지 혼동이 오는데 메서드명을 조정해보면 어떨까요?

2023-05-13 09:30 UTC, pjy1368 commented on src/main/java/subway/application/SubwayService.java
> +                .collect(Collectors.toList());
만약 `lineDao.findAll()`의 결과로 1만건의 레코드가 조회되었다면, `map()`을 거치면서 1만건의 select 쿼리가 추가로 나갈텐데 어떻게 개선하면 좋을까요?

2023-05-13 09:30 UTC, pjy1368 commented on src/main/java/subway/application/SubwayService.java
> +        }
이 부분도 난이도가 있겠지만 allLines에 대해서 `findRouteMap()`을 하면 반복 횟수에 따라 요청해야 하는 쿼리 개수가 많아지다보니 고민을 해보시면 좋을 것 같습니다 ㅎㅎ
크게 데이터베이스가 짊어질 일을 애플리케이션에 준다던지, 쿼리 자체를 개선해본다던지 등의 방법이 있습니다~

2023-05-13 09:30 UTC, pjy1368 commented on src/main/java/subway/dao/SubwayDao.java
> +        jdbcTemplate.update(deleteSql, line.getId());
save라는 메서드명을 보면 레코드를 insert하는 과정이라 생각할 수 있는데, 기존 line을 지우는 일까지 해당 메서드에서 넣어야 할까요??

2023-05-13 09:30 UTC, pjy1368 commented on src/main/java/subway/dao/SubwayDao.java
> +        jdbcTemplate.batchUpdate(insertSql, sections, 50,
50이라는 숫자는 매직 넘버로 보이는데 상수로 추출해보면 어떨까요?

2023-05-13 09:30 UTC, pjy1368 commented on src/main/java/subway/dao/SubwayDao.java
> +    }
select ... where ... in 쿼리를 사용해 보세요!

2023-05-13 09:30 UTC, pjy1368 commented on src/main/java/subway/dao/SubwayDao.java
> +    public Line findById(Long lineId) {
`SubwayDao.findById()`라는 네이밍을 보았을 때 Subway 객체가 반환될 것으로 기대할 것 같아요! 하지만 실제로는 Line 객체가 반환되며, findById() 외의 다른 메서드를 봐도 SubwayDao 대신 LineDao로 이름을 바꿔도 무방해보이는데, 어떻게 생각하시나요?

2023-05-13 09:30 UTC, pjy1368 commented on src/main/java/subway/domain/Section.java
> +    private final Station right;
Section 스키마에서는 up, down이던데 여기서는 left, right로 필드 이름을 정한 이유가 있으신가요?

2023-05-13 09:30 UTC, pjy1368 commented on src/main/java/subway/domain/Line.java
> +                .orElseThrow(() -> new IllegalStateException("노선과 연결되지 않는 역입니다."));
우리가 의도한 상황에 대해서는 커스텀 예외를 사용해 보시면 어떨까요?

2023-05-14 05:17 UTC, woosung1223 commented on src/main/resources/schema.sql
> +);
감사합니다! 상행, 하행의 개념을 보다 잘 내포하도록 `upbound`, `downbound`로 변경했습니다.

그리고 외래키를 설정하지 않은 이유는 개발편의성 때문인데요, 외래키 제약조건을 다는 순간 어플리케이션 레벨에서는 무조건 참조되는 테이블을 먼저 구성해야 하고, 테스트 시에도 마찬가지로 두 테이블을 다뤄야 해서.. 사용하지 않았습니다. 

사실 데이터의 정합성을 보장한다는 측면에서는 외래키가 되게 좋을 것 같으나 아직까지 사용할만한 메리트를 느끼지 못했습니다. 데이터의 정합성이라는 것도 어플리케이션 레벨이 탄탄하게 구성되었다면 문제가 없을 것이라 예상되구요.

제이온 질문을 듣고 조금 찾아보니 실무에서도 의견이 반반 나뉘는 것 같았습니다. 쿼리를 직접 쏴줄 때나, 데이터 구조를 변경해야 할 때 외래키 제약조건에 발이 묶이는 경우가 많다고 들었는데요!

저는 아직 외래키 사용에 대한 명확한 기준점이 없어 조금 꺼려지는 것 같은데 😅, 제이온은 이에 대해 어떻게 생각하시는지 궁금합니다. 외래키 부여에 대한 기준점이 있으실까요?

2023-05-14 08:59 UTC, woosung1223 commented on src/test/java/subway/integration/SubwayIntegrationTest.java
> +public class SubwayIntegrationTest extends IntegrationTest {
감사합니다!

만약 프로덕션 환경에서 사용하는 데이터베이스가 MySQL로 바뀌게 된다면 `@SpringBootTest`를 사용하는 모든 E2E 테스트가 해당 DataSource를 사용할 것이라 짐작됩니다. 현재야 프로덕션이나 테스트 코드나 사용하는 DataSource가 메모리를 사용하는 H2이기에 문제는 없지만, 만약 인메모리 DB가 아니라면 문제가 될 여지는 충분해 보입니다. 실제 데이터베이스에 부하를 가하는 것도 문제고, 만약 잘못된 쿼리를 날려 디비 정보가 날아갔다면 더 큰 문제라고 생각합니다.

따라서 테스트 환경을 프로덕션 환경으로부터 격리하는 것이 필요해보여 `@AutoConfigureTestDatabase` 어노테이션을 통해 Embedded H2 데이터베이스를 고정적으로 사용하도록 변경했습니다. 그리고 `@JdbcTest`의 경우는 이미 내부적으로 `@AutoConfigureTestDatabase`가 선언되어 있다는 것까지 확인했습니다. 이 과정을 통해 테스트에서 사용하는 DataSource를 프로덕션과 완전히 격리시켰습니다!

2023-05-14 09:12 UTC, woosung1223 commented on src/main/java/subway/entity/SectionEntity.java
> +    private final Integer distance;
감사합니다~ 제가 Wrapper 타입을 쓴 이유는 다음과 같은데요.

1. auto-boxing, auto-unboxing으로 인한 비용은 그렇게 크지 않다고 생각합니다. 만약 반복적으로 값을 변경해야 하는 상황이라면 비용 문제를 고려해볼 수 있겠으나, 현재 요구사항에서는 이러한 고민이 불필요하다고 생각했습니다. 반면 Wrapper 타입을 사용하는 경우 nullable한 필드까지 표현이 가능해집니다.
2. 현재 nullable한 필드가 없는 것은 사실이지만, 프로덕션 코드에서 DB 스키마에 대한 어떠한 가정은 할 필요가 없다고 생각했습니다. 

따라서 Wrapper 타입을 사용하고 있는데.. 제이온은 이에 대해 어떻게 생각하시는지 궁금하네요..!

2023-05-14 09:13 UTC, woosung1223 commented on src/main/java/subway/entity/LineEntity.java
> +public class LineEntity {
동의합니다! Entity의 경우 여러 곳에서 사용되는 네이밍이기 때문에(도메인 엔티티, 데이터베이스 엔티티, ResponseEntity, RequestEntity..) 이름이 같아 혼동의 여지가 충분하다고 생각합니다! 변경하도록 하겠습니다 😀

2023-05-14 09:14 UTC, woosung1223 commented on src/main/java/subway/application/SubwayService.java
> +                .getRouteMap()
`value()`로 변경했습니다 😄

2023-05-14 15:42 UTC, woosung1223 commented on src/main/java/subway/dao/SubwayDao.java
> +        jdbcTemplate.update(deleteSql, line.getId());
메소드를 사용하는 클라이언트 입장에서는 예측하지 못한 부수효과일 수 있을 것 같아 분리했습니다 😄

2023-05-14 15:43 UTC, woosung1223 commented on src/main/java/subway/dao/SubwayDao.java
> +    public Line findById(Long lineId) {
저도 동의합니다! Subway라는 네이밍은 적절하지 않은 것 같다는 생각이 듭니다.

따라서 기존 LineDao를 LinePropertyDao로 바꾸고, SubwayDao를 LineDao로 변경했습니다! ㅎㅎ

2023-05-14 15:43 UTC, woosung1223 commented on src/main/java/subway/domain/Section.java
> +    private final Station right;
빠르게 개발을 진행하다보니 나온 실수같네요 ㅎㅎ.. 모두 일관되게 upbound, downbound로 변경했습니다!

2023-05-16 07:49 UTC, woosung1223 commented on src/main/java/subway/application/SubwayService.java
> +                .collect(Collectors.toList());
데이터베이스 레벨에서 조인을 수행하거나 어플리케이션 레벨에서 비슷한 기능을 만들면 될 것 같은데요,

이번에는 어플리케이션 레벨에서 조인과 똑같은 기능을 수행하도록 개선해보았습니다!

2023-05-16 13:51 UTC, woosung1223 commented on src/main/java/subway/application/SubwayService.java
> +        }
쿼리 개선을 하려고 보니 로직 개선으로 충분히 해결할 수 있더라구요!

그래서 로직 개선을 통해 해결했습니다 ㅎㅎ

2023-05-17 13:05 UTC, pjy1368 approved these changes
안녕하세요 테오!
전체적으로 깔끔한 구조로 리팩토링을 아주 잘 해 주셨습니다👍
나머지는 2단계 진행하면서 반영해도 될 것 같아서 1단계는 머지할게요~

2023-05-17 13:05 UTC, pjy1368 commented on src/test/java/subway/integration/SubwayIntegrationTest.java
> +public class SubwayIntegrationTest extends IntegrationTest {
저는 테스트용 application.yml을 나누는 정도를 의도했는데 저런 설정이 있는 건 저도 처음 알았네요 ㅎㅎ 잘하셨어요!

2023-05-17 13:05 UTC, pjy1368 commented on src/main/java/subway/entity/SectionEntity.java
> +    private final Integer distance;
좋은 의견이네요~ Entity는 프로덕션 코드여도 DB 스키마를 기반으로 만들어진 객체이므로 DB 스키마를 고려하여 작성하는 것이 맞다고 판단되나, non-nullable을 nullable로 변경할 수도 있기도 해서 저도 Wrapper를 쓰는 편이긴 합니다.

2023-05-17 13:05 UTC, pjy1368 commented on src/main/java/subway/application/SubwayService.java
> +        }
사실 그게 베스트긴 합니다 ㅋㅋㅋ

2023-05-17 13:05 UTC, pjy1368 commented on src/main/resources/schema.sql
> +);
실무에서 저도 데이터 마이그레이션의 불편함과 데드락 위험성으로 인해 외래 키를 거의 걸지는 않고 있습니다. 만약 무결성이 정말 중요하다면 고려해볼 수 있겠네요~
하지만 우리는 연습을 하고 있는 단계이므로 외래 키 참조 무결성 원칙을 지키면서 개발해 보시면 좋겠어서 이러한 피드백을 드려봤습니다.

2023-05-17 13:05 UTC, pjy1368 commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS LINE_PROPERTY
line_property가 비즈니스의 이유로 생겨난 용어라 생각이 드는데, DB에서는 line으로 두어도 괜찮지 않을까요?
이와 더불어 프로덕션 코드에도 LineProperty는 도메인만 사용하고, DB 단은 전부 Line으로 네이밍을 수정해도 될 듯합니다.

2023-05-17 13:05 UTC, pjy1368 commented on src/main/java/subway/application/domain/LineProperty.java
> +public class LineProperty {
전체적인 구조를 보았을 때 LineProperty로 분리를 해 두어도 적합해 보이고, 실무에서 Property와 외부 연관 객체를 분리해 놓은 코드도 가끔 본 적이 있었습니다. 한 번 해 보시되, 만약 합치는 것이 더 나아보인다면 합치는 것도 염두해 두면서 2단계 진행해 보시면 좋을 것 같습니다~

2023-05-17 13:05 UTC, pjy1368 commented on src/main/java/subway/persistence/repository/H2LinePropertyRepository.java
> +public class H2LinePropertyRepository implements LinePropertyRepository {
오.. 제가 가장 선호하는 패턴으로 코드를 잘 작성해 주셨네요.
도메인에서 Repository 인터페이스를 정의해놓고, persistence 계층에서 Repository 구현체를 작성하고, 실질적인 SQL 처리는 DAO에서 작업하는 지금 구조는 SOLID 원칙 중에서 DIP 원칙을 가장 잘 구현한 사례라고 생각되며, 앞으로도 복잡한 요구 사항이 생긴다면 적용해볼 법한 아키텍처라고 생각합니다 ㅎㅎ

2023-05-17 13:05 UTC, pjy1368 commented on src/main/java/subway/application/exception/ExpectedException.java
> +}
우리는 Rest Api를 쓰고 있으니 HttpException으로 부모 예외를 만들고, 그 하위로 상태 코드에 대응되는 Exception들을 만들어 보면 어떨까요? 가령, BadRequestException, NotfoundException이 있고, 그 하위에 다시 도메인에서 발생한 예외(ex. SectionConnectedException) 등을 작성하는 것입니다 ㅎㅎ

2023-05-17 13:05 UTC, merged

2023-05-17 13:35 UTC, woosung1223 commented on src/main/resources/schema.sql
> +);
감사합니다~ 역시 실무에서는 잘 사용하지는 않는군요..
반면 데이터 자체가 중요한 경우(핀테크 기업 같은 경우)는 외래키를 적극 고려해볼 것 같긴 하네요.

하지만 말씀해주신 것처럼 연습을 하는 단계이고, 개인적으로 적용했을 때의 부수효과를 직접 경험해보고 싶은 마음도 있어 2단계에서 외래키까지 적용해 제출해보겠습니다! ㅎㅎ

2023-05-17 13:38 UTC, woosung1223 commented on src/main/java/subway/entity/SectionEntity.java
> +    private final Integer distance;
답변 감사합니다!

말씀하신 것처럼 엔티티 자체가 프로덕션 코드이기는 하나 영속성 레이어에 존재하기에 스키마를 고려할 수 밖에 없겠군요..!
덕분에 Wrapper 타입 사용 근거가 명확하게 잡힌 느낌입니다~ 감사합니다 😄

2023-05-17 13:43 UTC, woosung1223 commented on src/main/java/subway/application/domain/LineProperty.java
> +public class LineProperty {
감사합니다~ 

분리를 한다는 것은 LineProperty와 Line의 참조를 끊는다는 것을 의미하시는걸까요?
만약 연관관계를 끊어버린다면 서비스 레벨에서 연결 작업을 수행해야 할 것으로 짐작되는데 한 번 trade-off를 따져 step2에서 적용해보겠습니다! 👍

2023-05-17 13:59 UTC, woosung1223 commented on src/main/java/subway/application/exception/ExpectedException.java
> +}
감사합니다!~ 확실히 예외 객체에서 Status Code까지 관리한다는 점은 좋아보입니다!

다만 아래와 같은 이유로 사용이 꺼려지기는 합니다.
이 부분에 대해서는 제이온의 생각을 듣고 싶어요!

저는 예외 객체마저도 해당 레이어의 구성원이라고 생각합니다. 비즈니스 레이어에서 정의되고, 사용되어지는 예외 객체는 비즈니스 레이어에 속한다고 생각합니다. 따라서 Status code를 예외 객체에서 정의하는 경우, 비즈니스 레이어의 구성원이 상위 개념인 HTTP에 대해 알게 되는 것이고 예측 가능한 소프트웨어에서 멀어질 수도 있다고 생각합니다. 상속도 결국 의존이므로.. 표현 계층 <-> 비즈니스 계층 사이에 양방향 의존이 생긴다고 생각해요.

물론 `도메인 예외 객체에 상태코드 하나 추가되는게 어때서!`라는 입장도 있을 수 있지만, 계층형 아키텍쳐를 선택한 순간 가장 중요시되어야 하는 건 계층 간의 격리라고 생각합니다. 예외 객체에서 상태 코드를 정의해 두 레이어를 관통하는 개념을 만들어버린다면.. 깨진 유리창 이론처럼 추후 비슷한 문제가 발생했을 때 계층 간의 격리를 쉽게 무시해버릴 수 있으니까요.

이러한 이유로 저는 Status code에 관한 모든 내용은 표현 계층에서 다뤄져야 한다고 생각합니다!
이에 대해 제이온의 생각도 궁금합니다 🧐

2023-05-18 04:35 UTC, pjy1368 commented on src/main/java/subway/application/exception/ExpectedException.java
> +}
예외 전략은 팀 by 팀, 개인 by 개인이라서 정답은 없다고 생각합니다~
말씀주신대로 계층 간의 완벽히 격리를 하고 싶다고 하면 각 계층에서 예외를 작성할 때 상태 코드를 의도하지 않고 순전히 예외에 집중해서 클래스를 정의할 수 있습니다. 가령 인프라 예외는 자유롭게 작성하고, 서비스 레이어에서 인프라 레이어의 예외를 본인의 기준에 맞게 서비스 예외로 변환해 주고, 최종적으로 프레젠테이션 레이어에서 서비스 예외를 보고 상태 코드에 맞게 다시 변환하거나 RestControllerException에서 곧바로 상태 코드로 던져줄 수 있습니다.
하지만 이번 미션에서 저는 예외 처리 전략을 세밀하게 만드는 것이 주 목적이라고 판단하지는 않아서, 가장 심플하면서 예외 계층 전략을 세우기 쉬운 방법을 추천드렸습니다.

2023-05-18 04:37 UTC, pjy1368 commented on src/main/java/subway/application/domain/LineProperty.java
> +public class LineProperty {
Line과 LineProperty를 분리하지 않고 하나로 두는 것도 한 번 다시 고민해보시라는 의미였습니다~ 2단계에서도 크게 불편한 점이 없다면 유지하셔도 됩니다.

2023-05-18 04:40 UTC, pjy1368 commented on src/main/java/subway/application/exception/ExpectedException.java
> +}
실제로 현업에서 저희 팀은 아래와 같이 계층 간 예외를 명확히 구분하고, 애플리케이션에서 발생한 예외를 프레젠테이션에서 예외에 맞게 상태 코드로 변환하는 구조로 되어 있습니다. 아래 코드는 Kotlin + gRPC 코드라 Java + Rest Api와는 조금 다르지만 전체적인 맥락은 동일합니다.
<img width="639" alt="image" src="https://github.com/woowacourse/jwp-subway-path/assets/56083021/32ccbf00-2c18-4dd3-b354-2193c04c1fbc">