[1단계 - 지하철 정보 관리 기능] 헤나(박현서) 미션 제출합니다.
woowacourse/jwp-subway-path pull request #90
Opened 2023-05-11 08:56 UTC by hyena0608

안녕하세요 현구막 ! 😄

지하철 정보 관리 기능 1단계 리뷰 잘 부탁드리겠습니다.

페어와 어제 저녁까지 도메인 관련 토론을 진행하다가 시간 분배를 제대로 하지 못했습니다.

레벨 1때도 비슷한 경험을 했었는데 서로 의견이 꺾이지 않을 때 어떤 식으로 타협해야할지 고민이 많이 됐습니다.

결과적으로는 기능 구현이 되긴했지만 도메인 설계가 어려웠는데 Controller 테스트 -> Domain Test -> Service Test로 TDD를 진행하다가 Controller의 한 메서드 테스트를 완성시키려고 하니 많이 힘들었던거 같습니다.

2023-05-13 01:51 UTC, Hyeon9mak requested changes
안녕하세요 헤나, 지하철 미션 고생하셨어요.
레벨1 때 연습한 규칙들이 많이 지켜지지 않은 모습인데요.. 😢 
리팩터링 과정에서 레벨1 때 연습한 규칙들을 다시 적용해보면 좋겠어요.

너무 한번에 많은 이야기를 하면 힘들어하실 것 같아서,
이번 리뷰에서는 코드 작성과 제네럴한 규칙에 대해서만 리뷰를 남겼어요.
다음 리뷰에서 설계에 대해 이야기 나눠보면 좋겠어요.

> (DM 질문) 도메인 설계 방법

미션 도메인이 충분히 복잡하고 도메인을 풀어내는 과정에서 당연히 겪는 문제라고 생각합니다. 
잘 시도해주셨고 이를 통해 "이렇게 도메인을 풀려고 하면 어렵구나." 를 깨달으신거라고 생각해요.

유지보수하기 어려운 구조, 절차적인 코드가 작성된 근본적인 이유는 
지하철역 애플리케이션을 통해 하고 싶은게(use-case) 무엇인지 파악하지 않고
현실 세상 속 내가 알고 있는 지하철 노선 관련 구조에 따라 모델 설계를 끝낸 후
use-case 를 거기에 끼워맞추려해서인거 같아요.

현실 세상 속 모두가 알고 있는 상식으로 모델을 표현하고 행동 부여하는 것은 
분명 코드를 파악하는데 도움을 주고 유지보수가 쉬워지는 중요한 부분이지만,
꼭 그 상식에 맞춰 모든 걸 구성할 필요는 없다고 생각해요.
휴대폰 문자 메세지 발송 기능에 편지지, 우체통, 배달 과정이 없는 것처럼요.

> 의견을 타협하는 방법

당연히 서로 타협점을 찾고 만족하는 상태가 되면 좋겠지만, 현실적으로 쉽지 않죠.
내가 원하는 무언가를 추진하기 위해선 타당한 근거와 객관적인 자료로 상대방을 설득하는 과정이 필요해보여요.
서로 근거나 자료를 찾지 못했다면 적당히 중간 포인트를 협의해야 할 것 같구요. 서로 한쪽씩 적용해보는 것도 좋은 방법이겠네요.
"상대방 말대로 해보니까 이거 구리더라.", "내 말대로 해보니까 이거 구리더라."
서로 별로라고 생각하는거 하나씩 적용해보고 단점(근거)을 찾아내서 상대방을 설득하는거죠 😄 
어차피 완벽한 솔루션은 이 세상에 존재하지 않고, 서서히 차악을 찾아내는게 설계라고 생각해요.

얼마 전에 동욱님 발표를 듣고 정리한 내용이 있는데, 딱 이번 미션에 어울리는 내용 같아요.
https://hyeon9mak.github.io/avoid-dependencies-on-uncontrollable-factors/#%EC%9D%BC%EC%A0%95%EC%9D%80-%EC%A7%80%ED%82%A4%EC%A7%80%EB%A7%8C-%EB%B2%84%EA%B7%B8%EA%B0%80-%EB%A7%8E%EC%9D%80-%EA%B2%83-vs-%EC%9D%BC%EC%A0%95%EC%9D%80-%EB%AA%BB-%EC%A7%80%ED%82%A4%EC%A7%80%EB%A7%8C-%EB%B2%84%EA%B7%B8%EA%B0%80-%EC%97%86%EB%8A%94-%EA%B2%83

궁금하신 점 DM, 코멘트 남겨주세요 🙇‍♂️

2023-05-13 01:51 UTC, Hyeon9mak commented on src/main/java/subway/ui/StationController.java
> +        stationService.deleteStationByStationNameAndLineName(deleteStationRequest);
Line 과 Station 객체는 고유한 식별자를 갖고 있지 않나요? 😮 
entity(= identifier + VO)를 사용하는 이유는 식별자를 통해 값들의 변화를 추적하기 위함인데,
값을 통해 엔티티를 찾아내고 제거하는 플로우가 익숙하지 않네요.
이 방식에 대해 저를 설득시켜주시면 좋겠어요!

2023-05-13 01:51 UTC, Hyeon9mak commented on src/main/java/subway/ui/StationController.java
> +                .build();
CREATED, NO_CONTENT 같은 다양하고 명확한 상태코드 활용 좋아요~ 💯

2023-05-13 01:51 UTC, Hyeon9mak commented on src/main/resources/schema.sql
> +    line_id         bigint                not null,
구간정보는 역과 역 사이 정보 같은데, 호선 정보도 필요할지 고민이 되네요. 🤔 
"같은 호선으로 연결되지 않아 절대로 성사될 수 없는 구간 정보를 걸러준다." 는 장점도 있을 것 같고,
"`stations_lines` 매핑 테이블에 이미 중복된 정보가 있어서 정규화가 깨진다." 는 단점도 있을 것 같아요.
헤나는 어떤 의사결정을 배경으로 `line_id` 를 추가하셨나요?

2023-05-13 01:51 UTC, Hyeon9mak commented on src/test/java/subway/application/LineServiceTest.java
> +    private LineService lineService;
`LineServiceTest` 는 `LineService` 에 대해 테스트 하고싶은 것이므로 `@SpringBootTest` 를 이용할 수도 있었을 것 같은데,
`@JdbcTest` 를 사용한 이유가 있을까요?

2023-05-13 01:51 UTC, Hyeon9mak commented on src/test/java/subway/domain/SectionTest.java
> +    }
큰 의미가 있는 테스트인지 잘 모르겠어요.
불필요한 테스트는 과감하게 생략해주면, 정말 필요한 테스트들이 더욱 강조될 것 같아요.
나중에 헤나가 유지보수 할 포인트도 줄어들구요.

2023-05-13 01:51 UTC, Hyeon9mak commented on src/main/java/subway/dto/StationRequest.java
jackson 2.13 버전부터 request dto 에도 no args constructor 가 필요없어졌더라구요.
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.13#no-constructor-deserializer-module

2023-05-13 01:51 UTC, Hyeon9mak commented on src/main/java/subway/dto/StationRequest.java
`@Valid` 어노테이션을 활용해서 너무 당연한 값들의 검증을 진행해봐도 좋겠네요.

2023-05-13 01:51 UTC, Hyeon9mak commented on src/main/java/subway/application/StationService.java
> +    public Long saveStation(StationRequest stationRequest) {
헐~ 레벨1 때 메서드 라인 수 제한 열심히 연습하지 않았나요? 😨

2023-05-13 01:51 UTC, Hyeon9mak commented on src/main/java/subway/application/StationService.java
> +                .findFirst();
일급 컬렉션을 통해 해당 내용들을 축약해줄 수 있겠네요.

2023-05-13 01:51 UTC, Hyeon9mak commented on src/main/java/subway/application/StationService.java
> +        }
무얼 검증하고 싶은지 의미파악이 힘들어요.
디미터 법칙도 지킬 겸 객체에 메세지를 보내보면 어떨까요?
또, 검증 로직 자체를 메서드로 포장해서 메세지를 나타내주면 어떨까요?

2023-05-13 01:51 UTC, Hyeon9mak commented on src/main/java/subway/application/StationService.java
> +        final Station downStation = getStation(stationRequest.getDownStationName(), line.getId());
메서드 명칭은 `호선을 찾아온다.`, `역을 찾아온다.` 같은데, 내부에서 더 많은 일이 일어나네요.

2023-05-13 01:51 UTC, Hyeon9mak commented on src/main/java/subway/application/StationService.java
> +        }
레벨1부터 연습한 객체지향 생활체조 규칙이... 😱 
객체지향 생활체조를 무시하고 if-else 키워드를 사용해서 가독성이나 의도파악이 더 용이한 경우도 분명 존재하는데요, 현재는 그렇지 않아 보이네요..
if-else 키워드를 줄이기 위한 필살기로, 디자인 패턴을 적용해볼만한거 같아요.
https://refactoring.guru/ko/design-patterns/behavioral-patterns

2023-05-13 01:51 UTC, Hyeon9mak commented on src/main/java/subway/application/StationService.java
> +        }
지하철 역 생성 / 삭제에 대한 과정이 정말 길고 복잡한데요, 현재 구조에서 유지보수할 포인트를 찾는 과정은 아래와 같을 것 같아요.

1. 지하철 역 생성 로직 중 일부에 대해 요구사항 변경 요청 접수
2. 지하철 역 관련 패키지 탐색 `subway`
3. 컨트롤러 계층부터 탐색 `controller`
4. `StationController` 탐색, StationService` 발견
5. `StationService` 에서 170라인 전체 살펴보기

비즈니스 로직들을 도메인 객체로 나누어 보관하면 각각 행동에 이름이 생겨나면서 유지보수 포인트 탐색 과정이 획기적으로 줄어들텐데요,
영속화 과정 때문에 도메인 객체로 분리하기 애매하다고 느낀다면, service 클래스를 좁은 의미로 분리해보는 건 어떨까요?
현재는 지하철 역 생성 코드를 확인할 때도 `StationService`,
지하철 역 제거 코드를 확인할 때도 `StaitonService`,
지하철 역 조회 코드를 확인할 때도 `StaitonService` 를 열어봐야해요.
객체지향에서 책임은 유지보수할 이유를 뜻하고, 하나의 객체당 하나의 책임만을 가져야한다고 했는데 벌써 3개나 되네요.

2023-05-13 01:51 UTC, Hyeon9mak commented on src/main/java/subway/application/StationService.java
> +    private void deleteStationWhenAnotherLineNotExist(final Long stationId, final Long lineId) { //
불필요한 주석 관리해주세요!

2023-05-13 01:51 UTC, Hyeon9mak commented on src/main/java/subway/dao/SectionDao.java
> +    private final SimpleJdbcInsert simpleJdbcInsert;
SimpleJdbcInsert 활용 👍

2023-05-13 01:51 UTC, Hyeon9mak commented on src/main/java/subway/domain/Distance.java
> +    }
VO 포장 및 활용 👍

2023-05-13 01:51 UTC, Hyeon9mak commented on src/main/java/subway/domain/Section.java
> +        }
에러가 발생하면 온전히 동일한 메세지를 전달 받아서 확인이 어려울 것 같아요.

2023-05-13 01:51 UTC, Hyeon9mak commented on src/main/java/subway/domain/Section.java
> +
section 은 엔티티이므로 id 하나로만 동등성을 확인해야할 것 같아요!

2023-05-13 01:51 UTC, Hyeon9mak commented on src/main/java/subway/domain/Station.java
>      }
이름도 포장해보면 좋겠네요.

2023-05-13 05:03 UTC, hyena0608 commented on src/main/java/subway/ui/StationController.java
> +        stationService.deleteStationByStationNameAndLineName(deleteStationRequest);
단점이 많기에 정말 설득할 수가 없다고 결정했습니다.

이유는 아래와 같습니다.

위에 `deleteStationByName()` 메서드에서 고유한 식별자값(`id`)가 아닌 `역_이름`, `노선_이름`으로 검색을 진행하게 된 이점은 없습니다.

`역_이름`, `노선_이름`은 데이터베이스에 `unique` 제약이 있기 때문에 식별하는 것에 문제는 없습니다.

다만 PK값이 아닌 `이름`으로 판단하게 될 경우 이후에 비즈니스 조건이 바뀌었을 때 문제가 됩니다.
또한 `숫자`가 아닌 `문자열`로 조회하기 때문에 비용면에서도 혹은 실수(오타)가 발생할 확률이 높아집니다.


내부 DB에서 해당 이름으로 정확하게 한 하나의 자원을 가져오지 않는이상 Entity로써 식별할 수도 없습니다

2023-05-13 05:03 UTC, hyena0608 commented on src/main/resources/schema.sql
> +    line_id         bigint                not null,
저는 테이블에 편의를 위한 컬럼이 추가된다고 해서 큰 문제가 된다고 생각하지 않습니다.

`line_id`가 없어진다면 구간이 어떤 노선의 구간인지 확인하기 위한 다른 방법이 필요합니다.

먼저 `sections`에 `line_id`가 삭제될 경우
`stations_lines` 테이블에서 판단하기 힘든 상황이 발생할 수 있습니다.

`잠실 - 2호선 -> 잠실나루`
`잠실 - 8호선 -> 잠실나루`

이런 식으로 다른 노선으로 이어질 수 있는 상황이 있을 수 있기 때문입니다.

2023-05-13 05:07 UTC, hyena0608 commented on src/test/java/subway/application/LineServiceTest.java
> +    private LineService lineService;
`@SpringBootTest`를 이용할 경우 모든 `bean`을 가져와서 등록하는 상황이 생기기 때문에 테스트비용이 많이 들 수 있습니다.

테스트를 위한 구성 정보를 자동으로 캐싱 해주고 있지만 언제 어디서 다시 테스트 구성 정보를 새로 불러올지 확실하지 않고 관리하기 어렵기 때문에 `@JdbcTest`를 통해서 현재 `Service` 테스트에서 필요한 정보만 스캔하여 빈으로 등록하여 사용하기 위함입니다.

2023-05-13 05:10 UTC, hyena0608 commented on src/test/java/subway/domain/SectionTest.java
> +    }
어떤 검증에 대한 예외가 발생하는 테스트라면 충분히 상황에 대한 테스트이기에 있어야 하지만
이러한 단순한 `생성`에 대한 테스트는 확실히 필요 없다고 느껴지네요 !

어떤 식으로 생성하고 있는지 확인하기 위해서 테스트에 와서 이런 메서드를 보기보다 해당 클래스에 시그니처를 보는 편이 더 빠르고 이해하기도 좋을거 같다고 생각됩니다 !

생성에 대한 테스트가 정말 필요한 상황이라면 모르겠지만 불필요한 상황이 훨씬 더 많은거 같기에 필요없다고 느껴지는 테스트는 생략하겠습니다 😄

2023-05-13 05:12 UTC, hyena0608 commented on src/main/java/subway/dto/StationRequest.java
기본 생성자가 없어도 생성될 수 있는 상황보다
기본 생성자가 없음으로 생성될 수 없는 상황이 훨씬 많다고 생각했습니다.

만약 jackson 2.13 버전 이상을 사용한다고 팀에서 정확하게 얘기하고 진행한다면
기본 생성자가 필요없으므로 생략하겠지만  확실하지 않은 상황이라고 생각해서 기본생성자를 넣고 진행했습니다 !

2023-05-13 05:13 UTC, hyena0608 commented on src/main/java/subway/dto/StationRequest.java
요청에 대한 값을 검증할 수 있도록 validation 을 추가해서 사용해보겠습니다 !

2023-05-13 05:14 UTC, hyena0608 commented on src/main/java/subway/application/StationService.java
> +    public Long saveStation(StationRequest stationRequest) {
🫨 죄송합니다 ㅠㅠ

2023-05-13 05:34 UTC, hyena0608 commented on src/main/java/subway/application/StationService.java
> +                .findFirst();
상행역, 하행역이 노선에 등록될 때 이미 존재하는지 확인하는 부분의 내용입니다.
즉, 노선에 이미 상행역, 하행역이 있느냐를 물어보고 있습니다.
노선이 가질 수 있다고 생각이 들고 있으나 현재 `Line`객체로는 확인할 수 없습니다.

여기서는 `List<StationLine>`을 일급 컬렉션으로 만들어서 구간들 중에 역이 중복되는지 확인해달라고 할 수 있을거 같네요 !

2023-05-13 05:35 UTC, hyena0608 commented on src/main/java/subway/application/StationService.java
> +        }
일급 컬렉션을 만들어서 메시지를 보내 보겠습니다 !

2023-05-13 05:36 UTC, hyena0608 commented on src/main/java/subway/application/StationService.java
> +        }
죄송합니다..

2023-05-14 13:22 UTC, hyena0608 commented on src/main/java/subway/domain/Section.java
> +        }
조금 더 명확한 예외 메시지를 작성하겠습니다 !

2023-05-14 13:28 UTC, hyena0608 commented on src/main/resources/schema.sql
> +    line_id         bigint                not null,
저는 테이블에 컬럼이 중복되는 것에 따라서 합의하에 충분히 가능한 상황이라고 생각합니다.
테이블을 봤을 때 구간이 어떤 노선에 해당하는지 바로 파악할 수 있다는 점도 장점입니다.

저는 정규화가 깨진다는 단점이 있을 수는 있지만 항상 정규화가 정답은 아니라고 생각합니다. 🙂

2023-05-15 23:13 UTC, Hyeon9mak commented on src/main/resources/schema.sql
> +    line_id         bigint                not null,
> 정규화가 깨진다는 단점이 있을 수는 있지만 항상 정규화가 정답은 아니라고 생각합니다.

💯 💯 💯

2023-05-15 23:40 UTC, Hyeon9mak approved these changes
안녕하세요 헤나, 지하철 미션 고생하셨어요.
이전보다 훨씬 읽기 편한 코드였어요. 많은 공을 들이신게 느껴집니다.
다음 단계를 진행하면서 생각해보시면 좋을 부분들 코멘트 남겼어요.
화이팅입니다 💪

2023-05-15 23:40 UTC, Hyeon9mak commented on src/main/java/subway/application/StationService.java
> +        deleteAllThenSaveAllSections(line);
line 에 해당하는 section 들을 모두 지우고 다시 저장하는 행위는 추상적으로 보면 '새로 추가된 section 1개를 저장한다.' 로 보이네요.
실제로 새로 추가된 section 1개만 저장하거나, "새로 추가된 section 을 저장한다." 라는 네이밍을 부여해도 좋을 것 같아요.

2023-05-15 23:40 UTC, Hyeon9mak commented on src/main/java/subway/application/response/StationResponse.java
> +
response dto 는 정말로 no args constructor 가 필요 없어요!

2023-05-15 23:40 UTC, Hyeon9mak commented on src/main/java/subway/dao/entity/StationEntity.java
> +    }
👍

2023-05-15 23:40 UTC, Hyeon9mak commented on src/main/java/subway/dao/support/SqlHelper.java
> +    }
오... 흥미롭네요 ㅋㅋㅋ 👍

2023-05-15 23:40 UTC, Hyeon9mak commented on src/main/java/subway/dao/support/SqlHelper.java
> +    }
jdbctemplate 사용할 때 intellij 에서 SQL string 자동검사를 해주기 때문에 오타걱정을 덜긴 하는데.. 그래도 기가 막힙니다 ㅋㅋㅋ

2023-05-15 23:40 UTC, Hyeon9mak commented on src/main/java/subway/domain/Distance.java
> +    }
엇, 의도하신 한글일까요?

2023-05-15 23:40 UTC, Hyeon9mak commented on src/main/java/subway/domain/Line.java
> +    }
name, color 와 id 까지도 모두 포장해볼 수 있겠네요.
그런데, `Line` 객체에 id 가 정말 필요할까요?
`LineEntity` 와의 차이는 무엇일까요?

2023-05-15 23:40 UTC, Hyeon9mak commented on src/main/java/subway/ui/StationController.java
>      }
예외가 발생했을 때 사용자에게 적합한 메세지를 전달해줄 수 있는 곳이 필요해보여요.

2023-05-15 23:40 UTC, Hyeon9mak commented on src/test/java/subway/domain/SectionsTest.java
> +    }
일급 컬렉션을 만들어주신 덕분에 구간저장 과정이 간단한 단위테스트로 마무리되네요 👍

2023-05-15 23:40 UTC, Hyeon9mak commented on src/test/java/subway/domain/SectionsTest.java
> +    class SectionAddValidation {
`@Nested` 활용 👍

2023-05-15 23:41 UTC, merged

2023-05-16 00:15 UTC, hyena0608 commented on src/main/java/subway/application/StationService.java
> +        deleteAllThenSaveAllSections(line);
`deleteAllThenSaveAllSections` 메서드 네이밍을 일부러 자세하게 작성하여 내부 구현을 알려주려했는데 결과적으로 어떤 결과가 반영되는지는 현구막이 말씀해주신것처럼 현재 메서드의 행위를 추상적으로 보면 새로 추가된 section을 저장한다는 이야기가 되겠네요 !

어떤 상황에서 자세한 네이밍과 추상적인 네이밍 중 무엇을 선택할지 고민하고 2단계 제출하면서 반영해보겠습니다 ! 😄

2023-05-16 00:17 UTC, hyena0608 commented on src/main/java/subway/domain/Distance.java
> +    }
인텔리제이가 자동으로 재정의 해주는거 이용했는데 거리10이 어떻게.. 나오게 됐는지는 모르겠네요 ㅠㅠ
인텔리제이를 믿었는데 자동 재정의하고 한 번은 확인해봐야겠네요 🥲

2023-05-16 00:51 UTC, hyena0608 commented on src/main/java/subway/domain/Line.java
> +    }
이번에 `Line` 객체와 `LineEntity` 객체 둘 다 만들어서 이용했습니다.

`LineEntity` 같은 경우 식별자 값을 통해서 동등성 검사를 진행하고 노선에 대한 로직이 존재하지 않습니다.
DB에서 꺼내온 값을 가지고 있는 객체입니다.

`Line`에서는 도메인 로직을 가지고 있는 객체입니다.
실제 비즈니스 로직을 가지고 있고 동등성 검사는 `id`를 제외한 필드값으로 검사하고 있습니다.

## Line과 Entity의 차이

현재 `Entity`와 `Domain` 객체를 사용하는 범위는 다음과 같습니다.

```
Dao (Entity) -> Repository(Entity, Domain) -> Service(Domain)
```
Repository에서는 인자로 Entity를 받아 저장하거나
혹은 Dao에서 받은 Entity를 Domain 객체로 변환하여 반환하고 있습니다.

`Entity`는 비즈니스 로직이 없어서 `Service` 외부에 있어도 내부 상태가 변경될 위험성이 없습니다.

`Domain`은 비즈니스 로직이 있어서 `Service` 외부에 있으면 내부 상태가 변경될 위험성이 있습니다.

이러한 이유로 Domain이 사용되는 곳이 한정될 수 있도록 분리 해놨습니다.

## Line에 있는 id 문제
`Line`이 `id`를 갖고 있으면 두 가지 문제가 있다고 생각합니다.
- Long타입의 id는 NPE 문제를 야기할 수 있다.
- 도메인 객체가 아닌 `Entity`의 개념에 가깝다.

## Line에 id를 넣은 이유
식별자값을 통해서 다시 Repository에 접근할 때 유용해서 넣어놨습니다.

```java
    private List<SectionEntity> collectSectionEntitiesBy(final Line line) {
    // Line 객체 내부에 있는 식별자값을 가져와서 SectionEntity에 필요한 식별자 값을 바로 넣어줄 수 있습니다.
        return line.getSections()
                .stream()
                .map(sectionDomain -> SectionEntity.toEntity(sectionDomain, line.getId()))
                .collect(Collectors.toList());
    }
```

## Line에 id를 넣지 않기 위한 다른 방법
크루분들의 리뷰를 봤을 때 두 가지 방법을 볼 수 있었습니다.

1. 도메인 객체에는 아예 id(식별자값)을 넣지 말자 !

노선의 식별자값이 필요한 구간을 생성할 때
노선에 식별자값이 없다면 해당 노선인지 구별할 수 있는 다른 값을 가지고 있어야합니다.

만약 노선의 이름, 컬러가 unique가 아니라 중복이 가능했다면 원하는 노선을 찾을 수 없습니다.
하지만 노선 도메인 객체가 식별자값을 가지고 있었다면 이러한 문제에 대해 생각하지 않아도 되기 때문에
식별자값을 넣지않는 것보다 있는 편이 낫다고 생각합니다.


2. UUID를 이용해서 도메인 객체가 식별할 수 있는 값을 따로 넣자 !

도메인 객체와 엔티티 객체는 다음과 같은 필드를 가지게 됩니다.

```java
class Line {
    private final UUID uuid;
}

class LineEntity {
    private final Long id;
    private final UUID uuid;
}
```

```sql
CREATE TABLE LINES (
    id,
    UUID,
    ...
)
```

생성되는 경우에는 UUID를 애플리케이션에서 만들어 넣기 때문에 NPE 문제가 발생하지 않습니다.
이제 도메인에서 사용하는 Line 객체는 NPE 문제로부터 해방될 수 있지만 모든 테이블에 UUID 컬럼을 가지게 되는 문제점이 있습니다.

현재로서는 이 방법이 가장 괜찮다고 생각하고 있습니다.

2023-05-16 00:52 UTC, hyena0608 commented on src/main/java/subway/ui/StationController.java
>      }
사용자가 예외에 대한 메시지를 전달받을 수 있도록 적절한 예외 핸들링을 추가하겠습니다 !

2023-05-16 00:54 UTC, hyena0608 commented on src/test/java/subway/domain/SectionsTest.java
> +    }
`assertDoesNotThrow()` 검증 메서드를 이용해서 메서드가 호출될 때 문제가 발생하지 않는다는 테스트인데
내부 상태를 검증하지 않는 것에 대해서 어떻게 생각하시는지 궁금합니다 ! 
2단계에서 테스트를 추가하면서 조금 더 경험해보도록 하겠습니다

2023-05-16 00:55 UTC, hyena0608 commented on src/test/java/subway/domain/SectionsTest.java
> +    class SectionAddValidation {
테스트를 작성하면서 비슷하지만 다른 여러 상황이 있을 경우 `@Nested`를 이용하면 테스트 보기가 수월해서 사용해봤습니다 !

2023-05-16 01:37 UTC, hyena0608 commented on src/main/java/subway/application/response/StationResponse.java
> +
RestAssured 테스트 진행하면서 응답 객체를 받아올 때 사용되고 있습니다.

<img width="968" alt="image" src="https://github.com/woowacourse/jwp-subway-path/assets/82203978/8d3e007f-b3eb-41bc-a77e-a810366bd58e">

기본 생성자가 없을 경우 ObjectMapper에서 응답 객체를 생성할 수 없습니다.

<img width="718" alt="image" src="https://github.com/woowacourse/jwp-subway-path/assets/82203978/c5a57082-3bce-4c69-a2e5-d8c7b0b1b592">

물론 현구막이 말씀해주셨던 jackson 2.13 이상이거나 gradle로 실행시킬 경우는 기본 생성자가 없어도 성공합니다.

<img width="985" alt="image" src="https://github.com/woowacourse/jwp-subway-path/assets/82203978/8e0db0a1-aea6-4ee7-a669-15743d2eb4ed">

다만 이러한 상황에서 오류를 발생시키지 않을 상황은 기본 생성자가 있는 것이라 생각해서 넣어놨습니다 !

2023-05-21 09:48 UTC, Hyeon9mak commented on src/test/java/subway/domain/SectionsTest.java
> +    }
결국 중요한 것은 검증이냐 행위냐가 아니라, "내가 원하는 바가 잘 동작한다." 를 확인하는 것 아닐까요? 😄

2023-05-21 09:51 UTC, Hyeon9mak commented on src/main/java/subway/domain/Line.java
> +    }
여러가지 고민 좋습니다. 
다만 마지막 고민 파트에서 "나중에 비즈니스 요구사항 변화에 따라 유지보수 하기 좋은 코드를 만들기 위함" 보다는
"기술적으로 이렇게 해야 더 편리하다." 에 집중한다는 느낌을 받았어요.

"현실세계에서 노선의 이름과 컬러가 유니크하지 않을 경우가 있을까?"
"그리고 만약 그렇게 된다면 큰 대격변이라, 온전히 새로운 시스템을 준비하게 되지 않을까?"
현실적인 고민도 함께 해보면 좋겠네요!